// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

const (
	// Command name constants
	CommandAgentFeedSteer = "steer"
	CmdAgentFeedSteer     = "steer"

	// Flag name constants
	FlagAgentFeedSteerMessage      = "message"
	FlagAgentFeedSteerAgentId      = "agent-id"
	FlagAgentFeedSteerAgentID      = FlagAgentFeedSteerAgentId
	FlagAgentFeedSteerFeedId       = "feed-id"
	FlagAgentFeedSteerFeedID       = FlagAgentFeedSteerFeedId
	FlagAgentFeedSteerNoAck        = "no-ack"
	FlagAgentFeedSteerNoWake       = "no-wake"
	FlagAgentFeedSteerToAgentId    = "to-agent-id"
	FlagAgentFeedSteerToAgentID    = FlagAgentFeedSteerToAgentId
	FlagAgentFeedSteerAwaitPeerAck = "await-peer-ack"
)
