// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	"github.com/spf13/cobra"
	"github.com/zqk-os/zqk/internal/cli"
	clipkg "github.com/zqk-os/zqk/pkg/cli"
)

// NewAgentHookCommandBuilder creates a new agent_hook command
func NewAgentHookCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("hook")
	builder.WithShort("Manage agent lifecycle hooks")
	help := clipkg.DynamicHelpBuilder("Manage agent lifecycle hooks")
	help.WithDescriptionLines("Configure, trigger, and inspect agent lifecycle hooks.")
	help.AddExample("Run agent hook", "%s agent hook")
	builder.WithHelpBuilder(help)
	builder.WithArgs(cobra.NoArgs)
	builder.WithCommonFlagsDefault(cli.AddCommonFlags)
	cmd := builder.Build()
	return cmd
}
