// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

const (
	// Command name constants
	CommandAgentFeedBridgeIngest = "bridge-ingest"
	CmdAgentFeedBridgeIngest     = "bridge-ingest"

	// Flag name constants
	FlagAgentFeedBridgeIngestChannel     = "channel"
	FlagAgentFeedBridgeIngestPayloadFile = "payload-file"
	FlagAgentFeedBridgeIngestPayload     = "payload"
	FlagAgentFeedBridgeIngestAgentId     = "agent-id"
	FlagAgentFeedBridgeIngestAgentID     = FlagAgentFeedBridgeIngestAgentId
	FlagAgentFeedBridgeIngestToAgentId   = "to-agent-id"
	FlagAgentFeedBridgeIngestToAgentID   = FlagAgentFeedBridgeIngestToAgentId
	FlagAgentFeedBridgeIngestFeedId      = "feed-id"
	FlagAgentFeedBridgeIngestFeedID      = FlagAgentFeedBridgeIngestFeedId
	FlagAgentFeedBridgeIngestNoAck       = "no-ack"
	FlagAgentFeedBridgeIngestNoWake      = "no-wake"
)
