// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	"github.com/spf13/cobra"
	clipkg "github.com/zqk-os/zqk/pkg/cli"
)

// NewCiCommandBuilder creates a new ci command
func NewCiCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("ci")
	builder.WithShort("Local CI (commit → checkout elsewhere → test run)")
	help := clipkg.DynamicHelpBuilder("Local CI (commit → checkout elsewhere → test run)")
	help.WithDescriptionLines("Studio-local CI that mirrors remote CI. Commit on the studio root, then")
	help.WithDescriptionLines("checkout that SHA into .zqk/local-ci/workdir and run zqk test run against it")
	help.WithDescriptionLines("while health/logs stay on studio.")
	help.AddExample("Checkout HEAD into local-ci workdir and run test cases", "%s ci run")
	help.AddExample("Checkout only (no schedule)", "%s ci checkout")
	help.AddExample("Show pinned SOURCE_SHA and health summary", "%s ci status")
	help.ExcludeFlag("format")
	help.ExcludeFlag("output")
	help.ExcludeFlag("verbose")
	help.ExcludeFlag("quiet")
	help.ExcludeFlag("timeout")
	help.ExcludeFlag("columns")
	builder.WithHelpBuilder(help)
	builder.WithCommonFlags(false, nil)
	cmd := builder.Build()
	return cmd
}
