// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

const (
	// Command name constants
	CommandCi = "ci"
	CmdCi     = "ci"

	// Subcommand name constants
	SubcommandCiRun      = "run"
	SubcmdCiRun          = "run"
	SubcommandCiCheckout = "checkout"
	SubcmdCiCheckout     = "checkout"
	SubcommandCiStatus   = "status"
	SubcmdCiStatus       = "status"

	// Flag name constants
)
