// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	"github.com/spf13/cobra"
	"github.com/zqk-os/zqk/pkg/cliapp"
	clipkg "github.com/zqk-os/zqk/pkg/cli"
)

// NewConvergenceNestStatusCommandBuilder creates a new convergence_nest_status command
func NewConvergenceNestStatusCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("nest-status")
	builder.WithShort("Show nested CVS BFS tree under a parent")
	help := clipkg.DynamicHelpBuilder("Show nested CVS BFS tree under a parent")
	help.WithDescriptionLines("Returns parent plus descendants via related_object_refs (CollectCVSTreeBFS, depth-capped).")
	help.AddExample("JSON tree", "%s scheduler convergence nest-status --parent-session-id CVS-001 --format json")
	help.ExcludeFlag("format")
	help.ExcludeFlag("output")
	help.ExcludeFlag("verbose")
	help.ExcludeFlag("quiet")
	help.ExcludeFlag("timeout")
	help.ExcludeFlag("columns")
	builder.WithHelpBuilder(help)
	builder.AddStringFlag("parent-session-id", "", "", "Parent/coordinator convergence_session id (CVS-*)")
	builder.AddIntFlag("max-depth", "", 3, "Max nest depth")
	builder.WithCommonFlagsExcluding(cli.AddCommonFlagsExcluding, []string{"format", "output", "verbose", "quiet", "timeout", "columns"})
	cmd := builder.Build()
	return cmd
}
