// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

const (
	// Command name constants
	CommandFeedSteer = "steer"
	CmdFeedSteer     = "steer"

	// Flag name constants
	FlagFeedSteerMessage      = "message"
	FlagFeedSteerAgentId      = "agent-id"
	FlagFeedSteerAgentID      = FlagFeedSteerAgentId
	FlagFeedSteerFeedId       = "feed-id"
	FlagFeedSteerFeedID       = FlagFeedSteerFeedId
	FlagFeedSteerNoAck        = "no-ack"
	FlagFeedSteerNoWake       = "no-wake"
	FlagFeedSteerToAgentId    = "to-agent-id"
	FlagFeedSteerToAgentID    = FlagFeedSteerToAgentId
	FlagFeedSteerAwaitPeerAck = "await-peer-ack"
)
