// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	"github.com/spf13/cobra"
	clipkg "github.com/zqk-os/zqk/pkg/cli"
	"github.com/zqk-os/zqk/pkg/cliapp"
)

// NewInitCommandBuilder creates a new init command
func NewInitCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("init")
	builder.WithShort("Initialize a new ZQK project")
	help := clipkg.DynamicHelpBuilder("Initialize a new ZQK project")
	help.WithDescriptionLines("Initialize a new ZQK project in the current directory.")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("Supports three initialization scenarios:")
	help.WithDescriptionLines("  1. Greenfield: Brand new project (default)")
	help.WithDescriptionLines("  2. Legacy: Existing project being brought under ZQK management")
	help.WithDescriptionLines("  3. Snapshot: Initialize from snapshot data (test scenarios)")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("This command creates the necessary directory structure and configuration files")
	help.WithDescriptionLines("for a new ZQK project. It sets up:")
	help.WithDescriptionLines("  - .zqk/ directory for configuration and state")
	help.WithDescriptionLines("  - .zqk/process/ directory structure for object storage")
	help.WithDescriptionLines("  - Initial configuration files")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("  Greenfield: Initialize in current directory")
	help.WithDescriptionLines("  zqk system init")
	help.WithDescriptionLines("  Declarative Seed: Initialize with answer file")
	help.WithDescriptionLines("  zqk system init --answer-file seed.yaml")
	help.WithDescriptionLines("  Legacy: Initialize existing project")
	help.WithDescriptionLines("  zqk system init --legacy")
	help.WithDescriptionLines("  Snapshot: Initialize from snapshot (test scenario)")
	help.WithDescriptionLines("  ZQK_TEST_ROOT=test-scenarios/my-scenario zqk system init --from-snapshot snapshot.csnap --wipe")
	help.WithDescriptionLines("  Snapshot: Merge with existing data")
	help.WithDescriptionLines("  zqk system init --from-snapshot snapshot.csnap --merge")
	help.WithDescriptionLines("  Legacy + discover: Initialize and report existing objects")
	help.WithDescriptionLines("  zqk system init --legacy --discover")
	help.WithDescriptionLines("  Greenfield with maintenance jobs")
	help.WithDescriptionLines("  zqk system init --with-maintenance-jobs")
	help.WithDescriptionLines("  Greenfield with onboarding curriculum")
	help.WithDescriptionLines("  zqk system init --with-onboarding-roadmap")
	help.AddExample("Run init", "%s init")
	builder.WithHelpBuilder(help)
	builder.WithArgs(cobra.NoArgs)
	builder.AddBoolFlag("advanced", "", false, "Initialize with an advanced, ontology-aware interface (Semantic Bridge Phase 1)")
	builder.AddStringFlag("answer-file", "", "", "Declarative kernel seed answer file (.yaml or .json) for non-interactive swarm spawn")
	builder.AddBoolFlag("discover", "", false, "Run the interactive Project Discovery Wizard to capture strategic context, stakeholders, and important dates. If --legacy is provided, it will instead scan and report existing objects.")
	builder.AddBoolFlag("force", "", false, "Overwrite existing files")
	builder.AddStringFlag("from-snapshot", "", "", "Initialize from snapshot file (.csnap or .json)")
	builder.AddStringFlag("import-ontology", "", "", "Import an external ontology during initialization (requires --advanced)")
	builder.AddBoolFlag("legacy", "", false, "Legacy project mode (preserve existing files)")
	builder.AddBoolFlag("merge", "", false, "Merge snapshot data with existing (snapshot mode only)")
	builder.AddStringFlag("project-name", "", "", "Project name (defaults to directory name)")
	builder.AddBoolFlag("simple", "", false, "Initialize with a simple, guided interface (Semantic Bridge Phase 1)")
	builder.AddStringFlag("template", "", "standard", "Template to use (standard, minimal)")
	builder.AddBoolFlag("wipe", "", false, "Wipe existing data before restoring snapshot (requires --force)")
	builder.AddBoolFlag("with-maintenance-jobs", "", false, "After init, ensure retention and audit-aggregation scheduler jobs exist (same as running 'zqk system ensure-retention-jobs'). Puts the project in optimal maintenance configuration.")
	builder.AddBoolFlag("with-onboarding-roadmap", "", false, "After init, create the onboarding roadmap seed scheduler job. Start the scheduler to run it once and create the priority plan, workstream, and backlog items.")
	builder.WithCommonFlagsDefault(cli.AddCommonFlags)
	cmd := builder.Build()
	return cmd
}
