// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	"github.com/spf13/cobra"
	"github.com/zqk-os/zqk/internal/cli"
	clipkg "github.com/zqk-os/zqk/pkg/cli"
)

// NewMcpSvcListToolsCommandBuilder creates a new mcp_svc_list_tools command
func NewMcpSvcListToolsCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("list-tools")
	builder.WithShort("List MCP tool names")
	help := clipkg.DynamicHelpBuilder("List MCP tool names")
	help.WithDescriptionLines("List the exact MCP tool names the server would expose (after allowlist).")
	help.WithDescriptionLines("Use these names in mcp_server.tools.allowlist in .zqk/mcp/config.yaml.")
	help.AddExample("List exposed tool names", "%s mcp list-tools")
	help.AddExample("Include CLI command paths", "%s mcp list-tools --with-command")
	help.ExcludeFlag("columns")
	help.ExcludeFlag("ignore-scheduler-down")
	help.ExcludeFlag("format")
	help.ExcludeFlag("output")
	builder.WithHelpBuilder(help)
	builder.WithArgs(cobra.NoArgs)
	builder.AddBoolFlag("with-command", "", false, "Print the CLI command path for each tool when available (e.g. object list)")
	builder.WithCommonFlagsExcluding(cli.AddCommonFlagsExcluding, []string{"columns", "ignore-scheduler-down", "format", "output"})
	cmd := builder.Build()
	cli.RequireSession(cmd, false)
	return cmd
}
