// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	"github.com/spf13/cobra"
	clipkg "github.com/zqk-os/zqk/pkg/cli"
	"github.com/zqk-os/zqk/pkg/cliapp"
)

// NewObjectRefRemoveCommandBuilder creates a new object_ref_remove command
func NewObjectRefRemoveCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("remove")
	builder.WithShort("Remove references from an object")
	help := clipkg.DynamicHelpBuilder("Remove references from an object")
	help.WithDescriptionLines("Removes one or more references from a source object.")
	help.WithDescriptionLines("Can remove specific target IDs across reference fields, remove all references of a specific kind")
	help.WithDescriptionLines("using --kind, or clear all references on the object using --all.")
	help.AddExample("Remove specific requirement from backlog item", "%s object ref remove BLI-001 REQ-001")
	help.AddExample("Remove all criteria references", "%s object ref remove REQ-001 --kind criteria")
	help.AddExample("Purge all references on an object", "%s object ref remove BLI-001 --all")
	builder.WithHelpBuilder(help)
	builder.WithArgs(cobra.MinimumNArgs(1))
	builder.AddStringFlag("field", "", "", "Restrict removal to a specific reference field")
	builder.AddStringFlag("kind", "", "", "Remove all references pointing to objects of this kind")
	builder.AddBoolFlag("all", "", false, "Remove all references across all reference fields on the object")
	builder.AddBoolFlag("park", "", false, "Park parent execution plan (transition to paused) if remaining items reach zero instead of auto-completing")
	builder.WithCommonFlagsDefault(cli.AddCommonFlags)
	cmd := builder.Build()
	return cmd
}
