package bldr_cli_cmd_v1

import (
	"github.com/spf13/cobra"
	"github.com/zqk-os/zqk/internal/cli"
	clipkg "github.com/zqk-os/zqk/pkg/cli"
)

// NewObjectUpdateCommandBuilder creates a new object_update command
func NewObjectUpdateCommandBuilder() *cobra.Command {
	builder := clipkg.NewCRUDCommandBuilder("update", "update <id>[,id...] [id...]")
	builder.WithUpdateFlags()
	builder.WithDryRunFlag()
	builder.WithCommonFlagsDefault(cli.AddCommonFlags)
	builder.AddStringFlag("expected-updated-at", "", "", "Expected updated_at timestamp for optimistic locking")
	builder.AddBoolFlag("all", "", false, "Update all objects of a kind (requires --kind flag)")
	builder.AddStringFlag("kind", "", "", "Object kind (required when using --all)")
	builder.AddStringArrayFlag("filter", "", "Filter by field (format: field=value or field:value, can be used multiple times). Only applies when using --all")
	builder.AddBoolFlag("add-missing-fields", "", false, "Automatically add missing fields based on object spec (e.g., namespace_id)")
	builder.AddBoolFlag("relaxed", "", false, "Relax integrity constraints during update (allow references to objects that will be created later in batch operations)")
	builder.AddBoolFlag("force", "", false, "Force update even if object doesn't exist (create instead of fail)")
	builder.AddStringArrayFlag("add-ref", "", "Add a reference (format: field=id, e.g. milestone_refs=MIL-001). Validates target exists. Can be repeated. BLI-853.")
	builder.AddStringArrayFlag("remove-ref", "", "Remove a reference (format: field=id). Can be repeated. BLI-853.")
	builder.AddStringArrayFlag("unset-field", "", "Remove a field from the object (field name only; repeat flag per field). Cannot unset id, kind, created_at, created_by.")
	builder.AddBoolFlag("override", "", false, "Human interactive TTY snap-remedy only (blocked for non-TTY/agents). Prefer promote/demote. Records process debt.")
	builder.AddStringFlag("reason-code", "", "", "Required descriptive reason (≥5 words) when using --override")
	builder.AddStringFlag("ids", "", "", "Comma-separated list of object IDs (same as positional multi-ID / comma lists)")
	builder.WithShort("Update an existing object")
	help := clipkg.DynamicHelpBuilder("Update an existing object")
	help.WithDescriptionLines("Update one or more existing objects by ID.")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("IDs may be positional args, comma-separated (ID1,ID2), and/or --ids.")
	help.WithDescriptionLines("Multiple IDs use the same storage BulkUpdate path.")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("The update data can be provided via:")
	help.WithDescriptionLines("  - --file: Path to a YAML file containing the updates")
	help.WithDescriptionLines("  - --data: Inline YAML data")
	help.WithDescriptionLines("  - --field: Update one field (field=value or field:value). Parsed as JSON when valid (objects, arrays,")
	help.WithDescriptionLines("    quoted strings, numbers, booleans); otherwise kept as a literal string. For text with colons, use a JSON")
	help.WithDescriptionLines("    string (e.g. next_action=\"Done: shipped\") or --data.")
	help.WithDescriptionLines("  - --add-ref: Add a reference (field=id); validates target exists. BLI-853.")
	help.WithDescriptionLines("  - --remove-ref: Remove a reference (field=id).")
	help.WithDescriptionLines("  - --unset-field: Remove a non-immutable field from the object (repeatable). Use to drop stray keys (e.g. invalid test fields) without editing CAS YAML by hand.")
	help.WithDescriptionLines("  - --auto-status: Advance to the next lifecycle-valid status based on current status and lifecycle order.")
	help.WithDescriptionLines("  - --all: Update all objects of a kind (requires --kind)")
	help.WithDescriptionLines("  - --add-missing-fields: Automatically add missing fields based on object spec")
	help.WithDescriptionLines("  - stdin: YAML data piped from another command")
	help.AddExample("Update from file", "%s update BLI-626 --file updates.yaml")
	help.AddExample("Update from inline data", "%s update BLI-626 --data 'title: \"Updated Title\"'")
	help.AddExample("Update a single field", "%s update BLI-626 --field title=\"Updated Title\"")
	help.AddExample("Update multiple fields", "%s update BLI-626 --field title=\"New Title\" --field status=validated")
	help.AddExample("Update many IDs (comma-separated)", "%s update ATK-001,ATK-002 --field assignee_persona_ref=PER-DEFAULT-AGENT")
	help.AddExample("Text with colons (JSON string value)", "%s update CVS-001 --field 'next_action=\"Closed: matrix updated\"'")
	help.AddExample("Update all objects of a kind", "%s object update --all --kind backlog_item --add-missing-fields")
	help.AddExample("Update with optimistic locking", "%s update BLI-626 --field title=\"New Title\" --expected-updated-at \"2025-12-25T20:00:00Z\"")
	help.AddExample("Dry-run to see what would be updated", "%s update BLI-626 --field title=\"New Title\" --dry-run")
	help.AddExample("Add a reference (validates target exists)", "%s update BLI-626 --add-ref milestone_refs=MIL-001")
	help.AddExample("Remove a reference", "%s update BLI-626 --remove-ref milestone_refs=MIL-001")
	help.AddExample("Remove an invalid or stray field from the object", "%s update BLI-626 --unset-field stray_field")
	help.AddExample("Advance to next lifecycle status automatically", "%s update CRIT-9037 --auto-status")
	help.ExcludeFlag("format")
	help.ExcludeFlag("output")
	help.ExcludeFlag("verbose")
	help.ExcludeFlag("quiet")
	help.ExcludeFlag("timeout")
	help.ExcludeFlag("columns")
	builder.WithHelpBuilder(help)
	return builder.Build()
}
