// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	"github.com/spf13/cobra"
	"github.com/zqk-os/zqk/pkg/cliapp"
	clipkg "github.com/zqk-os/zqk/pkg/cli"
)

// NewObjectDraftSweepCommandBuilder creates a new object_draft_sweep command
func NewObjectDraftSweepCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("sweep")
	builder.WithShort("Delete (or dry-run) objects on the object draft plane")
	help := clipkg.DynamicHelpBuilder("Delete (or dry-run) objects on the object draft plane")
	help.WithDescriptionLines("Enumerates .zqk/object_drafts and deletes draft-plane YAML only.")
	help.WithDescriptionLines("Never deletes CAS-backed objects (skipped as cas_backed).")
	help.WithDescriptionLines("Default is dry-run; pass --all (or --max with filters) to apply deletes.")
	help.WithDescriptionLines("Applying deletes (--dry-run=false) requires RBAC permission delete:object_draft_plane")
	help.WithDescriptionLines("on the authenticated ACC (role-granted; parallel to delete:core). Dry-run stays open.")
	help.WithDescriptionLines("Unbound system context is refused — authenticate via ZQK_API_KEY / ACC seating.")
	help.AddExample("Dry-run (default): show what would be deleted", "%s object draft sweep --dry-run --all")
	help.AddExample("Apply deletes when ACC role grants delete:object_draft_plane", "%s object draft sweep --kind backlog_item --all --dry-run=false")
	help.AddExample("Apply with optional seat correlation", "%s object draft sweep --agent-id cursor-composer --id-prefix BLI- --max 10 --dry-run=false")
	help.ExcludeFlag("columns")
	help.ExcludeFlag("ignore-scheduler-down")
	builder.WithHelpBuilder(help)
	builder.WithArgs(cobra.NoArgs)
	builder.AddBoolFlag("dry-run", "", true, "List matching drafts without deleting")
	builder.AddBoolFlag("all", "", false, "Required to apply deletes across the matched set (fail closed without this or --max+filters)")
	builder.AddStringFlag("kind", "", "", "Limit to one object kind directory under object_drafts")
	builder.AddStringFlag("id-prefix", "", "", "Only ids with this prefix")
	builder.AddStringFlag("status", "", "", "Only drafts whose YAML status equals this value")
	builder.AddStringFlag("older-than", "", "", "Only drafts whose file mtime is older than this duration (e.g. 24h, 168h)")
	builder.AddIntFlag("max", "", 0, "Optional cap on deletions / would-delete listings")
	builder.AddStringFlag("agent-id", "", "", "Optional seat id for audit/correlation only; authorization is RBAC on the authenticated account")
	builder.WithCommonFlagsExcluding(cli.AddCommonFlagsExcluding, []string{"columns", "ignore-scheduler-down"})
	cmd := builder.Build()
	return cmd
}
