// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	"github.com/zqk-os/zqk/internal/cli"
	clipkg "github.com/zqk-os/zqk/pkg/cli"
	"github.com/spf13/cobra"
)

// NewObjectPplanCommandBuilder creates a new object_pplan command
func NewObjectPplanCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("pplan")
	builder.WithShort("Priority plan operations (current, next, prev, add, remove)")
	help := clipkg.DynamicHelpBuilder("Priority plan operations (current, next, prev, add, remove)")
	help.WithDescriptionLines("Priority plan operations for navigating and managing priority plans.")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("This command group provides operations for working with priority plans:")
	help.WithDescriptionLines("  - current: View backlog items for the current priority plan")
	help.WithDescriptionLines("  - next: Navigate to the next priority plan")
	help.WithDescriptionLines("  - prev: Navigate to the previous priority plan")
	help.WithDescriptionLines("  - add: Associate backlog item(s) with a priority plan (child-owned)")
	help.WithDescriptionLines("  - remove: Clear priority plan association from backlog item(s)")
	builder.WithHelpBuilder(help)
	builder.WithArgs(cobra.NoArgs)
	builder.WithCommonFlagsDefault(cli.AddCommonFlags)
	cmd := builder.Build()
	return cmd
}
