// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	"github.com/spf13/cobra"
	clipkg "github.com/zqk-os/zqk/pkg/cli"
)

// NewOpsOpsCommandBuilder creates a new ops_ops command
func NewOpsOpsCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("ops")
	builder.WithShort("Operations and utility commands")
	builder.WithCommonFlags(false, nil)
	cmd := builder.Build()
	return cmd
}
