// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	"github.com/spf13/cobra"
	"github.com/zqk-os/zqk/pkg/cliapp"
	clipkg "github.com/zqk-os/zqk/pkg/cli"
)

// NewQueryCommandBuilder creates a new query command
func NewQueryCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("query")
	builder.WithShort("Execute declarative ZPARQL graph queries")
	builder.WithAliases("zparql")
	help := clipkg.DynamicHelpBuilder("Execute declarative ZPARQL graph queries")
	help.WithDescriptionLines("Execute declarative graph queries across the knowledge kernel using the ZPARQL")
	help.WithDescriptionLines("graph pattern matching and relational traversal engine with cycle safety and")
	help.WithDescriptionLines("predicate pushdown.")
	help.AddExample("Find all planned backlog items", "%s query \"MATCH (b:backlog_item) WHERE b.status == 'planned' RETURN b.id, b.title;\"")
	help.AddExample("Multi-hop plan and criteria traversal", "%s query \"MATCH (p:priority_plan)-[:items]->(b:backlog_item)-[:criteria_refs]->(c:criteria) RETURN p.title AS plan, b.id AS bli, c.title AS criterion;\"")
	help.AddExample("Query from file formatted as JSON", "%s query -f query.zparql --format json")
	builder.WithHelpBuilder(help)
	builder.WithArgs(cobra.MaximumNArgs(1))
	builder.AddStringFlag("file", "f", "", "Path to file containing ZPARQL query")
	builder.AddStringFlag("format", "", "table", "Output format (table, json)")
	builder.WithCommonFlags(false, nil)
	cmd := builder.Build()
	cli.RequireStorage(cmd, false)
	cli.RequireSession(cmd, false)
	cli.RequireSchedulerCheck(cmd, false)
	return cmd
}
