// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	clipkg "github.com/lanceman/zqk/pkg/cli"
	"github.com/spf13/cobra"
)

// NewQuickQuickstartCommandBuilder creates a new quick_quickstart command
func NewQuickQuickstartCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("quickstart")
	builder.WithShort("Zero-friction project onboarding and quickstart guide")
	help := clipkg.DynamicHelpBuilder("Zero-friction project onboarding and quickstart guide")
	help.WithDescriptionLines("Alias surface under zqk quick for the same stranger-path quickstart guide.")
	builder.WithHelpBuilder(help)
	builder.WithCommonFlags(false, nil)
	cmd := builder.Build()
	return cmd
}
