package bldr_cli_cmd_v1

import (
	"github.com/lanceman/zqk/internal/cli"
	clipkg "github.com/lanceman/zqk/pkg/cli"
	"github.com/spf13/cobra"
)

// NewSchedulerScanTestsCommandBuilder creates a new scheduler_scan_tests command
func NewSchedulerScanTestsCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("scan-tests")
	builder.WithShort("Scan and schedule tests using the test scanner")
	help := clipkg.DynamicHelpBuilder("Scan and schedule tests using the test scanner")
	help.WithDescriptionLines("Scan Go test files and schedule them as scheduler jobs.")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("The scanner:")
	help.WithDescriptionLines("  - Identifies test functions in *_test.go files")
	help.WithDescriptionLines("  - Detects parallel safety (t.Parallel())")
	help.WithDescriptionLines("  - Bundles tests that can run safely in parallel")
	help.WithDescriptionLines("  - Schedules tests based on runtime metrics")
	help.WithDescriptionLines("  - Creates optimized scheduler jobs")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("Modes:")
	help.WithDescriptionLines("  --test <name>     - Scan and schedule a single test by name")
	help.WithDescriptionLines("  --tests <names>   - Scan and schedule multiple tests (comma-separated)")
	help.WithDescriptionLines("  --package <path>  - Scan and schedule all tests in one or more packages (comma-separated, e.g. ./pkg/a,./pkg/b)")
	help.WithDescriptionLines("  --all             - Scan and schedule all tests in the project")
	help.WithDescriptionLines("  --load-bundle <name> - Load a previously saved bundle")
	help.WithDescriptionLines("  --load-bundles <names> - Load multiple bundles (comma-separated) for regression")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("Bundle Management:")
	help.WithDescriptionLines("  --save-bundle <name> - Save created bundles with this name")
	help.WithDescriptionLines("  --load-bundle <name>  - Load a previously saved bundle")
	help.WithDescriptionLines("  --load-bundles <names> - Load multiple saved bundles (comma-separated)")
	help.WithDescriptionLines("  --list-bundles       - List all saved bundles")
	help.WithDescriptionLines("  --show-bundle        - Show bundle details without scheduling")
	help.WithDescriptionLines("  --only <indexes>     - Run only specified test indexes (e.g., 0,2,5)")
	help.WithDescriptionLines("  --skip <indexes>     - Skip specified test indexes (e.g., 1,3)")
	help.AddExample("Schedule a single test", "%s scheduler scan-tests --test TestMyFeature")
	help.AddExample("Schedule all tests in a package", "%s scheduler scan-tests --package ./pkg/storage")
	help.AddExample("Schedule all tests in multiple packages (comma-separated)", "%s scheduler scan-tests --package ./pkg/paths,./pkg/agentdelivery")
	help.AddExample("Schedule all tests in project", "%s scheduler scan-tests --all")
	help.AddExample("Run regression: schedule multiple saved bundles", "%s scheduler scan-tests --load-bundles pkg-storage-1,pkg-scheduler-2,cmd-zqk-system-2")
	help.ExcludeFlag("format")
	help.ExcludeFlag("output")
	help.ExcludeFlag("verbose")
	help.ExcludeFlag("quiet")
	help.ExcludeFlag("timeout")
	help.ExcludeFlag("columns")
	builder.WithHelpBuilder(help)
	builder.AddStringFlag("test", "", "", "Single test name to schedule")
	builder.AddStringFlag("tests", "", "", "Comma-separated list of test names to schedule")
	builder.AddStringFlag("package", "", "", "One package path or comma-separated paths (e.g., ./pkg/storage or ./pkg/a,./pkg/b)")
	builder.AddBoolFlag("all", "", false, "Schedule all tests in the project")
	builder.AddIntFlag("max-bundle-size", "", 10, "Maximum number of tests per bundle")
	builder.AddIntFlag("max-parallel", "", 4, "Maximum number of parallel bundles")
	builder.AddStringFlag("save-bundle", "", "", "Save the created bundles with this name")
	builder.AddStringFlag("load-bundle", "", "", "Load a previously saved bundle")
	builder.AddStringFlag("load-bundles", "", "", "Load multiple saved bundles (comma-separated names); schedules all for regression runs")
	builder.AddStringFlag("only", "", "", "Comma-separated list of test indexes to run (e.g., 0,2,5)")
	builder.AddStringFlag("skip", "", "", "Comma-separated list of test indexes to skip (e.g., 1,3)")
	builder.AddBoolFlag("list-bundles", "", false, "List all saved bundles")
	builder.AddBoolFlag("show-bundle", "", false, "Show bundle details without scheduling")
	builder.AddBoolFlag("overwrite", "", false, "Overwrite existing bundle when saving")
	builder.AddBoolFlag("merge", "", false, "Merge new tests with existing bundle (adds new, keeps existing)")
	builder.AddBoolFlag("remove-missing", "", false, "Remove tests from bundle that no longer exist (use with --merge)")
	builder.AddBoolFlag("setup-bundles", "", false, "Set up initial bundles for the project (scans all tests and creates bundles)")
	builder.AddBoolFlag("delete-all-bundles", "", false, "Delete all saved test bundles from .zqk/test-bundles (does not remove scheduler_job objects like SCH-run-bundle-*; use before --setup-bundles to recreate)")
	builder.AddBoolFlag("suggest-timeout", "", false, "Print suggested timeout in seconds for --package (dynamic from timing data and package defaults); if multiple comma-separated packages, prints the maximum; exit without scheduling")
	builder.WithCommonFlagsExcluding(cli.AddCommonFlagsExcluding, []string{"format", "output", "verbose", "quiet", "timeout", "columns"})
	cmd := builder.Build()
	return cmd
}
