// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

const (
	// Command name constants
	CommandService = "service"
	CmdService     = "service"

	// Flag name constants
)
