// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	"github.com/lanceman/zqk/internal/cli"
	clipkg "github.com/lanceman/zqk/pkg/cli"
	"github.com/spf13/cobra"
)

// NewSpecCommandBuilder creates a new spec command
func NewSpecCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("spec")
	builder.WithShort("Spec operations (list and manage object specifications)")
	help := clipkg.DynamicHelpBuilder("Spec operations (list and manage object specifications)")
	help.WithDescriptionLines("Programmatic management of object specifications (object_spec).")
	builder.WithHelpBuilder(help)
	builder.WithCommonFlagsDefault(cli.AddCommonFlags)
	cmd := builder.Build()
	return cmd
}
