// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	"github.com/spf13/cobra"
	"github.com/zqk-os/zqk/internal/cli"
	clipkg "github.com/zqk-os/zqk/pkg/cli"
)

// NewStateTsdbCommandBuilder creates a new state_tsdb command
func NewStateTsdbCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("tsdb")
	builder.WithShort("Inspect embedded kernel time-series database (TSDB) metrics and execution history")
	help := clipkg.DynamicHelpBuilder("Inspect embedded kernel time-series database (TSDB) metrics and execution history")
	help.WithDescriptionLines("Queries, aggregates, and inspects time-series performance data recorded in the kernel TSDB")
	help.WithDescriptionLines("(.zqk/scheduler/tsdb) and chunked metrics directories (.zqk/metrics).")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("  Inspect aggregate TSDB performance telemetry")
	help.WithDescriptionLines("  zqk state tsdb")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("  View time-series execution metrics for the last 24 hours")
	help.WithDescriptionLines("  zqk state tsdb --since 24h")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("  Inspect metrics for a specific scheduler job")
	help.WithDescriptionLines("  zqk state tsdb --job-id SCH-autofix-run")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("  Tail recent raw TSDB points in JSON format")
	help.WithDescriptionLines("  zqk state tsdb --limit 50 --format json")
	help.AddExample("View TSDB performance summary", "%s state tsdb")
	help.AddExample("Filter by job ID", "%s state tsdb --job-id SCH-cap-orchestrator")
	builder.WithHelpBuilder(help)
	builder.WithArgs(cobra.NoArgs)
	builder.AddIntFlag("limit", "l", 20, "Maximum number of recent TSDB points to display")
	builder.AddStringFlag("since", "s", "", "Time window filter (e.g. 1h, 6h, 24h, 7d, 30d)")
	builder.AddStringFlag("job-id", "j", "", "Filter execution metrics by specific scheduler job ID")
	builder.AddBoolFlag("summary", "", true, "Output aggregated performance and latency summary")
	builder.AddStringFlag("format", "f", "text", "Output format (text or json)")
	builder.WithCommonFlagsDefault(cli.AddCommonFlags)
	cmd := builder.Build()
	return cmd
}
