// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

const (
	// Command name constants
	CommandSystemSyncGitHooks = "sync-git-hooks"
	CmdSystemSyncGitHooks     = "sync-git-hooks"

	// Flag name constants
	FlagSystemSyncGitHooksDryRun  = "dry-run"
	FlagSystemSyncGitHooksSource  = "source"
	FlagSystemSyncGitHooksTarget  = "target"
	FlagSystemSyncGitHooksList    = "list"
	FlagSystemSyncGitHooksDisable = "disable"
	FlagSystemSyncGitHooksEnable  = "enable"
)
