// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	"github.com/spf13/cobra"
	clipkg "github.com/zqk-os/zqk/pkg/cli"
)

// NewSystemValidateCommandBuilder creates a new system_validate command
func NewSystemValidateCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("validate [object-id]")
	builder.WithShort("Validate object(s) against schema")
	help := clipkg.DynamicHelpBuilder("Validate object(s) against schema")
	help.WithDescriptionLines("Validate object(s) against schema and check references.")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("This command validates objects against their schema definitions and checks")
	help.WithDescriptionLines("that all references are valid. It can validate:")
	help.WithDescriptionLines("  - A specific object by ID")
	help.WithDescriptionLines("  - All objects of a specific kind (--kind)")
	help.WithDescriptionLines("  - All in-scope project objects (default when neither an ID nor --kind is given; same as --all)")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("  Validate a specific object")
	help.WithDescriptionLines("  zqk system validate BLI-657")
	help.WithDescriptionLines("  Validate all backlog items")
	help.WithDescriptionLines("  zqk system validate --kind backlog_item")
	help.WithDescriptionLines("  Validate all in-scope objects (default)")
	help.WithDescriptionLines("  zqk system validate")
	help.WithDescriptionLines("  Validate all (explicit)")
	help.WithDescriptionLines("  zqk system validate --all")
	help.WithDescriptionLines("  Attempt to fix validation errors")
	help.WithDescriptionLines("  zqk system validate --fix")
	builder.WithHelpBuilder(help)
	builder.WithCommonFlags(false, nil)
	cmd := builder.Build()
	return cmd
}
