// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

const (
	// Command name constants
	CommandSystemRebuildGraphProjection = "rebuild-graph-projection"
	CmdSystemRebuildGraphProjection     = "rebuild-graph-projection"

	// Flag name constants
	FlagSystemRebuildGraphProjectionDryRun = "dry-run"
)
