// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

const (
	// Command name constants
	CommandSystemObjectHygieneScan = "object-hygiene-scan"
	CmdSystemObjectHygieneScan     = "object-hygiene-scan"

	// Flag name constants
	FlagSystemObjectHygieneScanRulesFile  = "rules-file"
	FlagSystemObjectHygieneScanEmitEvents = "emit-events"
)
