// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	"github.com/spf13/cobra"
	clipkg "github.com/zqk-os/zqk/pkg/cli"
)

// NewSystemReportsBlockersCommandBuilder creates a new system_reports_blockers command
func NewSystemReportsBlockersCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("blockers")
	builder.WithShort("Get Dependencies & Blockers (D&B)")
	help := clipkg.DynamicHelpBuilder("Get Dependencies & Blockers (D&B)")
	help.WithDescriptionLines("Calculate and display Dependencies & Blockers (D&B), identifying potential")
	help.WithDescriptionLines("dependencies and blockers that may impact project delivery.")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("The D&B analysis is enhanced with Git commit data when available:")
	help.WithDescriptionLines("  - Code-level dependencies from file co-changes")
	help.WithDescriptionLines("  - Potential blockers from stale files or irregular patterns")
	help.WithDescriptionLines("  - Commit relationship analysis")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("Dependencies are categorized by:")
	help.WithDescriptionLines("  - Type: code, work_item, external")
	help.WithDescriptionLines("  - Severity: low, medium, high, critical")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("Blockers are identified from:")
	help.WithDescriptionLines("  - Risk/blocker objects in the system")
	help.WithDescriptionLines("  - Code patterns indicating blocked work")
	help.WithDescriptionLines("  - Commit frequency anomalies")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("  Get dependencies and blockers")
	help.WithDescriptionLines("  zqk reports blockers")
	help.WithDescriptionLines("  Get as JSON")
	help.WithDescriptionLines("  zqk reports blockers --format json")
	help.WithDescriptionLines("  Get with commit data explicitly enabled")
	help.WithDescriptionLines("  zqk reports blockers --include-commit-data")
	builder.WithHelpBuilder(help)
	builder.WithCommonFlags(false, nil)
	cmd := builder.Build()
	return cmd
}
