// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	"github.com/spf13/cobra"
	clipkg "github.com/zqk-os/zqk/pkg/cli"
	"github.com/zqk-os/zqk/pkg/cliapp"
)

// NewSystemRestartCommandBuilder creates a new system_restart command
func NewSystemRestartCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("restart")
	builder.WithShort("Restart all ZQK daemons cleanly")
	help := clipkg.DynamicHelpBuilder("Restart all ZQK daemons cleanly")
	help.WithDescriptionLines("Restarts the scheduler service, ambient daemon, and background daemons.")
	help.AddExample("Restart the entire system", "%s system restart")
	help.ExcludeFlag("columns")
	help.ExcludeFlag("ignore-scheduler-down")
	builder.WithHelpBuilder(help)
	builder.WithCommonFlags(false, nil)
	cmd := builder.Build()
	cli.RequireStorage(cmd, false)
	cli.RequireSession(cmd, false)
	cli.RequireSchedulerCheck(cmd, false)
	return cmd
}
