// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	"github.com/spf13/cobra"
	clipkg "github.com/zqk-os/zqk/pkg/cli"
)

// NewSystemMigrateCasCommandBuilder creates a new system_migrate_cas command
func NewSystemMigrateCasCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("migrate-cas")
	builder.WithShort("Migrate legacy UUID identities to deterministic CAS hashes")
	help := clipkg.DynamicHelpBuilder("Migrate legacy UUID identities to deterministic CAS hashes")
	help.WithDescriptionLines("Scans the .zqk/process/ object tree, migrates any legacy UUID identities to")
	help.WithDescriptionLines("deterministic CAS (Content-Addressable Storage) SHA256 hashes, and safely cleans")
	help.WithDescriptionLines("up orphaned object files.")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("This command helps transition legacy object IDs to the new stable CAS storage")
	help.WithDescriptionLines("scheme.")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("  Migrate all legacy items")
	help.WithDescriptionLines("  zqk system migrate-cas")
	help.WithDescriptionLines("  Migrate but keep old files (not recommended)")
	help.WithDescriptionLines("  zqk system migrate-cas --remove-old-files=false")
	builder.WithHelpBuilder(help)
	builder.WithCommonFlags(false, nil)
	cmd := builder.Build()
	return cmd
}
