// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	"github.com/spf13/cobra"
	clipkg "github.com/zqk-os/zqk/pkg/cli"
)

// NewSystemValidateScenarioCommandBuilder creates a new system_validate_scenario command
func NewSystemValidateScenarioCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("validate-scenario")
	builder.WithShort("Execute a programmatic validation scenario")
	help := clipkg.DynamicHelpBuilder("Execute a programmatic validation scenario")
	help.WithDescriptionLines("Execute a sequence of programmatic validation steps defined in a scenario file.")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("This command uses the scenario executor to run command, regex, and file existence checks")
	help.WithDescriptionLines("to natively verify that policies, architectural mandates, and tests are satisfied.")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("  Run a specific scenario")
	help.WithDescriptionLines("  zqk system validate-scenario --file scenarios/observability_check.yaml")
	builder.WithHelpBuilder(help)
	builder.WithCommonFlags(false, nil)
	cmd := builder.Build()
	return cmd
}
