// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

const (
	// Command name constants
	CommandSystemSealSkill = "seal-skill <name>"
	CmdSystemSealSkill     = "seal-skill <name>"

	// Flag name constants
	FlagSystemSealSkillVerify  = "verify"
	FlagSystemSealSkillVersion = "version"
	FlagSystemSealSkillIssuer  = "issuer"
)
