// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	"github.com/spf13/cobra"
	clipkg "github.com/zqk-os/zqk/pkg/cli"
)

// NewSystemHealthDataCommandBuilder creates a new system_health_data command
func NewSystemHealthDataCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("health-data")
	builder.WithShort("Output aggregated system-health data for dashboard")
	help := clipkg.DynamicHelpBuilder("Output aggregated system-health data for dashboard")
	help.WithDescriptionLines("Outputs quarantine and other system-health data in one payload. Use --format")
	help.WithDescriptionLines("json or --format yaml for dashboard/consumer use; default is a short table")
	help.WithDescriptionLines("summary.")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("Additional sections (e.g. check summary) may be added in future.")
	builder.WithHelpBuilder(help)
	builder.WithCommonFlags(false, nil)
	cmd := builder.Build()
	return cmd
}
