// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	"github.com/spf13/cobra"
	clipkg "github.com/zqk-os/zqk/pkg/cli"
)

// NewSystemPromptBuilderCommandBuilder creates a new system_prompt_builder command
func NewSystemPromptBuilderCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("prompt-builder [query]")
	builder.WithShort("Builds a topologically sorted context window prompt using the Vectorization Engine")
	help := clipkg.DynamicHelpBuilder("Builds a topologically sorted context window prompt using the Vectorization Engine")
	help.WithDescriptionLines("Builds a topologically sorted context window prompt by querying the graph for")
	help.WithDescriptionLines("initial matches and then walking the structural graph up to the root Policies, returning")
	help.WithDescriptionLines("the optimal token-budgeted prompt context.")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("Example:")
	help.WithDescriptionLines("  zqk system prompt-builder \"authentication mechanisms\" --budget 4000")
	builder.WithHelpBuilder(help)
	builder.WithCommonFlags(false, nil)
	cmd := builder.Build()
	return cmd
}
