// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	"github.com/spf13/cobra"
	clipkg "github.com/zqk-os/zqk/pkg/cli"
)

// NewSystemAutoFixProcessPendingCommandBuilder creates a new system_auto_fix_process_pending command
func NewSystemAutoFixProcessPendingCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("auto-fix-process-pending")
	builder.WithShort("Process all pending autofix batch files in .zqk/autofix/ (internal, scheduler)")
	help := clipkg.DynamicHelpBuilder("Process all pending autofix batch files in .zqk/autofix/ (internal, scheduler)")
	help.WithDescriptionLines("Discovers all AUTOFIX-*.json under .zqk/autofix/ and processes each via the")
	help.WithDescriptionLines("standardized")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("pipeline (INGEST → NORMALIZE → COMMIT → FINALIZE) per")
	help.WithDescriptionLines("docs/architecture/data-pipeline-lifecycle.md.")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("Used by SCH-autofix-process-pending so autofix files don't build up; can be")
	help.WithDescriptionLines("triggered when")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("batches are submitted or run on a timer. Internal command (hidden from main")
	help.WithDescriptionLines("help).")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("  Process pending (scheduler or manual)")
	help.WithDescriptionLines("  zqk system auto-fix-process-pending")
	help.WithDescriptionLines("  With explicit project root")
	help.WithDescriptionLines("  zqk system auto-fix-process-pending --project-root /path/to/project")
	builder.WithHelpBuilder(help)
	builder.WithCommonFlags(false, nil)
	cmd := builder.Build()
	return cmd
}
