// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

const (
	// Command name constants
	CommandSystemSeedDefaultAgentSeating = "seed-default-agent-seating"
	CmdSystemSeedDefaultAgentSeating     = "seed-default-agent-seating"

	// Flag name constants
)
