// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	"github.com/spf13/cobra"
	clipkg "github.com/zqk-os/zqk/pkg/cli"
)

// NewSystemQuarantineReportCommandBuilder creates a new system_quarantine_report command
func NewSystemQuarantineReportCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("quarantine-report")
	builder.WithShort("Report contents of the quarantine folder (data for dashboard)")
	help := clipkg.DynamicHelpBuilder("Report contents of the quarantine folder (data for dashboard)")
	help.WithDescriptionLines("Outputs quarantine stats (file counts by source). Use --format json or --format")
	help.WithDescriptionLines("yaml for structured data suitable for a dashboard or other consumers; default is")
	help.WithDescriptionLines("a human-readable table.")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("See .zqk/process/system-health/QUARANTINE_AND_ANALYSIS.md for what goes in")
	help.WithDescriptionLines("quarantine and the dashboard data story.")
	builder.WithHelpBuilder(help)
	builder.WithCommonFlags(false, nil)
	cmd := builder.Build()
	return cmd
}
