// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	"github.com/spf13/cobra"
	clipkg "github.com/zqk-os/zqk/pkg/cli"
)

// NewSystemReportsPcsCommandBuilder creates a new system_reports_pcs command
func NewSystemReportsPcsCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("pcs")
	builder.WithShort("Get Project Confidence Score (PCS)")
	help := clipkg.DynamicHelpBuilder("Get Project Confidence Score (PCS)")
	help.WithDescriptionLines("Calculate and display the Project Confidence Score (PCS), a metric that")
	help.WithDescriptionLines("indicates overall project health and confidence level (0-100).")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("The PCS is enhanced with Git commit data when available:")
	help.WithDescriptionLines("  - Commit frequency and patterns")
	help.WithDescriptionLines("  - Recent activity levels")
	help.WithDescriptionLines("  - Code change momentum")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("Higher scores indicate:")
	help.WithDescriptionLines("  - More completed work items")
	help.WithDescriptionLines("  - Healthy commit patterns")
	help.WithDescriptionLines("  - Positive development momentum")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("Lower scores may indicate:")
	help.WithDescriptionLines("  - Low completion rates")
	help.WithDescriptionLines("  - Irregular commit patterns")
	help.WithDescriptionLines("  - Declining activity")
	help.WithDescriptionLines("")
	help.WithDescriptionLines("  Get PCS score")
	help.WithDescriptionLines("  zqk reports pcs")
	help.WithDescriptionLines("  Get PCS as JSON")
	help.WithDescriptionLines("  zqk reports pcs --format json")
	help.WithDescriptionLines("  Get PCS with commit data explicitly enabled")
	help.WithDescriptionLines("  zqk reports pcs --include-commit-data")
	builder.WithHelpBuilder(help)
	builder.WithCommonFlags(false, nil)
	cmd := builder.Build()
	return cmd
}
