// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

const (
	// Command name constants
	CommandTraySign = "sign <name>"
	CmdTraySign     = "sign <name>"

	// Flag name constants
	FlagTraySignKeyPath = "key-path"
)
