// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

import (
	"github.com/spf13/cobra"
	clipkg "github.com/zqk-os/zqk/pkg/cli"
	"github.com/zqk-os/zqk/pkg/cliapp"
)

// NewVendorCursorCursorCommandBuilder creates a new vendor_cursor_cursor command
func NewVendorCursorCursorCommandBuilder() *cobra.Command {
	builder := clipkg.NewCommandBuilder("cursor")
	builder.WithShort("Cursor IDE integrations and adapters")
	help := clipkg.DynamicHelpBuilder("Cursor IDE integrations and adapters")
	help.WithDescriptionLines("Cursor-specific MCP adapters, AppleScript automation bridges,")
	help.WithDescriptionLines("and environment configurations.")
	builder.WithHelpBuilder(help)
	builder.WithCommonFlagsDefault(cli.AddCommonFlags)
	cmd := builder.Build()
	return cmd
}
