// Code generated by zqk-admin system generate-command-builders. DO NOT EDIT.

package bldr_cli_cmd_v1

const (
	// Command name constants
	CommandWorkflowGenTracePipeline = "gen-trace-pipeline"
	CmdWorkflowGenTracePipeline     = "gen-trace-pipeline"

	// Flag name constants
)
