// Code generated by pkg/specbuilder/instance_builders/codegen.go from lifecycle YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package shared_convergence_sessions

type Status string

const (
	StatusAbandoned  Status = "abandoned"
	StatusActive     Status = "active"
	StatusArchived   Status = "archived"
	StatusCompleted  Status = "completed"
	StatusConceptual Status = "conceptual"
	StatusDraft      Status = "draft"
	StatusError      Status = "error"
	StatusEscalated  Status = "escalated"
	StatusOriginated Status = "originated"
	StatusPaused     Status = "paused"
)
