// Lock operation names for RunInLockWithLogger / RunInRLockWithLogger.
// CONSTANTS_AND_DRY_INVENTORY_PLAN Phase A.
package objects

const (
	LockNameFieldDiscoveryGetCommonCheckLoaded = "field_discovery_get_common_check_loaded"
	LockNameFieldDiscoveryGetCommonCopy        = "field_discovery_get_common_copy"
	LockNameFieldRegistryGetAllCheckLoaded     = "field_registry_get_all_check_loaded"
	LockNameFieldRegistryGetAllCopy            = "field_registry_get_all_copy"
	LockNameFieldRegistryLoadCheck             = "field_registry_load_check"
	LockNameFieldRegistryLoadUpdate            = "field_registry_load_update"
	LockNameFieldRegistryReload                = "field_registry_reload"
	LockNameFieldRegistryTryReload             = "field_registry_try_reload"
	LockNameKindMapperGetDirCheckInit          = "kind_mapper_get_dir_check_init"
	LockNameKindMapperGetDirLookup             = "kind_mapper_get_dir_lookup"
	LockNameKindMapperGetKindCheckInit         = "kind_mapper_get_kind_check_init"
	LockNameKindMapperGetKindLookup            = "kind_mapper_get_kind_lookup"
	LockNameKindMapperInitializeCheck          = "kind_mapper_initialize_check"
	LockNameKindMapperInitializeUpdate         = "kind_mapper_initialize_update"
	LockNameKindMapperReload                   = "kind_mapper_reload"
	LockNameKindMapperSetDirectories           = "kind_mapper_set_directories"
	LockNameKindMappingsConfigGetBackendConfig = "kind_mappings_config_get_backend_config"
	LockNameKindMappingsConfigGetBackendType   = "kind_mappings_config_get_backend_type"
	LockNameKindMappingsConfigSetBackendType   = "kind_mappings_config_set_backend_type"
	LockNameKindMappingsDynamicGetAll          = "kind_mappings_dynamic_get_all"
	LockNameKindMappingsDynamicGetAllCheckInit = "kind_mappings_dynamic_get_all_check_init"
	LockNameKindSynonymsResolve                = "kind_synonyms_resolve"
	LockNameLifecycleLoaderClearCache          = "lifecycle_loader_clear_cache"
	LockNameLifecycleLoaderDoubleCheckCache    = "lifecycle_loader_double_check_cache"
	LockNameLifecycleLoaderEnsureReadyDir      = "lifecycle_loader_ensure_ready_dir"
	LockNameLifecycleLoaderInvalidate          = "lifecycle_loader_invalidate"
	LockNameStatusNormalizeLookup              = "status_normalize_lookup"
	LockNameStatusNormalizeRegisterAlias       = "status_normalize_register_alias"
	LockNameSpecLoaderEnsureReadyDir           = "spec_loader_ensure_ready_dir"
	LockNameSynonymResolverGet                 = "synonym_resolver_get"
	LockNameSynonymResolverGetAll              = "synonym_resolver_get_all"
	LockNameSynonymResolverGetLoader           = "synonym_resolver_get_loader"
	LockNameSynonymResolverInitGenerated       = "synonym_resolver_init_generated"
	LockNameSynonymResolverInitUpdate          = "synonym_resolver_init_update"
	LockNameSynonymResolverSetLoader           = "synonym_resolver_set_loader"
	LockNameSynonymResolverSetProvider         = "synonym_resolver_set_provider"
	LockNameSynonymResolverValidateCopy        = "synonym_resolver_validate_copy"
	LockNameSystemFieldsLoadCheck              = "system_fields_load_check"
	LockNameSystemFieldsLoadUpdate             = "system_fields_load_update"
	LockNameSystemFieldsReload                 = "system_fields_reload"
)
