// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec/lifecycle YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package change_journal_entry

import (
	base_objectenum "github.com/zqk-os/zqk/pkg/specbuilder/bldr_enum_v1/base_object"
	shared_change_journal_entriesenum "github.com/zqk-os/zqk/pkg/specbuilder/bldr_enum_v1/shared_change_journal_entries"
)

type ChangeType string

const (
	ChangeTypeCreate      ChangeType = "create"
	ChangeTypeDelete      ChangeType = "delete"
	ChangeTypeHealthCheck ChangeType = "health_check"
	ChangeTypeImport      ChangeType = "import"
	ChangeTypeUpdate      ChangeType = "update"
)

type Plane = base_objectenum.Plane

const (
	PlaneApoptotic Plane = base_objectenum.PlaneApoptotic
	PlaneDraft     Plane = base_objectenum.PlaneDraft
	PlanePromoted  Plane = base_objectenum.PlanePromoted
	PlaneStaged    Plane = base_objectenum.PlaneStaged
)

type PriorityTier = base_objectenum.PriorityTier

const (
	PriorityTierP0 PriorityTier = base_objectenum.PriorityTierP0
	PriorityTierP1 PriorityTier = base_objectenum.PriorityTierP1
	PriorityTierP2 PriorityTier = base_objectenum.PriorityTierP2
	PriorityTierP3 PriorityTier = base_objectenum.PriorityTierP3
)

type SourceType = base_objectenum.SourceType

const (
	SourceTypeExternal SourceType = base_objectenum.SourceTypeExternal
	SourceTypeImported SourceType = base_objectenum.SourceTypeImported
	SourceTypeInternal SourceType = base_objectenum.SourceTypeInternal
)

type Status = shared_change_journal_entriesenum.Status

const (
	StatusAggregated Status = shared_change_journal_entriesenum.StatusAggregated
	StatusArchived   Status = shared_change_journal_entriesenum.StatusArchived
	StatusCompleted  Status = shared_change_journal_entriesenum.StatusCompleted
	StatusConceptual Status = shared_change_journal_entriesenum.StatusConceptual
	StatusError      Status = shared_change_journal_entriesenum.StatusError
	StatusFailed     Status = shared_change_journal_entriesenum.StatusFailed
	StatusOriginated Status = shared_change_journal_entriesenum.StatusOriginated
	StatusPending    Status = shared_change_journal_entriesenum.StatusPending
	StatusReverted   Status = shared_change_journal_entriesenum.StatusReverted
)
