// Code generated by scripts/generate_enum_tests.py; DO NOT EDIT.

package technical_debt

import (
	"testing"
)

func TestEnums_Completeness(t *testing.T) {
	tests := []struct {
		name string
		val  string
	}{
		{"DebtTypeComplexity", string(DebtTypeComplexity)},
		{"DebtTypeDocumentation", string(DebtTypeDocumentation)},
		{"DebtTypeInfrastructure", string(DebtTypeInfrastructure)},
		{"DebtTypeMaintainability", string(DebtTypeMaintainability)},
		{"DebtTypeObservability", string(DebtTypeObservability)},
		{"DebtTypePerformance", string(DebtTypePerformance)},
		{"DebtTypeProcess", string(DebtTypeProcess)},
		{"DebtTypeSecurity", string(DebtTypeSecurity)},
		{"DebtTypeTesting", string(DebtTypeTesting)},
		{"DebtTypeTooling", string(DebtTypeTooling)},
		{"ImpactAssessmentCritical", string(ImpactAssessmentCritical)},
		{"ImpactAssessmentHigh", string(ImpactAssessmentHigh)},
		{"ImpactAssessmentLow", string(ImpactAssessmentLow)},
		{"ImpactAssessmentMedium", string(ImpactAssessmentMedium)},
		{"PlaneApoptotic", string(PlaneApoptotic)},
		{"PlaneDraft", string(PlaneDraft)},
		{"PlanePromoted", string(PlanePromoted)},
		{"PlaneStaged", string(PlaneStaged)},
		{"PriorityTierP0", string(PriorityTierP0)},
		{"PriorityTierP1", string(PriorityTierP1)},
		{"PriorityTierP2", string(PriorityTierP2)},
		{"PriorityTierP3", string(PriorityTierP3)},
		{"SourceTypeExternal", string(SourceTypeExternal)},
		{"SourceTypeImported", string(SourceTypeImported)},
		{"SourceTypeInternal", string(SourceTypeInternal)},
		{"StatusArchived", string(StatusArchived)},
		{"StatusConceptual", string(StatusConceptual)},
		{"StatusDeferred", string(StatusDeferred)},
		{"StatusError", string(StatusError)},
		{"StatusIdentified", string(StatusIdentified)},
		{"StatusInProgress", string(StatusInProgress)},
		{"StatusOriginated", string(StatusOriginated)},
		{"StatusPlanned", string(StatusPlanned)},
		{"StatusResolved", string(StatusResolved)},
		{"StatusVerifying", string(StatusVerifying)},
	}
	for _, tt := range tests {
		if tt.val == "" {
			t.Errorf("constant %s has empty value", tt.name)
		}
	}
}
