// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec/lifecycle YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package agent_onboarding_preparation

import (
	base_objectenum "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/base_object"
	shared_agent_onboarding_preparationsenum "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/shared_agent_onboarding_preparations"
)

type AgentType string

const (
	AgentTypeCoderAgent         AgentType = "coder_agent"
	AgentTypeDevopsAgent        AgentType = "devops_agent"
	AgentTypeDocumentationAgent AgentType = "documentation_agent"
	AgentTypeObserver           AgentType = "observer"
	AgentTypeOptimizationAgent  AgentType = "optimization_agent"
	AgentTypeTestAgent          AgentType = "test_agent"
)

type PreparationStatus string

const (
	PreparationStatusBlocked    PreparationStatus = "blocked"
	PreparationStatusComplete   PreparationStatus = "complete"
	PreparationStatusInProgress PreparationStatus = "in_progress"
	PreparationStatusNotStarted PreparationStatus = "not_started"
	PreparationStatusReady      PreparationStatus = "ready"
)

type PriorityTier = base_objectenum.PriorityTier

const (
	PriorityTierP0 PriorityTier = base_objectenum.PriorityTierP0
	PriorityTierP1 PriorityTier = base_objectenum.PriorityTierP1
	PriorityTierP2 PriorityTier = base_objectenum.PriorityTierP2
	PriorityTierP3 PriorityTier = base_objectenum.PriorityTierP3
)

type SourceType = base_objectenum.SourceType

const (
	SourceTypeExternal SourceType = base_objectenum.SourceTypeExternal
	SourceTypeImported SourceType = base_objectenum.SourceTypeImported
	SourceTypeInternal SourceType = base_objectenum.SourceTypeInternal
)

type Status = shared_agent_onboarding_preparationsenum.Status

const (
	StatusActive     Status = shared_agent_onboarding_preparationsenum.StatusActive
	StatusArchived   Status = shared_agent_onboarding_preparationsenum.StatusArchived
	StatusComplete   Status = shared_agent_onboarding_preparationsenum.StatusComplete
	StatusError      Status = shared_agent_onboarding_preparationsenum.StatusError
	StatusInProgress Status = shared_agent_onboarding_preparationsenum.StatusInProgress
	StatusPending    Status = shared_agent_onboarding_preparationsenum.StatusPending
)
