// Code generated by scripts/generate_enum_tests.py; DO NOT EDIT.

package shared_questions

import (
	"testing"
)

func TestEnums_Completeness(t *testing.T) {
	tests := []struct {
		name string
		val  string
	}{
		{"StatusAnswered", string(StatusAnswered)},
		{"StatusConceptual", string(StatusConceptual)},
		{"StatusDeferred", string(StatusDeferred)},
		{"StatusError", string(StatusError)},
		{"StatusOpen", string(StatusOpen)},
		{"StatusOriginated", string(StatusOriginated)},
		{"StatusResolved", string(StatusResolved)},
	}
	for _, tt := range tests {
		if tt.val == "" {
			t.Errorf("constant %s has empty value", tt.name)
		}
	}
}
