// Code generated by scripts/generate_enum_tests.py; DO NOT EDIT.

package shared_releases

import (
	"testing"
)

func TestEnums_Completeness(t *testing.T) {
	tests := []struct {
		name string
		val  string
	}{
		{"StatusArchived", string(StatusArchived)},
		{"StatusCancelled", string(StatusCancelled)},
		{"StatusConceptual", string(StatusConceptual)},
		{"StatusError", string(StatusError)},
		{"StatusInProgress", string(StatusInProgress)},
		{"StatusOriginated", string(StatusOriginated)},
		{"StatusPlanned", string(StatusPlanned)},
		{"StatusReleased", string(StatusReleased)},
	}
	for _, tt := range tests {
		if tt.val == "" {
			t.Errorf("constant %s has empty value", tt.name)
		}
	}
}
