package cas

import (
	pkgctx "github.com/zqk-os/zqk/pkg/context"
	"github.com/zqk-os/zqk/pkg/logging"
)

const ConstStreamFailedToRecordContentAddressedPutMetricValN = `failed to record content_addressed_put metric: %v\n`
const ConstStreamFailedToWriteNewFile = `failed to write new file`
const ConstStreamContentAddressedPuts = `content_addressed_puts`
const ConstStreamCasOperations = `cas_operations`
const ConstStreamCasIndexDrainWait = `cas_index_drain_wait`
const ConstStreamCasIndexRemove = `cas_index_remove`
const ConstStreamProcessingCasIndexWriteQueueForStr = `processing CAS index write queue for %s`
const ConstStreamEmittingBatchStartEventForStrSizeInt = `emitting batch start event for %s (size %d)`
const ConstStreamContentAddressed2 = `content_addressed`
const ConstStreamFailedToRecordContentAddressedDeleteMetricValN = `failed to record content_addressed_delete metric: %v\n`
const ConstStreamFailedToGetCasIndexQueueStatsCopyValN = `failed to get CAS index queue stats copy: %v\n`
const StorageMetricTagContentAddressable = "StorageMetricTagContentAddressable"
const ConstStreamListingIndexLockWaitTimeMs = `listing_index_lock_wait_time_ms`
const ConstStreamFailedToUpdateCasIndexQueueForKindStrValN = `failed to update CAS index queue for kind %s: %v\n`
const ConstStreamFailedFilesTruncated = `failed_files_truncated`
const LogEventStorageCASOrphanRefusedSoleSurvivor = "LogEventStorageCASOrphanRefusedSoleSurvivor"
const ConstStreamOrphanCleanupBatch = `orphan_cleanup_batch`
const ConstStreamEmittingWorkerShutdownEventForStr = `emitting worker shutdown event for %s`
const ConstStreamListingIndexAvgTimeMs = `listing_index_avg_time_ms`
const ConstStreamEmittingBatchStrEventForStrSizeInt = `emitting batch %s event for %s (size %d)`
const LogEventStorageCASOrphanWorkerIdleShutdown = "LogEventStorageCASOrphanWorkerIdleShutdown"
const ConstStreamWaitingForCasIndexQueueWorkerStr = `waiting for CAS index queue worker: %s`
const ConstStreamFailedToSyncDirStrAfterOrphanRemovalValN = `failed to sync dir %s after orphan removal: %v\n`
const ConstStreamCasIndexUpdate = `cas_index_update`
const ConstStreamListingIndexEntriesRemoved = `listing_index_entries_removed`
const ConstStreamContentAddressedMaxDeleteTimeMs = `content_addressed_max_delete_time_ms`
const ConstStreamWaitingForAllCasIndexQueueDrainsToComplete = `waiting for all CAS index queue drains to complete`
const MetricFieldLastSeen = "MetricFieldLastSeen"
const StorageMetricTypePerformance = "StorageMetricTypePerformance"
const ConstStreamListingIndexSize = `listing_index_size`
const ConstStreamEmittingStateChangeProjectRootSet = `emitting state change project_root_set`
const ConstStreamEmittingWorkerLifecycleEventViaCoordinator = `emitting worker lifecycle event via coordinator`
const ConstStreamCasIndexWriteQueueWorker = `cas_index_write_queue_worker`
const ConstStreamWorkerStarted = `worker_started`
const ConstStreamRecreatedFileFromIdBasedSourceHashStr = `Recreated file from ID-based source (hash: %s)`
const ConstStreamContentAddressedAvgUpdateTimeMs = `content_addressed_avg_update_time_ms`
const ConstStreamCleanedUpIntOrphanedCasHashFilesIntSucceededInt = `Cleaned up %d orphaned CAS hash files (%d succeeded, %d failed) in %v`
const LogEventStorageCASOrphanWorkerStarting = "LogEventStorageCASOrphanWorkerStarting"
const ConstStreamListingIndexFileLockFailures = `listing_index_file_lock_failures`
const MetricFieldSource = "MetricFieldSource"
const ConstStreamFailedToGetCasIndexQueueForKindStrValN = `failed to get CAS index queue for kind %s: %v\n`
const StorageMetricTagCAS = "StorageMetricTagCAS"
const ConstStreamFailedToReleaseCasIndexLockForStrValN = `failed to release CAS index lock for %s: %v\n`
const ConstStreamOrphanCleanupWorkerInt = `orphan_cleanup_worker_%d`
const ConstStreamFailedToGetCasIndexQueueStatsForKindStrValN = `failed to get CAS index queue stats for kind %s: %v\n`
const ConstStreamFailedToMarshalObject = `failed to marshal object`
const ConstStreamOrphanCleanupBatchInt = `orphan_cleanup_batch_%d`
const ConstStreamFailedToParseIdBasedFile = `failed to parse ID-based file`
const ConstStreamCasOrphanCleanupWorker = `cas_orphan_cleanup_worker`
const ConstStreamFailedToRemoveTmpOrphanFileStrValN = `failed to remove tmp orphan file %s: %v\n`
const MetricFieldTitle = "MetricFieldTitle"
const Optimized = "Optimized"
const ConstStreamContentAddressedMaxUpdateTimeMs = `content_addressed_max_update_time_ms`
const ConstStreamCasOrphanCleanupRetry = `cas_orphan_cleanup_retry`
const ConstStreamListingIndexFileLockWaitTimeMs = `listing_index_file_lock_wait_time_ms`
const LogEventStorageCASOrphanWorkerStoppedOK = "LogEventStorageCASOrphanWorkerStoppedOK"
const ConstStreamFileExistsNoRecoveryNeeded = `File exists, no recovery needed`
const ConstStreamFailedToRemoveFromIndex = `failed to remove from index`
const ConstStreamOrphanCleanupComplete = `orphan_cleanup_complete`
const ConstStreamContentAddressedAvgDeleteTimeMs = `content_addressed_avg_delete_time_ms`
const ConstStreamProcessingAsyncCasMetricsCollection = `processing async CAS metrics collection`
const ConstStreamListingIndexRemoveMappings = `listing_index_remove_mappings`
const ConstStreamCasOrphanCleanupShutdownWait = `cas_orphan_cleanup_shutdown_wait`
const ConstStreamProcessingOrphanedHashFileCleanupOperations = `processing orphaned hash file cleanup operations`
const ConstStreamTimeoutWaitingForQueueToFlushForKindStrPendingInt = `timeout waiting for queue to flush for kind %s (pending: %d)`
const ConstStreamFailedToCheckIfListingindexwritequeueIsDrained = `failed to check if ListingIndexWriteQueue is drained: %v\n`
const ConstStreamCasIndexQueueStrInt = `cas_index_queue_%s_%d`
const ConstStreamContentAddressedDelete = `content_addressed_delete`
const ConstStreamFailedToRecordListingIndexSetMappingMetricValN = `failed to record listing_index_set_mapping metric: %v\n`
const ConstStreamListingIndexSave = `listing_index_save`
const ConstStreamFailedToBuildCasMetricInstance = `failed to build cas_metric instance`
const ConstStreamFailedToCloseDirStrAfterOrphanRemovalValN = `failed to close dir %s after orphan removal: %v\n`
const MetricFieldCollectionCount = "MetricFieldCollectionCount"
const ConstStreamListingIndexEntriesAdded = `listing_index_entries_added`
const ConstStreamContentAddressed = `content_addressed_`
const ConstStreamTimeoutWaitingForAllListingIndexFlushesDeadline = `timeout waiting for all listing index flushes (deadline exceeded)`
const ConstStreamUnknownObjectKindStr = `unknown object kind: %s`
const ConstStreamCasIndexWorkerLifecycle = `cas_index_worker_lifecycle`
const Optional = "Optional"
const ConstStreamLockFailedInEnableValN = `lock failed in Enable: %v\n`
const StorageMetricTagStorage = "StorageMetricTagStorage"
const ConstStreamFailedToProcessFinalBatchForStrDuringShutdownValN = `failed to process final batch for %s during shutdown: %v\n`
const ConstStreamFileMissingRecoveryNotPossible = `File missing, recovery not possible`
const ConstStreamWorkerRunning = `worker_running`
const ConstStreamProjectRootSet = `project_root_set`
const ConstStreamFailedToRecordListingIndexSaveMetricValN = `failed to record listing_index_save metric: %v\n`
const Open = "Open"
const ConstStreamWaitingForCasOrphanCleanupWorkerToStop = `waiting for CAS orphan cleanup worker to stop`
const MetricFieldFirstSeen = "MetricFieldFirstSeen"
const ConstStreamLockFailedInStopValN = `lock failed in Stop: %v\n`
const ConstStreamListingIndexLoads = `listing_index_loads`
const ConstStreamCasOrphanCleanupDrainWait = `cas_orphan_cleanup_drain_wait`
const LogEventStorageCASOrphanRequeueFailed = "LogEventStorageCASOrphanRequeueFailed"
const ConstStreamFailedToCreateCasMetric = `failed to create CAS metric`
const ConstStreamFailedToUpdateIndex = `failed to update index`
const ConstStreamListingIndexSaves = `listing_index_saves`
const LogEventStorageCASOrphanShutdownWaitTimeout = "LogEventStorageCASOrphanShutdownWaitTimeout"
const ConstStreamFailedToGetListingIndexWriteQueueFactoryValN = `failed to get listing index write queue factory: %v\n`
const Operation = "Operation"
const ConstStreamCasIndexStateChangeEvent = `cas_index_state_change_event`
const ConstStreamListingIndexWriteQueue = `listing_index_write_queue`
const ConstStreamEmittingWorkerStartEventForStr = `emitting worker start event for %s`
const ConstStreamFileMissingAndRecoveryNotPossibleHashStr = `file missing and recovery not possible (hash: %s)`
const ConstStreamFailedToSnapshotCasPointerValN = `failed to snapshot CAS pointer: %v\n`
const ConstStreamFailedToRecordListingIndexRemoveMappingMetricValN = `failed to record listing_index_remove_mapping metric: %v\n`
const ConstStreamOrphanCleanupQueueIsFullCannotEnqueueCleanupFor = `orphan cleanup queue is full, cannot enqueue cleanup for %s`
const ConstStreamListingIndexFileLockAcquisitions = `listing_index_file_lock_acquisitions`
const ConstStreamFailedToAcquireLockForCasMetricsRecorderInitValN = `failed to acquire lock for CAS metrics recorder init: %v\n`
const ConstStreamFailedToRemoveOrphanedFileStrErr = `failed to remove orphaned file %s: %w`
const ConstStreamShutdownInProgressCannotEnqueueIndexUpdate = `shutdown in progress, cannot enqueue index update`
const ConstStreamShutdownInProgressCannotEnqueueCleanupOperation = `shutdown in progress, cannot enqueue cleanup operation`
const ConstStreamContentAddressedMaxReadTimeMs = `content_addressed_max_read_time_ms`
const ConstStreamFileMissingForHashStr = `File missing for hash %s`
const ConstStreamContentAddressedUpdates = `content_addressed_updates`
const ConstStreamObjectNotInCasIndex = `Object not in CAS index`
const ConstStreamListingIndex = `listing_index_`
const ConstStreamContentAddressedMeasurementWindowEnd = `content_addressed_measurement_window_end`
const ConstStreamRemovedFromIndex = `removed_from_index`
const LogEventStorageCASOrphanRequeuedForRetry = "LogEventStorageCASOrphanRequeuedForRetry"
const ConstStreamOrphanCleanupCoordinatorEvent = `orphan_cleanup_coordinator_event`
const ConstStreamMetricIdNotSetAfterCreation = `metric ID not set after creation`
const OpDelete = "OpDelete"
const ConstStreamFailedToGetAllMappings = `failed to get all mappings`
const CASSystemMetricSource = "CASSystemMetricSource"
const ConstStreamListingIndexLoad = `listing_index_load`
const ConstStreamContentAddressedRead = `content_addressed_read`
const ConstStreamEmittingBatchProcessingEventViaCoordinator = `emitting batch processing event via coordinator`
const ConstStreamContentAddressedMaxPutTimeMs = `content_addressed_max_put_time_ms`
const ConstStreamListingIndexReloads = `listing_index_reloads`
const ConstStreamListingIndexBatchEvent = `listing_index_batch_event`
const ConstStreamCasMetricsAsyncWorker = `cas_metrics_async_worker`
const ConstStreamPendingUpdates = `pending_updates`
const ConstStreamFailedToRemoveOrphanedTmpFileStrErr = `failed to remove orphaned .tmp file %s: %w`
const ConstStreamFailedToMergeBatchIntoInMemoryIndexValN = `failed to merge batch into in-memory index: %v\n`
const ConstStreamContentAddressedPut = `content_addressed_put`
const ConstStreamPartialFailure = `partial_failure`
const ConstStreamContentAddressedAvgPutTimeMs = `content_addressed_avg_put_time_ms`
const ConstStreamCasOrphanCleanupQueue = `cas_orphan_cleanup_queue`
const ConstStreamEmittingStateChangeStorageSet = `emitting state change storage_set`
const ConstStreamCasIndexDrainCollector = `cas_index_drain_collector`
const ConstStreamRetryingIntFailedCleanupOperations = `retrying %d failed cleanup operations`
const ConstStreamOrphanCleanupError = `orphan_cleanup_error`
const ConstStreamListingIndexMergeOperations = `listing_index_merge_operations`
const LogEventStorageCASOrphanWorkerStoppedIdle = "LogEventStorageCASOrphanWorkerStoppedIdle"
const ConstStreamWaitingForListingIndexQueueErr = `waiting for listing index queue: %w`
const ConstStreamShutdownTimeout = `shutdown_timeout`
const ConstStreamRemovedFromIndexFileMissingHashStr = `Removed from index (file missing, hash: %s)`
const ConstStreamBackgroundWorker = `background_worker`
const ConstStreamOrphanCleanup = `orphan_cleanup`
const LogEventStorageMetricsCASBuildFailed = "LogEventStorageMetricsCASBuildFailed"
const ConstStreamCasMetricsIntOperationsFromStrToStr = `CAS Metrics: %d operations from %s to %s`
const MetricFieldMetricType = "MetricFieldMetricType"
const ConstStreamFailedToSetListingIndexWriteQueueFactoryValN = `failed to set listing index write queue factory: %v\n`
const ConstStreamRemoveMapping = `remove_mapping`
const ConstStreamListingIndexSetMappings = `listing_index_set_mappings`
const ConstStreamListingIndexSetMapping = `listing_index_set_mapping`
const ConstStreamEntriesLoaded = `entries_loaded`
const ConstStreamContentAddressedReads = `content_addressed_reads`
const ConstStreamFailedToSetListingIndexWriteQueueFactoryFor = `failed to set listing index write queue factory for project root: %v\n`
const ConstStreamFailedToGetCasIndexTotalPendingCountValN = `failed to get CAS index total pending count: %v\n`
const OperationCallback = "OperationCallback"
const ConstStreamDrainTimeoutAfterVal = `drain timeout after %v`
const ConstStreamFailedToDisableAsyncCasMetricsCollectorValN = `failed to disable async CAS metrics collector: %v\n`
const ConstStreamWaitingForListingIndexFlushForKindStrErr = `waiting for listing index flush for kind %s: %w`
const ConstStreamRecreatedFileWithUpdatedHashOldStrNewStr = `Recreated file with updated hash (old: %s, new: %s)`
const ConstStreamOperationType = `operation_type`
const ConstStreamFailedToGetLatestSchemaVersionForCommandMetric = `failed to get latest schema version for command_metric`
const ConstStreamFailedToRecreateFile = `failed to recreate file`
const ConstStreamContentAddressedMeasurementWindowStart = `content_addressed_measurement_window_start`
const ConstStreamWorkerStopped = `worker_stopped`
const ConstStreamFailedToRecordContentAddressedReadMetricValN = `failed to record content_addressed_read metric: %v\n`
const ConstStreamFailedToSaveIndexAfterRemoval = `failed to save index after removal`
const ConstStreamContentAddressedAvgReadTimeMs = `content_addressed_avg_read_time_ms`
const Metrics = "Metrics"
const LogEventStorageCASOrphanWakeWorker = "LogEventStorageCASOrphanWakeWorker"
const ConstStreamListingIndexLockContention = `listing_index_lock_contention`
const ConstStreamListingIndexRemoveMapping = `listing_index_remove_mapping`
const ConstStreamTotalFailedFiles = `total_failed_files`
const ConstStreamWaitingForCasOrphanCleanupWorkerToDrain = `waiting for CAS orphan cleanup worker to drain`
const ConstStreamListingIndexReloadsDuringSet = `listing_index_reloads_during_set`
const ConstStreamListingIndexMaxTimeMs = `listing_index_max_time_ms`
const MetricFieldTags = "MetricFieldTags"
const ConstStreamFailedToRecordListingIndexLoadMetricValN = `failed to record listing_index_load metric: %v\n`
const ConstStreamFailedToAcquireCasIndexLockForSave = `failed to acquire CAS index lock for save`
const ConstStreamContentAddressedDeletes = `content_addressed_deletes`

func StorageLog(logger logging.Logger) *logging.FluentRoot {
	if logger == nil {
		return logging.Fluent(logging.GetLoggerFromProfile(string(pkgctx.ProfileSystem)))
	}
	return logging.Fluent(logger)
}

const emptyValue = ""

var _ = ""
