// Code generated by pkg/specbuilder/instance_builders/codegen.go from lifecycle YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package shared_code_references

type Status string

const (
	StatusActive     Status = "active"
	StatusArchived   Status = "archived"
	StatusComplete   Status = "complete"
	StatusConceptual Status = "conceptual"
	StatusOriginated Status = "originated"
	StatusVerified   Status = "verified"
)
