// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec/lifecycle YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package base_object

import (
	auditableenum "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/auditable"
)

type Plane string

const (
	PlaneApoptotic Plane = "apoptotic"
	PlaneDraft     Plane = "draft"
	PlanePromoted  Plane = "promoted"
	PlaneStaged    Plane = "staged"
)

type PriorityTier string

const (
	PriorityTierP0 PriorityTier = "P0"
	PriorityTierP1 PriorityTier = "P1"
	PriorityTierP2 PriorityTier = "P2"
	PriorityTierP3 PriorityTier = "P3"
)

type SourceType string

const (
	SourceTypeExternal SourceType = "external"
	SourceTypeImported SourceType = "imported"
	SourceTypeInternal SourceType = "internal"
)

type Status = auditableenum.Status

const (
	StatusApproved    Status = auditableenum.StatusApproved
	StatusArchived    Status = auditableenum.StatusArchived
	StatusConceptual  Status = auditableenum.StatusConceptual
	StatusError       Status = auditableenum.StatusError
	StatusImplemented Status = auditableenum.StatusImplemented
	StatusInProgress  Status = auditableenum.StatusInProgress
	StatusOriginated  Status = auditableenum.StatusOriginated
	StatusProposed    Status = auditableenum.StatusProposed
)
