// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec/lifecycle YAML.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package lifecycles

import (
	base_objectenum "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/base_object"
	shared_lifecyclesenum "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/shared_lifecycles"
)

type PriorityTier = base_objectenum.PriorityTier

const (
	PriorityTierP0 PriorityTier = base_objectenum.PriorityTierP0
	PriorityTierP1 PriorityTier = base_objectenum.PriorityTierP1
	PriorityTierP2 PriorityTier = base_objectenum.PriorityTierP2
	PriorityTierP3 PriorityTier = base_objectenum.PriorityTierP3
)

type SourceType string

const (
	SourceTypeBuiltIn  SourceType = "built-in"
	SourceTypeInternal SourceType = "internal"
)

type Status = shared_lifecyclesenum.Status

const (
	StatusApproved    Status = shared_lifecyclesenum.StatusApproved
	StatusArchived    Status = shared_lifecyclesenum.StatusArchived
	StatusError       Status = shared_lifecyclesenum.StatusError
	StatusImplemented Status = shared_lifecyclesenum.StatusImplemented
	StatusInProgress  Status = shared_lifecyclesenum.StatusInProgress
	StatusProposed    Status = shared_lifecyclesenum.StatusProposed
)
