// Code generated by zqk-admin system generate-builders. DO NOT EDIT.

package bldr_lifecycle_v1

import (
	"github.com/zqk-os/zqk/pkg/objects"
	"github.com/zqk-os/zqk/pkg/specbuilder/lifecycle_builders"
)

// ConvergenceSessionLifecycleBuilder builds the convergence_session lifecycle at version v1_0_0
// File: bldr_lifecycle_v1/convergence_session_builder.go - version is encoded in package/directory name
type ConvergenceSessionLifecycleBuilder struct {
	*lifecycle_builders.BaseLifecycleBuilder
}

// NewConvergenceSessionLifecycleBuilder creates a new builder for convergence_session lifecycle version v1_0_0
func NewConvergenceSessionLifecycleBuilder() *ConvergenceSessionLifecycleBuilder {
	builder := &ConvergenceSessionLifecycleBuilder{
		BaseLifecycleBuilder: lifecycle_builders.NewBaseLifecycleBuilder("convergence_session", "v1_0_0"),
	}

	// Configure the lifecycle
	builder.
		SetPercentComplete(objects.PercentCompleteConfig{
			Method: "status_based",
			DefaultByStatus: map[string]any{
				"abandoned":  0,
				"active":     40,
				"archived":   100,
				"completed":  100,
				"conceptual": 0,
				"draft":      10,
				"error":      0,
				"escalated":  50,
				"originated": 5,
				"paused":     35,
			},
		})

	// Add statuses and transitions
	builder.addConvergenceSessionLifecycleData()

	return builder
}

// addConvergenceSessionLifecycleData adds the convergence_session lifecycle statuses and transitions
func (b *ConvergenceSessionLifecycleBuilder) addConvergenceSessionLifecycleData() {

	b.AddStatus(objects.Status{
		Value:       "conceptual",
		Display:     "Conceptual",
		Origin:      true,
		Description: "Draft plane status. Prior to CAS membrane crossing.",
	})
	b.AddStatus(objects.Status{
		Value:       "originated",
		Display:     "Originated",
		Description: "CAS membrane crossed. Object officially originated.",
	})
	b.AddStatus(objects.Status{
		Value:       "draft",
		Display:     "Draft",
		Description: "Session contract being authored; hypothesis/thresholds may be incomplete — not yet measuring.",
	})
	b.AddStatus(objects.Status{
		Value:       "active",
		Display:     "Active",
		Description: "Convergence work in progress (phases C1–C5).",
	})
	b.AddStatus(objects.Status{
		Value:       "paused",
		Display:     "Paused",
		Description: "Stopped temporarily; handoff fields should be current.",
	})
	b.AddStatus(objects.Status{
		Value:       "completed",
		Display:     "Completed",
		Terminal:    true,
		WorkDone:    true,
		Description: "Desired end state reached or accepted stop.",
	})
	b.AddStatus(objects.Status{
		Value:       "abandoned",
		Display:     "Abandoned",
		Terminal:    true,
		Archive:     true,
		Description: "Work discontinued without reaching end state.",
	})
	b.AddStatus(objects.Status{
		Value:       "archived",
		Display:     "Archived",
		Terminal:    true,
		Archive:     true,
		Description: "Session retained for audit/lineage (synonym of abandoned for historical rows).",
	})
	b.AddStatus(objects.Status{
		Value:       "escalated",
		Display:     "Escalated",
		Description: "Option A (park-but-CAP-bound): recoverable handoff/parking hold. CAP may\\nstill bind; measure/tick must not persist session measurements; whats-next\\ndoes not auto-select for measure. Resume→active, or complete/abandon.\\nNOT lifecycle-terminal. See kernel-backlog /\\nkernel-backlog.\\n",
	})
	b.AddStatus(objects.Status{
		Value:       "error",
		Display:     "Error",
		System:      true,
		Description: "Session object incoherent or validation-failed; halt ticks until the contract/evidence is repaired.",
	})

	b.AddTransition(objects.Transition{
		From:        "conceptual",
		To:          "originated",
		Description: "Promote from draft plane to CAS membrane (CAS Qualification).",
		Manual:      true,
		Auto:        false,
	})

	b.AddTransition(objects.Transition{
		From:        "originated",
		To:          "draft",
		Description: "Initial domain workflow transition to draft.",
		Manual:      true,
		Auto:        true,
	})

	b.AddTransition(objects.Transition{
		From:        "draft",
		To:          "active",
		Description: "Start convergence work",
		Manual:      true,
		Auto:        false,
		Preconditions: []string{
			"hypothesis is set",
			"desired_end_state is set",
			"current_phase is set",
		},
	})

	b.AddTransition(objects.Transition{
		From:        "draft",
		To:          "abandoned",
		Description: "Discard draft",
		Manual:      true,
		Auto:        false,
	})

	b.AddTransition(objects.Transition{
		From:        "active",
		To:          "paused",
		Description: "Pause for handoff or dependency",
		Manual:      true,
		Auto:        false,
	})

	b.AddTransition(objects.Transition{
		From:        "active",
		To:          "completed",
		Description: "Mark converged or done",
		Manual:      true,
		Auto:        false,
	})

	b.AddTransition(objects.Transition{
		From:        "active",
		To:          "abandoned",
		Description: "Stop without success",
		Manual:      true,
		Auto:        false,
	})

	b.AddTransition(objects.Transition{
		From:        "active",
		To:          "escalated",
		Description: "Escalate to design or other owner",
		Manual:      true,
		Auto:        false,
	})

	b.AddTransition(objects.Transition{
		From:        "escalated",
		To:          "active",
		Description: "Resume after design return or false escalate (kernel integrity recovery)",
		Manual:      true,
		Auto:        false,
	})

	b.AddTransition(objects.Transition{
		From:        "escalated",
		To:          "completed",
		Description: "Close escalated session when end state accepted outside this loop",
		Manual:      true,
		Auto:        false,
	})

	b.AddTransition(objects.Transition{
		From:        "escalated",
		To:          "abandoned",
		Description: "Drop escalated session without resume",
		Manual:      true,
		Auto:        false,
	})

	b.AddTransition(objects.Transition{
		From:        "paused",
		To:          "active",
		Description: "Resume",
		Manual:      true,
		Auto:        false,
	})

	b.AddTransition(objects.Transition{
		From:        "paused",
		To:          "abandoned",
		Description: "Abandon while paused",
		Manual:      true,
		Auto:        false,
	})

	b.AddTransition(objects.Transition{
		From:        "*",
		To:          "error",
		Description: "System error",
		Manual:      false,
		Auto:        true,
	})

	b.AddTransition(objects.Transition{
		From:        "*",
		To:          "archived",
		Description: "Archive session for audit retention (lineage-preserving)",
		Manual:      true,
		Auto:        false,
	})
}

func init() {
	lifecycle_builders.RegisterBuilder(NewConvergenceSessionLifecycleBuilder())
}
