// Code generated by zqk-admin system generate-builders. DO NOT EDIT.

package bldr_lifecycle_v1

import (
	"github.com/lanceman/zqk/pkg/objects"
	"github.com/lanceman/zqk/pkg/specbuilder/lifecycle_builders"
)

// DomainRegistryLifecycleBuilder builds the domain_registry lifecycle at version v1_0_0
// File: bldr_lifecycle_v1/domain_registry_builder.go - version is encoded in package/directory name
type DomainRegistryLifecycleBuilder struct {
	*lifecycle_builders.BaseLifecycleBuilder
}

// NewDomainRegistryLifecycleBuilder creates a new builder for domain_registry lifecycle version v1_0_0
func NewDomainRegistryLifecycleBuilder() *DomainRegistryLifecycleBuilder {
	builder := &DomainRegistryLifecycleBuilder{
		BaseLifecycleBuilder: lifecycle_builders.NewBaseLifecycleBuilder("domain_registry", "v1_0_0"),
	}

	// Add statuses and transitions
	builder.addDomainRegistryLifecycleData()

	return builder
}

// addDomainRegistryLifecycleData adds the domain_registry lifecycle statuses and transitions
func (b *DomainRegistryLifecycleBuilder) addDomainRegistryLifecycleData() {

	b.AddStatus(objects.Status{
		Value:       "conceptual",
		Display:     "Conceptual",
		Origin:      true,
		Description: "Draft plane status. Prior to CAS membrane crossing.",
	})
	b.AddStatus(objects.Status{
		Value:       "originated",
		Display:     "Originated",
		Description: "CAS membrane crossed. Object officially originated.",
	})
	b.AddStatus(objects.Status{
		Value:       "active",
		Display:     "Active",
		Description: "domain registry status 'active' (Active): ready for pickup or use; not locked mid-flight. Flags: origin status.",
	})
	b.AddStatus(objects.Status{
		Value:       "deprecated",
		Display:     "Deprecated",
		Description: "domain registry status 'deprecated' (Deprecated): not yet committed for execution; reshape before pickup.",
	})
	b.AddStatus(objects.Status{
		Value:       "archived",
		Display:     "Archived",
		Terminal:    true,
		Description: "domain registry status 'archived' (Archived): ended; no further normal execution transitions expected. Flags: terminal.",
	})

	b.AddTransition(objects.Transition{
		From:        "conceptual",
		To:          "originated",
		Description: "Promote from draft plane to CAS membrane (CAS Qualification).",
		Manual:      true,
		Auto:        false,
	})

	b.AddTransition(objects.Transition{
		From:        "originated",
		To:          "active",
		Description: "Initial domain workflow transition to active.",
		Manual:      true,
		Auto:        true,
	})

	b.AddTransition(objects.Transition{
		From:        "active",
		To:          "deprecated",
		Description: "Deprecate domain registry",
		Manual:      true,
		Auto:        false,
	})

	b.AddTransition(objects.Transition{
		From:        "*",
		To:          "archived",
		Description: "Archive domain registry",
		Manual:      true,
		Auto:        false,
	})
}

func init() {
	lifecycle_builders.RegisterBuilder(NewDomainRegistryLifecycleBuilder())
}
