// Code generated by zqk-admin system generate-builders. DO NOT EDIT.

package bldr_lifecycle_v1

import (
	"github.com/lanceman/zqk/pkg/objects"
	"github.com/lanceman/zqk/pkg/specbuilder/lifecycle_builders"
)

// MissionLifecycleBuilder builds the mission lifecycle at version v1_0_0
// File: bldr_lifecycle_v1/mission_builder.go - version is encoded in package/directory name
type MissionLifecycleBuilder struct {
	*lifecycle_builders.BaseLifecycleBuilder
}

// NewMissionLifecycleBuilder creates a new builder for mission lifecycle version v1_0_0
func NewMissionLifecycleBuilder() *MissionLifecycleBuilder {
	builder := &MissionLifecycleBuilder{
		BaseLifecycleBuilder: lifecycle_builders.NewBaseLifecycleBuilder("mission", "v1_0_0"),
	}

	// Configure the lifecycle
	builder.
		SetPercentComplete(objects.PercentCompleteConfig{
			Method: "status_defaults",
			DefaultByStatus: map[string]any{
				"active":   100,
				"archived": 100,
				"draft":    0,
				"error":    0,
			},
		})

	// Add statuses and transitions
	builder.addMissionLifecycleData()

	return builder
}

// addMissionLifecycleData adds the mission lifecycle statuses and transitions
func (b *MissionLifecycleBuilder) addMissionLifecycleData() {

	b.AddStatus(objects.Status{
		Value:       "draft",
		Display:     "Draft",
		Origin:      true,
		Description: "mission status 'draft' (Draft): not yet committed for execution; reshape before pickup. Flags: origin status, preliminary.",
	})
	b.AddStatus(objects.Status{
		Value:       "active",
		Display:     "Active",
		Description: "mission status 'active' (Active): ready for pickup or use; not locked mid-flight.",
	})
	b.AddStatus(objects.Status{
		Value:       "archived",
		Display:     "Archived",
		Terminal:    true,
		Archive:     true,
		Description: "mission status 'archived' (Archived): ended; no further normal execution transitions expected. Flags: archive, terminal.",
		Shockwave: objects.ShockwavePolicy{
			Mode: "prune",
			Fail: "closed",
		},
	})
	b.AddStatus(objects.Status{
		Value:       "error",
		Display:     "Error",
		System:      true,
		Description: "mission status 'error' (Error): paused or system-held for repair; resolve before advancing. Flags: system-assigned.",
	})

	b.AddTransition(objects.Transition{
		From:        "draft",
		To:          "active",
		Description: "Mission is published and active",
		Manual:      true,
		Auto:        false,
	})

	b.AddTransition(objects.Transition{
		From:        "active",
		To:          "archived",
		Description: "Mission is archived (no longer active)",
		Manual:      true,
		Auto:        false,
	})

	b.AddTransition(objects.Transition{
		From:        "*",
		To:          "error",
		Description: "System error occurred",
		Manual:      false,
		Auto:        true,
	})
}

func init() {
	lifecycle_builders.RegisterBuilder(NewMissionLifecycleBuilder())
}
