// Code generated by zqk-admin system generate-builders. DO NOT EDIT.

package bldr_lifecycle_v1

import (
	"github.com/lanceman/zqk/pkg/objects"
	"github.com/lanceman/zqk/pkg/specbuilder/lifecycle_builders"
)

// NamespaceRegistryLifecycleBuilder builds the namespace_registry lifecycle at version v1_0_0
// File: bldr_lifecycle_v1/namespace_registry_builder.go - version is encoded in package/directory name
type NamespaceRegistryLifecycleBuilder struct {
	*lifecycle_builders.BaseLifecycleBuilder
}

// NewNamespaceRegistryLifecycleBuilder creates a new builder for namespace_registry lifecycle version v1_0_0
func NewNamespaceRegistryLifecycleBuilder() *NamespaceRegistryLifecycleBuilder {
	builder := &NamespaceRegistryLifecycleBuilder{
		BaseLifecycleBuilder: lifecycle_builders.NewBaseLifecycleBuilder("namespace_registry", "v1_0_0"),
	}

	// Add statuses and transitions
	builder.addNamespaceRegistryLifecycleData()

	return builder
}

// addNamespaceRegistryLifecycleData adds the namespace_registry lifecycle statuses and transitions
func (b *NamespaceRegistryLifecycleBuilder) addNamespaceRegistryLifecycleData() {

	b.AddStatus(objects.Status{
		Value:       "active",
		Display:     "Active",
		Origin:      true,
		Description: "namespace registry status 'active' (Active): ready for pickup or use; not locked mid-flight. Flags: origin status.",
	})
	b.AddStatus(objects.Status{
		Value:       "deprecated",
		Display:     "Deprecated",
		Description: "namespace registry status 'deprecated' (Deprecated): not yet committed for execution; reshape before pickup.",
	})
	b.AddStatus(objects.Status{
		Value:       "archived",
		Display:     "Archived",
		Terminal:    true,
		Description: "namespace registry status 'archived' (Archived): ended; no further normal execution transitions expected. Flags: terminal.",
	})

	b.AddTransition(objects.Transition{
		From:        "active",
		To:          "deprecated",
		Description: "Deprecate namespace registry",
		Manual:      true,
		Auto:        false,
	})

	b.AddTransition(objects.Transition{
		From:        "*",
		To:          "archived",
		Description: "Archive namespace registry",
		Manual:      true,
		Auto:        false,
	})
}

func init() {
	lifecycle_builders.RegisterBuilder(NewNamespaceRegistryLifecycleBuilder())
}
