// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec/lifecycle YAML.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package agent_feeds

import (
	base_objectenum "github.com/zqk-os/zqk/pkg/specbuilder/bldr_enum_v1/base_object"
	shared_agent_feedsenum "github.com/zqk-os/zqk/pkg/specbuilder/bldr_enum_v1/shared_agent_feeds"
)

type DeliveryMode string

const (
	DeliveryModeClipboard DeliveryMode = "clipboard"
	DeliveryModeLog       DeliveryMode = "log"
	DeliveryModeNotify    DeliveryMode = "notify"
	DeliveryModeOff       DeliveryMode = "off"
	DeliveryModePaste     DeliveryMode = "paste"
)

type PriorityTier = base_objectenum.PriorityTier

const (
	PriorityTierP0 PriorityTier = base_objectenum.PriorityTierP0
	PriorityTierP1 PriorityTier = base_objectenum.PriorityTierP1
	PriorityTierP2 PriorityTier = base_objectenum.PriorityTierP2
	PriorityTierP3 PriorityTier = base_objectenum.PriorityTierP3
)

type SourceType = base_objectenum.SourceType

const (
	SourceTypeExternal SourceType = base_objectenum.SourceTypeExternal
	SourceTypeImported SourceType = base_objectenum.SourceTypeImported
	SourceTypeInternal SourceType = base_objectenum.SourceTypeInternal
)

type Status = shared_agent_feedsenum.Status

const (
	StatusActive   Status = shared_agent_feedsenum.StatusActive
	StatusArchived Status = shared_agent_feedsenum.StatusArchived
	StatusError    Status = shared_agent_feedsenum.StatusError
)
