// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec/lifecycle YAML.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package field_registry

import (
	base_objectenum "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/base_object"
	shared_field_registriesenum "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/shared_field_registries"
)

type PriorityTier = base_objectenum.PriorityTier

const (
	PriorityTierP0 PriorityTier = base_objectenum.PriorityTierP0
	PriorityTierP1 PriorityTier = base_objectenum.PriorityTierP1
	PriorityTierP2 PriorityTier = base_objectenum.PriorityTierP2
	PriorityTierP3 PriorityTier = base_objectenum.PriorityTierP3
)

type SourceType = base_objectenum.SourceType

const (
	SourceTypeExternal SourceType = base_objectenum.SourceTypeExternal
	SourceTypeImported SourceType = base_objectenum.SourceTypeImported
	SourceTypeInternal SourceType = base_objectenum.SourceTypeInternal
)

type Status = shared_field_registriesenum.Status

const (
	StatusApproved    Status = shared_field_registriesenum.StatusApproved
	StatusArchived    Status = shared_field_registriesenum.StatusArchived
	StatusError       Status = shared_field_registriesenum.StatusError
	StatusImplemented Status = shared_field_registriesenum.StatusImplemented
	StatusInProgress  Status = shared_field_registriesenum.StatusInProgress
	StatusProposed    Status = shared_field_registriesenum.StatusProposed
)
