// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec/lifecycle YAML.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package organizational_changes

import (
	base_objectenum "github.com/zqk-os/zqk/pkg/specbuilder/bldr_enum_v1/base_object"
	shared_organizational_changesenum "github.com/zqk-os/zqk/pkg/specbuilder/bldr_enum_v1/shared_organizational_changes"
)

type PriorityTier = base_objectenum.PriorityTier

const (
	PriorityTierP0 PriorityTier = base_objectenum.PriorityTierP0
	PriorityTierP1 PriorityTier = base_objectenum.PriorityTierP1
	PriorityTierP2 PriorityTier = base_objectenum.PriorityTierP2
	PriorityTierP3 PriorityTier = base_objectenum.PriorityTierP3
)

type SourceType = base_objectenum.SourceType

const (
	SourceTypeExternal SourceType = base_objectenum.SourceTypeExternal
	SourceTypeImported SourceType = base_objectenum.SourceTypeImported
	SourceTypeInternal SourceType = base_objectenum.SourceTypeInternal
)

type Status = shared_organizational_changesenum.Status

const (
	StatusApproved    Status = shared_organizational_changesenum.StatusApproved
	StatusArchived    Status = shared_organizational_changesenum.StatusArchived
	StatusError       Status = shared_organizational_changesenum.StatusError
	StatusImplemented Status = shared_organizational_changesenum.StatusImplemented
	StatusInProgress  Status = shared_organizational_changesenum.StatusInProgress
	StatusProposed    Status = shared_organizational_changesenum.StatusProposed
)
