// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec/lifecycle YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package work_unit

import (
	base_objectenum "github.com/zqk-os/zqk/pkg/specbuilder/bldr_enum_v1/base_object"
	work_intervalenum "github.com/zqk-os/zqk/packs/pm/bldr_enum_v1/work_interval"
)

type Plane = base_objectenum.Plane

const (
	PlaneApoptotic Plane = base_objectenum.PlaneApoptotic
	PlaneDraft     Plane = base_objectenum.PlaneDraft
	PlanePromoted  Plane = base_objectenum.PlanePromoted
	PlaneStaged    Plane = base_objectenum.PlaneStaged
)

type PriorityTier = base_objectenum.PriorityTier

const (
	PriorityTierP0 PriorityTier = base_objectenum.PriorityTierP0
	PriorityTierP1 PriorityTier = base_objectenum.PriorityTierP1
	PriorityTierP2 PriorityTier = base_objectenum.PriorityTierP2
	PriorityTierP3 PriorityTier = base_objectenum.PriorityTierP3
)

type SourceType = base_objectenum.SourceType

const (
	SourceTypeExternal SourceType = base_objectenum.SourceTypeExternal
	SourceTypeImported SourceType = base_objectenum.SourceTypeImported
	SourceTypeInternal SourceType = base_objectenum.SourceTypeInternal
)

type Status = work_intervalenum.Status

const (
	StatusApproved    Status = work_intervalenum.StatusApproved
	StatusArchived    Status = work_intervalenum.StatusArchived
	StatusConceptual  Status = work_intervalenum.StatusConceptual
	StatusError       Status = work_intervalenum.StatusError
	StatusImplemented Status = work_intervalenum.StatusImplemented
	StatusInProgress  Status = work_intervalenum.StatusInProgress
	StatusOriginated  Status = work_intervalenum.StatusOriginated
	StatusProposed    Status = work_intervalenum.StatusProposed
)
