// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec/lifecycle YAML.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package partnerships

import (
	base_objectenum "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/base_object"
	shared_partnershipsenum "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/shared_partnerships"
)

type PartnershipType string

const (
	PartnershipTypeCollaboration     PartnershipType = "collaboration"
	PartnershipTypeCustomer          PartnershipType = "customer"
	PartnershipTypeJointVenture      PartnershipType = "joint_venture"
	PartnershipTypeOther             PartnershipType = "other"
	PartnershipTypeStrategicAlliance PartnershipType = "strategic_alliance"
	PartnershipTypeSupplier          PartnershipType = "supplier"
)

type PriorityTier = base_objectenum.PriorityTier

const (
	PriorityTierP0 PriorityTier = base_objectenum.PriorityTierP0
	PriorityTierP1 PriorityTier = base_objectenum.PriorityTierP1
	PriorityTierP2 PriorityTier = base_objectenum.PriorityTierP2
	PriorityTierP3 PriorityTier = base_objectenum.PriorityTierP3
)

type SourceType = base_objectenum.SourceType

const (
	SourceTypeExternal SourceType = base_objectenum.SourceTypeExternal
	SourceTypeImported SourceType = base_objectenum.SourceTypeImported
	SourceTypeInternal SourceType = base_objectenum.SourceTypeInternal
)

type Status = shared_partnershipsenum.Status

const (
	StatusApproved    Status = shared_partnershipsenum.StatusApproved
	StatusArchived    Status = shared_partnershipsenum.StatusArchived
	StatusError       Status = shared_partnershipsenum.StatusError
	StatusImplemented Status = shared_partnershipsenum.StatusImplemented
	StatusInProgress  Status = shared_partnershipsenum.StatusInProgress
	StatusProposed    Status = shared_partnershipsenum.StatusProposed
)
