// Code generated by pkg/specbuilder/instance_builders/codegen.go from lifecycle YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package shared_criteria

type Status string

const (
	StatusArchived             Status = "archived"
	StatusAwaitingVerification Status = "awaiting_verification"
	StatusBlocked              Status = "blocked"
	StatusComplete             Status = "complete"
	StatusInProgress           Status = "in_progress"
	StatusRejected             Status = "rejected"
	StatusValidated            Status = "validated"
)
