// Code generated by scripts/generate_enum_tests.py; DO NOT EDIT.

package verification_matrix

import (
	"testing"
)

func TestEnums_Completeness(t *testing.T) {
	tests := []struct {
		name string
		val  string
	}{
		{"MatrixRoleAgentCoordination", string(MatrixRoleAgentCoordination)},
		{"MatrixRoleCodebaseVetting", string(MatrixRoleCodebaseVetting)},
		{"MatrixRoleCustom", string(MatrixRoleCustom)},
		{"MatrixRoleGoalProgress", string(MatrixRoleGoalProgress)},
		{"MatrixRoleTestBundle", string(MatrixRoleTestBundle)},
		{"MatrixRoleTransitionGate", string(MatrixRoleTransitionGate)},
		{"PlaneApoptotic", string(PlaneApoptotic)},
		{"PlaneDraft", string(PlaneDraft)},
		{"PlanePromoted", string(PlanePromoted)},
		{"PlaneStaged", string(PlaneStaged)},
		{"PriorityTierP0", string(PriorityTierP0)},
		{"PriorityTierP1", string(PriorityTierP1)},
		{"PriorityTierP2", string(PriorityTierP2)},
		{"PriorityTierP3", string(PriorityTierP3)},
		{"SourceTypeExternal", string(SourceTypeExternal)},
		{"SourceTypeImported", string(SourceTypeImported)},
		{"SourceTypeInternal", string(SourceTypeInternal)},
		{"StatusActive", string(StatusActive)},
		{"StatusArchived", string(StatusArchived)},
		{"StatusDraft", string(StatusDraft)},
	}
	for _, tt := range tests {
		if tt.val == "" {
			t.Errorf("constant %s has empty value", tt.name)
		}
	}
}
