// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec/lifecycle YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package prompt_template

import (
	base_objectenum "github.com/zqk-os/zqk/pkg/specbuilder/bldr_enum_v1/base_object"
	shared_prompt_templatesenum "github.com/zqk-os/zqk/pkg/specbuilder/bldr_enum_v1/shared_prompt_templates"
)

type Plane = base_objectenum.Plane

const (
	PlaneApoptotic Plane = base_objectenum.PlaneApoptotic
	PlaneDraft     Plane = base_objectenum.PlaneDraft
	PlanePromoted  Plane = base_objectenum.PlanePromoted
	PlaneStaged    Plane = base_objectenum.PlaneStaged
)

type PriorityTier = base_objectenum.PriorityTier

const (
	PriorityTierP0 PriorityTier = base_objectenum.PriorityTierP0
	PriorityTierP1 PriorityTier = base_objectenum.PriorityTierP1
	PriorityTierP2 PriorityTier = base_objectenum.PriorityTierP2
	PriorityTierP3 PriorityTier = base_objectenum.PriorityTierP3
)

type PromptArchetype string

const (
	PromptArchetypeHybrid     PromptArchetype = "hybrid"
	PromptArchetypeStrategic  PromptArchetype = "strategic"
	PromptArchetypeStructured PromptArchetype = "structured"
	PromptArchetypeTactical   PromptArchetype = "tactical"
)

type SourceType = base_objectenum.SourceType

const (
	SourceTypeExternal SourceType = base_objectenum.SourceTypeExternal
	SourceTypeImported SourceType = base_objectenum.SourceTypeImported
	SourceTypeInternal SourceType = base_objectenum.SourceTypeInternal
)

type SpecificityLevel string

const (
	SpecificityLevelHigh   SpecificityLevel = "high"
	SpecificityLevelLow    SpecificityLevel = "low"
	SpecificityLevelMedium SpecificityLevel = "medium"
)

type Status = shared_prompt_templatesenum.Status

const (
	StatusActive     Status = shared_prompt_templatesenum.StatusActive
	StatusArchived   Status = shared_prompt_templatesenum.StatusArchived
	StatusConceptual Status = shared_prompt_templatesenum.StatusConceptual
	StatusDeprecated Status = shared_prompt_templatesenum.StatusDeprecated
	StatusDraft      Status = shared_prompt_templatesenum.StatusDraft
	StatusError      Status = shared_prompt_templatesenum.StatusError
	StatusOriginated Status = shared_prompt_templatesenum.StatusOriginated
)
