// Code generated by zqk-admin system generate-builders. DO NOT EDIT.

package bldr_lifecycle_v1

import (
	"github.com/zqk-os/zqk/pkg/objects"
	"github.com/zqk-os/zqk/pkg/specbuilder/lifecycle_builders"
)

// AgentInstructionLifecycleBuilder builds the agent_instruction lifecycle at version v1_0_0
// File: bldr_lifecycle_v1/agent_instruction_builder.go - version is encoded in package/directory name
type AgentInstructionLifecycleBuilder struct {
	*lifecycle_builders.BaseLifecycleBuilder
}

// NewAgentInstructionLifecycleBuilder creates a new builder for agent_instruction lifecycle version v1_0_0
func NewAgentInstructionLifecycleBuilder() *AgentInstructionLifecycleBuilder {
	builder := &AgentInstructionLifecycleBuilder{
		BaseLifecycleBuilder: lifecycle_builders.NewBaseLifecycleBuilder("agent_instruction", "v1_0_0"),
	}

	// Configure the lifecycle
	builder.
		SetExtends("base_lifecycle").
		SetStatusMapping(map[string]string{
			"approved":    "approved",
			"archived":    "completed",
			"error":       "error",
			"implemented": "completed",
			"in_progress": "in_progress",
			"proposed":    "proposed",
		}).
		SetPercentComplete(objects.PercentCompleteConfig{
			Method: "status_defaults",
			DefaultByStatus: map[string]any{
				"approved":    10,
				"archived":    100,
				"completed":   100,
				"conceptual":  0,
				"error":       0,
				"in_progress": 50,
				"originated":  5,
				"proposed":    15,
				"rejected":    100,
			},
		})

	// Add statuses and transitions
	builder.addAgentInstructionLifecycleData()

	return builder
}

// addAgentInstructionLifecycleData adds the agent_instruction lifecycle statuses and transitions
func (b *AgentInstructionLifecycleBuilder) addAgentInstructionLifecycleData() {

	b.AddStatus(objects.Status{
		Value:       "conceptual",
		Display:     "Conceptual",
		Origin:      true,
		Description: "Draft plane status. Prior to CAS membrane crossing.",
	})
	b.AddStatus(objects.Status{
		Value:       "originated",
		Display:     "Originated",
		Description: "CAS membrane crossed. Object officially originated.",
	})
	b.AddStatus(objects.Status{
		Value:       "proposed",
		Display:     "Proposed",
		Description: "agent instruction status 'proposed' (Proposed): not yet committed for execution; reshape before pickup.",
	})
	b.AddStatus(objects.Status{
		Value:       "approved",
		Display:     "Approved",
		Description: "agent instruction status 'approved' (Approved): ready for pickup or use; not locked mid-flight.",
	})
	b.AddStatus(objects.Status{
		Value:       "rejected",
		Display:     "Rejected",
		Terminal:    true,
		Description: "agent instruction status 'rejected' (Rejected): ended; no further normal execution transitions expected. Flags: terminal.",
	})
	b.AddStatus(objects.Status{
		Value:       "in_progress",
		Display:     "In Progress",
		Description: "agent instruction status 'in_progress' (In Progress): in flight; treat as scope-locked until it advances or halts.",
	})
	b.AddStatus(objects.Status{
		Value:       "completed",
		Display:     "Completed",
		Terminal:    true,
		Description: "agent instruction status 'completed' (Completed): ended; no further normal execution transitions expected. Flags: terminal.",
	})
	b.AddStatus(objects.Status{
		Value:       "archived",
		Display:     "Archived",
		Terminal:    true,
		Archive:     true,
		Description: "agent instruction status 'archived' (Archived): retained for history; no further execution.",
	})
	b.AddStatus(objects.Status{
		Value:       "error",
		Display:     "Error",
		System:      true,
		Description: "agent instruction status 'error' (Error): paused or system-held for repair; resolve before advancing. Flags: system-assigned.",
	})

	b.AddTransition(objects.Transition{
		From:        "conceptual",
		To:          "originated",
		Description: "Promote from draft plane to CAS membrane (CAS Qualification).",
		Manual:      true,
		Auto:        false,
	})

	b.AddTransition(objects.Transition{
		From:        "originated",
		To:          "proposed",
		Description: "Initial domain workflow transition to proposed.",
		Manual:      true,
		Auto:        true,
	})

	b.AddTransition(objects.Transition{
		From:        "proposed",
		To:          "approved",
		Description: "Human operator approves the instruction",
		Manual:      true,
		Auto:        false,
	})

	b.AddTransition(objects.Transition{
		From:        "proposed",
		To:          "rejected",
		Description: "Human operator rejects the instruction",
		Manual:      true,
		Auto:        false,
	})

	b.AddTransition(objects.Transition{
		From:        "approved",
		To:          "in_progress",
		Description: "Agent begins executing the instruction",
		Manual:      true,
		Auto:        true,
	})

	b.AddTransition(objects.Transition{
		From:        "in_progress",
		To:          "completed",
		Description: "Agent completes the instruction successfully",
		Manual:      true,
		Auto:        true,
	})

	b.AddTransition(objects.Transition{
		From:        "in_progress",
		To:          "error",
		Description: "Agent encounters an error during execution",
		Manual:      true,
		Auto:        true,
	})

	b.AddTransition(objects.Transition{
		From:        "error",
		To:          "in_progress",
		Description: "Retry the instruction after fixing the error",
		Manual:      true,
		Auto:        false,
	})

	b.AddTransition(objects.Transition{
		From:        "*",
		To:          "error",
		Description: "System error occurred",
		Manual:      false,
		Auto:        true,
	})

	b.AddTransition(objects.Transition{
		From:        "*",
		To:          "archived",
		Description: "Archive instruction from any status",
		Manual:      true,
		Auto:        false,
	})

	b.AddTransition(objects.Transition{
		From:        "archived",
		To:          "completed",
		Description: "Normalize archived historical instruction to completed",
		Manual:      true,
		Auto:        false,
	})
}

func init() {
	lifecycle_builders.RegisterBuilder(NewAgentInstructionLifecycleBuilder())
}
