// Code generated by scripts/generate_enum_tests.py; DO NOT EDIT.

package requirements

import (
	"testing"
)

func TestEnums_Completeness(t *testing.T) {
	tests := []struct {
		name string
		val  string
	}{
		{"PriorityP0", string(PriorityP0)},
		{"PriorityP1", string(PriorityP1)},
		{"PriorityP2", string(PriorityP2)},
		{"PriorityP3", string(PriorityP3)},
		{"PriorityTierP0", string(PriorityTierP0)},
		{"PriorityTierP1", string(PriorityTierP1)},
		{"PriorityTierP2", string(PriorityTierP2)},
		{"PriorityTierP3", string(PriorityTierP3)},
		{"SourceTypeExternal", string(SourceTypeExternal)},
		{"SourceTypeImported", string(SourceTypeImported)},
		{"SourceTypeInternal", string(SourceTypeInternal)},
		{"StatusActive", string(StatusActive)},
		{"StatusArchived", string(StatusArchived)},
		{"StatusComplete", string(StatusComplete)},
		{"StatusDeferred", string(StatusDeferred)},
		{"StatusProposed", string(StatusProposed)},
		{"StatusRejected", string(StatusRejected)},
	}
	for _, tt := range tests {
		if tt.val == "" {
			t.Errorf("constant %s has empty value", tt.name)
		}
	}
}
