// Code generated by scripts/generate_enum_tests.py; DO NOT EDIT.

package code_quality_metric

import (
	"testing"
)

func TestEnums_Completeness(t *testing.T) {
	tests := []struct {
		name string
		val  string
	}{
		{"MeasurementPeriodDaily", string(MeasurementPeriodDaily)},
		{"MeasurementPeriodMonthly", string(MeasurementPeriodMonthly)},
		{"MeasurementPeriodWeekly", string(MeasurementPeriodWeekly)},
		{"MetricCategoryAdherence", string(MetricCategoryAdherence)},
		{"MetricCategoryCompliance", string(MetricCategoryCompliance)},
		{"MetricCategoryResolution", string(MetricCategoryResolution)},
		{"MetricCategoryTrend", string(MetricCategoryTrend)},
		{"MetricCategoryViolation", string(MetricCategoryViolation)},
		{"MetricTypeApplication", string(MetricTypeApplication)},
		{"MetricTypeCommand", string(MetricTypeCommand)},
		{"MetricTypeCustom", string(MetricTypeCustom)},
		{"MetricTypePerformance", string(MetricTypePerformance)},
		{"MetricTypeSystem", string(MetricTypeSystem)},
		{"PlaneApoptotic", string(PlaneApoptotic)},
		{"PlaneDraft", string(PlaneDraft)},
		{"PlanePromoted", string(PlanePromoted)},
		{"PlaneStaged", string(PlaneStaged)},
		{"PriorityTierP0", string(PriorityTierP0)},
		{"PriorityTierP1", string(PriorityTierP1)},
		{"PriorityTierP2", string(PriorityTierP2)},
		{"PriorityTierP3", string(PriorityTierP3)},
		{"SourceTypeExternal", string(SourceTypeExternal)},
		{"SourceTypeImported", string(SourceTypeImported)},
		{"SourceTypeInternal", string(SourceTypeInternal)},
		{"StatusAnalyzed", string(StatusAnalyzed)},
		{"StatusArchived", string(StatusArchived)},
		{"StatusCollected", string(StatusCollected)},
		{"StatusConceptual", string(StatusConceptual)},
		{"StatusError", string(StatusError)},
		{"StatusOriginated", string(StatusOriginated)},
		{"StatusReported", string(StatusReported)},
		{"TierTierN1", string(TierTierN1)},
		{"TierTierN2", string(TierTierN2)},
		{"TierTierN3", string(TierTierN3)},
		{"TrendDirectionDegrading", string(TrendDirectionDegrading)},
		{"TrendDirectionImproving", string(TrendDirectionImproving)},
		{"TrendDirectionStable", string(TrendDirectionStable)},
	}
	for _, tt := range tests {
		if tt.val == "" {
			t.Errorf("constant %s has empty value", tt.name)
		}
	}
}
