// Code generated by pkg/specbuilder/instance_builders/codegen.go from lifecycle YAML.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package shared_agent_feeds

type Status string

const (
	StatusActive   Status = "active"
	StatusArchived Status = "archived"
	StatusError    Status = "error"
)
