// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package bldr_instance_v1

import (
	"github.com/zqk-os/zqk/pkg/objects"
	enumv "github.com/zqk-os/zqk/packs/agent/bldr_enum_v1/prompt_template"
	"github.com/zqk-os/zqk/pkg/specbuilder/instance_builders"
)

// PromptTemplateInstanceBuilder builds prompt_template instances
// ONE builder handles ALL prompt_template instances
type PromptTemplateInstanceBuilder struct {
	*instance_builders.BaseInstanceBuilder
}

// NewPromptTemplateInstanceBuilder creates a new prompt_template instance builder.
// Pass the instance schema_version string for this spec; use objects.DefaultSchemaVersion for the project default (pkg/objects constants).
// Field order is derived from the spec (not hardcoded) to avoid drift
func NewPromptTemplateInstanceBuilder(schemaVersion string) *PromptTemplateInstanceBuilder {
	// Derive canonical field order from spec (follows architecture pattern)
	// System fields first, then spec-defined fields in sorted order
	fieldOrder := instance_builders.FieldOrderFromSpec("prompt_template")

	// Create base builder
	builder := &PromptTemplateInstanceBuilder{
		BaseInstanceBuilder: instance_builders.NewBaseInstanceBuilder(
			"prompt_template",
			schemaVersion,
			fieldOrder,
			nil, // spec builder (optional)
		),
	}

	return builder
}

// Status sets the status field
func (b *PromptTemplateInstanceBuilder) Status(value enumv.Status) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyStatus, string(value))
	return b
}

// ID sets the id field
func (b *PromptTemplateInstanceBuilder) ID(value string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyID, value)
	return b
}

// ArchivedAt sets the archived_at field
func (b *PromptTemplateInstanceBuilder) ArchivedAt(value any) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedAt, value)
	return b
}

// SetArchivedAt is a compatibility alias for ArchivedAt.
func (b *PromptTemplateInstanceBuilder) SetArchivedAt(value any) *PromptTemplateInstanceBuilder {
	return b.ArchivedAt(value)
}

// ArchivedBy sets the archived_by field
func (b *PromptTemplateInstanceBuilder) ArchivedBy(value string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedBy, value)
	return b
}

// SetArchivedBy is a compatibility alias for ArchivedBy.
func (b *PromptTemplateInstanceBuilder) SetArchivedBy(value string) *PromptTemplateInstanceBuilder {
	return b.ArchivedBy(value)
}

// Artifacts sets the artifacts field
func (b *PromptTemplateInstanceBuilder) Artifacts(value []string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyArtifacts, value)
	return b
}

// SetArtifacts is a compatibility alias for Artifacts.
func (b *PromptTemplateInstanceBuilder) SetArtifacts(value []string) *PromptTemplateInstanceBuilder {
	return b.Artifacts(value)
}

// Category sets the category field
func (b *PromptTemplateInstanceBuilder) Category(value string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyCategory, value)
	return b
}

// SetCategory is a compatibility alias for Category.
func (b *PromptTemplateInstanceBuilder) SetCategory(value string) *PromptTemplateInstanceBuilder {
	return b.Category(value)
}

// ChangeLog sets the change_log field
func (b *PromptTemplateInstanceBuilder) ChangeLog(value []string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyChangeLog, value)
	return b
}

// SetChangeLog is a compatibility alias for ChangeLog.
func (b *PromptTemplateInstanceBuilder) SetChangeLog(value []string) *PromptTemplateInstanceBuilder {
	return b.ChangeLog(value)
}

// CompletenessValidation sets the completeness_validation field
func (b *PromptTemplateInstanceBuilder) CompletenessValidation(value []string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyCompletenessValidation, value)
	return b
}

// SetCompletenessValidation is a compatibility alias for CompletenessValidation.
func (b *PromptTemplateInstanceBuilder) SetCompletenessValidation(value []string) *PromptTemplateInstanceBuilder {
	return b.CompletenessValidation(value)
}

// Context sets the context field
func (b *PromptTemplateInstanceBuilder) Context(value any) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyContext, value)
	return b
}

// SetContext is a compatibility alias for Context.
func (b *PromptTemplateInstanceBuilder) SetContext(value any) *PromptTemplateInstanceBuilder {
	return b.Context(value)
}

// Deadline sets the deadline field
func (b *PromptTemplateInstanceBuilder) Deadline(value string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyDeadline, value)
	return b
}

// SetDeadline is a compatibility alias for Deadline.
func (b *PromptTemplateInstanceBuilder) SetDeadline(value string) *PromptTemplateInstanceBuilder {
	return b.Deadline(value)
}

// Dependencies sets the dependencies field
func (b *PromptTemplateInstanceBuilder) Dependencies(value []string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyDependencies, value)
	return b
}

// SetDependencies is a compatibility alias for Dependencies.
func (b *PromptTemplateInstanceBuilder) SetDependencies(value []string) *PromptTemplateInstanceBuilder {
	return b.Dependencies(value)
}

// Description sets the description field
func (b *PromptTemplateInstanceBuilder) Description(value any) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyDescription, value)
	return b
}

// SetDescription is a compatibility alias for Description.
func (b *PromptTemplateInstanceBuilder) SetDescription(value any) *PromptTemplateInstanceBuilder {
	return b.Description(value)
}

// DocEntryRefs sets the doc_entry_refs field
func (b *PromptTemplateInstanceBuilder) DocEntryRefs(value []string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyDocEntryRefs, value)
	return b
}

// SetDocEntryRefs is a compatibility alias for DocEntryRefs.
func (b *PromptTemplateInstanceBuilder) SetDocEntryRefs(value []string) *PromptTemplateInstanceBuilder {
	return b.DocEntryRefs(value)
}

// ExpectedOutcomeKinds sets the expected_outcome_kinds field
func (b *PromptTemplateInstanceBuilder) ExpectedOutcomeKinds(value []string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyExpectedOutcomeKinds, value)
	return b
}

// SetExpectedOutcomeKinds is a compatibility alias for ExpectedOutcomeKinds.
func (b *PromptTemplateInstanceBuilder) SetExpectedOutcomeKinds(value []string) *PromptTemplateInstanceBuilder {
	return b.ExpectedOutcomeKinds(value)
}

// GoalRefs sets the goal_refs field
func (b *PromptTemplateInstanceBuilder) GoalRefs(value []string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyGoalRefs, value)
	return b
}

// SetGoalRefs is a compatibility alias for GoalRefs.
func (b *PromptTemplateInstanceBuilder) SetGoalRefs(value []string) *PromptTemplateInstanceBuilder {
	return b.GoalRefs(value)
}

// MandatoryConstraints sets the mandatory_constraints field
func (b *PromptTemplateInstanceBuilder) MandatoryConstraints(value []string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyMandatoryConstraints, value)
	return b
}

// SetMandatoryConstraints is a compatibility alias for MandatoryConstraints.
func (b *PromptTemplateInstanceBuilder) SetMandatoryConstraints(value []string) *PromptTemplateInstanceBuilder {
	return b.MandatoryConstraints(value)
}

// OriginProject sets the origin_project field
func (b *PromptTemplateInstanceBuilder) OriginProject(value string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyOriginProject, value)
	return b
}

// SetOriginProject is a compatibility alias for OriginProject.
func (b *PromptTemplateInstanceBuilder) SetOriginProject(value string) *PromptTemplateInstanceBuilder {
	return b.OriginProject(value)
}

// OriginSystem sets the origin_system field
func (b *PromptTemplateInstanceBuilder) OriginSystem(value string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyOriginSystem, value)
	return b
}

// SetOriginSystem is a compatibility alias for OriginSystem.
func (b *PromptTemplateInstanceBuilder) SetOriginSystem(value string) *PromptTemplateInstanceBuilder {
	return b.OriginSystem(value)
}

// OriginatorQuestionnaireRefs sets the originator_questionnaire_refs field
func (b *PromptTemplateInstanceBuilder) OriginatorQuestionnaireRefs(value []string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyOriginatorQuestionnaireRefs, value)
	return b
}

// SetOriginatorQuestionnaireRefs is a compatibility alias for OriginatorQuestionnaireRefs.
func (b *PromptTemplateInstanceBuilder) SetOriginatorQuestionnaireRefs(value []string) *PromptTemplateInstanceBuilder {
	return b.OriginatorQuestionnaireRefs(value)
}

// Plane sets the plane field
func (b *PromptTemplateInstanceBuilder) Plane(value enumv.Plane) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyPlane, string(value))
	return b
}

// SetPlane is a compatibility alias for Plane.
func (b *PromptTemplateInstanceBuilder) SetPlane(value enumv.Plane) *PromptTemplateInstanceBuilder {
	return b.Plane(value)
}

// PriorityTier sets the priority_tier field
func (b *PromptTemplateInstanceBuilder) PriorityTier(value enumv.PriorityTier) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyPriorityTier, string(value))
	return b
}

// SetPriorityTier is a compatibility alias for PriorityTier.
func (b *PromptTemplateInstanceBuilder) SetPriorityTier(value enumv.PriorityTier) *PromptTemplateInstanceBuilder {
	return b.PriorityTier(value)
}

// PromptArchetype sets the prompt_archetype field
func (b *PromptTemplateInstanceBuilder) PromptArchetype(value enumv.PromptArchetype) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyPromptArchetype, string(value))
	return b
}

// SetPromptArchetype is a compatibility alias for PromptArchetype.
func (b *PromptTemplateInstanceBuilder) SetPromptArchetype(value enumv.PromptArchetype) *PromptTemplateInstanceBuilder {
	return b.PromptArchetype(value)
}

// PromptBody sets the prompt_body field
func (b *PromptTemplateInstanceBuilder) PromptBody(value any) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyPromptBody, value)
	return b
}

// SetPromptBody is a compatibility alias for PromptBody.
func (b *PromptTemplateInstanceBuilder) SetPromptBody(value any) *PromptTemplateInstanceBuilder {
	return b.PromptBody(value)
}

// Provenance sets the provenance field
func (b *PromptTemplateInstanceBuilder) Provenance(value map[string]any) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyProvenance, value)
	return b
}

// SetProvenance is a compatibility alias for Provenance.
func (b *PromptTemplateInstanceBuilder) SetProvenance(value map[string]any) *PromptTemplateInstanceBuilder {
	return b.Provenance(value)
}

// Questions sets the questions field
func (b *PromptTemplateInstanceBuilder) Questions(value []string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyQuestions, value)
	return b
}

// SetQuestions is a compatibility alias for Questions.
func (b *PromptTemplateInstanceBuilder) SetQuestions(value []string) *PromptTemplateInstanceBuilder {
	return b.Questions(value)
}

// RelatedObjectRefs sets the related_object_refs field
func (b *PromptTemplateInstanceBuilder) RelatedObjectRefs(value []string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyRelatedObjectRefs, value)
	return b
}

// SetRelatedObjectRefs is a compatibility alias for RelatedObjectRefs.
func (b *PromptTemplateInstanceBuilder) SetRelatedObjectRefs(value []string) *PromptTemplateInstanceBuilder {
	return b.RelatedObjectRefs(value)
}

// RiskBlockerRefs sets the risk_blocker_refs field
func (b *PromptTemplateInstanceBuilder) RiskBlockerRefs(value []string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyRiskBlockerRefs, value)
	return b
}

// SetRiskBlockerRefs is a compatibility alias for RiskBlockerRefs.
func (b *PromptTemplateInstanceBuilder) SetRiskBlockerRefs(value []string) *PromptTemplateInstanceBuilder {
	return b.RiskBlockerRefs(value)
}

// SchemaRef sets the schema_ref field
func (b *PromptTemplateInstanceBuilder) SchemaRef(value string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeySchemaRef, value)
	return b
}

// SetSchemaRef is a compatibility alias for SchemaRef.
func (b *PromptTemplateInstanceBuilder) SetSchemaRef(value string) *PromptTemplateInstanceBuilder {
	return b.SchemaRef(value)
}

// SourceType sets the source_type field
func (b *PromptTemplateInstanceBuilder) SourceType(value enumv.SourceType) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeySourceType, string(value))
	return b
}

// SetSourceType is a compatibility alias for SourceType.
func (b *PromptTemplateInstanceBuilder) SetSourceType(value enumv.SourceType) *PromptTemplateInstanceBuilder {
	return b.SourceType(value)
}

// SpecAdherence sets the spec_adherence field
func (b *PromptTemplateInstanceBuilder) SpecAdherence(value map[string]any) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeySpecAdherence, value)
	return b
}

// SetSpecAdherence is a compatibility alias for SpecAdherence.
func (b *PromptTemplateInstanceBuilder) SetSpecAdherence(value map[string]any) *PromptTemplateInstanceBuilder {
	return b.SpecAdherence(value)
}

// SpecificityLevel sets the specificity_level field
func (b *PromptTemplateInstanceBuilder) SpecificityLevel(value enumv.SpecificityLevel) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeySpecificityLevel, string(value))
	return b
}

// SetSpecificityLevel is a compatibility alias for SpecificityLevel.
func (b *PromptTemplateInstanceBuilder) SetSpecificityLevel(value enumv.SpecificityLevel) *PromptTemplateInstanceBuilder {
	return b.SpecificityLevel(value)
}

// Stakeholders sets the stakeholders field
func (b *PromptTemplateInstanceBuilder) Stakeholders(value []string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyStakeholders, value)
	return b
}

// SetStakeholders is a compatibility alias for Stakeholders.
func (b *PromptTemplateInstanceBuilder) SetStakeholders(value []string) *PromptTemplateInstanceBuilder {
	return b.Stakeholders(value)
}

// StatusHistory sets the status_history field
func (b *PromptTemplateInstanceBuilder) StatusHistory(value []string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyStatusHistory, value)
	return b
}

// SetStatusHistory is a compatibility alias for StatusHistory.
func (b *PromptTemplateInstanceBuilder) SetStatusHistory(value []string) *PromptTemplateInstanceBuilder {
	return b.StatusHistory(value)
}

// TargetDate sets the target_date field
func (b *PromptTemplateInstanceBuilder) TargetDate(value string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyTargetDate, value)
	return b
}

// SetTargetDate is a compatibility alias for TargetDate.
func (b *PromptTemplateInstanceBuilder) SetTargetDate(value string) *PromptTemplateInstanceBuilder {
	return b.TargetDate(value)
}

// Title sets the title field
func (b *PromptTemplateInstanceBuilder) Title(value string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyTitle, value)
	return b
}

// SetTitle is a compatibility alias for Title.
func (b *PromptTemplateInstanceBuilder) SetTitle(value string) *PromptTemplateInstanceBuilder {
	return b.Title(value)
}

// Urn sets the urn field
func (b *PromptTemplateInstanceBuilder) Urn(value string) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyUrn, value)
	return b
}

// SetUrn is a compatibility alias for Urn.
func (b *PromptTemplateInstanceBuilder) SetUrn(value string) *PromptTemplateInstanceBuilder {
	return b.Urn(value)
}

// Version sets the version field
func (b *PromptTemplateInstanceBuilder) Version(value int) *PromptTemplateInstanceBuilder {
	b.SetField(objects.FieldKeyVersion, value)
	return b
}

// SetVersion is a compatibility alias for Version.
func (b *PromptTemplateInstanceBuilder) SetVersion(value int) *PromptTemplateInstanceBuilder {
	return b.Version(value)
}
