package vds

import (
	"bytes"
	"context"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/zqk-os/zqk/pkg/errfmt"
	"github.com/zqk-os/zqk/pkg/objects"
	"github.com/zqk-os/zqk/pkg/paths"
	fileutil "github.com/zqk-os/zqk/pkg/utils/fileutil"
)

const (
	schemaProject      = "zqk_vds_project_v1"
	generatedMarkerFmt = "GENERATED by %s --provider %s"
)

// ProjectOptions controls a config-driven vendor instruction export.
type ProjectOptions struct {
	ProjectRoot   string
	ProviderID    string // empty → config default
	AllProviders  bool
	OutRel        string // optional override of provider.out
	Lookup        ObjectLookup
	TitleLookup   TitleLookup
	Customization *Customization
	Spine         *SpineProfile
}

// ProjectResult is one provider export outcome.
type ProjectResult struct {
	Schema     string           `json:"schema"`
	ProviderID string           `json:"provider_id"`
	Format     string           `json:"format"`
	OutPath    string           `json:"out_path"`
	PolicyID   string           `json:"policy_id"`
	Glossary   GlossaryRefs     `json:"glossary"`
	Wrote      bool             `json:"wrote,omitempty"`
	CheckOK    bool             `json:"check_ok,omitempty"`
	Differs    bool             `json:"differs,omitempty"`
	Bytes      int              `json:"bytes"`
	ContentSHA string           `json:"content_fingerprint,omitempty"`
	Providers  []VendorProvider `json:"configured_providers,omitempty"`
}

// ProjectBatchResult covers --all.
type ProjectBatchResult struct {
	Schema  string          `json:"schema"`
	Results []ProjectResult `json:"results"`
	Failed  []string        `json:"failed_provider_ids,omitempty"`
}

// RenderProviderBody builds export text for a provider format.
func RenderProviderBody(ctx context.Context, prov VendorProvider, opt ProjectOptions) (string, GlossaryRefs, error) {
	switch strings.TrimSpace(prov.Format) {
	case FormatIDEMDC, "":
		return renderIDEMDC(ctx, prov, opt)
	default:
		return "", GlossaryRefs{}, errfmt.Errorf("vds project: unsupported format %q for provider %q", prov.Format, prov.ID)
	}
}

func renderIDEMDC(ctx context.Context, prov VendorProvider, opt ProjectOptions) (string, GlossaryRefs, error) {
	gls := ResolveGlossary(ctx, opt.Customization, opt.TitleLookup)
	polTitle := PolicyID
	polEnforcement := "standard (blocking when active)"
	if opt.Lookup != nil {
		if obj, err := opt.Lookup(ctx, PolicyID); err == nil && obj != nil {
			if t, _ := obj[objects.FieldKeyTitle].(string); strings.TrimSpace(t) != "" {
				polTitle = strings.TrimSpace(t)
			}
			if pt, _ := obj[objects.FieldKeyPolicyType].(string); strings.TrimSpace(pt) != "" {
				polEnforcement = strings.TrimSpace(pt)
			}
			if enf, ok := obj[objects.FieldKeyEnforcement].(map[string]any); ok {
				if sev, _ := enf[objects.FieldKeySeverity].(string); sev != "" {
					polEnforcement += "; severity=" + sev
				}
				if auto, ok := enf["automated"].(bool); ok && auto {
					polEnforcement += "; automated evaluator"
				}
			}
		}
	}

	var stageLines []string
	if opt.Spine != nil {
		for _, s := range opt.Spine.Stages {
			stageLines = append(stageLines, fmt.Sprintf("- `%s` — %s", s.ID, strings.TrimSpace(s.Purpose)))
		}
	}
	if len(stageLines) == 0 {
		for _, id := range StageIDs {
			stageLines = append(stageLines, "- `"+id+"`")
		}
	}

	testMode := "(see customization)"
	if opt.Customization != nil && strings.TrimSpace(opt.Customization.TestExecution.Mode) != "" {
		testMode = opt.Customization.TestExecution.Mode
	}
	glsLine := CultureGlossaryLine(gls)
	marker := fmt.Sprintf(generatedMarkerFmt, paths.CLIUsage("workflow", "vds", "project"), prov.ID)

	var b strings.Builder
	b.WriteString("# Verifiable Decomposition Spine (VDS)\n\n")
	b.WriteString("<!-- " + marker + " — do not hand-edit body; update kernel objects then re-run. -->\n")
	b.WriteString("<!-- SSOT: POL-WORKFLOW-VDS + glossary titles + docs/quality VDS profiles. TRACK: [REDACTED-ID] -->\n\n")
	fmt.Fprintf(&b, "**Policy:** `%s` — %s (%s)\n", PolicyID, polTitle, polEnforcement)
	fmt.Fprintf(&b, "**%s**\n", glsLine)
	b.WriteString("**Contract:** `docs/architecture/VERIFIABLE_DECOMPOSITION_SPINE.md`\n")
	b.WriteString("**Vendor projection:** `docs/architecture/KERNEL_VENDOR_INSTRUCTION_PROJECTION.md`\n")
	b.WriteString("**Spine:** `docs/quality/verifiable_decomposition_spine_profile.yaml`\n")
	b.WriteString("**Customization:** `docs/quality/verifiable_decomposition_customization.yaml` (`vendor_providers`)\n\n")
	b.WriteString("## When this applies\n\n")
	b.WriteString("Any claim of progress/completion across intent → operate/release — including CAP/CVS/BLI close and \"done\" in chat.\n\n")
	b.WriteString("## Required before saying done\n\n")
	b.WriteString("1. Name **stage** + **chunk_id**(s).\n")
	b.WriteString("2. Show **rubric_ref** + **dsl_checks**.\n")
	b.WriteString("3. Show **evidence_refs** (job id, log path, object id, commit SHA — re-runnable).\n")
	b.WriteString("4. Run **`" + paths.CLIUsage("workflow", "vds", "evaluate", "--format", "json") + "`** (or `agent-prompt`) and keep exit 0 — or human **waiver_ref**.\n\n")
	b.WriteString("Missing any item ⇒ **not done**. Do not substitute narrative.\n\n")
	b.WriteString("```bash\n")
	b.WriteString(paths.CLIUsage("workflow", "vds", "checklist", "--format", "agent-prompt") + "\n")
	b.WriteString(paths.CLIUsage("workflow", "vds", "evaluate", "--format", "json") + "\n")
	fmt.Fprintf(&b, "%s\n", paths.CLIUsage("workflow", "vds", "project", "--provider", prov.ID, "--check"))
	b.WriteString("```\n\n")
	b.WriteString("## Rigid stages (from spine profile)\n\n")
	b.WriteString(strings.Join(stageLines, "\n"))
	b.WriteString("\n\n## Rigid vs customizable\n\n")
	b.WriteString("- **Rigid:** five stages, chunk contract, hard gates, forbidden theater (VDS-R1–R7).\n")
	fmt.Fprintf(&b, "- **Customizable** (customization file only): lint commands, `test_execution.mode` (this project: **%s**), process-data mutation, CI/security/perf, `vendor_providers`.\n\n", testMode)
	b.WriteString("## Do not\n\n")
	b.WriteString("- Claim done from chat alone.\n")
	b.WriteString("- Advance CAP / close BLI/CVS without VDS evidence for in-scope chunks.\n")
	b.WriteString("- Self-waive; waivers are human-authored objects only.\n")
	b.WriteString("- Delete or rename spine stages in customization.\n")
	b.WriteString("- Treat vendor instruction files as SSOT — re-project from the kernel after policy/glossary changes.\n")
	return b.String(), gls, nil
}

// WriteOrCheckProvider projects one configured provider.
func WriteOrCheckProvider(ctx context.Context, opt ProjectOptions, write, check bool) (*ProjectResult, error) {
	if opt.ProjectRoot == "" {
		return nil, errfmt.Errorf("vds project: project root required")
	}
	cfg := ResolveVendorProviders(opt.Customization)
	prov, err := LookupProvider(cfg, opt.ProviderID)
	if err != nil {
		return nil, err
	}
	return writeOrCheckOne(ctx, opt, prov, cfg, write, check)
}

// WriteOrCheckAllProviders projects every enabled provider.
func WriteOrCheckAllProviders(ctx context.Context, opt ProjectOptions, write, check bool) (*ProjectBatchResult, error) {
	if opt.ProjectRoot == "" {
		return nil, errfmt.Errorf("vds project: project root required")
	}
	if !write && !check {
		return nil, errfmt.Errorf("vds project: pass --write and/or --check")
	}
	cfg := ResolveVendorProviders(opt.Customization)
	batch := &ProjectBatchResult{Schema: schemaProject}
	for _, prov := range EnabledProviders(cfg) {
		res, err := writeOrCheckOne(ctx, opt, prov, cfg, write, check)
		if res != nil {
			batch.Results = append(batch.Results, *res)
		}
		if err != nil {
			batch.Failed = append(batch.Failed, prov.ID)
		}
	}
	if len(batch.Failed) > 0 {
		return batch, errfmt.Errorf("vds project --all: failed providers: %s", strings.Join(batch.Failed, ", "))
	}
	if len(batch.Results) == 0 {
		return batch, errfmt.Errorf("vds project --all: no enabled providers in config")
	}
	return batch, nil
}

func writeOrCheckOne(ctx context.Context, opt ProjectOptions, prov VendorProvider, cfg VendorProvidersConfig, write, check bool) (*ProjectResult, error) {
	if !write && !check {
		return nil, errfmt.Errorf("vds project: pass --write and/or --check")
	}
	body, gls, err := RenderProviderBody(ctx, prov, opt)
	if err != nil {
		return nil, err
	}
	rel := strings.TrimSpace(opt.OutRel)
	if rel == "" {
		rel = prov.Out
	}
	outPath := rel
	if !filepath.IsAbs(outPath) {
		outPath = filepath.Join(opt.ProjectRoot, rel)
	}
	want := []byte(body)
	res := &ProjectResult{
		Schema:     schemaProject,
		ProviderID: prov.ID,
		Format:     prov.Format,
		OutPath:    outPath,
		PolicyID:   PolicyID,
		Glossary:   gls,
		Bytes:      len(want),
		Providers:  cfg.Providers,
	}
	res.ContentSHA = shortFingerprint(want)

	existing, readErr := fileutil.ReadFile(outPath)
	if check {
		if readErr != nil {
			res.Differs = true
			res.CheckOK = false
			if !write {
				return res, errfmt.Errorf("vds project --check: missing or unreadable %s (provider %s)", outPath, prov.ID)
			}
		} else if !bytes.Equal(normalizeNewlines(existing), normalizeNewlines(want)) {
			res.Differs = true
			res.CheckOK = false
			if !write {
				return res, errfmt.Errorf("vds project --check: drift for provider %s (%s); run with --write", prov.ID, outPath)
			}
		} else {
			res.CheckOK = true
			res.Differs = false
			if !write {
				return res, nil
			}
		}
	}

	if write {
		if err := fileutil.MkdirAll(filepath.Dir(outPath), paths.DirPerm755); err != nil {
			return res, errfmt.Errorf("vds project: mkdir: %w", err)
		}
		if err := fileutil.WriteFile(outPath, want, paths.FilePerm644); err != nil {
			return res, errfmt.Errorf("vds project: write: %w", err)
		}
		res.Wrote = true
		res.CheckOK = true
		res.Differs = false
	}
	return res, nil
}

func normalizeNewlines(b []byte) []byte {
	return bytes.ReplaceAll(b, []byte("\r\n"), []byte("\n"))
}

func shortFingerprint(b []byte) string {
	var h uint64 = 14695981039346656037
	for _, c := range b {
		h ^= uint64(c)
		h *= 1099511628211
	}
	return fmt.Sprintf("%016x", h)
}
