package locknames

import "testing"

func TestLockNames(t *testing.T) {
	// Verify that constant locknames are non-empty strings
	names := []string{
		LockNameAsyncMetricsCollectorDisable,
		LockNameAsyncMetricsCollectorEnable,
		LockNameAsyncMetricsCollectorEnqueue,
		LockNameAsyncMetricsCollectorStop,
		LockNameAuditBufferAddEvent,
		LockNameAuditBufferGetCallback,
		LockNameAuditBufferGetFilestorage,
		LockNameAuditBufferGetGlobal,
		LockNameAuditBufferGetPendingCount,
		LockNameAuditBufferGetProjectRoot,
		LockNameAuditBufferGetStats,
		LockNameAuditBufferInitGlobal,
		LockNameAuditBufferIsDrained,
		LockNameAuditBufferIsEnabled,
		LockNameAuditBufferSetCallback,
		LockNameAuditBufferSetEnabled,
		LockNameAuditBufferSetFlushCallback,
		LockNameAuditBufferSetFlushChannel,
		LockNameBatchGeneratorDirScan,
		LockNameBatchGeneratorGenerateBatch,
		LockNameBatchGeneratorGetCachedCheck,
		LockNameBatchGeneratorGetCachedRead,
		LockNameBatchGeneratorGetDirScanLock,
		LockNameBatchGeneratorGetLastSequence,
		LockNameBatchGeneratorGetMaxSequence,
		LockNameBatchGeneratorLegacyGetCreate,
		LockNameBatchGeneratorLegacyGetFast,
		LockNameBatchGeneratorReset,
		LockNameBatchGeneratorScanCacheCheck,
		LockNameBatchGeneratorScanCacheDoubleCheck,
		LockNameBatchGeneratorScanCacheRead,
		LockNameBatchGeneratorScanCacheRead2,
		LockNameBatchGeneratorUpdateCache,
		LockNameBucketStrategyGetBaseCache,
		LockNameBucketStrategyGetBaseCheck,
		LockNameBucketStrategyGetDefaultCache,
		LockNameBucketStrategyGetDefaultCheck,
		LockNameBucketStrategyLoaderCache,
		LockNameBucketStrategyLoaderGetAll,
		LockNameBucketStrategyLoaderGetCheck,
		LockNameBucketStrategyLoaderGetForKind,
		LockNameBucketStrategyLoaderLoadFromCache,
		LockNameBucketStrategyLoaderReload,
		LockNameBucketStrategyLoaderUpdateCache,
		LockNameBulkDeleteCleanup,
		LockNameBulkDeleteCreateJob,
		LockNameBulkDeleteExecuteGetJob,
		LockNameBulkDeleteExecuteStart,
		LockNameBulkDeleteGetStatusJob,
		LockNameBulkDeleteGetStatusManager,
		LockNameBulkDeleteJobFailed,
		LockNameBulkDeleteJobUpdate,
		LockNameCacheManagerCleanupOldInvalidations,
		LockNameCacheManagerGetConsistency,
		LockNameCacheManagerInvalidateAsync,
		LockNameStorageOrchestratorRegisterOperation,
		LockNameStreamRegistryCacheInvalidate,
		LockNameTestModeUpdateSerialize,
		LockNameTransactionAddFile,
		LockNameTransactionCommitCheck,
		LockNameTransactionCommitDeferCheck,
		LockNameTransactionCommitMark,
		LockNameTransactionCreate,
		LockNameTransactionDeleteAdd,
		LockNameTransactionDeleteCheck,
		LockNameTransactionUpdate,
		LockNameTransactionUpdateAdd,
		LockNameUnifiedMetricsStopCopy,
		LockNameUpdateAppendWal,
		LockNameVolumeTrackerGetVolume,
		LockNameVolumeTrackerRecord,
		LockNameWaitgroupManagerAdd,
		LockNameWaitgroupManagerCount,
		LockNameWaitgroupManagerCreateGroup,
		LockNameWaitgroupManagerDeleteGroup,
		LockNameWaitgroupManagerDone,
		LockNameWaitgroupManagerGetGroup,
		LockNameWaitgroupManagerGetInfo,
		LockNameWaitgroupManagerListGroups,
		LockNameWaitgroupManagerSetObserver,
		LockNameWaitgroupManagerWait,
		LockNameWaitgroupObserverClearStats,
		LockNameWaitgroupObserverGetAllStats,
		LockNameWaitgroupObserverGetStats,
		LockNameWaitgroupObserverOnAdd,
		LockNameWaitgroupObserverOnCompleted,
		LockNameWaitgroupObserverOnCreated,
		LockNameWaitgroupObserverOnDone,
		LockNameWaitgroupObserverOnWait,
		LockNameWaitgroupObserverSetEnabled,
		LockNameWaitgroupObserverSummary,
		LockNameWalCompact,
		LockNameKindMapperInitializeCheck,
		LockNameKindMapperSetDirectories,
		LockNameKindMapperGetDirectories,
		LockNameEvolutionOutput,
	}

	for _, name := range names {
		if name == "" {
			t.Errorf("expected lock name constant to be non-empty")
		}
	}
}
