// Code generated by zqk-admin system generate-builders. DO NOT EDIT.

package bldr_trait_v1

import (
	"github.com/zqk-os/zqk/pkg/specbuilder/trait_builders"
)

// StatusReactiveBuilder builds the status_reactive trait at version v1_0_0
// File: bldr_trait_v1/status_reactive_builder.go - version is encoded in package/directory name
type StatusReactiveBuilder struct {
	*trait_builders.BaseTraitBuilder
}

// NewStatusReactiveBuilder creates a new builder for status_reactive trait version v1_0_0
func NewStatusReactiveBuilder() *StatusReactiveBuilder {
	builder := &StatusReactiveBuilder{
		BaseTraitBuilder: trait_builders.NewBaseTraitBuilder("status_reactive", "v1_0_0"),
	}

	// Configure the trait
	builder.
		SetDescription("Object-level admission for status-event listeners. A catalyst status save\\npublishes one event to each outbound ref (listener stubs). Kinds with this\\ntrait may run the generic interpreter (lifecycle on_dependent_status).\\nKinds without this trait no-op. The listener updates only itself.\\nNot occupiable (claimed_by slot). Not open_countable (remaining_open_count).\\nNot auto_status_transitionable (--auto-status).\\nTRACK: POL-ARCH-20260901 / kernel-backlog.\\n").
		SetCategory("behavior").
		SetObjectLevel(true).
		SetFieldLevel(false)

	return builder
}

func init() {
	trait_builders.RegisterBuilder(NewStatusReactiveBuilder())
}
