// Code generated by scripts/generate_enum_tests.py; DO NOT EDIT.

package shared_displays

import (
	"testing"
)

func TestEnums_Completeness(t *testing.T) {
	tests := []struct {
		name string
		val  string
	}{
		{"StatusArchived", string(StatusArchived)},
		{"StatusConceptual", string(StatusConceptual)},
		{"StatusConfigured", string(StatusConfigured)},
		{"StatusCreated", string(StatusCreated)},
		{"StatusError", string(StatusError)},
		{"StatusOriginated", string(StatusOriginated)},
		{"StatusRendered", string(StatusRendered)},
		{"StatusValidated", string(StatusValidated)},
	}
	for _, tt := range tests {
		if tt.val == "" {
			t.Errorf("constant %s has empty value", tt.name)
		}
	}
}
