// Code generated by pkg/specbuilder/instance_builders/codegen.go from lifecycle YAML.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package shared_displays

type Status string

const (
	StatusArchived   Status = "archived"
	StatusConfigured Status = "configured"
	StatusCreated    Status = "created"
	StatusError      Status = "error"
	StatusRendered   Status = "rendered"
	StatusValidated  Status = "validated"
)
