package observer

const emptyEntityValue = ""

// Entity represents a single code entity extracted from source (function, method, type, etc.).
// Used to feed the knowledge kernel graph (ITEM-OBS-001, ITEM-OBS-002).
type Entity struct {
	Kind       string            // function, method, type, interface, struct, file, package
	Name       string            // symbol name (e.g. "Foo", "ProcessPayment")
	File       string            // path relative to project root or absolute
	Line       int               // 1-based line number
	Signature  string            // e.g. "func Foo(x int) error", "struct { X int }"
	Language   string            // go, python, etc.
	Receiver   string            // for methods: receiver type name
	Complexity int               // Cyclomatic complexity (AST-based)
	Calls      []string          // function/method names called
	DependsOn  []string          // types referenced
	Imports    []string          // packages imported
	Intent     string            // Semantic intent generated by LLM
	Embedding  []float32         // Vector embedding of the entity
	Metadata   map[string]string // extra (e.g. package, doc)
}

// ExtractResult holds the result of extracting entities from one or more files.
type ExtractResult struct {
	Entities []Entity
	Errors   []ExtractError
}

// ExtractError records a non-fatal error during extraction (e.g. parse error for one file).
type ExtractError struct {
	File string
	Line int
	Msg  string
}

// Error implements error.
func (e ExtractError) Error() string {
	if e.File != emptyEntityValue {
		return e.File + ": " + e.Msg
	}
	return e.Msg
}
