// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec/lifecycle YAML.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package rules

import (
	base_objectenum "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/base_object"
	shared_rulesenum "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/shared_rules"
)

type PriorityTier = base_objectenum.PriorityTier

const (
	PriorityTierP0 PriorityTier = base_objectenum.PriorityTierP0
	PriorityTierP1 PriorityTier = base_objectenum.PriorityTierP1
	PriorityTierP2 PriorityTier = base_objectenum.PriorityTierP2
	PriorityTierP3 PriorityTier = base_objectenum.PriorityTierP3
)

type SourceType = base_objectenum.SourceType

const (
	SourceTypeExternal SourceType = base_objectenum.SourceTypeExternal
	SourceTypeImported SourceType = base_objectenum.SourceTypeImported
	SourceTypeInternal SourceType = base_objectenum.SourceTypeInternal
)

type Status = shared_rulesenum.Status

const (
	StatusApproved    Status = shared_rulesenum.StatusApproved
	StatusArchived    Status = shared_rulesenum.StatusArchived
	StatusError       Status = shared_rulesenum.StatusError
	StatusImplemented Status = shared_rulesenum.StatusImplemented
	StatusInProgress  Status = shared_rulesenum.StatusInProgress
	StatusProposed    Status = shared_rulesenum.StatusProposed
)

type Type string

const (
	TypeHardLimit      Type = "hard_limit"
	TypeInformational  Type = "informational"
	TypeRecommendation Type = "recommendation"
	TypeRequired       Type = "required"
)
