// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec/lifecycle YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package tde_envelope

import (
	base_objectenum "github.com/zqk-os/zqk/pkg/specbuilder/bldr_enum_v1/base_object"
	shared__internal_tde_envelopesenum "github.com/zqk-os/zqk/pkg/specbuilder/bldr_enum_v1/shared__internal_tde_envelopes"
)

type PriorityTier = base_objectenum.PriorityTier

const (
	PriorityTierP0 PriorityTier = base_objectenum.PriorityTierP0
	PriorityTierP1 PriorityTier = base_objectenum.PriorityTierP1
	PriorityTierP2 PriorityTier = base_objectenum.PriorityTierP2
	PriorityTierP3 PriorityTier = base_objectenum.PriorityTierP3
)

type SourceType = base_objectenum.SourceType

const (
	SourceTypeExternal SourceType = base_objectenum.SourceTypeExternal
	SourceTypeImported SourceType = base_objectenum.SourceTypeImported
	SourceTypeInternal SourceType = base_objectenum.SourceTypeInternal
)

type Status = shared__internal_tde_envelopesenum.Status

const (
	StatusApproved   Status = shared__internal_tde_envelopesenum.StatusApproved
	StatusConceptual Status = shared__internal_tde_envelopesenum.StatusConceptual
	StatusError      Status = shared__internal_tde_envelopesenum.StatusError
	StatusOriginated Status = shared__internal_tde_envelopesenum.StatusOriginated
	StatusPending    Status = shared__internal_tde_envelopesenum.StatusPending
	StatusRejected   Status = shared__internal_tde_envelopesenum.StatusRejected
)
