// Code generated by pkg/specbuilder/instance_builders/codegen.go from lifecycle YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package shared_stakeholder_profiles

type Status string

const (
	StatusActive     Status = "active"
	StatusArchived   Status = "archived"
	StatusConceptual Status = "conceptual"
	StatusDraft      Status = "draft"
	StatusError      Status = "error"
	StatusOriginated Status = "originated"
)
