package scheduler

// Log events for cache_prewarm handler (POL-CODE-007). Prefix matches [JobTypeCachePrewarm].
const (
	LogEventCachePrewarmStarted                                     = JobTypeCachePrewarm + "_started"
	LogEventCachePrewarmSkippedInsufficientTime                     = JobTypeCachePrewarm + "_skipped_insufficient_time"
	LogEventCachePrewarmCancelledAfterTier1                         = JobTypeCachePrewarm + "_cancelled_after_tier_1"
	LogEventCachePrewarmCompletedContextExpired                     = JobTypeCachePrewarm + "_completed_context_expired"
	LogEventCachePrewarmCompleted                                   = JobTypeCachePrewarm + "_completed"
	LogEventCachePrewarmTierTaskFailed                              = JobTypeCachePrewarm + "_tier_task_failed"
	LogEventCachePrewarmTierTimedOut                                = JobTypeCachePrewarm + "_tier_timed_out"
	LogEventCachePrewarmSpecsDirNotFound                            = JobTypeCachePrewarm + "_specs_dir_not_found"
	LogEventCachePrewarmSpecsDirReadFailed                          = JobTypeCachePrewarm + "_specs_dir_read_failed"
	LogEventCachePrewarmSpecScanCancelled                           = JobTypeCachePrewarm + "_spec_scan_cancelled"
	LogEventCachePrewarmSpecInvalidOrMissing                        = JobTypeCachePrewarm + "_spec_invalid_or_missing"
	LogEventCachePrewarmSpecCacheCompleted                          = JobTypeCachePrewarm + "_spec_cache_completed"
	LogEventCachePrewarmSpecKindLoadSkipped                         = JobTypeCachePrewarm + "_spec_kind_load_skipped"
	LogEventCachePrewarmLifecycleScanCancelled                      = JobTypeCachePrewarm + "_lifecycle_scan_cancelled"
	LogEventCachePrewarmLifecycleKindNotFound                       = JobTypeCachePrewarm + "_lifecycle_kind_not_found"
	LogEventCachePrewarmFieldRegistryCancelledBeforeStart           = JobTypeCachePrewarm + "_field_registry_cancelled_before_start"
	LogEventCachePrewarmFieldRegistryFailed                         = JobTypeCachePrewarm + "_field_registry_failed"
	LogEventCachePrewarmSystemFieldsCancelledBeforeStart            = JobTypeCachePrewarm + "_system_fields_cancelled_before_start"
	LogEventCachePrewarmSystemFieldsFailed                          = JobTypeCachePrewarm + "_system_fields_failed"
	LogEventCachePrewarmJobTypeViewFailed                           = JobTypeCachePrewarm + "_job_type_view_failed"
	LogEventCachePrewarmPathAliasHeartbeat                          = JobTypeCachePrewarm + "_path_alias_heartbeat"
	LogEventCachePrewarmPathCacheFinishedWithError                  = JobTypeCachePrewarm + "_path_cache_finished_with_error"
	LogEventCachePrewarmObjectIDCancelled                           = JobTypeCachePrewarm + "_object_id_cancelled"
	LogEventCachePrewarmObjectIDSkippedNoBuilder                    = JobTypeCachePrewarm + "_object_id_skipped_no_builder"
	LogEventCachePrewarmObjectIDSkippedNoProjectRoot                = JobTypeCachePrewarm + "_object_id_skipped_no_project_root"
	LogEventCachePrewarmObjectIDFailed                              = JobTypeCachePrewarm + "_object_id_failed"
	LogEventCachePrewarmObjectIDSucceeded                           = JobTypeCachePrewarm + "_object_id_succeeded"
	LogEventCachePrewarmValidationStateCancelled                    = JobTypeCachePrewarm + "_validation_state_cancelled"
	LogEventCachePrewarmValidationStateSkippedNoProjectRoot         = JobTypeCachePrewarm + "_validation_state_skipped_no_project_root"
	LogEventCachePrewarmValidationStateFailed                       = JobTypeCachePrewarm + "_validation_state_failed"
	LogEventCachePrewarmValidationStateSucceeded                    = JobTypeCachePrewarm + "_validation_state_succeeded"
	LogEventCachePrewarmBackgroundValidationCancelledBeforeStart    = JobTypeCachePrewarm + "_background_validation_cancelled_before_start"
	LogEventCachePrewarmBackgroundValidationSkippedNoScanner        = JobTypeCachePrewarm + "_background_validation_skipped_no_scanner"
	LogEventCachePrewarmBackgroundValidationSkippedNoProjectRoot    = JobTypeCachePrewarm + "_background_validation_skipped_no_project_root"
	LogEventCachePrewarmBackgroundValidationEnqueueFailed           = JobTypeCachePrewarm + "_background_validation_enqueue_failed"
	LogEventCachePrewarmBackgroundValidationNothingEnqueued         = JobTypeCachePrewarm + "_background_validation_nothing_enqueued"
	LogEventCachePrewarmBackgroundValidationEnqueued                = JobTypeCachePrewarm + "_background_validation_enqueued"
	LogEventCachePrewarmReverseReferenceCancelled                   = JobTypeCachePrewarm + "_reverse_reference_cancelled"
	LogEventCachePrewarmReverseReferenceSkippedNoProjectRoot        = JobTypeCachePrewarm + "_reverse_reference_skipped_no_project_root"
	LogEventCachePrewarmReverseReferenceAlreadyLoaded               = JobTypeCachePrewarm + "_reverse_reference_already_loaded"
	LogEventCachePrewarmReverseReferenceSkippedProcessDir           = JobTypeCachePrewarm + "_reverse_reference_skipped_process_dir"
	LogEventCachePrewarmReverseReferenceSkippedNoKindMapper         = JobTypeCachePrewarm + "_reverse_reference_skipped_no_kind_mapper"
	LogEventCachePrewarmReverseReferenceKindMapperEnsureReadyFailed = JobTypeCachePrewarm + "_reverse_reference_kind_mapper_ensure_ready_failed"
	LogEventCachePrewarmReverseReferenceSkippedNoKinds              = JobTypeCachePrewarm + "_reverse_reference_skipped_no_kinds"
	LogEventCachePrewarmReverseReferenceBuildFailed                 = JobTypeCachePrewarm + "_reverse_reference_build_failed"
	LogEventCachePrewarmReverseReferenceSaveFailed                  = JobTypeCachePrewarm + "_reverse_reference_save_failed"
	LogEventCachePrewarmReverseReferenceSucceeded                   = JobTypeCachePrewarm + "_reverse_reference_succeeded"
	LogEventCachePrewarmHandlerBindingOverlayListSkipped            = JobTypeCachePrewarm + "_handler_binding_overlay_list_skipped"
	LogEventCachePrewarmHandlerBindingOverlayLoaded                 = JobTypeCachePrewarm + "_handler_binding_overlay_loaded"
	LogEventCachePrewarmHandlerBindingUnknownJobType                = JobTypeCachePrewarm + "_handler_binding_unknown_job_type"
	LogEventCachePrewarmHandlerBindingUnknownHandlerKey             = JobTypeCachePrewarm + "_handler_binding_unknown_handler_key"
)
