package scheduler

// Log events for retention_tolerance handler (POLICY-CODE-007). Prefix matches [JobTypeRetentionTolerance].
const (
	LogEventRetentionToleranceStarted                                          = JobTypeRetentionTolerance + "_started"
	LogEventRetentionToleranceConfigLoadFailed                                 = JobTypeRetentionTolerance + "_config_load_failed"
	LogEventRetentionToleranceNoKindsConfiguredSkip                            = JobTypeRetentionTolerance + "_no_kinds_configured_skip"
	LogEventRetentionToleranceNoKindsAfterFilterSkip                           = JobTypeRetentionTolerance + "_no_kinds_after_filter_skip"
	LogEventRetentionToleranceCancelled                                        = JobTypeRetentionTolerance + "_cancelled"
	LogEventRetentionToleranceArchivedByTolerance                              = JobTypeRetentionTolerance + "_archived_by_tolerance"
	LogEventRetentionToleranceCleanedUpByTolerance                             = JobTypeRetentionTolerance + "_cleaned_up_by_tolerance"
	LogEventRetentionToleranceKindEnforcedMaxCountDeleted                      = JobTypeRetentionTolerance + "_kind_enforced_max_count_deleted"
	LogEventRetentionToleranceCASIndexFlushNonFatal                            = JobTypeRetentionTolerance + "_cas_index_flush_non_fatal"
	LogEventRetentionToleranceSkipKindConfigError                              = JobTypeRetentionTolerance + "_skip_kind_config_error"
	LogEventRetentionToleranceSkipStrategyForKind                              = JobTypeRetentionTolerance + "_skip_strategy_for_kind"
	LogEventRetentionToleranceBulkUpdateArchiveFailed                          = JobTypeRetentionTolerance + "_bulk_update_archive_failed"
	LogEventRetentionToleranceBulkDeleteCleanupByAgeFailed                     = JobTypeRetentionTolerance + "_bulk_delete_cleanup_by_age_failed"
	LogEventRetentionToleranceUsingCASOldestIDsForMaxCount                     = JobTypeRetentionTolerance + "_using_cas_oldest_ids_for_max_count"
	LogEventRetentionToleranceUsingHVCacheForMaxCount                          = JobTypeRetentionTolerance + "_using_hv_cache_for_max_count"
	LogEventRetentionToleranceBulkDeleteMaxCountPathFailed                     = JobTypeRetentionTolerance + "_bulk_delete_max_count_path_failed"
	LogEventRetentionToleranceEnforcedMaxCountDeletedOldestObjects             = JobTypeRetentionTolerance + "_enforced_max_count_deleted_oldest_objects"
	LogEventRetentionToleranceUsingHVCacheExcludeProtectMaxCount               = JobTypeRetentionTolerance + "_using_hv_cache_exclude_protect_max_count"
	LogEventRetentionToleranceBulkDeleteMaxCountCachePathFailed                = JobTypeRetentionTolerance + "_bulk_delete_max_count_cache_path_failed"
	LogEventRetentionToleranceEnforcedMaxCountDeletedOldestCacheExcludeProtect = JobTypeRetentionTolerance + "_enforced_max_count_deleted_oldest_cache_exclude_protect"
	LogEventRetentionToleranceCountFailedCASFallback                           = JobTypeRetentionTolerance + "_count_failed_cas_fallback"
	LogEventRetentionToleranceUsingCASIndexCountFallback                       = JobTypeRetentionTolerance + "_using_cas_index_count_fallback"
	LogEventRetentionToleranceEnforcingMaxCountExceeds                         = JobTypeRetentionTolerance + "_enforcing_max_count_exceeds"
	LogEventRetentionToleranceLimitingMaxCountToBatchLimit                     = JobTypeRetentionTolerance + "_limiting_max_count_to_batch_limit"
	LogEventRetentionToleranceCASUnavailableListFallback                       = JobTypeRetentionTolerance + "_cas_unavailable_list_fallback"
	LogEventRetentionToleranceFastPathCASDelete                                = JobTypeRetentionTolerance + "_fast_path_cas_delete"
	LogEventRetentionToleranceMaxCountFastPathCancelled                        = JobTypeRetentionTolerance + "_max_count_fast_path_cancelled"
	LogEventRetentionToleranceBulkDeleteEnforceMaxCountFailed                  = JobTypeRetentionTolerance + "_bulk_delete_enforce_max_count_failed"
	LogEventRetentionToleranceUsingBatchedListMaxCountProtect                  = JobTypeRetentionTolerance + "_using_batched_list_max_count_protect"
	LogEventRetentionToleranceMaxCountBatchedListCancelled                     = JobTypeRetentionTolerance + "_max_count_batched_list_cancelled"
	LogEventRetentionToleranceObjectOverfillProtectedStatus                    = JobTypeRetentionTolerance + "_object_overfill_protected_status"
	LogEventRetentionToleranceBulkDeleteEnforceMaxCountBatchedListFailed       = JobTypeRetentionTolerance + "_bulk_delete_enforce_max_count_batched_list_failed"
)
