package scheduler

// Log events for run_wrapper execution (POL-CODE-007). Prefix matches [JobTypeRunWrapper].
const (
	LogEventRunWrapperDynamicTimeout                             = JobTypeRunWrapper + "_dynamic_timeout"
	LogEventRunWrapperDefaultSuiteTimeout                        = JobTypeRunWrapper + "_default_suite_timeout"
	LogEventRunWrapperBundleCommandFingerprintMismatch           = JobTypeRunWrapper + "_bundle_command_fingerprint_mismatch"
	LogEventRunWrapperExecutingCommand                           = JobTypeRunWrapper + "_executing_command"
	LogEventRunWrapperShellSyntaxFailed                          = JobTypeRunWrapper + "_shell_syntax_failed"
	LogEventRunWrapperPanicked                                   = JobTypeRunWrapper + "_panicked"
	LogEventRunWrapperCommandSucceeded                           = JobTypeRunWrapper + "_command_succeeded"
	LogEventRunWrapperCommandStdout                              = JobTypeRunWrapper + "_command_stdout"
	LogEventRunWrapperCommandTimedOut                            = JobTypeRunWrapper + "_command_timed_out"
	LogEventRunWrapperCommandFailed                              = JobTypeRunWrapper + "_command_failed"
	LogEventRunWrapperCommandStderr                              = JobTypeRunWrapper + "_command_stderr"
	LogEventRunWrapperTestFailureFlagSet                         = JobTypeRunWrapper + "_test_failure_flag_set"
	LogEventRunWrapperRetryingCommand                            = JobTypeRunWrapper + "_retrying_command"
	LogEventRunWrapperBootstrapTestRootFailed                    = JobTypeRunWrapper + "_bootstrap_test_root_failed"
	LogEventRunWrapperCommandStillRunning                        = JobTypeRunWrapper + "_command_still_running"
	LogEventRunWrapperCallbackRoutedThroughTransceiver           = JobTypeRunWrapper + "_callback_routed_through_transceiver"
	LogEventRunWrapperCallbackTransceiverRouteFailed             = JobTypeRunWrapper + "_callback_transceiver_route_failed"
	LogEventRunWrapperCallbackInvokeRouteFailedExecutingDirect   = JobTypeRunWrapper + "_callback_invoke_route_failed_executing_direct"
	LogEventRunWrapperCallbackUnknownMechanism                   = JobTypeRunWrapper + "_callback_unknown_mechanism"
	LogEventRunWrapperCallbackMarshalWebhookPayloadFailed        = JobTypeRunWrapper + "_callback_marshal_webhook_payload_failed"
	LogEventRunWrapperCallbackCreateWebhookRequestFailed         = JobTypeRunWrapper + "_callback_create_webhook_request_failed"
	LogEventRunWrapperCallbackWebhookRequestFailed               = JobTypeRunWrapper + "_callback_webhook_request_failed"
	LogEventRunWrapperCallbackWebhookSucceeded                   = JobTypeRunWrapper + "_callback_webhook_succeeded"
	LogEventRunWrapperCallbackWebhookNon2xx                      = JobTypeRunWrapper + "_callback_webhook_non_2xx"
	LogEventRunWrapperCallbackMarshalCommandPayloadFailed        = JobTypeRunWrapper + "_callback_marshal_command_payload_failed"
	LogEventRunWrapperCallbackEmptyCommand                       = JobTypeRunWrapper + "_callback_empty_command"
	LogEventRunWrapperCallbackCommandFailed                      = JobTypeRunWrapper + "_callback_command_failed"
	LogEventRunWrapperCallbackCommandSucceeded                   = JobTypeRunWrapper + "_callback_command_succeeded"
	LogEventRunWrapperCallbackEventNotImplemented                = JobTypeRunWrapper + "_callback_event_not_implemented"
	LogEventRunWrapperRouteJobMessageFailed                      = JobTypeRunWrapper + "_route_job_message_failed"
	LogEventRunWrapperConvergenceTickAfterTestBundleHealthFailed = JobTypeRunWrapper + "_convergence_tick_after_test_bundle_health_failed"
	LogEventRunWrapperCVSLedgerSkippedTooManyFailures            = JobTypeRunWrapper + "_cvs_per_test_ledger_skipped_threshold"
	LogEventRunWrapperCVSLedgerPersistFailed                     = JobTypeRunWrapper + "_cvs_per_test_ledger_persist_failed"
	LogEventRunWrapperCriteriaAutovalidateFailed                 = JobTypeRunWrapper + "_criteria_autovalidate_failed"
)
