// Code generated by pkg/specbuilder/instance_builders/codegen.go from lifecycle YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package shared_agent_tasks

type Status string

const (
	StatusApproved            Status = "approved"
	StatusArchived            Status = "archived"
	StatusConceptual          Status = "conceptual"
	StatusError               Status = "error"
	StatusImplemented         Status = "implemented"
	StatusInProgress          Status = "in_progress"
	StatusOriginated          Status = "originated"
	StatusPendingVerification Status = "pending_verification"
	StatusProposed            Status = "proposed"
)
