// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package bldr_instance_v1

import (
	"github.com/zqk-os/zqk/pkg/objects"
	enumv "github.com/zqk-os/zqk/packs/surface/bldr_enum_v1/display"
	"github.com/zqk-os/zqk/pkg/specbuilder/instance_builders"
)

// DisplayInstanceBuilder builds display instances
// ONE builder handles ALL display instances
type DisplayInstanceBuilder struct {
	*instance_builders.BaseInstanceBuilder
}

// NewDisplayInstanceBuilder creates a new display instance builder.
// Pass the instance schema_version string for this spec; use objects.DefaultSchemaVersion for the project default (pkg/objects constants).
// Field order is derived from the spec (not hardcoded) to avoid drift
func NewDisplayInstanceBuilder(schemaVersion string) *DisplayInstanceBuilder {
	// Derive canonical field order from spec (follows architecture pattern)
	// System fields first, then spec-defined fields in sorted order
	fieldOrder := instance_builders.FieldOrderFromSpec("display")

	// Create base builder
	builder := &DisplayInstanceBuilder{
		BaseInstanceBuilder: instance_builders.NewBaseInstanceBuilder(
			"display",
			schemaVersion,
			fieldOrder,
			nil, // spec builder (optional)
		),
	}

	return builder
}

// Status sets the status field
func (b *DisplayInstanceBuilder) Status(value enumv.Status) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyStatus, string(value))
	return b
}

// ID sets the id field
func (b *DisplayInstanceBuilder) ID(value string) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyID, value)
	return b
}

// ArchivedAt sets the archived_at field
func (b *DisplayInstanceBuilder) ArchivedAt(value any) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedAt, value)
	return b
}

// SetArchivedAt is a compatibility alias for ArchivedAt.
func (b *DisplayInstanceBuilder) SetArchivedAt(value any) *DisplayInstanceBuilder {
	return b.ArchivedAt(value)
}

// ArchivedBy sets the archived_by field
func (b *DisplayInstanceBuilder) ArchivedBy(value string) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedBy, value)
	return b
}

// SetArchivedBy is a compatibility alias for ArchivedBy.
func (b *DisplayInstanceBuilder) SetArchivedBy(value string) *DisplayInstanceBuilder {
	return b.ArchivedBy(value)
}

// Artifacts sets the artifacts field
func (b *DisplayInstanceBuilder) Artifacts(value []string) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyArtifacts, value)
	return b
}

// SetArtifacts is a compatibility alias for Artifacts.
func (b *DisplayInstanceBuilder) SetArtifacts(value []string) *DisplayInstanceBuilder {
	return b.Artifacts(value)
}

// ChangeLog sets the change_log field
func (b *DisplayInstanceBuilder) ChangeLog(value []string) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyChangeLog, value)
	return b
}

// SetChangeLog is a compatibility alias for ChangeLog.
func (b *DisplayInstanceBuilder) SetChangeLog(value []string) *DisplayInstanceBuilder {
	return b.ChangeLog(value)
}

// CompletenessValidation sets the completeness_validation field
func (b *DisplayInstanceBuilder) CompletenessValidation(value []string) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyCompletenessValidation, value)
	return b
}

// SetCompletenessValidation is a compatibility alias for CompletenessValidation.
func (b *DisplayInstanceBuilder) SetCompletenessValidation(value []string) *DisplayInstanceBuilder {
	return b.CompletenessValidation(value)
}

// ConstraintContexts sets the constraint_contexts field
func (b *DisplayInstanceBuilder) ConstraintContexts(value []string) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyConstraintContexts, value)
	return b
}

// SetConstraintContexts is a compatibility alias for ConstraintContexts.
func (b *DisplayInstanceBuilder) SetConstraintContexts(value []string) *DisplayInstanceBuilder {
	return b.ConstraintContexts(value)
}

// Context sets the context field
func (b *DisplayInstanceBuilder) Context(value any) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyContext, value)
	return b
}

// SetContext is a compatibility alias for Context.
func (b *DisplayInstanceBuilder) SetContext(value any) *DisplayInstanceBuilder {
	return b.Context(value)
}

// Deadline sets the deadline field
func (b *DisplayInstanceBuilder) Deadline(value string) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyDeadline, value)
	return b
}

// SetDeadline is a compatibility alias for Deadline.
func (b *DisplayInstanceBuilder) SetDeadline(value string) *DisplayInstanceBuilder {
	return b.Deadline(value)
}

// Dependencies sets the dependencies field
func (b *DisplayInstanceBuilder) Dependencies(value []string) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyDependencies, value)
	return b
}

// SetDependencies is a compatibility alias for Dependencies.
func (b *DisplayInstanceBuilder) SetDependencies(value []string) *DisplayInstanceBuilder {
	return b.Dependencies(value)
}

// Description sets the description field
func (b *DisplayInstanceBuilder) Description(value any) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyDescription, value)
	return b
}

// SetDescription is a compatibility alias for Description.
func (b *DisplayInstanceBuilder) SetDescription(value any) *DisplayInstanceBuilder {
	return b.Description(value)
}

// DisplayType sets the display_type field
func (b *DisplayInstanceBuilder) DisplayType(value string) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyDisplayType, value)
	return b
}

// SetDisplayType is a compatibility alias for DisplayType.
func (b *DisplayInstanceBuilder) SetDisplayType(value string) *DisplayInstanceBuilder {
	return b.DisplayType(value)
}

// Domain sets the domain field
func (b *DisplayInstanceBuilder) Domain(value string) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyDomain, value)
	return b
}

// SetDomain is a compatibility alias for Domain.
func (b *DisplayInstanceBuilder) SetDomain(value string) *DisplayInstanceBuilder {
	return b.Domain(value)
}

// LayoutConfig sets the layout_config field
func (b *DisplayInstanceBuilder) LayoutConfig(value map[string]any) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyLayoutConfig, value)
	return b
}

// SetLayoutConfig is a compatibility alias for LayoutConfig.
func (b *DisplayInstanceBuilder) SetLayoutConfig(value map[string]any) *DisplayInstanceBuilder {
	return b.LayoutConfig(value)
}

// LifecycleFile sets the lifecycle_file field
func (b *DisplayInstanceBuilder) LifecycleFile(value string) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyLifecycleFile, value)
	return b
}

// SetLifecycleFile is a compatibility alias for LifecycleFile.
func (b *DisplayInstanceBuilder) SetLifecycleFile(value string) *DisplayInstanceBuilder {
	return b.LifecycleFile(value)
}

// OriginProject sets the origin_project field
func (b *DisplayInstanceBuilder) OriginProject(value string) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyOriginProject, value)
	return b
}

// SetOriginProject is a compatibility alias for OriginProject.
func (b *DisplayInstanceBuilder) SetOriginProject(value string) *DisplayInstanceBuilder {
	return b.OriginProject(value)
}

// OriginSystem sets the origin_system field
func (b *DisplayInstanceBuilder) OriginSystem(value string) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyOriginSystem, value)
	return b
}

// SetOriginSystem is a compatibility alias for OriginSystem.
func (b *DisplayInstanceBuilder) SetOriginSystem(value string) *DisplayInstanceBuilder {
	return b.OriginSystem(value)
}

// Plane sets the plane field
func (b *DisplayInstanceBuilder) Plane(value enumv.Plane) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyPlane, string(value))
	return b
}

// SetPlane is a compatibility alias for Plane.
func (b *DisplayInstanceBuilder) SetPlane(value enumv.Plane) *DisplayInstanceBuilder {
	return b.Plane(value)
}

// PriorityTier sets the priority_tier field
func (b *DisplayInstanceBuilder) PriorityTier(value enumv.PriorityTier) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyPriorityTier, string(value))
	return b
}

// SetPriorityTier is a compatibility alias for PriorityTier.
func (b *DisplayInstanceBuilder) SetPriorityTier(value enumv.PriorityTier) *DisplayInstanceBuilder {
	return b.PriorityTier(value)
}

// Provenance sets the provenance field
func (b *DisplayInstanceBuilder) Provenance(value map[string]any) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyProvenance, value)
	return b
}

// SetProvenance is a compatibility alias for Provenance.
func (b *DisplayInstanceBuilder) SetProvenance(value map[string]any) *DisplayInstanceBuilder {
	return b.Provenance(value)
}

// Questions sets the questions field
func (b *DisplayInstanceBuilder) Questions(value []string) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyQuestions, value)
	return b
}

// SetQuestions is a compatibility alias for Questions.
func (b *DisplayInstanceBuilder) SetQuestions(value []string) *DisplayInstanceBuilder {
	return b.Questions(value)
}

// RelatedObjectRefs sets the related_object_refs field
func (b *DisplayInstanceBuilder) RelatedObjectRefs(value []string) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyRelatedObjectRefs, value)
	return b
}

// SetRelatedObjectRefs is a compatibility alias for RelatedObjectRefs.
func (b *DisplayInstanceBuilder) SetRelatedObjectRefs(value []string) *DisplayInstanceBuilder {
	return b.RelatedObjectRefs(value)
}

// SchemaRef sets the schema_ref field
func (b *DisplayInstanceBuilder) SchemaRef(value string) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeySchemaRef, value)
	return b
}

// SetSchemaRef is a compatibility alias for SchemaRef.
func (b *DisplayInstanceBuilder) SetSchemaRef(value string) *DisplayInstanceBuilder {
	return b.SchemaRef(value)
}

// SourceType sets the source_type field
func (b *DisplayInstanceBuilder) SourceType(value enumv.SourceType) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeySourceType, string(value))
	return b
}

// SetSourceType is a compatibility alias for SourceType.
func (b *DisplayInstanceBuilder) SetSourceType(value enumv.SourceType) *DisplayInstanceBuilder {
	return b.SourceType(value)
}

// SpecAdherence sets the spec_adherence field
func (b *DisplayInstanceBuilder) SpecAdherence(value map[string]any) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeySpecAdherence, value)
	return b
}

// SetSpecAdherence is a compatibility alias for SpecAdherence.
func (b *DisplayInstanceBuilder) SetSpecAdherence(value map[string]any) *DisplayInstanceBuilder {
	return b.SpecAdherence(value)
}

// SpecContextBroker sets the spec_context_broker field
func (b *DisplayInstanceBuilder) SpecContextBroker(value string) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeySpecContextBroker, value)
	return b
}

// SetSpecContextBroker is a compatibility alias for SpecContextBroker.
func (b *DisplayInstanceBuilder) SetSpecContextBroker(value string) *DisplayInstanceBuilder {
	return b.SpecContextBroker(value)
}

// SpecInterpreter sets the spec_interpreter field
func (b *DisplayInstanceBuilder) SpecInterpreter(value string) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeySpecInterpreter, value)
	return b
}

// SetSpecInterpreter is a compatibility alias for SpecInterpreter.
func (b *DisplayInstanceBuilder) SetSpecInterpreter(value string) *DisplayInstanceBuilder {
	return b.SpecInterpreter(value)
}

// Stakeholders sets the stakeholders field
func (b *DisplayInstanceBuilder) Stakeholders(value []string) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyStakeholders, value)
	return b
}

// SetStakeholders is a compatibility alias for Stakeholders.
func (b *DisplayInstanceBuilder) SetStakeholders(value []string) *DisplayInstanceBuilder {
	return b.Stakeholders(value)
}

// StatusHistory sets the status_history field
func (b *DisplayInstanceBuilder) StatusHistory(value []string) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyStatusHistory, value)
	return b
}

// SetStatusHistory is a compatibility alias for StatusHistory.
func (b *DisplayInstanceBuilder) SetStatusHistory(value []string) *DisplayInstanceBuilder {
	return b.StatusHistory(value)
}

// TargetDate sets the target_date field
func (b *DisplayInstanceBuilder) TargetDate(value string) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyTargetDate, value)
	return b
}

// SetTargetDate is a compatibility alias for TargetDate.
func (b *DisplayInstanceBuilder) SetTargetDate(value string) *DisplayInstanceBuilder {
	return b.TargetDate(value)
}

// Title sets the title field
func (b *DisplayInstanceBuilder) Title(value string) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyTitle, value)
	return b
}

// SetTitle is a compatibility alias for Title.
func (b *DisplayInstanceBuilder) SetTitle(value string) *DisplayInstanceBuilder {
	return b.Title(value)
}

// Urn sets the urn field
func (b *DisplayInstanceBuilder) Urn(value string) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyUrn, value)
	return b
}

// SetUrn is a compatibility alias for Urn.
func (b *DisplayInstanceBuilder) SetUrn(value string) *DisplayInstanceBuilder {
	return b.Urn(value)
}

// Version sets the version field
func (b *DisplayInstanceBuilder) Version(value int) *DisplayInstanceBuilder {
	b.SetField(objects.FieldKeyVersion, value)
	return b
}

// SetVersion is a compatibility alias for Version.
func (b *DisplayInstanceBuilder) SetVersion(value int) *DisplayInstanceBuilder {
	return b.Version(value)
}
