// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package bldr_instance_v1

import (
	"github.com/zqk-os/zqk/pkg/objects"
	enumv "github.com/zqk-os/zqk/pkg/specbuilder/bldr_enum_v1/agent_onboarding_preparation"
	"github.com/zqk-os/zqk/pkg/specbuilder/instance_builders"
)

// AgentOnboardingPreparationInstanceBuilder builds agent_onboarding_preparation instances
// ONE builder handles ALL agent_onboarding_preparation instances
type AgentOnboardingPreparationInstanceBuilder struct {
	*instance_builders.BaseInstanceBuilder
}

// NewAgentOnboardingPreparationInstanceBuilder creates a new agent_onboarding_preparation instance builder.
// Pass the instance schema_version string for this spec; use objects.DefaultSchemaVersion for the project default (pkg/objects constants).
// Field order is derived from the spec (not hardcoded) to avoid drift
func NewAgentOnboardingPreparationInstanceBuilder(schemaVersion string) *AgentOnboardingPreparationInstanceBuilder {
	// Derive canonical field order from spec (follows architecture pattern)
	// System fields first, then spec-defined fields in sorted order
	fieldOrder := buildFieldOrderFromSpec("agent_onboarding_preparation")

	// Create base builder
	builder := &AgentOnboardingPreparationInstanceBuilder{
		BaseInstanceBuilder: instance_builders.NewBaseInstanceBuilder(
			"agent_onboarding_preparation",
			schemaVersion,
			fieldOrder,
			nil, // spec builder (optional)
		),
	}

	return builder
}

// Status sets the status field
func (b *AgentOnboardingPreparationInstanceBuilder) Status(value enumv.Status) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyStatus, string(value))
	return b
}

// ID sets the id field
func (b *AgentOnboardingPreparationInstanceBuilder) ID(value string) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyID, value)
	return b
}

// AgentType sets the agent_type field
func (b *AgentOnboardingPreparationInstanceBuilder) AgentType(value enumv.AgentType) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyAgentType, string(value))
	return b
}

// SetAgentType is a compatibility alias for AgentType.
func (b *AgentOnboardingPreparationInstanceBuilder) SetAgentType(value enumv.AgentType) *AgentOnboardingPreparationInstanceBuilder {
	return b.AgentType(value)
}

// ArchivedAt sets the archived_at field
func (b *AgentOnboardingPreparationInstanceBuilder) ArchivedAt(value any) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedAt, value)
	return b
}

// SetArchivedAt is a compatibility alias for ArchivedAt.
func (b *AgentOnboardingPreparationInstanceBuilder) SetArchivedAt(value any) *AgentOnboardingPreparationInstanceBuilder {
	return b.ArchivedAt(value)
}

// ArchivedBy sets the archived_by field
func (b *AgentOnboardingPreparationInstanceBuilder) ArchivedBy(value string) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedBy, value)
	return b
}

// SetArchivedBy is a compatibility alias for ArchivedBy.
func (b *AgentOnboardingPreparationInstanceBuilder) SetArchivedBy(value string) *AgentOnboardingPreparationInstanceBuilder {
	return b.ArchivedBy(value)
}

// Artifacts sets the artifacts field
func (b *AgentOnboardingPreparationInstanceBuilder) Artifacts(value []string) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyArtifacts, value)
	return b
}

// SetArtifacts is a compatibility alias for Artifacts.
func (b *AgentOnboardingPreparationInstanceBuilder) SetArtifacts(value []string) *AgentOnboardingPreparationInstanceBuilder {
	return b.Artifacts(value)
}

// ChangeLog sets the change_log field
func (b *AgentOnboardingPreparationInstanceBuilder) ChangeLog(value []string) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyChangeLog, value)
	return b
}

// SetChangeLog is a compatibility alias for ChangeLog.
func (b *AgentOnboardingPreparationInstanceBuilder) SetChangeLog(value []string) *AgentOnboardingPreparationInstanceBuilder {
	return b.ChangeLog(value)
}

// CompletenessValidation sets the completeness_validation field
func (b *AgentOnboardingPreparationInstanceBuilder) CompletenessValidation(value []string) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyCompletenessValidation, value)
	return b
}

// SetCompletenessValidation is a compatibility alias for CompletenessValidation.
func (b *AgentOnboardingPreparationInstanceBuilder) SetCompletenessValidation(value []string) *AgentOnboardingPreparationInstanceBuilder {
	return b.CompletenessValidation(value)
}

// Context sets the context field
func (b *AgentOnboardingPreparationInstanceBuilder) Context(value any) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyContext, value)
	return b
}

// SetContext is a compatibility alias for Context.
func (b *AgentOnboardingPreparationInstanceBuilder) SetContext(value any) *AgentOnboardingPreparationInstanceBuilder {
	return b.Context(value)
}

// Deadline sets the deadline field
func (b *AgentOnboardingPreparationInstanceBuilder) Deadline(value string) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyDeadline, value)
	return b
}

// SetDeadline is a compatibility alias for Deadline.
func (b *AgentOnboardingPreparationInstanceBuilder) SetDeadline(value string) *AgentOnboardingPreparationInstanceBuilder {
	return b.Deadline(value)
}

// Dependencies sets the dependencies field
func (b *AgentOnboardingPreparationInstanceBuilder) Dependencies(value []string) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyDependencies, value)
	return b
}

// SetDependencies is a compatibility alias for Dependencies.
func (b *AgentOnboardingPreparationInstanceBuilder) SetDependencies(value []string) *AgentOnboardingPreparationInstanceBuilder {
	return b.Dependencies(value)
}

// Description sets the description field
func (b *AgentOnboardingPreparationInstanceBuilder) Description(value any) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyDescription, value)
	return b
}

// SetDescription is a compatibility alias for Description.
func (b *AgentOnboardingPreparationInstanceBuilder) SetDescription(value any) *AgentOnboardingPreparationInstanceBuilder {
	return b.Description(value)
}

// OriginProject sets the origin_project field
func (b *AgentOnboardingPreparationInstanceBuilder) OriginProject(value string) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyOriginProject, value)
	return b
}

// SetOriginProject is a compatibility alias for OriginProject.
func (b *AgentOnboardingPreparationInstanceBuilder) SetOriginProject(value string) *AgentOnboardingPreparationInstanceBuilder {
	return b.OriginProject(value)
}

// OriginSystem sets the origin_system field
func (b *AgentOnboardingPreparationInstanceBuilder) OriginSystem(value string) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyOriginSystem, value)
	return b
}

// SetOriginSystem is a compatibility alias for OriginSystem.
func (b *AgentOnboardingPreparationInstanceBuilder) SetOriginSystem(value string) *AgentOnboardingPreparationInstanceBuilder {
	return b.OriginSystem(value)
}

// Plane sets the plane field
func (b *AgentOnboardingPreparationInstanceBuilder) Plane(value enumv.Plane) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyPlane, string(value))
	return b
}

// SetPlane is a compatibility alias for Plane.
func (b *AgentOnboardingPreparationInstanceBuilder) SetPlane(value enumv.Plane) *AgentOnboardingPreparationInstanceBuilder {
	return b.Plane(value)
}

// PreparationStatus sets the preparation_status field
func (b *AgentOnboardingPreparationInstanceBuilder) PreparationStatus(value enumv.PreparationStatus) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyPreparationStatus, string(value))
	return b
}

// SetPreparationStatus is a compatibility alias for PreparationStatus.
func (b *AgentOnboardingPreparationInstanceBuilder) SetPreparationStatus(value enumv.PreparationStatus) *AgentOnboardingPreparationInstanceBuilder {
	return b.PreparationStatus(value)
}

// PreparationTasks sets the preparation_tasks field
func (b *AgentOnboardingPreparationInstanceBuilder) PreparationTasks(value []string) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyPreparationTasks, value)
	return b
}

// SetPreparationTasks is a compatibility alias for PreparationTasks.
func (b *AgentOnboardingPreparationInstanceBuilder) SetPreparationTasks(value []string) *AgentOnboardingPreparationInstanceBuilder {
	return b.PreparationTasks(value)
}

// PriorityTier sets the priority_tier field
func (b *AgentOnboardingPreparationInstanceBuilder) PriorityTier(value enumv.PriorityTier) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyPriorityTier, string(value))
	return b
}

// SetPriorityTier is a compatibility alias for PriorityTier.
func (b *AgentOnboardingPreparationInstanceBuilder) SetPriorityTier(value enumv.PriorityTier) *AgentOnboardingPreparationInstanceBuilder {
	return b.PriorityTier(value)
}

// Provenance sets the provenance field
func (b *AgentOnboardingPreparationInstanceBuilder) Provenance(value map[string]any) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyProvenance, value)
	return b
}

// SetProvenance is a compatibility alias for Provenance.
func (b *AgentOnboardingPreparationInstanceBuilder) SetProvenance(value map[string]any) *AgentOnboardingPreparationInstanceBuilder {
	return b.Provenance(value)
}

// Questions sets the questions field
func (b *AgentOnboardingPreparationInstanceBuilder) Questions(value []string) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyQuestions, value)
	return b
}

// SetQuestions is a compatibility alias for Questions.
func (b *AgentOnboardingPreparationInstanceBuilder) SetQuestions(value []string) *AgentOnboardingPreparationInstanceBuilder {
	return b.Questions(value)
}

// ReadinessCriteria sets the readiness_criteria field
func (b *AgentOnboardingPreparationInstanceBuilder) ReadinessCriteria(value []string) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyReadinessCriteria, value)
	return b
}

// SetReadinessCriteria is a compatibility alias for ReadinessCriteria.
func (b *AgentOnboardingPreparationInstanceBuilder) SetReadinessCriteria(value []string) *AgentOnboardingPreparationInstanceBuilder {
	return b.ReadinessCriteria(value)
}

// RelatedObjectRefs sets the related_object_refs field
func (b *AgentOnboardingPreparationInstanceBuilder) RelatedObjectRefs(value []string) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyRelatedObjectRefs, value)
	return b
}

// SetRelatedObjectRefs is a compatibility alias for RelatedObjectRefs.
func (b *AgentOnboardingPreparationInstanceBuilder) SetRelatedObjectRefs(value []string) *AgentOnboardingPreparationInstanceBuilder {
	return b.RelatedObjectRefs(value)
}

// SchemaRef sets the schema_ref field
func (b *AgentOnboardingPreparationInstanceBuilder) SchemaRef(value string) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeySchemaRef, value)
	return b
}

// SetSchemaRef is a compatibility alias for SchemaRef.
func (b *AgentOnboardingPreparationInstanceBuilder) SetSchemaRef(value string) *AgentOnboardingPreparationInstanceBuilder {
	return b.SchemaRef(value)
}

// SourceType sets the source_type field
func (b *AgentOnboardingPreparationInstanceBuilder) SourceType(value enumv.SourceType) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeySourceType, string(value))
	return b
}

// SetSourceType is a compatibility alias for SourceType.
func (b *AgentOnboardingPreparationInstanceBuilder) SetSourceType(value enumv.SourceType) *AgentOnboardingPreparationInstanceBuilder {
	return b.SourceType(value)
}

// SpecAdherence sets the spec_adherence field
func (b *AgentOnboardingPreparationInstanceBuilder) SpecAdherence(value map[string]any) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeySpecAdherence, value)
	return b
}

// SetSpecAdherence is a compatibility alias for SpecAdherence.
func (b *AgentOnboardingPreparationInstanceBuilder) SetSpecAdherence(value map[string]any) *AgentOnboardingPreparationInstanceBuilder {
	return b.SpecAdherence(value)
}

// Stakeholders sets the stakeholders field
func (b *AgentOnboardingPreparationInstanceBuilder) Stakeholders(value []string) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyStakeholders, value)
	return b
}

// SetStakeholders is a compatibility alias for Stakeholders.
func (b *AgentOnboardingPreparationInstanceBuilder) SetStakeholders(value []string) *AgentOnboardingPreparationInstanceBuilder {
	return b.Stakeholders(value)
}

// StatusHistory sets the status_history field
func (b *AgentOnboardingPreparationInstanceBuilder) StatusHistory(value []string) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyStatusHistory, value)
	return b
}

// SetStatusHistory is a compatibility alias for StatusHistory.
func (b *AgentOnboardingPreparationInstanceBuilder) SetStatusHistory(value []string) *AgentOnboardingPreparationInstanceBuilder {
	return b.StatusHistory(value)
}

// TargetDate sets the target_date field
func (b *AgentOnboardingPreparationInstanceBuilder) TargetDate(value any) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyTargetDate, value)
	return b
}

// SetTargetDate is a compatibility alias for TargetDate.
func (b *AgentOnboardingPreparationInstanceBuilder) SetTargetDate(value any) *AgentOnboardingPreparationInstanceBuilder {
	return b.TargetDate(value)
}

// TargetWorkstreamRef sets the target_workstream_ref field
func (b *AgentOnboardingPreparationInstanceBuilder) TargetWorkstreamRef(value string) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyTargetWorkstreamRef, value)
	return b
}

// SetTargetWorkstreamRef is a compatibility alias for TargetWorkstreamRef.
func (b *AgentOnboardingPreparationInstanceBuilder) SetTargetWorkstreamRef(value string) *AgentOnboardingPreparationInstanceBuilder {
	return b.TargetWorkstreamRef(value)
}

// Title sets the title field
func (b *AgentOnboardingPreparationInstanceBuilder) Title(value string) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyTitle, value)
	return b
}

// SetTitle is a compatibility alias for Title.
func (b *AgentOnboardingPreparationInstanceBuilder) SetTitle(value string) *AgentOnboardingPreparationInstanceBuilder {
	return b.Title(value)
}

// Urn sets the urn field
func (b *AgentOnboardingPreparationInstanceBuilder) Urn(value string) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyUrn, value)
	return b
}

// SetUrn is a compatibility alias for Urn.
func (b *AgentOnboardingPreparationInstanceBuilder) SetUrn(value string) *AgentOnboardingPreparationInstanceBuilder {
	return b.Urn(value)
}

// Version sets the version field
func (b *AgentOnboardingPreparationInstanceBuilder) Version(value int) *AgentOnboardingPreparationInstanceBuilder {
	b.SetField(objects.FieldKeyVersion, value)
	return b
}

// SetVersion is a compatibility alias for Version.
func (b *AgentOnboardingPreparationInstanceBuilder) SetVersion(value int) *AgentOnboardingPreparationInstanceBuilder {
	return b.Version(value)
}

func init() {
	instance_builders.RegisterBuilder(NewAgentOnboardingPreparationInstanceBuilder(objects.DefaultSchemaVersion))
}
