// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package bldr_instance_v1

import (
	"github.com/lanceman/zqk/pkg/objects"
	enumv "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/bucketing_strategy"
	"github.com/lanceman/zqk/pkg/specbuilder/instance_builders"
)

// BucketingStrategyInstanceBuilder builds bucketing_strategy instances
// ONE builder handles ALL bucketing_strategy instances
type BucketingStrategyInstanceBuilder struct {
	*instance_builders.BaseInstanceBuilder
}

// NewBucketingStrategyInstanceBuilder creates a new bucketing_strategy instance builder.
// Pass the instance schema_version string for this spec; use objects.DefaultSchemaVersion for the project default (pkg/objects constants).
// Field order is derived from the spec (not hardcoded) to avoid drift
func NewBucketingStrategyInstanceBuilder(schemaVersion string) *BucketingStrategyInstanceBuilder {
	// Derive canonical field order from spec (follows architecture pattern)
	// System fields first, then spec-defined fields in sorted order
	fieldOrder := buildFieldOrderFromSpec("bucketing_strategy")

	// Create base builder
	builder := &BucketingStrategyInstanceBuilder{
		BaseInstanceBuilder: instance_builders.NewBaseInstanceBuilder(
			"bucketing_strategy",
			schemaVersion,
			fieldOrder,
			nil, // spec builder (optional)
		),
	}

	return builder
}

// Status sets the status field
func (b *BucketingStrategyInstanceBuilder) Status(value enumv.Status) *BucketingStrategyInstanceBuilder {
	b.SetField(objects.FieldKeyStatus, string(value))
	return b
}

// ID sets the id field
func (b *BucketingStrategyInstanceBuilder) ID(value string) *BucketingStrategyInstanceBuilder {
	b.SetField(objects.FieldKeyID, value)
	return b
}

// AppliesTo sets the applies_to field
func (b *BucketingStrategyInstanceBuilder) AppliesTo(value []string) *BucketingStrategyInstanceBuilder {
	b.SetField(objects.FieldKeyAppliesTo, value)
	return b
}

// SetAppliesTo is a compatibility alias for AppliesTo.
func (b *BucketingStrategyInstanceBuilder) SetAppliesTo(value []string) *BucketingStrategyInstanceBuilder {
	return b.AppliesTo(value)
}

// ArchiveStrategy sets the archive_strategy field
func (b *BucketingStrategyInstanceBuilder) ArchiveStrategy(value map[string]any) *BucketingStrategyInstanceBuilder {
	b.SetField(objects.FieldKeyArchiveStrategy, value)
	return b
}

// SetArchiveStrategy is a compatibility alias for ArchiveStrategy.
func (b *BucketingStrategyInstanceBuilder) SetArchiveStrategy(value map[string]any) *BucketingStrategyInstanceBuilder {
	return b.ArchiveStrategy(value)
}

// ArchivedAt sets the archived_at field
func (b *BucketingStrategyInstanceBuilder) ArchivedAt(value any) *BucketingStrategyInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedAt, value)
	return b
}

// SetArchivedAt is a compatibility alias for ArchivedAt.
func (b *BucketingStrategyInstanceBuilder) SetArchivedAt(value any) *BucketingStrategyInstanceBuilder {
	return b.ArchivedAt(value)
}

// ArchivedBy sets the archived_by field
func (b *BucketingStrategyInstanceBuilder) ArchivedBy(value string) *BucketingStrategyInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedBy, value)
	return b
}

// SetArchivedBy is a compatibility alias for ArchivedBy.
func (b *BucketingStrategyInstanceBuilder) SetArchivedBy(value string) *BucketingStrategyInstanceBuilder {
	return b.ArchivedBy(value)
}

// ChangeLog sets the change_log field
func (b *BucketingStrategyInstanceBuilder) ChangeLog(value []string) *BucketingStrategyInstanceBuilder {
	b.SetField(objects.FieldKeyChangeLog, value)
	return b
}

// SetChangeLog is a compatibility alias for ChangeLog.
func (b *BucketingStrategyInstanceBuilder) SetChangeLog(value []string) *BucketingStrategyInstanceBuilder {
	return b.ChangeLog(value)
}

// Enabled sets the enabled field
func (b *BucketingStrategyInstanceBuilder) Enabled(value bool) *BucketingStrategyInstanceBuilder {
	b.SetField(objects.FieldKeyEnabled, value)
	return b
}

// SetEnabled is a compatibility alias for Enabled.
func (b *BucketingStrategyInstanceBuilder) SetEnabled(value bool) *BucketingStrategyInstanceBuilder {
	return b.Enabled(value)
}

// Format sets the format field
func (b *BucketingStrategyInstanceBuilder) Format(value string) *BucketingStrategyInstanceBuilder {
	b.SetField(objects.FieldKeyFormat, value)
	return b
}

// SetFormat is a compatibility alias for Format.
func (b *BucketingStrategyInstanceBuilder) SetFormat(value string) *BucketingStrategyInstanceBuilder {
	return b.Format(value)
}

// OriginProject sets the origin_project field
func (b *BucketingStrategyInstanceBuilder) OriginProject(value string) *BucketingStrategyInstanceBuilder {
	b.SetField(objects.FieldKeyOriginProject, value)
	return b
}

// SetOriginProject is a compatibility alias for OriginProject.
func (b *BucketingStrategyInstanceBuilder) SetOriginProject(value string) *BucketingStrategyInstanceBuilder {
	return b.OriginProject(value)
}

// OriginSystem sets the origin_system field
func (b *BucketingStrategyInstanceBuilder) OriginSystem(value string) *BucketingStrategyInstanceBuilder {
	b.SetField(objects.FieldKeyOriginSystem, value)
	return b
}

// SetOriginSystem is a compatibility alias for OriginSystem.
func (b *BucketingStrategyInstanceBuilder) SetOriginSystem(value string) *BucketingStrategyInstanceBuilder {
	return b.OriginSystem(value)
}

// RetentionTolerance sets the retention_tolerance field
func (b *BucketingStrategyInstanceBuilder) RetentionTolerance(value map[string]any) *BucketingStrategyInstanceBuilder {
	b.SetField(objects.FieldKeyRetentionTolerance, value)
	return b
}

// SetRetentionTolerance is a compatibility alias for RetentionTolerance.
func (b *BucketingStrategyInstanceBuilder) SetRetentionTolerance(value map[string]any) *BucketingStrategyInstanceBuilder {
	return b.RetentionTolerance(value)
}

// StrategyName sets the strategy_name field
func (b *BucketingStrategyInstanceBuilder) StrategyName(value string) *BucketingStrategyInstanceBuilder {
	b.SetField(objects.FieldKeyStrategyName, value)
	return b
}

// SetStrategyName is a compatibility alias for StrategyName.
func (b *BucketingStrategyInstanceBuilder) SetStrategyName(value string) *BucketingStrategyInstanceBuilder {
	return b.StrategyName(value)
}

// StrategyType sets the strategy_type field
func (b *BucketingStrategyInstanceBuilder) StrategyType(value any) *BucketingStrategyInstanceBuilder {
	b.SetField(objects.FieldKeyStrategyType, value)
	return b
}

// SetStrategyType is a compatibility alias for StrategyType.
func (b *BucketingStrategyInstanceBuilder) SetStrategyType(value any) *BucketingStrategyInstanceBuilder {
	return b.StrategyType(value)
}

func init() {
	instance_builders.RegisterBuilder(NewBucketingStrategyInstanceBuilder(objects.DefaultSchemaVersion))
}
