// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec YAML.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package bldr_instance_v1

import (
	"github.com/lanceman/zqk/pkg/objects"
	enumv "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/commercial_sequence"
	"github.com/lanceman/zqk/pkg/specbuilder/instance_builders"
)

// CommercialSequenceInstanceBuilder builds commercial_sequence instances
// ONE builder handles ALL commercial_sequence instances
type CommercialSequenceInstanceBuilder struct {
	*instance_builders.BaseInstanceBuilder
}

// NewCommercialSequenceInstanceBuilder creates a new commercial_sequence instance builder.
// Pass the instance schema_version string for this spec; use objects.DefaultSchemaVersion for the project default (pkg/objects constants).
// Field order is derived from the spec (not hardcoded) to avoid drift
func NewCommercialSequenceInstanceBuilder(schemaVersion string) *CommercialSequenceInstanceBuilder {
	// Derive canonical field order from spec (follows architecture pattern)
	// System fields first, then spec-defined fields in sorted order
	fieldOrder := buildFieldOrderFromSpec("commercial_sequence")

	// Create base builder
	builder := &CommercialSequenceInstanceBuilder{
		BaseInstanceBuilder: instance_builders.NewBaseInstanceBuilder(
			"commercial_sequence",
			schemaVersion,
			fieldOrder,
			nil, // spec builder (optional)
		),
	}

	return builder
}

// Status sets the status field
func (b *CommercialSequenceInstanceBuilder) Status(value enumv.Status) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyStatus, string(value))
	return b
}

// ID sets the id field
func (b *CommercialSequenceInstanceBuilder) ID(value string) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyID, value)
	return b
}

// ActualEffort sets the actual_effort field
func (b *CommercialSequenceInstanceBuilder) ActualEffort(value string) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyActualEffort, value)
	return b
}

// SetActualEffort is a compatibility alias for ActualEffort.
func (b *CommercialSequenceInstanceBuilder) SetActualEffort(value string) *CommercialSequenceInstanceBuilder {
	return b.ActualEffort(value)
}

// AnswerDueBy sets the answer_due_by field
func (b *CommercialSequenceInstanceBuilder) AnswerDueBy(value string) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyAnswerDueBy, value)
	return b
}

// SetAnswerDueBy is a compatibility alias for AnswerDueBy.
func (b *CommercialSequenceInstanceBuilder) SetAnswerDueBy(value string) *CommercialSequenceInstanceBuilder {
	return b.AnswerDueBy(value)
}

// ArchivedAt sets the archived_at field
func (b *CommercialSequenceInstanceBuilder) ArchivedAt(value any) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedAt, value)
	return b
}

// SetArchivedAt is a compatibility alias for ArchivedAt.
func (b *CommercialSequenceInstanceBuilder) SetArchivedAt(value any) *CommercialSequenceInstanceBuilder {
	return b.ArchivedAt(value)
}

// ArchivedBy sets the archived_by field
func (b *CommercialSequenceInstanceBuilder) ArchivedBy(value string) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedBy, value)
	return b
}

// SetArchivedBy is a compatibility alias for ArchivedBy.
func (b *CommercialSequenceInstanceBuilder) SetArchivedBy(value string) *CommercialSequenceInstanceBuilder {
	return b.ArchivedBy(value)
}

// Artifacts sets the artifacts field
func (b *CommercialSequenceInstanceBuilder) Artifacts(value []string) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyArtifacts, value)
	return b
}

// SetArtifacts is a compatibility alias for Artifacts.
func (b *CommercialSequenceInstanceBuilder) SetArtifacts(value []string) *CommercialSequenceInstanceBuilder {
	return b.Artifacts(value)
}

// ChangeLog sets the change_log field
func (b *CommercialSequenceInstanceBuilder) ChangeLog(value []string) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyChangeLog, value)
	return b
}

// SetChangeLog is a compatibility alias for ChangeLog.
func (b *CommercialSequenceInstanceBuilder) SetChangeLog(value []string) *CommercialSequenceInstanceBuilder {
	return b.ChangeLog(value)
}

// CompletenessValidation sets the completeness_validation field
func (b *CommercialSequenceInstanceBuilder) CompletenessValidation(value []string) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyCompletenessValidation, value)
	return b
}

// SetCompletenessValidation is a compatibility alias for CompletenessValidation.
func (b *CommercialSequenceInstanceBuilder) SetCompletenessValidation(value []string) *CommercialSequenceInstanceBuilder {
	return b.CompletenessValidation(value)
}

// Context sets the context field
func (b *CommercialSequenceInstanceBuilder) Context(value any) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyContext, value)
	return b
}

// SetContext is a compatibility alias for Context.
func (b *CommercialSequenceInstanceBuilder) SetContext(value any) *CommercialSequenceInstanceBuilder {
	return b.Context(value)
}

// ConversionGoal sets the conversion_goal field
func (b *CommercialSequenceInstanceBuilder) ConversionGoal(value string) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyConversionGoal, value)
	return b
}

// SetConversionGoal is a compatibility alias for ConversionGoal.
func (b *CommercialSequenceInstanceBuilder) SetConversionGoal(value string) *CommercialSequenceInstanceBuilder {
	return b.ConversionGoal(value)
}

// Deadline sets the deadline field
func (b *CommercialSequenceInstanceBuilder) Deadline(value string) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyDeadline, value)
	return b
}

// SetDeadline is a compatibility alias for Deadline.
func (b *CommercialSequenceInstanceBuilder) SetDeadline(value string) *CommercialSequenceInstanceBuilder {
	return b.Deadline(value)
}

// Dependencies sets the dependencies field
func (b *CommercialSequenceInstanceBuilder) Dependencies(value []string) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyDependencies, value)
	return b
}

// SetDependencies is a compatibility alias for Dependencies.
func (b *CommercialSequenceInstanceBuilder) SetDependencies(value []string) *CommercialSequenceInstanceBuilder {
	return b.Dependencies(value)
}

// EstimatedEffort sets the estimated_effort field
func (b *CommercialSequenceInstanceBuilder) EstimatedEffort(value string) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyEstimatedEffort, value)
	return b
}

// SetEstimatedEffort is a compatibility alias for EstimatedEffort.
func (b *CommercialSequenceInstanceBuilder) SetEstimatedEffort(value string) *CommercialSequenceInstanceBuilder {
	return b.EstimatedEffort(value)
}

// NarrativeRefs sets the narrative_refs field
func (b *CommercialSequenceInstanceBuilder) NarrativeRefs(value []string) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyNarrativeRefs, value)
	return b
}

// SetNarrativeRefs is a compatibility alias for NarrativeRefs.
func (b *CommercialSequenceInstanceBuilder) SetNarrativeRefs(value []string) *CommercialSequenceInstanceBuilder {
	return b.NarrativeRefs(value)
}

// OriginProject sets the origin_project field
func (b *CommercialSequenceInstanceBuilder) OriginProject(value string) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyOriginProject, value)
	return b
}

// SetOriginProject is a compatibility alias for OriginProject.
func (b *CommercialSequenceInstanceBuilder) SetOriginProject(value string) *CommercialSequenceInstanceBuilder {
	return b.OriginProject(value)
}

// OriginSystem sets the origin_system field
func (b *CommercialSequenceInstanceBuilder) OriginSystem(value string) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyOriginSystem, value)
	return b
}

// SetOriginSystem is a compatibility alias for OriginSystem.
func (b *CommercialSequenceInstanceBuilder) SetOriginSystem(value string) *CommercialSequenceInstanceBuilder {
	return b.OriginSystem(value)
}

// PriorityTier sets the priority_tier field
func (b *CommercialSequenceInstanceBuilder) PriorityTier(value enumv.PriorityTier) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyPriorityTier, string(value))
	return b
}

// SetPriorityTier is a compatibility alias for PriorityTier.
func (b *CommercialSequenceInstanceBuilder) SetPriorityTier(value enumv.PriorityTier) *CommercialSequenceInstanceBuilder {
	return b.PriorityTier(value)
}

// Questions sets the questions field
func (b *CommercialSequenceInstanceBuilder) Questions(value []string) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyQuestions, value)
	return b
}

// SetQuestions is a compatibility alias for Questions.
func (b *CommercialSequenceInstanceBuilder) SetQuestions(value []string) *CommercialSequenceInstanceBuilder {
	return b.Questions(value)
}

// RelatedObjectRefs sets the related_object_refs field
func (b *CommercialSequenceInstanceBuilder) RelatedObjectRefs(value []string) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyRelatedObjectRefs, value)
	return b
}

// SetRelatedObjectRefs is a compatibility alias for RelatedObjectRefs.
func (b *CommercialSequenceInstanceBuilder) SetRelatedObjectRefs(value []string) *CommercialSequenceInstanceBuilder {
	return b.RelatedObjectRefs(value)
}

// SequenceType sets the sequence_type field
func (b *CommercialSequenceInstanceBuilder) SequenceType(value enumv.SequenceType) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeySequenceType, string(value))
	return b
}

// SetSequenceType is a compatibility alias for SequenceType.
func (b *CommercialSequenceInstanceBuilder) SetSequenceType(value enumv.SequenceType) *CommercialSequenceInstanceBuilder {
	return b.SequenceType(value)
}

// SourceType sets the source_type field
func (b *CommercialSequenceInstanceBuilder) SourceType(value enumv.SourceType) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeySourceType, string(value))
	return b
}

// SetSourceType is a compatibility alias for SourceType.
func (b *CommercialSequenceInstanceBuilder) SetSourceType(value enumv.SourceType) *CommercialSequenceInstanceBuilder {
	return b.SourceType(value)
}

// SpecAdherence sets the spec_adherence field
func (b *CommercialSequenceInstanceBuilder) SpecAdherence(value map[string]any) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeySpecAdherence, value)
	return b
}

// SetSpecAdherence is a compatibility alias for SpecAdherence.
func (b *CommercialSequenceInstanceBuilder) SetSpecAdherence(value map[string]any) *CommercialSequenceInstanceBuilder {
	return b.SpecAdherence(value)
}

// Stages sets the stages field
func (b *CommercialSequenceInstanceBuilder) Stages(value []string) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyStages, value)
	return b
}

// SetStages is a compatibility alias for Stages.
func (b *CommercialSequenceInstanceBuilder) SetStages(value []string) *CommercialSequenceInstanceBuilder {
	return b.Stages(value)
}

// Stakeholders sets the stakeholders field
func (b *CommercialSequenceInstanceBuilder) Stakeholders(value []string) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyStakeholders, value)
	return b
}

// SetStakeholders is a compatibility alias for Stakeholders.
func (b *CommercialSequenceInstanceBuilder) SetStakeholders(value []string) *CommercialSequenceInstanceBuilder {
	return b.Stakeholders(value)
}

// StatusHistory sets the status_history field
func (b *CommercialSequenceInstanceBuilder) StatusHistory(value []string) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyStatusHistory, value)
	return b
}

// SetStatusHistory is a compatibility alias for StatusHistory.
func (b *CommercialSequenceInstanceBuilder) SetStatusHistory(value []string) *CommercialSequenceInstanceBuilder {
	return b.StatusHistory(value)
}

// TargetDate sets the target_date field
func (b *CommercialSequenceInstanceBuilder) TargetDate(value string) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyTargetDate, value)
	return b
}

// SetTargetDate is a compatibility alias for TargetDate.
func (b *CommercialSequenceInstanceBuilder) SetTargetDate(value string) *CommercialSequenceInstanceBuilder {
	return b.TargetDate(value)
}

// Title sets the title field
func (b *CommercialSequenceInstanceBuilder) Title(value string) *CommercialSequenceInstanceBuilder {
	b.SetField(objects.FieldKeyTitle, value)
	return b
}

// SetTitle is a compatibility alias for Title.
func (b *CommercialSequenceInstanceBuilder) SetTitle(value string) *CommercialSequenceInstanceBuilder {
	return b.Title(value)
}

func init() {
	instance_builders.RegisterBuilder(NewCommercialSequenceInstanceBuilder(objects.DefaultSchemaVersion))
}
