// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec YAML.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package bldr_instance_v1

import (
	"github.com/lanceman/zqk/pkg/objects"
	enumv "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/corporate_initiative"
	"github.com/lanceman/zqk/pkg/specbuilder/instance_builders"
)

// CorporateInitiativeInstanceBuilder builds corporate_initiative instances
// ONE builder handles ALL corporate_initiative instances
type CorporateInitiativeInstanceBuilder struct {
	*instance_builders.BaseInstanceBuilder
}

// NewCorporateInitiativeInstanceBuilder creates a new corporate_initiative instance builder.
// Pass the instance schema_version string for this spec; use objects.DefaultSchemaVersion for the project default (pkg/objects constants).
// Field order is derived from the spec (not hardcoded) to avoid drift
func NewCorporateInitiativeInstanceBuilder(schemaVersion string) *CorporateInitiativeInstanceBuilder {
	// Derive canonical field order from spec (follows architecture pattern)
	// System fields first, then spec-defined fields in sorted order
	fieldOrder := buildFieldOrderFromSpec("corporate_initiative")

	// Create base builder
	builder := &CorporateInitiativeInstanceBuilder{
		BaseInstanceBuilder: instance_builders.NewBaseInstanceBuilder(
			"corporate_initiative",
			schemaVersion,
			fieldOrder,
			nil, // spec builder (optional)
		),
	}

	return builder
}

// Status sets the status field
func (b *CorporateInitiativeInstanceBuilder) Status(value enumv.Status) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyStatus, string(value))
	return b
}

// ID sets the id field
func (b *CorporateInitiativeInstanceBuilder) ID(value string) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyID, value)
	return b
}

// ActualEffort sets the actual_effort field
func (b *CorporateInitiativeInstanceBuilder) ActualEffort(value string) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyActualEffort, value)
	return b
}

// SetActualEffort is a compatibility alias for ActualEffort.
func (b *CorporateInitiativeInstanceBuilder) SetActualEffort(value string) *CorporateInitiativeInstanceBuilder {
	return b.ActualEffort(value)
}

// AggregatedDb sets the aggregated_db field
func (b *CorporateInitiativeInstanceBuilder) AggregatedDb(value map[string]any) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyAggregatedDb, value)
	return b
}

// SetAggregatedDb is a compatibility alias for AggregatedDb.
func (b *CorporateInitiativeInstanceBuilder) SetAggregatedDb(value map[string]any) *CorporateInitiativeInstanceBuilder {
	return b.AggregatedDb(value)
}

// AggregatedEdd sets the aggregated_edd field
func (b *CorporateInitiativeInstanceBuilder) AggregatedEdd(value any) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyAggregatedEdd, value)
	return b
}

// SetAggregatedEdd is a compatibility alias for AggregatedEdd.
func (b *CorporateInitiativeInstanceBuilder) SetAggregatedEdd(value any) *CorporateInitiativeInstanceBuilder {
	return b.AggregatedEdd(value)
}

// AggregatedPcs sets the aggregated_pcs field
func (b *CorporateInitiativeInstanceBuilder) AggregatedPcs(value any) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyAggregatedPcs, value)
	return b
}

// SetAggregatedPcs is a compatibility alias for AggregatedPcs.
func (b *CorporateInitiativeInstanceBuilder) SetAggregatedPcs(value any) *CorporateInitiativeInstanceBuilder {
	return b.AggregatedPcs(value)
}

// AggregationStatus sets the aggregation_status field
func (b *CorporateInitiativeInstanceBuilder) AggregationStatus(value enumv.AggregationStatus) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyAggregationStatus, string(value))
	return b
}

// SetAggregationStatus is a compatibility alias for AggregationStatus.
func (b *CorporateInitiativeInstanceBuilder) SetAggregationStatus(value enumv.AggregationStatus) *CorporateInitiativeInstanceBuilder {
	return b.AggregationStatus(value)
}

// AnswerDueBy sets the answer_due_by field
func (b *CorporateInitiativeInstanceBuilder) AnswerDueBy(value string) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyAnswerDueBy, value)
	return b
}

// SetAnswerDueBy is a compatibility alias for AnswerDueBy.
func (b *CorporateInitiativeInstanceBuilder) SetAnswerDueBy(value string) *CorporateInitiativeInstanceBuilder {
	return b.AnswerDueBy(value)
}

// ArchivedAt sets the archived_at field
func (b *CorporateInitiativeInstanceBuilder) ArchivedAt(value any) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedAt, value)
	return b
}

// SetArchivedAt is a compatibility alias for ArchivedAt.
func (b *CorporateInitiativeInstanceBuilder) SetArchivedAt(value any) *CorporateInitiativeInstanceBuilder {
	return b.ArchivedAt(value)
}

// ArchivedBy sets the archived_by field
func (b *CorporateInitiativeInstanceBuilder) ArchivedBy(value string) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedBy, value)
	return b
}

// SetArchivedBy is a compatibility alias for ArchivedBy.
func (b *CorporateInitiativeInstanceBuilder) SetArchivedBy(value string) *CorporateInitiativeInstanceBuilder {
	return b.ArchivedBy(value)
}

// Artifacts sets the artifacts field
func (b *CorporateInitiativeInstanceBuilder) Artifacts(value []string) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyArtifacts, value)
	return b
}

// SetArtifacts is a compatibility alias for Artifacts.
func (b *CorporateInitiativeInstanceBuilder) SetArtifacts(value []string) *CorporateInitiativeInstanceBuilder {
	return b.Artifacts(value)
}

// ChangeLog sets the change_log field
func (b *CorporateInitiativeInstanceBuilder) ChangeLog(value []string) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyChangeLog, value)
	return b
}

// SetChangeLog is a compatibility alias for ChangeLog.
func (b *CorporateInitiativeInstanceBuilder) SetChangeLog(value []string) *CorporateInitiativeInstanceBuilder {
	return b.ChangeLog(value)
}

// CompletenessValidation sets the completeness_validation field
func (b *CorporateInitiativeInstanceBuilder) CompletenessValidation(value []string) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyCompletenessValidation, value)
	return b
}

// SetCompletenessValidation is a compatibility alias for CompletenessValidation.
func (b *CorporateInitiativeInstanceBuilder) SetCompletenessValidation(value []string) *CorporateInitiativeInstanceBuilder {
	return b.CompletenessValidation(value)
}

// Context sets the context field
func (b *CorporateInitiativeInstanceBuilder) Context(value any) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyContext, value)
	return b
}

// SetContext is a compatibility alias for Context.
func (b *CorporateInitiativeInstanceBuilder) SetContext(value any) *CorporateInitiativeInstanceBuilder {
	return b.Context(value)
}

// CrossProjectDependencies sets the cross_project_dependencies field
func (b *CorporateInitiativeInstanceBuilder) CrossProjectDependencies(value []string) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyCrossProjectDependencies, value)
	return b
}

// SetCrossProjectDependencies is a compatibility alias for CrossProjectDependencies.
func (b *CorporateInitiativeInstanceBuilder) SetCrossProjectDependencies(value []string) *CorporateInitiativeInstanceBuilder {
	return b.CrossProjectDependencies(value)
}

// Deadline sets the deadline field
func (b *CorporateInitiativeInstanceBuilder) Deadline(value string) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyDeadline, value)
	return b
}

// SetDeadline is a compatibility alias for Deadline.
func (b *CorporateInitiativeInstanceBuilder) SetDeadline(value string) *CorporateInitiativeInstanceBuilder {
	return b.Deadline(value)
}

// Dependencies sets the dependencies field
func (b *CorporateInitiativeInstanceBuilder) Dependencies(value []string) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyDependencies, value)
	return b
}

// SetDependencies is a compatibility alias for Dependencies.
func (b *CorporateInitiativeInstanceBuilder) SetDependencies(value []string) *CorporateInitiativeInstanceBuilder {
	return b.Dependencies(value)
}

// EstimatedEffort sets the estimated_effort field
func (b *CorporateInitiativeInstanceBuilder) EstimatedEffort(value string) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyEstimatedEffort, value)
	return b
}

// SetEstimatedEffort is a compatibility alias for EstimatedEffort.
func (b *CorporateInitiativeInstanceBuilder) SetEstimatedEffort(value string) *CorporateInitiativeInstanceBuilder {
	return b.EstimatedEffort(value)
}

// LastAggregatedAt sets the last_aggregated_at field
func (b *CorporateInitiativeInstanceBuilder) LastAggregatedAt(value string) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyLastAggregatedAt, value)
	return b
}

// SetLastAggregatedAt is a compatibility alias for LastAggregatedAt.
func (b *CorporateInitiativeInstanceBuilder) SetLastAggregatedAt(value string) *CorporateInitiativeInstanceBuilder {
	return b.LastAggregatedAt(value)
}

// OriginProject sets the origin_project field
func (b *CorporateInitiativeInstanceBuilder) OriginProject(value string) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyOriginProject, value)
	return b
}

// SetOriginProject is a compatibility alias for OriginProject.
func (b *CorporateInitiativeInstanceBuilder) SetOriginProject(value string) *CorporateInitiativeInstanceBuilder {
	return b.OriginProject(value)
}

// OriginSystem sets the origin_system field
func (b *CorporateInitiativeInstanceBuilder) OriginSystem(value string) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyOriginSystem, value)
	return b
}

// SetOriginSystem is a compatibility alias for OriginSystem.
func (b *CorporateInitiativeInstanceBuilder) SetOriginSystem(value string) *CorporateInitiativeInstanceBuilder {
	return b.OriginSystem(value)
}

// OwnerRef sets the owner_ref field
func (b *CorporateInitiativeInstanceBuilder) OwnerRef(value string) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyOwnerRef, value)
	return b
}

// SetOwnerRef is a compatibility alias for OwnerRef.
func (b *CorporateInitiativeInstanceBuilder) SetOwnerRef(value string) *CorporateInitiativeInstanceBuilder {
	return b.OwnerRef(value)
}

// PriorityTier sets the priority_tier field
func (b *CorporateInitiativeInstanceBuilder) PriorityTier(value enumv.PriorityTier) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyPriorityTier, string(value))
	return b
}

// SetPriorityTier is a compatibility alias for PriorityTier.
func (b *CorporateInitiativeInstanceBuilder) SetPriorityTier(value enumv.PriorityTier) *CorporateInitiativeInstanceBuilder {
	return b.PriorityTier(value)
}

// ProjectRefs sets the project_refs field
func (b *CorporateInitiativeInstanceBuilder) ProjectRefs(value []string) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyProjectRefs, value)
	return b
}

// SetProjectRefs is a compatibility alias for ProjectRefs.
func (b *CorporateInitiativeInstanceBuilder) SetProjectRefs(value []string) *CorporateInitiativeInstanceBuilder {
	return b.ProjectRefs(value)
}

// Questions sets the questions field
func (b *CorporateInitiativeInstanceBuilder) Questions(value []string) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyQuestions, value)
	return b
}

// SetQuestions is a compatibility alias for Questions.
func (b *CorporateInitiativeInstanceBuilder) SetQuestions(value []string) *CorporateInitiativeInstanceBuilder {
	return b.Questions(value)
}

// RelatedObjectRefs sets the related_object_refs field
func (b *CorporateInitiativeInstanceBuilder) RelatedObjectRefs(value []string) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyRelatedObjectRefs, value)
	return b
}

// SetRelatedObjectRefs is a compatibility alias for RelatedObjectRefs.
func (b *CorporateInitiativeInstanceBuilder) SetRelatedObjectRefs(value []string) *CorporateInitiativeInstanceBuilder {
	return b.RelatedObjectRefs(value)
}

// ResourceAllocation sets the resource_allocation field
func (b *CorporateInitiativeInstanceBuilder) ResourceAllocation(value map[string]any) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyResourceAllocation, value)
	return b
}

// SetResourceAllocation is a compatibility alias for ResourceAllocation.
func (b *CorporateInitiativeInstanceBuilder) SetResourceAllocation(value map[string]any) *CorporateInitiativeInstanceBuilder {
	return b.ResourceAllocation(value)
}

// SourceType sets the source_type field
func (b *CorporateInitiativeInstanceBuilder) SourceType(value enumv.SourceType) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeySourceType, string(value))
	return b
}

// SetSourceType is a compatibility alias for SourceType.
func (b *CorporateInitiativeInstanceBuilder) SetSourceType(value enumv.SourceType) *CorporateInitiativeInstanceBuilder {
	return b.SourceType(value)
}

// SpecAdherence sets the spec_adherence field
func (b *CorporateInitiativeInstanceBuilder) SpecAdherence(value map[string]any) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeySpecAdherence, value)
	return b
}

// SetSpecAdherence is a compatibility alias for SpecAdherence.
func (b *CorporateInitiativeInstanceBuilder) SetSpecAdherence(value map[string]any) *CorporateInitiativeInstanceBuilder {
	return b.SpecAdherence(value)
}

// Stakeholders sets the stakeholders field
func (b *CorporateInitiativeInstanceBuilder) Stakeholders(value []string) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyStakeholders, value)
	return b
}

// SetStakeholders is a compatibility alias for Stakeholders.
func (b *CorporateInitiativeInstanceBuilder) SetStakeholders(value []string) *CorporateInitiativeInstanceBuilder {
	return b.Stakeholders(value)
}

// StatusHistory sets the status_history field
func (b *CorporateInitiativeInstanceBuilder) StatusHistory(value []string) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyStatusHistory, value)
	return b
}

// SetStatusHistory is a compatibility alias for StatusHistory.
func (b *CorporateInitiativeInstanceBuilder) SetStatusHistory(value []string) *CorporateInitiativeInstanceBuilder {
	return b.StatusHistory(value)
}

// TargetDate sets the target_date field
func (b *CorporateInitiativeInstanceBuilder) TargetDate(value string) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyTargetDate, value)
	return b
}

// SetTargetDate is a compatibility alias for TargetDate.
func (b *CorporateInitiativeInstanceBuilder) SetTargetDate(value string) *CorporateInitiativeInstanceBuilder {
	return b.TargetDate(value)
}

// Title sets the title field
func (b *CorporateInitiativeInstanceBuilder) Title(value string) *CorporateInitiativeInstanceBuilder {
	b.SetField(objects.FieldKeyTitle, value)
	return b
}

// SetTitle is a compatibility alias for Title.
func (b *CorporateInitiativeInstanceBuilder) SetTitle(value string) *CorporateInitiativeInstanceBuilder {
	return b.Title(value)
}

func init() {
	instance_builders.RegisterBuilder(NewCorporateInitiativeInstanceBuilder(objects.DefaultSchemaVersion))
}
