// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec YAML.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package bldr_instance_v1

import (
	"github.com/lanceman/zqk/pkg/objects"
	enumv "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/criteria"
	"github.com/lanceman/zqk/pkg/specbuilder/instance_builders"
)

// CriteriaInstanceBuilder builds criteria instances
// ONE builder handles ALL criteria instances
type CriteriaInstanceBuilder struct {
	*instance_builders.BaseInstanceBuilder
}

// NewCriteriaInstanceBuilder creates a new criteria instance builder.
// Pass the instance schema_version string for this spec; use objects.DefaultSchemaVersion for the project default (pkg/objects constants).
// Field order is derived from the spec (not hardcoded) to avoid drift
func NewCriteriaInstanceBuilder(schemaVersion string) *CriteriaInstanceBuilder {
	// Derive canonical field order from spec (follows architecture pattern)
	// System fields first, then spec-defined fields in sorted order
	fieldOrder := buildFieldOrderFromSpec("criteria")

	// Create base builder
	builder := &CriteriaInstanceBuilder{
		BaseInstanceBuilder: instance_builders.NewBaseInstanceBuilder(
			"criteria",
			schemaVersion,
			fieldOrder,
			nil, // spec builder (optional)
		),
	}

	return builder
}

// Status sets the status field
func (b *CriteriaInstanceBuilder) Status(value enumv.Status) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyStatus, string(value))
	return b
}

// ID sets the id field
func (b *CriteriaInstanceBuilder) ID(value string) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyID, value)
	return b
}

// ActualEffort sets the actual_effort field
func (b *CriteriaInstanceBuilder) ActualEffort(value string) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyActualEffort, value)
	return b
}

// SetActualEffort is a compatibility alias for ActualEffort.
func (b *CriteriaInstanceBuilder) SetActualEffort(value string) *CriteriaInstanceBuilder {
	return b.ActualEffort(value)
}

// AnswerDueBy sets the answer_due_by field
func (b *CriteriaInstanceBuilder) AnswerDueBy(value string) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyAnswerDueBy, value)
	return b
}

// SetAnswerDueBy is a compatibility alias for AnswerDueBy.
func (b *CriteriaInstanceBuilder) SetAnswerDueBy(value string) *CriteriaInstanceBuilder {
	return b.AnswerDueBy(value)
}

// ArchivedAt sets the archived_at field
func (b *CriteriaInstanceBuilder) ArchivedAt(value any) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedAt, value)
	return b
}

// SetArchivedAt is a compatibility alias for ArchivedAt.
func (b *CriteriaInstanceBuilder) SetArchivedAt(value any) *CriteriaInstanceBuilder {
	return b.ArchivedAt(value)
}

// ArchivedBy sets the archived_by field
func (b *CriteriaInstanceBuilder) ArchivedBy(value string) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedBy, value)
	return b
}

// SetArchivedBy is a compatibility alias for ArchivedBy.
func (b *CriteriaInstanceBuilder) SetArchivedBy(value string) *CriteriaInstanceBuilder {
	return b.ArchivedBy(value)
}

// Artifacts sets the artifacts field
func (b *CriteriaInstanceBuilder) Artifacts(value []string) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyArtifacts, value)
	return b
}

// SetArtifacts is a compatibility alias for Artifacts.
func (b *CriteriaInstanceBuilder) SetArtifacts(value []string) *CriteriaInstanceBuilder {
	return b.Artifacts(value)
}

// BacklogItemRefs sets the backlog_item_refs field
func (b *CriteriaInstanceBuilder) BacklogItemRefs(value []string) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyBacklogItemRefs, value)
	return b
}

// SetBacklogItemRefs is a compatibility alias for BacklogItemRefs.
func (b *CriteriaInstanceBuilder) SetBacklogItemRefs(value []string) *CriteriaInstanceBuilder {
	return b.BacklogItemRefs(value)
}

// Category sets the category field
func (b *CriteriaInstanceBuilder) Category(value enumv.Category) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyCategory, string(value))
	return b
}

// SetCategory is a compatibility alias for Category.
func (b *CriteriaInstanceBuilder) SetCategory(value enumv.Category) *CriteriaInstanceBuilder {
	return b.Category(value)
}

// ChangeLog sets the change_log field
func (b *CriteriaInstanceBuilder) ChangeLog(value []string) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyChangeLog, value)
	return b
}

// SetChangeLog is a compatibility alias for ChangeLog.
func (b *CriteriaInstanceBuilder) SetChangeLog(value []string) *CriteriaInstanceBuilder {
	return b.ChangeLog(value)
}

// CompletenessValidation sets the completeness_validation field
func (b *CriteriaInstanceBuilder) CompletenessValidation(value []string) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyCompletenessValidation, value)
	return b
}

// SetCompletenessValidation is a compatibility alias for CompletenessValidation.
func (b *CriteriaInstanceBuilder) SetCompletenessValidation(value []string) *CriteriaInstanceBuilder {
	return b.CompletenessValidation(value)
}

// Context sets the context field
func (b *CriteriaInstanceBuilder) Context(value any) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyContext, value)
	return b
}

// SetContext is a compatibility alias for Context.
func (b *CriteriaInstanceBuilder) SetContext(value any) *CriteriaInstanceBuilder {
	return b.Context(value)
}

// Deadline sets the deadline field
func (b *CriteriaInstanceBuilder) Deadline(value string) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyDeadline, value)
	return b
}

// SetDeadline is a compatibility alias for Deadline.
func (b *CriteriaInstanceBuilder) SetDeadline(value string) *CriteriaInstanceBuilder {
	return b.Deadline(value)
}

// Dependencies sets the dependencies field
func (b *CriteriaInstanceBuilder) Dependencies(value []string) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyDependencies, value)
	return b
}

// SetDependencies is a compatibility alias for Dependencies.
func (b *CriteriaInstanceBuilder) SetDependencies(value []string) *CriteriaInstanceBuilder {
	return b.Dependencies(value)
}

// EstimatedEffort sets the estimated_effort field
func (b *CriteriaInstanceBuilder) EstimatedEffort(value string) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyEstimatedEffort, value)
	return b
}

// SetEstimatedEffort is a compatibility alias for EstimatedEffort.
func (b *CriteriaInstanceBuilder) SetEstimatedEffort(value string) *CriteriaInstanceBuilder {
	return b.EstimatedEffort(value)
}

// GoalRefs sets the goal_refs field
func (b *CriteriaInstanceBuilder) GoalRefs(value []string) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyGoalRefs, value)
	return b
}

// SetGoalRefs is a compatibility alias for GoalRefs.
func (b *CriteriaInstanceBuilder) SetGoalRefs(value []string) *CriteriaInstanceBuilder {
	return b.GoalRefs(value)
}

// MilestoneRefs sets the milestone_refs field
func (b *CriteriaInstanceBuilder) MilestoneRefs(value []string) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyMilestoneRefs, value)
	return b
}

// SetMilestoneRefs is a compatibility alias for MilestoneRefs.
func (b *CriteriaInstanceBuilder) SetMilestoneRefs(value []string) *CriteriaInstanceBuilder {
	return b.MilestoneRefs(value)
}

// OriginProject sets the origin_project field
func (b *CriteriaInstanceBuilder) OriginProject(value string) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyOriginProject, value)
	return b
}

// SetOriginProject is a compatibility alias for OriginProject.
func (b *CriteriaInstanceBuilder) SetOriginProject(value string) *CriteriaInstanceBuilder {
	return b.OriginProject(value)
}

// OriginSystem sets the origin_system field
func (b *CriteriaInstanceBuilder) OriginSystem(value string) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyOriginSystem, value)
	return b
}

// SetOriginSystem is a compatibility alias for OriginSystem.
func (b *CriteriaInstanceBuilder) SetOriginSystem(value string) *CriteriaInstanceBuilder {
	return b.OriginSystem(value)
}

// Priority sets the priority field
func (b *CriteriaInstanceBuilder) Priority(value enumv.Priority) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyPriority, string(value))
	return b
}

// SetPriority is a compatibility alias for Priority.
func (b *CriteriaInstanceBuilder) SetPriority(value enumv.Priority) *CriteriaInstanceBuilder {
	return b.Priority(value)
}

// PriorityTier sets the priority_tier field
func (b *CriteriaInstanceBuilder) PriorityTier(value enumv.PriorityTier) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyPriorityTier, string(value))
	return b
}

// SetPriorityTier is a compatibility alias for PriorityTier.
func (b *CriteriaInstanceBuilder) SetPriorityTier(value enumv.PriorityTier) *CriteriaInstanceBuilder {
	return b.PriorityTier(value)
}

// Questions sets the questions field
func (b *CriteriaInstanceBuilder) Questions(value []string) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyQuestions, value)
	return b
}

// SetQuestions is a compatibility alias for Questions.
func (b *CriteriaInstanceBuilder) SetQuestions(value []string) *CriteriaInstanceBuilder {
	return b.Questions(value)
}

// RelatedObjectRefs sets the related_object_refs field
func (b *CriteriaInstanceBuilder) RelatedObjectRefs(value []string) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyRelatedObjectRefs, value)
	return b
}

// SetRelatedObjectRefs is a compatibility alias for RelatedObjectRefs.
func (b *CriteriaInstanceBuilder) SetRelatedObjectRefs(value []string) *CriteriaInstanceBuilder {
	return b.RelatedObjectRefs(value)
}

// RequirementRefs sets the requirement_refs field
func (b *CriteriaInstanceBuilder) RequirementRefs(value []string) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyRequirementRefs, value)
	return b
}

// SetRequirementRefs is a compatibility alias for RequirementRefs.
func (b *CriteriaInstanceBuilder) SetRequirementRefs(value []string) *CriteriaInstanceBuilder {
	return b.RequirementRefs(value)
}

// SourceType sets the source_type field
func (b *CriteriaInstanceBuilder) SourceType(value enumv.SourceType) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeySourceType, string(value))
	return b
}

// SetSourceType is a compatibility alias for SourceType.
func (b *CriteriaInstanceBuilder) SetSourceType(value enumv.SourceType) *CriteriaInstanceBuilder {
	return b.SourceType(value)
}

// SpecAdherence sets the spec_adherence field
func (b *CriteriaInstanceBuilder) SpecAdherence(value map[string]any) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeySpecAdherence, value)
	return b
}

// SetSpecAdherence is a compatibility alias for SpecAdherence.
func (b *CriteriaInstanceBuilder) SetSpecAdherence(value map[string]any) *CriteriaInstanceBuilder {
	return b.SpecAdherence(value)
}

// Stakeholders sets the stakeholders field
func (b *CriteriaInstanceBuilder) Stakeholders(value []string) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyStakeholders, value)
	return b
}

// SetStakeholders is a compatibility alias for Stakeholders.
func (b *CriteriaInstanceBuilder) SetStakeholders(value []string) *CriteriaInstanceBuilder {
	return b.Stakeholders(value)
}

// StatusHistory sets the status_history field
func (b *CriteriaInstanceBuilder) StatusHistory(value []string) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyStatusHistory, value)
	return b
}

// SetStatusHistory is a compatibility alias for StatusHistory.
func (b *CriteriaInstanceBuilder) SetStatusHistory(value []string) *CriteriaInstanceBuilder {
	return b.StatusHistory(value)
}

// TargetDate sets the target_date field
func (b *CriteriaInstanceBuilder) TargetDate(value string) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyTargetDate, value)
	return b
}

// SetTargetDate is a compatibility alias for TargetDate.
func (b *CriteriaInstanceBuilder) SetTargetDate(value string) *CriteriaInstanceBuilder {
	return b.TargetDate(value)
}

// Title sets the title field
func (b *CriteriaInstanceBuilder) Title(value string) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyTitle, value)
	return b
}

// SetTitle is a compatibility alias for Title.
func (b *CriteriaInstanceBuilder) SetTitle(value string) *CriteriaInstanceBuilder {
	return b.Title(value)
}

// ValidationMethod sets the validation_method field
func (b *CriteriaInstanceBuilder) ValidationMethod(value enumv.ValidationMethod) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyValidationMethod, string(value))
	return b
}

// SetValidationMethod is a compatibility alias for ValidationMethod.
func (b *CriteriaInstanceBuilder) SetValidationMethod(value enumv.ValidationMethod) *CriteriaInstanceBuilder {
	return b.ValidationMethod(value)
}

// ValidationThreshold sets the validation_threshold field
func (b *CriteriaInstanceBuilder) ValidationThreshold(value string) *CriteriaInstanceBuilder {
	b.SetField(objects.FieldKeyValidationThreshold, value)
	return b
}

// SetValidationThreshold is a compatibility alias for ValidationThreshold.
func (b *CriteriaInstanceBuilder) SetValidationThreshold(value string) *CriteriaInstanceBuilder {
	return b.ValidationThreshold(value)
}

func init() {
	instance_builders.RegisterBuilder(NewCriteriaInstanceBuilder(objects.DefaultSchemaVersion))
}
