// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package bldr_instance_v1

import (
	"github.com/lanceman/zqk/pkg/objects"
	enumv "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/department"
	"github.com/lanceman/zqk/pkg/specbuilder/instance_builders"
)

// DepartmentInstanceBuilder builds department instances
// ONE builder handles ALL department instances
type DepartmentInstanceBuilder struct {
	*instance_builders.BaseInstanceBuilder
}

// NewDepartmentInstanceBuilder creates a new department instance builder.
// Pass the instance schema_version string for this spec; use objects.DefaultSchemaVersion for the project default (pkg/objects constants).
// Field order is derived from the spec (not hardcoded) to avoid drift
func NewDepartmentInstanceBuilder(schemaVersion string) *DepartmentInstanceBuilder {
	// Derive canonical field order from spec (follows architecture pattern)
	// System fields first, then spec-defined fields in sorted order
	fieldOrder := buildFieldOrderFromSpec("department")

	// Create base builder
	builder := &DepartmentInstanceBuilder{
		BaseInstanceBuilder: instance_builders.NewBaseInstanceBuilder(
			"department",
			schemaVersion,
			fieldOrder,
			nil, // spec builder (optional)
		),
	}

	return builder
}

// Status sets the status field
func (b *DepartmentInstanceBuilder) Status(value enumv.Status) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyStatus, string(value))
	return b
}

// ID sets the id field
func (b *DepartmentInstanceBuilder) ID(value string) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyID, value)
	return b
}

// AnswerDueBy sets the answer_due_by field
func (b *DepartmentInstanceBuilder) AnswerDueBy(value string) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyAnswerDueBy, value)
	return b
}

// SetAnswerDueBy is a compatibility alias for AnswerDueBy.
func (b *DepartmentInstanceBuilder) SetAnswerDueBy(value string) *DepartmentInstanceBuilder {
	return b.AnswerDueBy(value)
}

// ArchivedAt sets the archived_at field
func (b *DepartmentInstanceBuilder) ArchivedAt(value any) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedAt, value)
	return b
}

// SetArchivedAt is a compatibility alias for ArchivedAt.
func (b *DepartmentInstanceBuilder) SetArchivedAt(value any) *DepartmentInstanceBuilder {
	return b.ArchivedAt(value)
}

// ArchivedBy sets the archived_by field
func (b *DepartmentInstanceBuilder) ArchivedBy(value string) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedBy, value)
	return b
}

// SetArchivedBy is a compatibility alias for ArchivedBy.
func (b *DepartmentInstanceBuilder) SetArchivedBy(value string) *DepartmentInstanceBuilder {
	return b.ArchivedBy(value)
}

// Artifacts sets the artifacts field
func (b *DepartmentInstanceBuilder) Artifacts(value []string) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyArtifacts, value)
	return b
}

// SetArtifacts is a compatibility alias for Artifacts.
func (b *DepartmentInstanceBuilder) SetArtifacts(value []string) *DepartmentInstanceBuilder {
	return b.Artifacts(value)
}

// ChangeLog sets the change_log field
func (b *DepartmentInstanceBuilder) ChangeLog(value []string) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyChangeLog, value)
	return b
}

// SetChangeLog is a compatibility alias for ChangeLog.
func (b *DepartmentInstanceBuilder) SetChangeLog(value []string) *DepartmentInstanceBuilder {
	return b.ChangeLog(value)
}

// CompletenessValidation sets the completeness_validation field
func (b *DepartmentInstanceBuilder) CompletenessValidation(value []string) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyCompletenessValidation, value)
	return b
}

// SetCompletenessValidation is a compatibility alias for CompletenessValidation.
func (b *DepartmentInstanceBuilder) SetCompletenessValidation(value []string) *DepartmentInstanceBuilder {
	return b.CompletenessValidation(value)
}

// Context sets the context field
func (b *DepartmentInstanceBuilder) Context(value any) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyContext, value)
	return b
}

// SetContext is a compatibility alias for Context.
func (b *DepartmentInstanceBuilder) SetContext(value any) *DepartmentInstanceBuilder {
	return b.Context(value)
}

// Deadline sets the deadline field
func (b *DepartmentInstanceBuilder) Deadline(value string) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyDeadline, value)
	return b
}

// SetDeadline is a compatibility alias for Deadline.
func (b *DepartmentInstanceBuilder) SetDeadline(value string) *DepartmentInstanceBuilder {
	return b.Deadline(value)
}

// DepartmentName sets the department_name field
func (b *DepartmentInstanceBuilder) DepartmentName(value string) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyDepartmentName, value)
	return b
}

// SetDepartmentName is a compatibility alias for DepartmentName.
func (b *DepartmentInstanceBuilder) SetDepartmentName(value string) *DepartmentInstanceBuilder {
	return b.DepartmentName(value)
}

// Dependencies sets the dependencies field
func (b *DepartmentInstanceBuilder) Dependencies(value []string) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyDependencies, value)
	return b
}

// SetDependencies is a compatibility alias for Dependencies.
func (b *DepartmentInstanceBuilder) SetDependencies(value []string) *DepartmentInstanceBuilder {
	return b.Dependencies(value)
}

// DivisionRef sets the division_ref field
func (b *DepartmentInstanceBuilder) DivisionRef(value any) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyDivisionRef, value)
	return b
}

// SetDivisionRef is a compatibility alias for DivisionRef.
func (b *DepartmentInstanceBuilder) SetDivisionRef(value any) *DepartmentInstanceBuilder {
	return b.DivisionRef(value)
}

// Domain sets the domain field
func (b *DepartmentInstanceBuilder) Domain(value string) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyDomain, value)
	return b
}

// SetDomain is a compatibility alias for Domain.
func (b *DepartmentInstanceBuilder) SetDomain(value string) *DepartmentInstanceBuilder {
	return b.Domain(value)
}

// KernelGoalsRefs sets the kernel_goals_refs field
func (b *DepartmentInstanceBuilder) KernelGoalsRefs(value []string) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyKernelGoalsRefs, value)
	return b
}

// SetKernelGoalsRefs is a compatibility alias for KernelGoalsRefs.
func (b *DepartmentInstanceBuilder) SetKernelGoalsRefs(value []string) *DepartmentInstanceBuilder {
	return b.KernelGoalsRefs(value)
}

// LifecycleRef sets the lifecycle_ref field
func (b *DepartmentInstanceBuilder) LifecycleRef(value string) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyLifecycleRef, value)
	return b
}

// SetLifecycleRef is a compatibility alias for LifecycleRef.
func (b *DepartmentInstanceBuilder) SetLifecycleRef(value string) *DepartmentInstanceBuilder {
	return b.LifecycleRef(value)
}

// OriginProject sets the origin_project field
func (b *DepartmentInstanceBuilder) OriginProject(value string) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyOriginProject, value)
	return b
}

// SetOriginProject is a compatibility alias for OriginProject.
func (b *DepartmentInstanceBuilder) SetOriginProject(value string) *DepartmentInstanceBuilder {
	return b.OriginProject(value)
}

// OriginSystem sets the origin_system field
func (b *DepartmentInstanceBuilder) OriginSystem(value string) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyOriginSystem, value)
	return b
}

// SetOriginSystem is a compatibility alias for OriginSystem.
func (b *DepartmentInstanceBuilder) SetOriginSystem(value string) *DepartmentInstanceBuilder {
	return b.OriginSystem(value)
}

// PriorityTier sets the priority_tier field
func (b *DepartmentInstanceBuilder) PriorityTier(value enumv.PriorityTier) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyPriorityTier, string(value))
	return b
}

// SetPriorityTier is a compatibility alias for PriorityTier.
func (b *DepartmentInstanceBuilder) SetPriorityTier(value enumv.PriorityTier) *DepartmentInstanceBuilder {
	return b.PriorityTier(value)
}

// Questions sets the questions field
func (b *DepartmentInstanceBuilder) Questions(value []string) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyQuestions, value)
	return b
}

// SetQuestions is a compatibility alias for Questions.
func (b *DepartmentInstanceBuilder) SetQuestions(value []string) *DepartmentInstanceBuilder {
	return b.Questions(value)
}

// RelatedObjectRefs sets the related_object_refs field
func (b *DepartmentInstanceBuilder) RelatedObjectRefs(value []string) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyRelatedObjectRefs, value)
	return b
}

// SetRelatedObjectRefs is a compatibility alias for RelatedObjectRefs.
func (b *DepartmentInstanceBuilder) SetRelatedObjectRefs(value []string) *DepartmentInstanceBuilder {
	return b.RelatedObjectRefs(value)
}

// SourceType sets the source_type field
func (b *DepartmentInstanceBuilder) SourceType(value enumv.SourceType) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeySourceType, string(value))
	return b
}

// SetSourceType is a compatibility alias for SourceType.
func (b *DepartmentInstanceBuilder) SetSourceType(value enumv.SourceType) *DepartmentInstanceBuilder {
	return b.SourceType(value)
}

// SpecAdherence sets the spec_adherence field
func (b *DepartmentInstanceBuilder) SpecAdherence(value map[string]any) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeySpecAdherence, value)
	return b
}

// SetSpecAdherence is a compatibility alias for SpecAdherence.
func (b *DepartmentInstanceBuilder) SetSpecAdherence(value map[string]any) *DepartmentInstanceBuilder {
	return b.SpecAdherence(value)
}

// SpecContextBroker sets the spec_context_broker field
func (b *DepartmentInstanceBuilder) SpecContextBroker(value string) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeySpecContextBroker, value)
	return b
}

// SetSpecContextBroker is a compatibility alias for SpecContextBroker.
func (b *DepartmentInstanceBuilder) SetSpecContextBroker(value string) *DepartmentInstanceBuilder {
	return b.SpecContextBroker(value)
}

// SpecInterpreter sets the spec_interpreter field
func (b *DepartmentInstanceBuilder) SpecInterpreter(value string) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeySpecInterpreter, value)
	return b
}

// SetSpecInterpreter is a compatibility alias for SpecInterpreter.
func (b *DepartmentInstanceBuilder) SetSpecInterpreter(value string) *DepartmentInstanceBuilder {
	return b.SpecInterpreter(value)
}

// Stakeholders sets the stakeholders field
func (b *DepartmentInstanceBuilder) Stakeholders(value []string) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyStakeholders, value)
	return b
}

// SetStakeholders is a compatibility alias for Stakeholders.
func (b *DepartmentInstanceBuilder) SetStakeholders(value []string) *DepartmentInstanceBuilder {
	return b.Stakeholders(value)
}

// StatusHistory sets the status_history field
func (b *DepartmentInstanceBuilder) StatusHistory(value []string) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyStatusHistory, value)
	return b
}

// SetStatusHistory is a compatibility alias for StatusHistory.
func (b *DepartmentInstanceBuilder) SetStatusHistory(value []string) *DepartmentInstanceBuilder {
	return b.StatusHistory(value)
}

// TargetDate sets the target_date field
func (b *DepartmentInstanceBuilder) TargetDate(value string) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyTargetDate, value)
	return b
}

// SetTargetDate is a compatibility alias for TargetDate.
func (b *DepartmentInstanceBuilder) SetTargetDate(value string) *DepartmentInstanceBuilder {
	return b.TargetDate(value)
}

// Title sets the title field
func (b *DepartmentInstanceBuilder) Title(value string) *DepartmentInstanceBuilder {
	b.SetField(objects.FieldKeyTitle, value)
	return b
}

// SetTitle is a compatibility alias for Title.
func (b *DepartmentInstanceBuilder) SetTitle(value string) *DepartmentInstanceBuilder {
	return b.Title(value)
}

func init() {
	instance_builders.RegisterBuilder(NewDepartmentInstanceBuilder(objects.DefaultSchemaVersion))
}
