// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package bldr_instance_v1

import (
	"github.com/zqk-os/zqk/pkg/objects"
	enumv "github.com/zqk-os/zqk/pkg/specbuilder/bldr_enum_v1/domain_registry"
	"github.com/zqk-os/zqk/pkg/specbuilder/instance_builders"
)

// DomainRegistryInstanceBuilder builds domain_registry instances
// ONE builder handles ALL domain_registry instances
type DomainRegistryInstanceBuilder struct {
	*instance_builders.BaseInstanceBuilder
}

// NewDomainRegistryInstanceBuilder creates a new domain_registry instance builder.
// Pass the instance schema_version string for this spec; use objects.DefaultSchemaVersion for the project default (pkg/objects constants).
// Field order is derived from the spec (not hardcoded) to avoid drift
func NewDomainRegistryInstanceBuilder(schemaVersion string) *DomainRegistryInstanceBuilder {
	// Derive canonical field order from spec (follows architecture pattern)
	// System fields first, then spec-defined fields in sorted order
	fieldOrder := buildFieldOrderFromSpec("domain_registry")

	// Create base builder
	builder := &DomainRegistryInstanceBuilder{
		BaseInstanceBuilder: instance_builders.NewBaseInstanceBuilder(
			"domain_registry",
			schemaVersion,
			fieldOrder,
			nil, // spec builder (optional)
		),
	}

	return builder
}

// Status sets the status field
func (b *DomainRegistryInstanceBuilder) Status(value enumv.Status) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyStatus, string(value))
	return b
}

// ID sets the id field
func (b *DomainRegistryInstanceBuilder) ID(value string) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyID, value)
	return b
}

// ArchivedAt sets the archived_at field
func (b *DomainRegistryInstanceBuilder) ArchivedAt(value any) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedAt, value)
	return b
}

// SetArchivedAt is a compatibility alias for ArchivedAt.
func (b *DomainRegistryInstanceBuilder) SetArchivedAt(value any) *DomainRegistryInstanceBuilder {
	return b.ArchivedAt(value)
}

// ArchivedBy sets the archived_by field
func (b *DomainRegistryInstanceBuilder) ArchivedBy(value string) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedBy, value)
	return b
}

// SetArchivedBy is a compatibility alias for ArchivedBy.
func (b *DomainRegistryInstanceBuilder) SetArchivedBy(value string) *DomainRegistryInstanceBuilder {
	return b.ArchivedBy(value)
}

// Artifacts sets the artifacts field
func (b *DomainRegistryInstanceBuilder) Artifacts(value []string) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyArtifacts, value)
	return b
}

// SetArtifacts is a compatibility alias for Artifacts.
func (b *DomainRegistryInstanceBuilder) SetArtifacts(value []string) *DomainRegistryInstanceBuilder {
	return b.Artifacts(value)
}

// ChangeLog sets the change_log field
func (b *DomainRegistryInstanceBuilder) ChangeLog(value []string) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyChangeLog, value)
	return b
}

// SetChangeLog is a compatibility alias for ChangeLog.
func (b *DomainRegistryInstanceBuilder) SetChangeLog(value []string) *DomainRegistryInstanceBuilder {
	return b.ChangeLog(value)
}

// CompletenessValidation sets the completeness_validation field
func (b *DomainRegistryInstanceBuilder) CompletenessValidation(value []string) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyCompletenessValidation, value)
	return b
}

// SetCompletenessValidation is a compatibility alias for CompletenessValidation.
func (b *DomainRegistryInstanceBuilder) SetCompletenessValidation(value []string) *DomainRegistryInstanceBuilder {
	return b.CompletenessValidation(value)
}

// Context sets the context field
func (b *DomainRegistryInstanceBuilder) Context(value any) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyContext, value)
	return b
}

// SetContext is a compatibility alias for Context.
func (b *DomainRegistryInstanceBuilder) SetContext(value any) *DomainRegistryInstanceBuilder {
	return b.Context(value)
}

// Deadline sets the deadline field
func (b *DomainRegistryInstanceBuilder) Deadline(value string) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyDeadline, value)
	return b
}

// SetDeadline is a compatibility alias for Deadline.
func (b *DomainRegistryInstanceBuilder) SetDeadline(value string) *DomainRegistryInstanceBuilder {
	return b.Deadline(value)
}

// Dependencies sets the dependencies field
func (b *DomainRegistryInstanceBuilder) Dependencies(value []string) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyDependencies, value)
	return b
}

// SetDependencies is a compatibility alias for Dependencies.
func (b *DomainRegistryInstanceBuilder) SetDependencies(value []string) *DomainRegistryInstanceBuilder {
	return b.Dependencies(value)
}

// Description sets the description field
func (b *DomainRegistryInstanceBuilder) Description(value any) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyDescription, value)
	return b
}

// SetDescription is a compatibility alias for Description.
func (b *DomainRegistryInstanceBuilder) SetDescription(value any) *DomainRegistryInstanceBuilder {
	return b.Description(value)
}

// Domains sets the domains field
func (b *DomainRegistryInstanceBuilder) Domains(value []string) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyDomains, value)
	return b
}

// SetDomains is a compatibility alias for Domains.
func (b *DomainRegistryInstanceBuilder) SetDomains(value []string) *DomainRegistryInstanceBuilder {
	return b.Domains(value)
}

// OriginProject sets the origin_project field
func (b *DomainRegistryInstanceBuilder) OriginProject(value string) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyOriginProject, value)
	return b
}

// SetOriginProject is a compatibility alias for OriginProject.
func (b *DomainRegistryInstanceBuilder) SetOriginProject(value string) *DomainRegistryInstanceBuilder {
	return b.OriginProject(value)
}

// OriginSystem sets the origin_system field
func (b *DomainRegistryInstanceBuilder) OriginSystem(value string) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyOriginSystem, value)
	return b
}

// SetOriginSystem is a compatibility alias for OriginSystem.
func (b *DomainRegistryInstanceBuilder) SetOriginSystem(value string) *DomainRegistryInstanceBuilder {
	return b.OriginSystem(value)
}

// Plane sets the plane field
func (b *DomainRegistryInstanceBuilder) Plane(value enumv.Plane) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyPlane, string(value))
	return b
}

// SetPlane is a compatibility alias for Plane.
func (b *DomainRegistryInstanceBuilder) SetPlane(value enumv.Plane) *DomainRegistryInstanceBuilder {
	return b.Plane(value)
}

// PriorityTier sets the priority_tier field
func (b *DomainRegistryInstanceBuilder) PriorityTier(value enumv.PriorityTier) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyPriorityTier, string(value))
	return b
}

// SetPriorityTier is a compatibility alias for PriorityTier.
func (b *DomainRegistryInstanceBuilder) SetPriorityTier(value enumv.PriorityTier) *DomainRegistryInstanceBuilder {
	return b.PriorityTier(value)
}

// Provenance sets the provenance field
func (b *DomainRegistryInstanceBuilder) Provenance(value map[string]any) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyProvenance, value)
	return b
}

// SetProvenance is a compatibility alias for Provenance.
func (b *DomainRegistryInstanceBuilder) SetProvenance(value map[string]any) *DomainRegistryInstanceBuilder {
	return b.Provenance(value)
}

// Questions sets the questions field
func (b *DomainRegistryInstanceBuilder) Questions(value []string) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyQuestions, value)
	return b
}

// SetQuestions is a compatibility alias for Questions.
func (b *DomainRegistryInstanceBuilder) SetQuestions(value []string) *DomainRegistryInstanceBuilder {
	return b.Questions(value)
}

// RelatedObjectRefs sets the related_object_refs field
func (b *DomainRegistryInstanceBuilder) RelatedObjectRefs(value []string) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyRelatedObjectRefs, value)
	return b
}

// SetRelatedObjectRefs is a compatibility alias for RelatedObjectRefs.
func (b *DomainRegistryInstanceBuilder) SetRelatedObjectRefs(value []string) *DomainRegistryInstanceBuilder {
	return b.RelatedObjectRefs(value)
}

// SchemaRef sets the schema_ref field
func (b *DomainRegistryInstanceBuilder) SchemaRef(value string) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeySchemaRef, value)
	return b
}

// SetSchemaRef is a compatibility alias for SchemaRef.
func (b *DomainRegistryInstanceBuilder) SetSchemaRef(value string) *DomainRegistryInstanceBuilder {
	return b.SchemaRef(value)
}

// SourceType sets the source_type field
func (b *DomainRegistryInstanceBuilder) SourceType(value enumv.SourceType) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeySourceType, string(value))
	return b
}

// SetSourceType is a compatibility alias for SourceType.
func (b *DomainRegistryInstanceBuilder) SetSourceType(value enumv.SourceType) *DomainRegistryInstanceBuilder {
	return b.SourceType(value)
}

// SpecAdherence sets the spec_adherence field
func (b *DomainRegistryInstanceBuilder) SpecAdherence(value map[string]any) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeySpecAdherence, value)
	return b
}

// SetSpecAdherence is a compatibility alias for SpecAdherence.
func (b *DomainRegistryInstanceBuilder) SetSpecAdherence(value map[string]any) *DomainRegistryInstanceBuilder {
	return b.SpecAdherence(value)
}

// Stakeholders sets the stakeholders field
func (b *DomainRegistryInstanceBuilder) Stakeholders(value []string) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyStakeholders, value)
	return b
}

// SetStakeholders is a compatibility alias for Stakeholders.
func (b *DomainRegistryInstanceBuilder) SetStakeholders(value []string) *DomainRegistryInstanceBuilder {
	return b.Stakeholders(value)
}

// StatusHistory sets the status_history field
func (b *DomainRegistryInstanceBuilder) StatusHistory(value []string) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyStatusHistory, value)
	return b
}

// SetStatusHistory is a compatibility alias for StatusHistory.
func (b *DomainRegistryInstanceBuilder) SetStatusHistory(value []string) *DomainRegistryInstanceBuilder {
	return b.StatusHistory(value)
}

// TargetDate sets the target_date field
func (b *DomainRegistryInstanceBuilder) TargetDate(value string) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyTargetDate, value)
	return b
}

// SetTargetDate is a compatibility alias for TargetDate.
func (b *DomainRegistryInstanceBuilder) SetTargetDate(value string) *DomainRegistryInstanceBuilder {
	return b.TargetDate(value)
}

// Title sets the title field
func (b *DomainRegistryInstanceBuilder) Title(value string) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyTitle, value)
	return b
}

// SetTitle is a compatibility alias for Title.
func (b *DomainRegistryInstanceBuilder) SetTitle(value string) *DomainRegistryInstanceBuilder {
	return b.Title(value)
}

// Urn sets the urn field
func (b *DomainRegistryInstanceBuilder) Urn(value string) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyUrn, value)
	return b
}

// SetUrn is a compatibility alias for Urn.
func (b *DomainRegistryInstanceBuilder) SetUrn(value string) *DomainRegistryInstanceBuilder {
	return b.Urn(value)
}

// Version sets the version field
func (b *DomainRegistryInstanceBuilder) Version(value int) *DomainRegistryInstanceBuilder {
	b.SetField(objects.FieldKeyVersion, value)
	return b
}

// SetVersion is a compatibility alias for Version.
func (b *DomainRegistryInstanceBuilder) SetVersion(value int) *DomainRegistryInstanceBuilder {
	return b.Version(value)
}

func init() {
	instance_builders.RegisterBuilder(NewDomainRegistryInstanceBuilder(objects.DefaultSchemaVersion))
}
