// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec YAML.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package bldr_instance_v1

import (
	"github.com/lanceman/zqk/pkg/objects"
	enumv "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/economic_policy"
	"github.com/lanceman/zqk/pkg/specbuilder/instance_builders"
)

// EconomicPolicyInstanceBuilder builds economic_policy instances
// ONE builder handles ALL economic_policy instances
type EconomicPolicyInstanceBuilder struct {
	*instance_builders.BaseInstanceBuilder
}

// NewEconomicPolicyInstanceBuilder creates a new economic_policy instance builder.
// Pass the instance schema_version string for this spec; use objects.DefaultSchemaVersion for the project default (pkg/objects constants).
// Field order is derived from the spec (not hardcoded) to avoid drift
func NewEconomicPolicyInstanceBuilder(schemaVersion string) *EconomicPolicyInstanceBuilder {
	// Derive canonical field order from spec (follows architecture pattern)
	// System fields first, then spec-defined fields in sorted order
	fieldOrder := buildFieldOrderFromSpec("economic_policy")

	// Create base builder
	builder := &EconomicPolicyInstanceBuilder{
		BaseInstanceBuilder: instance_builders.NewBaseInstanceBuilder(
			"economic_policy",
			schemaVersion,
			fieldOrder,
			nil, // spec builder (optional)
		),
	}

	return builder
}

// Status sets the status field
func (b *EconomicPolicyInstanceBuilder) Status(value enumv.Status) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyStatus, string(value))
	return b
}

// ID sets the id field
func (b *EconomicPolicyInstanceBuilder) ID(value string) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyID, value)
	return b
}

// ActualEffort sets the actual_effort field
func (b *EconomicPolicyInstanceBuilder) ActualEffort(value string) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyActualEffort, value)
	return b
}

// SetActualEffort is a compatibility alias for ActualEffort.
func (b *EconomicPolicyInstanceBuilder) SetActualEffort(value string) *EconomicPolicyInstanceBuilder {
	return b.ActualEffort(value)
}

// AnswerDueBy sets the answer_due_by field
func (b *EconomicPolicyInstanceBuilder) AnswerDueBy(value string) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyAnswerDueBy, value)
	return b
}

// SetAnswerDueBy is a compatibility alias for AnswerDueBy.
func (b *EconomicPolicyInstanceBuilder) SetAnswerDueBy(value string) *EconomicPolicyInstanceBuilder {
	return b.AnswerDueBy(value)
}

// ArchivedAt sets the archived_at field
func (b *EconomicPolicyInstanceBuilder) ArchivedAt(value any) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedAt, value)
	return b
}

// SetArchivedAt is a compatibility alias for ArchivedAt.
func (b *EconomicPolicyInstanceBuilder) SetArchivedAt(value any) *EconomicPolicyInstanceBuilder {
	return b.ArchivedAt(value)
}

// ArchivedBy sets the archived_by field
func (b *EconomicPolicyInstanceBuilder) ArchivedBy(value string) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedBy, value)
	return b
}

// SetArchivedBy is a compatibility alias for ArchivedBy.
func (b *EconomicPolicyInstanceBuilder) SetArchivedBy(value string) *EconomicPolicyInstanceBuilder {
	return b.ArchivedBy(value)
}

// Artifacts sets the artifacts field
func (b *EconomicPolicyInstanceBuilder) Artifacts(value []string) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyArtifacts, value)
	return b
}

// SetArtifacts is a compatibility alias for Artifacts.
func (b *EconomicPolicyInstanceBuilder) SetArtifacts(value []string) *EconomicPolicyInstanceBuilder {
	return b.Artifacts(value)
}

// ChangeLog sets the change_log field
func (b *EconomicPolicyInstanceBuilder) ChangeLog(value []string) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyChangeLog, value)
	return b
}

// SetChangeLog is a compatibility alias for ChangeLog.
func (b *EconomicPolicyInstanceBuilder) SetChangeLog(value []string) *EconomicPolicyInstanceBuilder {
	return b.ChangeLog(value)
}

// CompletenessValidation sets the completeness_validation field
func (b *EconomicPolicyInstanceBuilder) CompletenessValidation(value []string) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyCompletenessValidation, value)
	return b
}

// SetCompletenessValidation is a compatibility alias for CompletenessValidation.
func (b *EconomicPolicyInstanceBuilder) SetCompletenessValidation(value []string) *EconomicPolicyInstanceBuilder {
	return b.CompletenessValidation(value)
}

// Context sets the context field
func (b *EconomicPolicyInstanceBuilder) Context(value any) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyContext, value)
	return b
}

// SetContext is a compatibility alias for Context.
func (b *EconomicPolicyInstanceBuilder) SetContext(value any) *EconomicPolicyInstanceBuilder {
	return b.Context(value)
}

// CostPerQuery sets the cost_per_query field
func (b *EconomicPolicyInstanceBuilder) CostPerQuery(value int) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyCostPerQuery, value)
	return b
}

// SetCostPerQuery is a compatibility alias for CostPerQuery.
func (b *EconomicPolicyInstanceBuilder) SetCostPerQuery(value int) *EconomicPolicyInstanceBuilder {
	return b.CostPerQuery(value)
}

// Deadline sets the deadline field
func (b *EconomicPolicyInstanceBuilder) Deadline(value string) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyDeadline, value)
	return b
}

// SetDeadline is a compatibility alias for Deadline.
func (b *EconomicPolicyInstanceBuilder) SetDeadline(value string) *EconomicPolicyInstanceBuilder {
	return b.Deadline(value)
}

// Dependencies sets the dependencies field
func (b *EconomicPolicyInstanceBuilder) Dependencies(value []string) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyDependencies, value)
	return b
}

// SetDependencies is a compatibility alias for Dependencies.
func (b *EconomicPolicyInstanceBuilder) SetDependencies(value []string) *EconomicPolicyInstanceBuilder {
	return b.Dependencies(value)
}

// EstimatedEffort sets the estimated_effort field
func (b *EconomicPolicyInstanceBuilder) EstimatedEffort(value string) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyEstimatedEffort, value)
	return b
}

// SetEstimatedEffort is a compatibility alias for EstimatedEffort.
func (b *EconomicPolicyInstanceBuilder) SetEstimatedEffort(value string) *EconomicPolicyInstanceBuilder {
	return b.EstimatedEffort(value)
}

// MaxCreditLimit sets the max_credit_limit field
func (b *EconomicPolicyInstanceBuilder) MaxCreditLimit(value int) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyMaxCreditLimit, value)
	return b
}

// SetMaxCreditLimit is a compatibility alias for MaxCreditLimit.
func (b *EconomicPolicyInstanceBuilder) SetMaxCreditLimit(value int) *EconomicPolicyInstanceBuilder {
	return b.MaxCreditLimit(value)
}

// OriginProject sets the origin_project field
func (b *EconomicPolicyInstanceBuilder) OriginProject(value string) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyOriginProject, value)
	return b
}

// SetOriginProject is a compatibility alias for OriginProject.
func (b *EconomicPolicyInstanceBuilder) SetOriginProject(value string) *EconomicPolicyInstanceBuilder {
	return b.OriginProject(value)
}

// OriginSystem sets the origin_system field
func (b *EconomicPolicyInstanceBuilder) OriginSystem(value string) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyOriginSystem, value)
	return b
}

// SetOriginSystem is a compatibility alias for OriginSystem.
func (b *EconomicPolicyInstanceBuilder) SetOriginSystem(value string) *EconomicPolicyInstanceBuilder {
	return b.OriginSystem(value)
}

// PriorityTier sets the priority_tier field
func (b *EconomicPolicyInstanceBuilder) PriorityTier(value enumv.PriorityTier) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyPriorityTier, string(value))
	return b
}

// SetPriorityTier is a compatibility alias for PriorityTier.
func (b *EconomicPolicyInstanceBuilder) SetPriorityTier(value enumv.PriorityTier) *EconomicPolicyInstanceBuilder {
	return b.PriorityTier(value)
}

// Questions sets the questions field
func (b *EconomicPolicyInstanceBuilder) Questions(value []string) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyQuestions, value)
	return b
}

// SetQuestions is a compatibility alias for Questions.
func (b *EconomicPolicyInstanceBuilder) SetQuestions(value []string) *EconomicPolicyInstanceBuilder {
	return b.Questions(value)
}

// RelatedObjectRefs sets the related_object_refs field
func (b *EconomicPolicyInstanceBuilder) RelatedObjectRefs(value []string) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyRelatedObjectRefs, value)
	return b
}

// SetRelatedObjectRefs is a compatibility alias for RelatedObjectRefs.
func (b *EconomicPolicyInstanceBuilder) SetRelatedObjectRefs(value []string) *EconomicPolicyInstanceBuilder {
	return b.RelatedObjectRefs(value)
}

// SettlementCurrency sets the settlement_currency field
func (b *EconomicPolicyInstanceBuilder) SettlementCurrency(value string) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeySettlementCurrency, value)
	return b
}

// SetSettlementCurrency is a compatibility alias for SettlementCurrency.
func (b *EconomicPolicyInstanceBuilder) SetSettlementCurrency(value string) *EconomicPolicyInstanceBuilder {
	return b.SettlementCurrency(value)
}

// SourceType sets the source_type field
func (b *EconomicPolicyInstanceBuilder) SourceType(value enumv.SourceType) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeySourceType, string(value))
	return b
}

// SetSourceType is a compatibility alias for SourceType.
func (b *EconomicPolicyInstanceBuilder) SetSourceType(value enumv.SourceType) *EconomicPolicyInstanceBuilder {
	return b.SourceType(value)
}

// SpecAdherence sets the spec_adherence field
func (b *EconomicPolicyInstanceBuilder) SpecAdherence(value map[string]any) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeySpecAdherence, value)
	return b
}

// SetSpecAdherence is a compatibility alias for SpecAdherence.
func (b *EconomicPolicyInstanceBuilder) SetSpecAdherence(value map[string]any) *EconomicPolicyInstanceBuilder {
	return b.SpecAdherence(value)
}

// Stakeholders sets the stakeholders field
func (b *EconomicPolicyInstanceBuilder) Stakeholders(value []string) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyStakeholders, value)
	return b
}

// SetStakeholders is a compatibility alias for Stakeholders.
func (b *EconomicPolicyInstanceBuilder) SetStakeholders(value []string) *EconomicPolicyInstanceBuilder {
	return b.Stakeholders(value)
}

// StatusHistory sets the status_history field
func (b *EconomicPolicyInstanceBuilder) StatusHistory(value []string) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyStatusHistory, value)
	return b
}

// SetStatusHistory is a compatibility alias for StatusHistory.
func (b *EconomicPolicyInstanceBuilder) SetStatusHistory(value []string) *EconomicPolicyInstanceBuilder {
	return b.StatusHistory(value)
}

// StorageRentPerMb sets the storage_rent_per_mb field
func (b *EconomicPolicyInstanceBuilder) StorageRentPerMb(value int) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyStorageRentPerMb, value)
	return b
}

// SetStorageRentPerMb is a compatibility alias for StorageRentPerMb.
func (b *EconomicPolicyInstanceBuilder) SetStorageRentPerMb(value int) *EconomicPolicyInstanceBuilder {
	return b.StorageRentPerMb(value)
}

// TargetDate sets the target_date field
func (b *EconomicPolicyInstanceBuilder) TargetDate(value string) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyTargetDate, value)
	return b
}

// SetTargetDate is a compatibility alias for TargetDate.
func (b *EconomicPolicyInstanceBuilder) SetTargetDate(value string) *EconomicPolicyInstanceBuilder {
	return b.TargetDate(value)
}

// Title sets the title field
func (b *EconomicPolicyInstanceBuilder) Title(value string) *EconomicPolicyInstanceBuilder {
	b.SetField(objects.FieldKeyTitle, value)
	return b
}

// SetTitle is a compatibility alias for Title.
func (b *EconomicPolicyInstanceBuilder) SetTitle(value string) *EconomicPolicyInstanceBuilder {
	return b.Title(value)
}

func init() {
	instance_builders.RegisterBuilder(NewEconomicPolicyInstanceBuilder(objects.DefaultSchemaVersion))
}
