// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package bldr_instance_v1

import (
	"github.com/zqk-os/zqk/pkg/objects"
	enumv "github.com/zqk-os/zqk/pkg/specbuilder/bldr_enum_v1/kind_synonym"
	"github.com/zqk-os/zqk/pkg/specbuilder/instance_builders"
)

// KindSynonymInstanceBuilder builds kind_synonym instances
// ONE builder handles ALL kind_synonym instances
type KindSynonymInstanceBuilder struct {
	*instance_builders.BaseInstanceBuilder
}

// NewKindSynonymInstanceBuilder creates a new kind_synonym instance builder.
// Pass the instance schema_version string for this spec; use objects.DefaultSchemaVersion for the project default (pkg/objects constants).
// Field order is derived from the spec (not hardcoded) to avoid drift
func NewKindSynonymInstanceBuilder(schemaVersion string) *KindSynonymInstanceBuilder {
	// Derive canonical field order from spec (follows architecture pattern)
	// System fields first, then spec-defined fields in sorted order
	fieldOrder := buildFieldOrderFromSpec("kind_synonym")

	// Create base builder
	builder := &KindSynonymInstanceBuilder{
		BaseInstanceBuilder: instance_builders.NewBaseInstanceBuilder(
			"kind_synonym",
			schemaVersion,
			fieldOrder,
			nil, // spec builder (optional)
		),
	}

	return builder
}

// Status sets the status field
func (b *KindSynonymInstanceBuilder) Status(value enumv.Status) *KindSynonymInstanceBuilder {
	b.SetField(objects.FieldKeyStatus, string(value))
	return b
}

// ID sets the id field
func (b *KindSynonymInstanceBuilder) ID(value string) *KindSynonymInstanceBuilder {
	b.SetField(objects.FieldKeyID, value)
	return b
}

// Convention sets the convention field
func (b *KindSynonymInstanceBuilder) Convention(value string) *KindSynonymInstanceBuilder {
	b.SetField(objects.FieldKeyConvention, value)
	return b
}

// SetConvention is a compatibility alias for Convention.
func (b *KindSynonymInstanceBuilder) SetConvention(value string) *KindSynonymInstanceBuilder {
	return b.Convention(value)
}

// Description sets the description field
func (b *KindSynonymInstanceBuilder) Description(value string) *KindSynonymInstanceBuilder {
	b.SetField(objects.FieldKeyDescription, value)
	return b
}

// SetDescription is a compatibility alias for Description.
func (b *KindSynonymInstanceBuilder) SetDescription(value string) *KindSynonymInstanceBuilder {
	return b.Description(value)
}

// Priority sets the priority field
func (b *KindSynonymInstanceBuilder) Priority(value int) *KindSynonymInstanceBuilder {
	b.SetField(objects.FieldKeyPriority, value)
	return b
}

// SetPriority is a compatibility alias for Priority.
func (b *KindSynonymInstanceBuilder) SetPriority(value int) *KindSynonymInstanceBuilder {
	return b.Priority(value)
}

// Synonym sets the synonym field
func (b *KindSynonymInstanceBuilder) Synonym(value string) *KindSynonymInstanceBuilder {
	b.SetField(objects.FieldKeySynonym, value)
	return b
}

// SetSynonym is a compatibility alias for Synonym.
func (b *KindSynonymInstanceBuilder) SetSynonym(value string) *KindSynonymInstanceBuilder {
	return b.Synonym(value)
}

// TargetKind sets the target_kind field
func (b *KindSynonymInstanceBuilder) TargetKind(value string) *KindSynonymInstanceBuilder {
	b.SetField(objects.FieldKeyTargetKind, value)
	return b
}

// SetTargetKind is a compatibility alias for TargetKind.
func (b *KindSynonymInstanceBuilder) SetTargetKind(value string) *KindSynonymInstanceBuilder {
	return b.TargetKind(value)
}

func init() {
	instance_builders.RegisterBuilder(NewKindSynonymInstanceBuilder(objects.DefaultSchemaVersion))
}
