// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package bldr_instance_v1

import (
	"github.com/lanceman/zqk/pkg/objects"
	enumv "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/object_spec"
	"github.com/lanceman/zqk/pkg/specbuilder/instance_builders"
)

// ObjectSpecInstanceBuilder builds object_spec instances
// ONE builder handles ALL object_spec instances
type ObjectSpecInstanceBuilder struct {
	*instance_builders.BaseInstanceBuilder
}

// NewObjectSpecInstanceBuilder creates a new object_spec instance builder.
// Pass the instance schema_version string for this spec; use objects.DefaultSchemaVersion for the project default (pkg/objects constants).
// Field order is derived from the spec (not hardcoded) to avoid drift
func NewObjectSpecInstanceBuilder(schemaVersion string) *ObjectSpecInstanceBuilder {
	// Derive canonical field order from spec (follows architecture pattern)
	// System fields first, then spec-defined fields in sorted order
	fieldOrder := buildFieldOrderFromSpec("object_spec")

	// Create base builder
	builder := &ObjectSpecInstanceBuilder{
		BaseInstanceBuilder: instance_builders.NewBaseInstanceBuilder(
			"object_spec",
			schemaVersion,
			fieldOrder,
			nil, // spec builder (optional)
		),
	}

	return builder
}

// Status sets the status field
func (b *ObjectSpecInstanceBuilder) Status(value enumv.Status) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeyStatus, string(value))
	return b
}

// ID sets the id field
func (b *ObjectSpecInstanceBuilder) ID(value string) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeyID, value)
	return b
}

// AnswerDueBy sets the answer_due_by field
func (b *ObjectSpecInstanceBuilder) AnswerDueBy(value string) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeyAnswerDueBy, value)
	return b
}

// SetAnswerDueBy is a compatibility alias for AnswerDueBy.
func (b *ObjectSpecInstanceBuilder) SetAnswerDueBy(value string) *ObjectSpecInstanceBuilder {
	return b.AnswerDueBy(value)
}

// ArchivedAt sets the archived_at field
func (b *ObjectSpecInstanceBuilder) ArchivedAt(value any) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedAt, value)
	return b
}

// SetArchivedAt is a compatibility alias for ArchivedAt.
func (b *ObjectSpecInstanceBuilder) SetArchivedAt(value any) *ObjectSpecInstanceBuilder {
	return b.ArchivedAt(value)
}

// ArchivedBy sets the archived_by field
func (b *ObjectSpecInstanceBuilder) ArchivedBy(value string) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedBy, value)
	return b
}

// SetArchivedBy is a compatibility alias for ArchivedBy.
func (b *ObjectSpecInstanceBuilder) SetArchivedBy(value string) *ObjectSpecInstanceBuilder {
	return b.ArchivedBy(value)
}

// Artifacts sets the artifacts field
func (b *ObjectSpecInstanceBuilder) Artifacts(value []string) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeyArtifacts, value)
	return b
}

// SetArtifacts is a compatibility alias for Artifacts.
func (b *ObjectSpecInstanceBuilder) SetArtifacts(value []string) *ObjectSpecInstanceBuilder {
	return b.Artifacts(value)
}

// ChangeLog sets the change_log field
func (b *ObjectSpecInstanceBuilder) ChangeLog(value []string) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeyChangeLog, value)
	return b
}

// SetChangeLog is a compatibility alias for ChangeLog.
func (b *ObjectSpecInstanceBuilder) SetChangeLog(value []string) *ObjectSpecInstanceBuilder {
	return b.ChangeLog(value)
}

// CompletenessValidation sets the completeness_validation field
func (b *ObjectSpecInstanceBuilder) CompletenessValidation(value []string) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeyCompletenessValidation, value)
	return b
}

// SetCompletenessValidation is a compatibility alias for CompletenessValidation.
func (b *ObjectSpecInstanceBuilder) SetCompletenessValidation(value []string) *ObjectSpecInstanceBuilder {
	return b.CompletenessValidation(value)
}

// Context sets the context field
func (b *ObjectSpecInstanceBuilder) Context(value any) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeyContext, value)
	return b
}

// SetContext is a compatibility alias for Context.
func (b *ObjectSpecInstanceBuilder) SetContext(value any) *ObjectSpecInstanceBuilder {
	return b.Context(value)
}

// Deadline sets the deadline field
func (b *ObjectSpecInstanceBuilder) Deadline(value string) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeyDeadline, value)
	return b
}

// SetDeadline is a compatibility alias for Deadline.
func (b *ObjectSpecInstanceBuilder) SetDeadline(value string) *ObjectSpecInstanceBuilder {
	return b.Deadline(value)
}

// Dependencies sets the dependencies field
func (b *ObjectSpecInstanceBuilder) Dependencies(value []string) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeyDependencies, value)
	return b
}

// SetDependencies is a compatibility alias for Dependencies.
func (b *ObjectSpecInstanceBuilder) SetDependencies(value []string) *ObjectSpecInstanceBuilder {
	return b.Dependencies(value)
}

// FilePath sets the file_path field
func (b *ObjectSpecInstanceBuilder) FilePath(value string) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeyFilePath, value)
	return b
}

// SetFilePath is a compatibility alias for FilePath.
func (b *ObjectSpecInstanceBuilder) SetFilePath(value string) *ObjectSpecInstanceBuilder {
	return b.FilePath(value)
}

// Ontology sets the ontology field
func (b *ObjectSpecInstanceBuilder) Ontology(value string) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeyOntology, value)
	return b
}

// SetOntology is a compatibility alias for Ontology.
func (b *ObjectSpecInstanceBuilder) SetOntology(value string) *ObjectSpecInstanceBuilder {
	return b.Ontology(value)
}

// OriginProject sets the origin_project field
func (b *ObjectSpecInstanceBuilder) OriginProject(value string) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeyOriginProject, value)
	return b
}

// SetOriginProject is a compatibility alias for OriginProject.
func (b *ObjectSpecInstanceBuilder) SetOriginProject(value string) *ObjectSpecInstanceBuilder {
	return b.OriginProject(value)
}

// OriginSystem sets the origin_system field
func (b *ObjectSpecInstanceBuilder) OriginSystem(value string) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeyOriginSystem, value)
	return b
}

// SetOriginSystem is a compatibility alias for OriginSystem.
func (b *ObjectSpecInstanceBuilder) SetOriginSystem(value string) *ObjectSpecInstanceBuilder {
	return b.OriginSystem(value)
}

// PriorityTier sets the priority_tier field
func (b *ObjectSpecInstanceBuilder) PriorityTier(value enumv.PriorityTier) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeyPriorityTier, string(value))
	return b
}

// SetPriorityTier is a compatibility alias for PriorityTier.
func (b *ObjectSpecInstanceBuilder) SetPriorityTier(value enumv.PriorityTier) *ObjectSpecInstanceBuilder {
	return b.PriorityTier(value)
}

// Questions sets the questions field
func (b *ObjectSpecInstanceBuilder) Questions(value []string) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeyQuestions, value)
	return b
}

// SetQuestions is a compatibility alias for Questions.
func (b *ObjectSpecInstanceBuilder) SetQuestions(value []string) *ObjectSpecInstanceBuilder {
	return b.Questions(value)
}

// RelatedObjectRefs sets the related_object_refs field
func (b *ObjectSpecInstanceBuilder) RelatedObjectRefs(value []string) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeyRelatedObjectRefs, value)
	return b
}

// SetRelatedObjectRefs is a compatibility alias for RelatedObjectRefs.
func (b *ObjectSpecInstanceBuilder) SetRelatedObjectRefs(value []string) *ObjectSpecInstanceBuilder {
	return b.RelatedObjectRefs(value)
}

// SourceType sets the source_type field
func (b *ObjectSpecInstanceBuilder) SourceType(value enumv.SourceType) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeySourceType, string(value))
	return b
}

// SetSourceType is a compatibility alias for SourceType.
func (b *ObjectSpecInstanceBuilder) SetSourceType(value enumv.SourceType) *ObjectSpecInstanceBuilder {
	return b.SourceType(value)
}

// SpecAdherence sets the spec_adherence field
func (b *ObjectSpecInstanceBuilder) SpecAdherence(value map[string]any) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeySpecAdherence, value)
	return b
}

// SetSpecAdherence is a compatibility alias for SpecAdherence.
func (b *ObjectSpecInstanceBuilder) SetSpecAdherence(value map[string]any) *ObjectSpecInstanceBuilder {
	return b.SpecAdherence(value)
}

// Stakeholders sets the stakeholders field
func (b *ObjectSpecInstanceBuilder) Stakeholders(value []string) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeyStakeholders, value)
	return b
}

// SetStakeholders is a compatibility alias for Stakeholders.
func (b *ObjectSpecInstanceBuilder) SetStakeholders(value []string) *ObjectSpecInstanceBuilder {
	return b.Stakeholders(value)
}

// StatusHistory sets the status_history field
func (b *ObjectSpecInstanceBuilder) StatusHistory(value []string) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeyStatusHistory, value)
	return b
}

// SetStatusHistory is a compatibility alias for StatusHistory.
func (b *ObjectSpecInstanceBuilder) SetStatusHistory(value []string) *ObjectSpecInstanceBuilder {
	return b.StatusHistory(value)
}

// TargetDate sets the target_date field
func (b *ObjectSpecInstanceBuilder) TargetDate(value string) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeyTargetDate, value)
	return b
}

// SetTargetDate is a compatibility alias for TargetDate.
func (b *ObjectSpecInstanceBuilder) SetTargetDate(value string) *ObjectSpecInstanceBuilder {
	return b.TargetDate(value)
}

// Title sets the title field
func (b *ObjectSpecInstanceBuilder) Title(value string) *ObjectSpecInstanceBuilder {
	b.SetField(objects.FieldKeyTitle, value)
	return b
}

// SetTitle is a compatibility alias for Title.
func (b *ObjectSpecInstanceBuilder) SetTitle(value string) *ObjectSpecInstanceBuilder {
	return b.Title(value)
}

func init() {
	instance_builders.RegisterBuilder(NewObjectSpecInstanceBuilder(objects.DefaultSchemaVersion))
}
