// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package bldr_instance_v1

import (
	"github.com/lanceman/zqk/pkg/objects"
	enumv "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/pipeline_execution"
	"github.com/lanceman/zqk/pkg/specbuilder/instance_builders"
)

// PipelineExecutionInstanceBuilder builds pipeline_execution instances
// ONE builder handles ALL pipeline_execution instances
type PipelineExecutionInstanceBuilder struct {
	*instance_builders.BaseInstanceBuilder
}

// NewPipelineExecutionInstanceBuilder creates a new pipeline_execution instance builder.
// Pass the instance schema_version string for this spec; use objects.DefaultSchemaVersion for the project default (pkg/objects constants).
// Field order is derived from the spec (not hardcoded) to avoid drift
func NewPipelineExecutionInstanceBuilder(schemaVersion string) *PipelineExecutionInstanceBuilder {
	// Derive canonical field order from spec (follows architecture pattern)
	// System fields first, then spec-defined fields in sorted order
	fieldOrder := buildFieldOrderFromSpec("pipeline_execution")

	// Create base builder
	builder := &PipelineExecutionInstanceBuilder{
		BaseInstanceBuilder: instance_builders.NewBaseInstanceBuilder(
			"pipeline_execution",
			schemaVersion,
			fieldOrder,
			nil, // spec builder (optional)
		),
	}

	return builder
}

// Status sets the status field
func (b *PipelineExecutionInstanceBuilder) Status(value enumv.Status) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyStatus, string(value))
	return b
}

// ID sets the id field
func (b *PipelineExecutionInstanceBuilder) ID(value string) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyID, value)
	return b
}

// AnswerDueBy sets the answer_due_by field
func (b *PipelineExecutionInstanceBuilder) AnswerDueBy(value string) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyAnswerDueBy, value)
	return b
}

// SetAnswerDueBy is a compatibility alias for AnswerDueBy.
func (b *PipelineExecutionInstanceBuilder) SetAnswerDueBy(value string) *PipelineExecutionInstanceBuilder {
	return b.AnswerDueBy(value)
}

// ArchivedAt sets the archived_at field
func (b *PipelineExecutionInstanceBuilder) ArchivedAt(value any) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedAt, value)
	return b
}

// SetArchivedAt is a compatibility alias for ArchivedAt.
func (b *PipelineExecutionInstanceBuilder) SetArchivedAt(value any) *PipelineExecutionInstanceBuilder {
	return b.ArchivedAt(value)
}

// ArchivedBy sets the archived_by field
func (b *PipelineExecutionInstanceBuilder) ArchivedBy(value string) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedBy, value)
	return b
}

// SetArchivedBy is a compatibility alias for ArchivedBy.
func (b *PipelineExecutionInstanceBuilder) SetArchivedBy(value string) *PipelineExecutionInstanceBuilder {
	return b.ArchivedBy(value)
}

// Artifacts sets the artifacts field
func (b *PipelineExecutionInstanceBuilder) Artifacts(value []string) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyArtifacts, value)
	return b
}

// SetArtifacts is a compatibility alias for Artifacts.
func (b *PipelineExecutionInstanceBuilder) SetArtifacts(value []string) *PipelineExecutionInstanceBuilder {
	return b.Artifacts(value)
}

// AuditTrail sets the audit_trail field
func (b *PipelineExecutionInstanceBuilder) AuditTrail(value []string) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyAuditTrail, value)
	return b
}

// SetAuditTrail is a compatibility alias for AuditTrail.
func (b *PipelineExecutionInstanceBuilder) SetAuditTrail(value []string) *PipelineExecutionInstanceBuilder {
	return b.AuditTrail(value)
}

// ChangeLog sets the change_log field
func (b *PipelineExecutionInstanceBuilder) ChangeLog(value []string) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyChangeLog, value)
	return b
}

// SetChangeLog is a compatibility alias for ChangeLog.
func (b *PipelineExecutionInstanceBuilder) SetChangeLog(value []string) *PipelineExecutionInstanceBuilder {
	return b.ChangeLog(value)
}

// CompletenessValidation sets the completeness_validation field
func (b *PipelineExecutionInstanceBuilder) CompletenessValidation(value []string) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyCompletenessValidation, value)
	return b
}

// SetCompletenessValidation is a compatibility alias for CompletenessValidation.
func (b *PipelineExecutionInstanceBuilder) SetCompletenessValidation(value []string) *PipelineExecutionInstanceBuilder {
	return b.CompletenessValidation(value)
}

// Context sets the context field
func (b *PipelineExecutionInstanceBuilder) Context(value any) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyContext, value)
	return b
}

// SetContext is a compatibility alias for Context.
func (b *PipelineExecutionInstanceBuilder) SetContext(value any) *PipelineExecutionInstanceBuilder {
	return b.Context(value)
}

// ContextPayload sets the context_payload field
func (b *PipelineExecutionInstanceBuilder) ContextPayload(value map[string]any) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyContextPayload, value)
	return b
}

// SetContextPayload is a compatibility alias for ContextPayload.
func (b *PipelineExecutionInstanceBuilder) SetContextPayload(value map[string]any) *PipelineExecutionInstanceBuilder {
	return b.ContextPayload(value)
}

// CurrentStage sets the current_stage field
func (b *PipelineExecutionInstanceBuilder) CurrentStage(value string) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyCurrentStage, value)
	return b
}

// SetCurrentStage is a compatibility alias for CurrentStage.
func (b *PipelineExecutionInstanceBuilder) SetCurrentStage(value string) *PipelineExecutionInstanceBuilder {
	return b.CurrentStage(value)
}

// Deadline sets the deadline field
func (b *PipelineExecutionInstanceBuilder) Deadline(value string) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyDeadline, value)
	return b
}

// SetDeadline is a compatibility alias for Deadline.
func (b *PipelineExecutionInstanceBuilder) SetDeadline(value string) *PipelineExecutionInstanceBuilder {
	return b.Deadline(value)
}

// DefinitionRef sets the definition_ref field
func (b *PipelineExecutionInstanceBuilder) DefinitionRef(value string) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyDefinitionRef, value)
	return b
}

// SetDefinitionRef is a compatibility alias for DefinitionRef.
func (b *PipelineExecutionInstanceBuilder) SetDefinitionRef(value string) *PipelineExecutionInstanceBuilder {
	return b.DefinitionRef(value)
}

// Dependencies sets the dependencies field
func (b *PipelineExecutionInstanceBuilder) Dependencies(value []string) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyDependencies, value)
	return b
}

// SetDependencies is a compatibility alias for Dependencies.
func (b *PipelineExecutionInstanceBuilder) SetDependencies(value []string) *PipelineExecutionInstanceBuilder {
	return b.Dependencies(value)
}

// OriginProject sets the origin_project field
func (b *PipelineExecutionInstanceBuilder) OriginProject(value string) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyOriginProject, value)
	return b
}

// SetOriginProject is a compatibility alias for OriginProject.
func (b *PipelineExecutionInstanceBuilder) SetOriginProject(value string) *PipelineExecutionInstanceBuilder {
	return b.OriginProject(value)
}

// OriginSystem sets the origin_system field
func (b *PipelineExecutionInstanceBuilder) OriginSystem(value string) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyOriginSystem, value)
	return b
}

// SetOriginSystem is a compatibility alias for OriginSystem.
func (b *PipelineExecutionInstanceBuilder) SetOriginSystem(value string) *PipelineExecutionInstanceBuilder {
	return b.OriginSystem(value)
}

// PriorityTier sets the priority_tier field
func (b *PipelineExecutionInstanceBuilder) PriorityTier(value enumv.PriorityTier) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyPriorityTier, string(value))
	return b
}

// SetPriorityTier is a compatibility alias for PriorityTier.
func (b *PipelineExecutionInstanceBuilder) SetPriorityTier(value enumv.PriorityTier) *PipelineExecutionInstanceBuilder {
	return b.PriorityTier(value)
}

// Questions sets the questions field
func (b *PipelineExecutionInstanceBuilder) Questions(value []string) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyQuestions, value)
	return b
}

// SetQuestions is a compatibility alias for Questions.
func (b *PipelineExecutionInstanceBuilder) SetQuestions(value []string) *PipelineExecutionInstanceBuilder {
	return b.Questions(value)
}

// RelatedObjectRefs sets the related_object_refs field
func (b *PipelineExecutionInstanceBuilder) RelatedObjectRefs(value []string) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyRelatedObjectRefs, value)
	return b
}

// SetRelatedObjectRefs is a compatibility alias for RelatedObjectRefs.
func (b *PipelineExecutionInstanceBuilder) SetRelatedObjectRefs(value []string) *PipelineExecutionInstanceBuilder {
	return b.RelatedObjectRefs(value)
}

// SourceType sets the source_type field
func (b *PipelineExecutionInstanceBuilder) SourceType(value enumv.SourceType) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeySourceType, string(value))
	return b
}

// SetSourceType is a compatibility alias for SourceType.
func (b *PipelineExecutionInstanceBuilder) SetSourceType(value enumv.SourceType) *PipelineExecutionInstanceBuilder {
	return b.SourceType(value)
}

// SpecAdherence sets the spec_adherence field
func (b *PipelineExecutionInstanceBuilder) SpecAdherence(value map[string]any) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeySpecAdherence, value)
	return b
}

// SetSpecAdherence is a compatibility alias for SpecAdherence.
func (b *PipelineExecutionInstanceBuilder) SetSpecAdherence(value map[string]any) *PipelineExecutionInstanceBuilder {
	return b.SpecAdherence(value)
}

// Stakeholders sets the stakeholders field
func (b *PipelineExecutionInstanceBuilder) Stakeholders(value []string) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyStakeholders, value)
	return b
}

// SetStakeholders is a compatibility alias for Stakeholders.
func (b *PipelineExecutionInstanceBuilder) SetStakeholders(value []string) *PipelineExecutionInstanceBuilder {
	return b.Stakeholders(value)
}

// StatusHistory sets the status_history field
func (b *PipelineExecutionInstanceBuilder) StatusHistory(value []string) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyStatusHistory, value)
	return b
}

// SetStatusHistory is a compatibility alias for StatusHistory.
func (b *PipelineExecutionInstanceBuilder) SetStatusHistory(value []string) *PipelineExecutionInstanceBuilder {
	return b.StatusHistory(value)
}

// TargetDate sets the target_date field
func (b *PipelineExecutionInstanceBuilder) TargetDate(value string) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyTargetDate, value)
	return b
}

// SetTargetDate is a compatibility alias for TargetDate.
func (b *PipelineExecutionInstanceBuilder) SetTargetDate(value string) *PipelineExecutionInstanceBuilder {
	return b.TargetDate(value)
}

// Title sets the title field
func (b *PipelineExecutionInstanceBuilder) Title(value string) *PipelineExecutionInstanceBuilder {
	b.SetField(objects.FieldKeyTitle, value)
	return b
}

// SetTitle is a compatibility alias for Title.
func (b *PipelineExecutionInstanceBuilder) SetTitle(value string) *PipelineExecutionInstanceBuilder {
	return b.Title(value)
}

func init() {
	instance_builders.RegisterBuilder(NewPipelineExecutionInstanceBuilder(objects.DefaultSchemaVersion))
}
