// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec YAML.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package bldr_instance_v1

import (
	"github.com/lanceman/zqk/pkg/objects"
	enumv "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/rule"
	"github.com/lanceman/zqk/pkg/specbuilder/instance_builders"
)

// RuleInstanceBuilder builds rule instances
// ONE builder handles ALL rule instances
type RuleInstanceBuilder struct {
	*instance_builders.BaseInstanceBuilder
}

// NewRuleInstanceBuilder creates a new rule instance builder.
// Pass the instance schema_version string for this spec; use objects.DefaultSchemaVersion for the project default (pkg/objects constants).
// Field order is derived from the spec (not hardcoded) to avoid drift
func NewRuleInstanceBuilder(schemaVersion string) *RuleInstanceBuilder {
	// Derive canonical field order from spec (follows architecture pattern)
	// System fields first, then spec-defined fields in sorted order
	fieldOrder := buildFieldOrderFromSpec("rule")

	// Create base builder
	builder := &RuleInstanceBuilder{
		BaseInstanceBuilder: instance_builders.NewBaseInstanceBuilder(
			"rule",
			schemaVersion,
			fieldOrder,
			nil, // spec builder (optional)
		),
	}

	return builder
}

// Status sets the status field
func (b *RuleInstanceBuilder) Status(value enumv.Status) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyStatus, string(value))
	return b
}

// ID sets the id field
func (b *RuleInstanceBuilder) ID(value string) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyID, value)
	return b
}

// ActualEffort sets the actual_effort field
func (b *RuleInstanceBuilder) ActualEffort(value string) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyActualEffort, value)
	return b
}

// SetActualEffort is a compatibility alias for ActualEffort.
func (b *RuleInstanceBuilder) SetActualEffort(value string) *RuleInstanceBuilder {
	return b.ActualEffort(value)
}

// AnswerDueBy sets the answer_due_by field
func (b *RuleInstanceBuilder) AnswerDueBy(value string) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyAnswerDueBy, value)
	return b
}

// SetAnswerDueBy is a compatibility alias for AnswerDueBy.
func (b *RuleInstanceBuilder) SetAnswerDueBy(value string) *RuleInstanceBuilder {
	return b.AnswerDueBy(value)
}

// ArchivedAt sets the archived_at field
func (b *RuleInstanceBuilder) ArchivedAt(value any) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedAt, value)
	return b
}

// SetArchivedAt is a compatibility alias for ArchivedAt.
func (b *RuleInstanceBuilder) SetArchivedAt(value any) *RuleInstanceBuilder {
	return b.ArchivedAt(value)
}

// ArchivedBy sets the archived_by field
func (b *RuleInstanceBuilder) ArchivedBy(value string) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedBy, value)
	return b
}

// SetArchivedBy is a compatibility alias for ArchivedBy.
func (b *RuleInstanceBuilder) SetArchivedBy(value string) *RuleInstanceBuilder {
	return b.ArchivedBy(value)
}

// Artifacts sets the artifacts field
func (b *RuleInstanceBuilder) Artifacts(value []string) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyArtifacts, value)
	return b
}

// SetArtifacts is a compatibility alias for Artifacts.
func (b *RuleInstanceBuilder) SetArtifacts(value []string) *RuleInstanceBuilder {
	return b.Artifacts(value)
}

// Body sets the body field
func (b *RuleInstanceBuilder) Body(value any) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyBody, value)
	return b
}

// SetBody is a compatibility alias for Body.
func (b *RuleInstanceBuilder) SetBody(value any) *RuleInstanceBuilder {
	return b.Body(value)
}

// ChangeLog sets the change_log field
func (b *RuleInstanceBuilder) ChangeLog(value []string) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyChangeLog, value)
	return b
}

// SetChangeLog is a compatibility alias for ChangeLog.
func (b *RuleInstanceBuilder) SetChangeLog(value []string) *RuleInstanceBuilder {
	return b.ChangeLog(value)
}

// CompletenessValidation sets the completeness_validation field
func (b *RuleInstanceBuilder) CompletenessValidation(value []string) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyCompletenessValidation, value)
	return b
}

// SetCompletenessValidation is a compatibility alias for CompletenessValidation.
func (b *RuleInstanceBuilder) SetCompletenessValidation(value []string) *RuleInstanceBuilder {
	return b.CompletenessValidation(value)
}

// Context sets the context field
func (b *RuleInstanceBuilder) Context(value any) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyContext, value)
	return b
}

// SetContext is a compatibility alias for Context.
func (b *RuleInstanceBuilder) SetContext(value any) *RuleInstanceBuilder {
	return b.Context(value)
}

// Deadline sets the deadline field
func (b *RuleInstanceBuilder) Deadline(value string) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyDeadline, value)
	return b
}

// SetDeadline is a compatibility alias for Deadline.
func (b *RuleInstanceBuilder) SetDeadline(value string) *RuleInstanceBuilder {
	return b.Deadline(value)
}

// Dependencies sets the dependencies field
func (b *RuleInstanceBuilder) Dependencies(value []string) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyDependencies, value)
	return b
}

// SetDependencies is a compatibility alias for Dependencies.
func (b *RuleInstanceBuilder) SetDependencies(value []string) *RuleInstanceBuilder {
	return b.Dependencies(value)
}

// EstimatedEffort sets the estimated_effort field
func (b *RuleInstanceBuilder) EstimatedEffort(value string) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyEstimatedEffort, value)
	return b
}

// SetEstimatedEffort is a compatibility alias for EstimatedEffort.
func (b *RuleInstanceBuilder) SetEstimatedEffort(value string) *RuleInstanceBuilder {
	return b.EstimatedEffort(value)
}

// GoalRefs sets the goal_refs field
func (b *RuleInstanceBuilder) GoalRefs(value []string) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyGoalRefs, value)
	return b
}

// SetGoalRefs is a compatibility alias for GoalRefs.
func (b *RuleInstanceBuilder) SetGoalRefs(value []string) *RuleInstanceBuilder {
	return b.GoalRefs(value)
}

// OriginProject sets the origin_project field
func (b *RuleInstanceBuilder) OriginProject(value string) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyOriginProject, value)
	return b
}

// SetOriginProject is a compatibility alias for OriginProject.
func (b *RuleInstanceBuilder) SetOriginProject(value string) *RuleInstanceBuilder {
	return b.OriginProject(value)
}

// OriginSystem sets the origin_system field
func (b *RuleInstanceBuilder) OriginSystem(value string) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyOriginSystem, value)
	return b
}

// SetOriginSystem is a compatibility alias for OriginSystem.
func (b *RuleInstanceBuilder) SetOriginSystem(value string) *RuleInstanceBuilder {
	return b.OriginSystem(value)
}

// PriorityTier sets the priority_tier field
func (b *RuleInstanceBuilder) PriorityTier(value enumv.PriorityTier) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyPriorityTier, string(value))
	return b
}

// SetPriorityTier is a compatibility alias for PriorityTier.
func (b *RuleInstanceBuilder) SetPriorityTier(value enumv.PriorityTier) *RuleInstanceBuilder {
	return b.PriorityTier(value)
}

// Questions sets the questions field
func (b *RuleInstanceBuilder) Questions(value []string) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyQuestions, value)
	return b
}

// SetQuestions is a compatibility alias for Questions.
func (b *RuleInstanceBuilder) SetQuestions(value []string) *RuleInstanceBuilder {
	return b.Questions(value)
}

// RelatedObjectRefs sets the related_object_refs field
func (b *RuleInstanceBuilder) RelatedObjectRefs(value []string) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyRelatedObjectRefs, value)
	return b
}

// SetRelatedObjectRefs is a compatibility alias for RelatedObjectRefs.
func (b *RuleInstanceBuilder) SetRelatedObjectRefs(value []string) *RuleInstanceBuilder {
	return b.RelatedObjectRefs(value)
}

// Scope sets the scope field
func (b *RuleInstanceBuilder) Scope(value string) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyScope, value)
	return b
}

// SetScope is a compatibility alias for Scope.
func (b *RuleInstanceBuilder) SetScope(value string) *RuleInstanceBuilder {
	return b.Scope(value)
}

// SourceType sets the source_type field
func (b *RuleInstanceBuilder) SourceType(value enumv.SourceType) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeySourceType, string(value))
	return b
}

// SetSourceType is a compatibility alias for SourceType.
func (b *RuleInstanceBuilder) SetSourceType(value enumv.SourceType) *RuleInstanceBuilder {
	return b.SourceType(value)
}

// SpecAdherence sets the spec_adherence field
func (b *RuleInstanceBuilder) SpecAdherence(value map[string]any) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeySpecAdherence, value)
	return b
}

// SetSpecAdherence is a compatibility alias for SpecAdherence.
func (b *RuleInstanceBuilder) SetSpecAdherence(value map[string]any) *RuleInstanceBuilder {
	return b.SpecAdherence(value)
}

// Stakeholders sets the stakeholders field
func (b *RuleInstanceBuilder) Stakeholders(value []string) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyStakeholders, value)
	return b
}

// SetStakeholders is a compatibility alias for Stakeholders.
func (b *RuleInstanceBuilder) SetStakeholders(value []string) *RuleInstanceBuilder {
	return b.Stakeholders(value)
}

// StatusHistory sets the status_history field
func (b *RuleInstanceBuilder) StatusHistory(value []string) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyStatusHistory, value)
	return b
}

// SetStatusHistory is a compatibility alias for StatusHistory.
func (b *RuleInstanceBuilder) SetStatusHistory(value []string) *RuleInstanceBuilder {
	return b.StatusHistory(value)
}

// TargetDate sets the target_date field
func (b *RuleInstanceBuilder) TargetDate(value string) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyTargetDate, value)
	return b
}

// SetTargetDate is a compatibility alias for TargetDate.
func (b *RuleInstanceBuilder) SetTargetDate(value string) *RuleInstanceBuilder {
	return b.TargetDate(value)
}

// Title sets the title field
func (b *RuleInstanceBuilder) Title(value string) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyTitle, value)
	return b
}

// SetTitle is a compatibility alias for Title.
func (b *RuleInstanceBuilder) SetTitle(value string) *RuleInstanceBuilder {
	return b.Title(value)
}

// Type sets the type field
func (b *RuleInstanceBuilder) Type(value enumv.Type) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyType, string(value))
	return b
}

// SetType is a compatibility alias for Type.
func (b *RuleInstanceBuilder) SetType(value enumv.Type) *RuleInstanceBuilder {
	return b.Type(value)
}

// WorkstreamRefs sets the workstream_refs field
func (b *RuleInstanceBuilder) WorkstreamRefs(value []string) *RuleInstanceBuilder {
	b.SetField(objects.FieldKeyWorkstreamRefs, value)
	return b
}

// SetWorkstreamRefs is a compatibility alias for WorkstreamRefs.
func (b *RuleInstanceBuilder) SetWorkstreamRefs(value []string) *RuleInstanceBuilder {
	return b.WorkstreamRefs(value)
}

func init() {
	instance_builders.RegisterBuilder(NewRuleInstanceBuilder(objects.DefaultSchemaVersion))
}
