// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec YAML.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package bldr_instance_v1

import (
	"github.com/lanceman/zqk/pkg/objects"
	enumv "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/shockwave_router"
	"github.com/lanceman/zqk/pkg/specbuilder/instance_builders"
)

// ShockwaveRouterInstanceBuilder builds shockwave_router instances
// ONE builder handles ALL shockwave_router instances
type ShockwaveRouterInstanceBuilder struct {
	*instance_builders.BaseInstanceBuilder
}

// NewShockwaveRouterInstanceBuilder creates a new shockwave_router instance builder.
// Pass the instance schema_version string for this spec; use objects.DefaultSchemaVersion for the project default (pkg/objects constants).
// Field order is derived from the spec (not hardcoded) to avoid drift
func NewShockwaveRouterInstanceBuilder(schemaVersion string) *ShockwaveRouterInstanceBuilder {
	// Derive canonical field order from spec (follows architecture pattern)
	// System fields first, then spec-defined fields in sorted order
	fieldOrder := buildFieldOrderFromSpec("shockwave_router")

	// Create base builder
	builder := &ShockwaveRouterInstanceBuilder{
		BaseInstanceBuilder: instance_builders.NewBaseInstanceBuilder(
			"shockwave_router",
			schemaVersion,
			fieldOrder,
			nil, // spec builder (optional)
		),
	}

	return builder
}

// Status sets the status field
func (b *ShockwaveRouterInstanceBuilder) Status(value enumv.Status) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyStatus, string(value))
	return b
}

// ID sets the id field
func (b *ShockwaveRouterInstanceBuilder) ID(value string) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyID, value)
	return b
}

// ActualEffort sets the actual_effort field
func (b *ShockwaveRouterInstanceBuilder) ActualEffort(value string) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyActualEffort, value)
	return b
}

// SetActualEffort is a compatibility alias for ActualEffort.
func (b *ShockwaveRouterInstanceBuilder) SetActualEffort(value string) *ShockwaveRouterInstanceBuilder {
	return b.ActualEffort(value)
}

// AnswerDueBy sets the answer_due_by field
func (b *ShockwaveRouterInstanceBuilder) AnswerDueBy(value string) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyAnswerDueBy, value)
	return b
}

// SetAnswerDueBy is a compatibility alias for AnswerDueBy.
func (b *ShockwaveRouterInstanceBuilder) SetAnswerDueBy(value string) *ShockwaveRouterInstanceBuilder {
	return b.AnswerDueBy(value)
}

// ArchivedAt sets the archived_at field
func (b *ShockwaveRouterInstanceBuilder) ArchivedAt(value any) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedAt, value)
	return b
}

// SetArchivedAt is a compatibility alias for ArchivedAt.
func (b *ShockwaveRouterInstanceBuilder) SetArchivedAt(value any) *ShockwaveRouterInstanceBuilder {
	return b.ArchivedAt(value)
}

// ArchivedBy sets the archived_by field
func (b *ShockwaveRouterInstanceBuilder) ArchivedBy(value string) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedBy, value)
	return b
}

// SetArchivedBy is a compatibility alias for ArchivedBy.
func (b *ShockwaveRouterInstanceBuilder) SetArchivedBy(value string) *ShockwaveRouterInstanceBuilder {
	return b.ArchivedBy(value)
}

// Artifacts sets the artifacts field
func (b *ShockwaveRouterInstanceBuilder) Artifacts(value []string) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyArtifacts, value)
	return b
}

// SetArtifacts is a compatibility alias for Artifacts.
func (b *ShockwaveRouterInstanceBuilder) SetArtifacts(value []string) *ShockwaveRouterInstanceBuilder {
	return b.Artifacts(value)
}

// ChangeLog sets the change_log field
func (b *ShockwaveRouterInstanceBuilder) ChangeLog(value []string) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyChangeLog, value)
	return b
}

// SetChangeLog is a compatibility alias for ChangeLog.
func (b *ShockwaveRouterInstanceBuilder) SetChangeLog(value []string) *ShockwaveRouterInstanceBuilder {
	return b.ChangeLog(value)
}

// CompletenessValidation sets the completeness_validation field
func (b *ShockwaveRouterInstanceBuilder) CompletenessValidation(value []string) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyCompletenessValidation, value)
	return b
}

// SetCompletenessValidation is a compatibility alias for CompletenessValidation.
func (b *ShockwaveRouterInstanceBuilder) SetCompletenessValidation(value []string) *ShockwaveRouterInstanceBuilder {
	return b.CompletenessValidation(value)
}

// Context sets the context field
func (b *ShockwaveRouterInstanceBuilder) Context(value any) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyContext, value)
	return b
}

// SetContext is a compatibility alias for Context.
func (b *ShockwaveRouterInstanceBuilder) SetContext(value any) *ShockwaveRouterInstanceBuilder {
	return b.Context(value)
}

// Deadline sets the deadline field
func (b *ShockwaveRouterInstanceBuilder) Deadline(value string) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyDeadline, value)
	return b
}

// SetDeadline is a compatibility alias for Deadline.
func (b *ShockwaveRouterInstanceBuilder) SetDeadline(value string) *ShockwaveRouterInstanceBuilder {
	return b.Deadline(value)
}

// Dependencies sets the dependencies field
func (b *ShockwaveRouterInstanceBuilder) Dependencies(value []string) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyDependencies, value)
	return b
}

// SetDependencies is a compatibility alias for Dependencies.
func (b *ShockwaveRouterInstanceBuilder) SetDependencies(value []string) *ShockwaveRouterInstanceBuilder {
	return b.Dependencies(value)
}

// EstimatedEffort sets the estimated_effort field
func (b *ShockwaveRouterInstanceBuilder) EstimatedEffort(value string) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyEstimatedEffort, value)
	return b
}

// SetEstimatedEffort is a compatibility alias for EstimatedEffort.
func (b *ShockwaveRouterInstanceBuilder) SetEstimatedEffort(value string) *ShockwaveRouterInstanceBuilder {
	return b.EstimatedEffort(value)
}

// OriginProject sets the origin_project field
func (b *ShockwaveRouterInstanceBuilder) OriginProject(value string) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyOriginProject, value)
	return b
}

// SetOriginProject is a compatibility alias for OriginProject.
func (b *ShockwaveRouterInstanceBuilder) SetOriginProject(value string) *ShockwaveRouterInstanceBuilder {
	return b.OriginProject(value)
}

// OriginSystem sets the origin_system field
func (b *ShockwaveRouterInstanceBuilder) OriginSystem(value string) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyOriginSystem, value)
	return b
}

// SetOriginSystem is a compatibility alias for OriginSystem.
func (b *ShockwaveRouterInstanceBuilder) SetOriginSystem(value string) *ShockwaveRouterInstanceBuilder {
	return b.OriginSystem(value)
}

// PriorityTier sets the priority_tier field
func (b *ShockwaveRouterInstanceBuilder) PriorityTier(value enumv.PriorityTier) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyPriorityTier, string(value))
	return b
}

// SetPriorityTier is a compatibility alias for PriorityTier.
func (b *ShockwaveRouterInstanceBuilder) SetPriorityTier(value enumv.PriorityTier) *ShockwaveRouterInstanceBuilder {
	return b.PriorityTier(value)
}

// PropagationRules sets the propagation_rules field
func (b *ShockwaveRouterInstanceBuilder) PropagationRules(value map[string]any) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyPropagationRules, value)
	return b
}

// SetPropagationRules is a compatibility alias for PropagationRules.
func (b *ShockwaveRouterInstanceBuilder) SetPropagationRules(value map[string]any) *ShockwaveRouterInstanceBuilder {
	return b.PropagationRules(value)
}

// Questions sets the questions field
func (b *ShockwaveRouterInstanceBuilder) Questions(value []string) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyQuestions, value)
	return b
}

// SetQuestions is a compatibility alias for Questions.
func (b *ShockwaveRouterInstanceBuilder) SetQuestions(value []string) *ShockwaveRouterInstanceBuilder {
	return b.Questions(value)
}

// ReduceStrategy sets the reduce_strategy field
func (b *ShockwaveRouterInstanceBuilder) ReduceStrategy(value map[string]any) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyReduceStrategy, value)
	return b
}

// SetReduceStrategy is a compatibility alias for ReduceStrategy.
func (b *ShockwaveRouterInstanceBuilder) SetReduceStrategy(value map[string]any) *ShockwaveRouterInstanceBuilder {
	return b.ReduceStrategy(value)
}

// RelatedObjectRefs sets the related_object_refs field
func (b *ShockwaveRouterInstanceBuilder) RelatedObjectRefs(value []string) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyRelatedObjectRefs, value)
	return b
}

// SetRelatedObjectRefs is a compatibility alias for RelatedObjectRefs.
func (b *ShockwaveRouterInstanceBuilder) SetRelatedObjectRefs(value []string) *ShockwaveRouterInstanceBuilder {
	return b.RelatedObjectRefs(value)
}

// SourceType sets the source_type field
func (b *ShockwaveRouterInstanceBuilder) SourceType(value enumv.SourceType) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeySourceType, string(value))
	return b
}

// SetSourceType is a compatibility alias for SourceType.
func (b *ShockwaveRouterInstanceBuilder) SetSourceType(value enumv.SourceType) *ShockwaveRouterInstanceBuilder {
	return b.SourceType(value)
}

// SpecAdherence sets the spec_adherence field
func (b *ShockwaveRouterInstanceBuilder) SpecAdherence(value map[string]any) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeySpecAdherence, value)
	return b
}

// SetSpecAdherence is a compatibility alias for SpecAdherence.
func (b *ShockwaveRouterInstanceBuilder) SetSpecAdherence(value map[string]any) *ShockwaveRouterInstanceBuilder {
	return b.SpecAdherence(value)
}

// Stakeholders sets the stakeholders field
func (b *ShockwaveRouterInstanceBuilder) Stakeholders(value []string) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyStakeholders, value)
	return b
}

// SetStakeholders is a compatibility alias for Stakeholders.
func (b *ShockwaveRouterInstanceBuilder) SetStakeholders(value []string) *ShockwaveRouterInstanceBuilder {
	return b.Stakeholders(value)
}

// StatusHistory sets the status_history field
func (b *ShockwaveRouterInstanceBuilder) StatusHistory(value []string) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyStatusHistory, value)
	return b
}

// SetStatusHistory is a compatibility alias for StatusHistory.
func (b *ShockwaveRouterInstanceBuilder) SetStatusHistory(value []string) *ShockwaveRouterInstanceBuilder {
	return b.StatusHistory(value)
}

// TargetDate sets the target_date field
func (b *ShockwaveRouterInstanceBuilder) TargetDate(value string) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyTargetDate, value)
	return b
}

// SetTargetDate is a compatibility alias for TargetDate.
func (b *ShockwaveRouterInstanceBuilder) SetTargetDate(value string) *ShockwaveRouterInstanceBuilder {
	return b.TargetDate(value)
}

// Title sets the title field
func (b *ShockwaveRouterInstanceBuilder) Title(value string) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyTitle, value)
	return b
}

// SetTitle is a compatibility alias for Title.
func (b *ShockwaveRouterInstanceBuilder) SetTitle(value string) *ShockwaveRouterInstanceBuilder {
	return b.Title(value)
}

// TriggerCondition sets the trigger_condition field
func (b *ShockwaveRouterInstanceBuilder) TriggerCondition(value map[string]any) *ShockwaveRouterInstanceBuilder {
	b.SetField(objects.FieldKeyTriggerCondition, value)
	return b
}

// SetTriggerCondition is a compatibility alias for TriggerCondition.
func (b *ShockwaveRouterInstanceBuilder) SetTriggerCondition(value map[string]any) *ShockwaveRouterInstanceBuilder {
	return b.TriggerCondition(value)
}

func init() {
	instance_builders.RegisterBuilder(NewShockwaveRouterInstanceBuilder(objects.DefaultSchemaVersion))
}
