// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package bldr_instance_v1

import (
	"github.com/lanceman/zqk/pkg/objects"
	enumv "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/team"
	"github.com/lanceman/zqk/pkg/specbuilder/instance_builders"
)

// TeamInstanceBuilder builds team instances
// ONE builder handles ALL team instances
type TeamInstanceBuilder struct {
	*instance_builders.BaseInstanceBuilder
}

// NewTeamInstanceBuilder creates a new team instance builder.
// Pass the instance schema_version string for this spec; use objects.DefaultSchemaVersion for the project default (pkg/objects constants).
// Field order is derived from the spec (not hardcoded) to avoid drift
func NewTeamInstanceBuilder(schemaVersion string) *TeamInstanceBuilder {
	// Derive canonical field order from spec (follows architecture pattern)
	// System fields first, then spec-defined fields in sorted order
	fieldOrder := buildFieldOrderFromSpec("team")

	// Create base builder
	builder := &TeamInstanceBuilder{
		BaseInstanceBuilder: instance_builders.NewBaseInstanceBuilder(
			"team",
			schemaVersion,
			fieldOrder,
			nil, // spec builder (optional)
		),
	}

	return builder
}

// Status sets the status field
func (b *TeamInstanceBuilder) Status(value enumv.Status) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyStatus, string(value))
	return b
}

// ID sets the id field
func (b *TeamInstanceBuilder) ID(value string) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyID, value)
	return b
}

// AnswerDueBy sets the answer_due_by field
func (b *TeamInstanceBuilder) AnswerDueBy(value string) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyAnswerDueBy, value)
	return b
}

// SetAnswerDueBy is a compatibility alias for AnswerDueBy.
func (b *TeamInstanceBuilder) SetAnswerDueBy(value string) *TeamInstanceBuilder {
	return b.AnswerDueBy(value)
}

// ArchivedAt sets the archived_at field
func (b *TeamInstanceBuilder) ArchivedAt(value any) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedAt, value)
	return b
}

// SetArchivedAt is a compatibility alias for ArchivedAt.
func (b *TeamInstanceBuilder) SetArchivedAt(value any) *TeamInstanceBuilder {
	return b.ArchivedAt(value)
}

// ArchivedBy sets the archived_by field
func (b *TeamInstanceBuilder) ArchivedBy(value string) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedBy, value)
	return b
}

// SetArchivedBy is a compatibility alias for ArchivedBy.
func (b *TeamInstanceBuilder) SetArchivedBy(value string) *TeamInstanceBuilder {
	return b.ArchivedBy(value)
}

// Artifacts sets the artifacts field
func (b *TeamInstanceBuilder) Artifacts(value []string) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyArtifacts, value)
	return b
}

// SetArtifacts is a compatibility alias for Artifacts.
func (b *TeamInstanceBuilder) SetArtifacts(value []string) *TeamInstanceBuilder {
	return b.Artifacts(value)
}

// ChangeLog sets the change_log field
func (b *TeamInstanceBuilder) ChangeLog(value []string) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyChangeLog, value)
	return b
}

// SetChangeLog is a compatibility alias for ChangeLog.
func (b *TeamInstanceBuilder) SetChangeLog(value []string) *TeamInstanceBuilder {
	return b.ChangeLog(value)
}

// CompletenessValidation sets the completeness_validation field
func (b *TeamInstanceBuilder) CompletenessValidation(value []string) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyCompletenessValidation, value)
	return b
}

// SetCompletenessValidation is a compatibility alias for CompletenessValidation.
func (b *TeamInstanceBuilder) SetCompletenessValidation(value []string) *TeamInstanceBuilder {
	return b.CompletenessValidation(value)
}

// Context sets the context field
func (b *TeamInstanceBuilder) Context(value any) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyContext, value)
	return b
}

// SetContext is a compatibility alias for Context.
func (b *TeamInstanceBuilder) SetContext(value any) *TeamInstanceBuilder {
	return b.Context(value)
}

// Deadline sets the deadline field
func (b *TeamInstanceBuilder) Deadline(value string) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyDeadline, value)
	return b
}

// SetDeadline is a compatibility alias for Deadline.
func (b *TeamInstanceBuilder) SetDeadline(value string) *TeamInstanceBuilder {
	return b.Deadline(value)
}

// DepartmentRef sets the department_ref field
func (b *TeamInstanceBuilder) DepartmentRef(value any) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyDepartmentRef, value)
	return b
}

// SetDepartmentRef is a compatibility alias for DepartmentRef.
func (b *TeamInstanceBuilder) SetDepartmentRef(value any) *TeamInstanceBuilder {
	return b.DepartmentRef(value)
}

// Dependencies sets the dependencies field
func (b *TeamInstanceBuilder) Dependencies(value []string) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyDependencies, value)
	return b
}

// SetDependencies is a compatibility alias for Dependencies.
func (b *TeamInstanceBuilder) SetDependencies(value []string) *TeamInstanceBuilder {
	return b.Dependencies(value)
}

// DivisionRef sets the division_ref field
func (b *TeamInstanceBuilder) DivisionRef(value any) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyDivisionRef, value)
	return b
}

// SetDivisionRef is a compatibility alias for DivisionRef.
func (b *TeamInstanceBuilder) SetDivisionRef(value any) *TeamInstanceBuilder {
	return b.DivisionRef(value)
}

// Domain sets the domain field
func (b *TeamInstanceBuilder) Domain(value string) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyDomain, value)
	return b
}

// SetDomain is a compatibility alias for Domain.
func (b *TeamInstanceBuilder) SetDomain(value string) *TeamInstanceBuilder {
	return b.Domain(value)
}

// LifecycleRef sets the lifecycle_ref field
func (b *TeamInstanceBuilder) LifecycleRef(value string) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyLifecycleRef, value)
	return b
}

// SetLifecycleRef is a compatibility alias for LifecycleRef.
func (b *TeamInstanceBuilder) SetLifecycleRef(value string) *TeamInstanceBuilder {
	return b.LifecycleRef(value)
}

// MemberRefs sets the member_refs field
func (b *TeamInstanceBuilder) MemberRefs(value []string) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyMemberRefs, value)
	return b
}

// SetMemberRefs is a compatibility alias for MemberRefs.
func (b *TeamInstanceBuilder) SetMemberRefs(value []string) *TeamInstanceBuilder {
	return b.MemberRefs(value)
}

// OriginProject sets the origin_project field
func (b *TeamInstanceBuilder) OriginProject(value string) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyOriginProject, value)
	return b
}

// SetOriginProject is a compatibility alias for OriginProject.
func (b *TeamInstanceBuilder) SetOriginProject(value string) *TeamInstanceBuilder {
	return b.OriginProject(value)
}

// OriginSystem sets the origin_system field
func (b *TeamInstanceBuilder) OriginSystem(value string) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyOriginSystem, value)
	return b
}

// SetOriginSystem is a compatibility alias for OriginSystem.
func (b *TeamInstanceBuilder) SetOriginSystem(value string) *TeamInstanceBuilder {
	return b.OriginSystem(value)
}

// PriorityTier sets the priority_tier field
func (b *TeamInstanceBuilder) PriorityTier(value enumv.PriorityTier) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyPriorityTier, string(value))
	return b
}

// SetPriorityTier is a compatibility alias for PriorityTier.
func (b *TeamInstanceBuilder) SetPriorityTier(value enumv.PriorityTier) *TeamInstanceBuilder {
	return b.PriorityTier(value)
}

// Questions sets the questions field
func (b *TeamInstanceBuilder) Questions(value []string) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyQuestions, value)
	return b
}

// SetQuestions is a compatibility alias for Questions.
func (b *TeamInstanceBuilder) SetQuestions(value []string) *TeamInstanceBuilder {
	return b.Questions(value)
}

// RelatedObjectRefs sets the related_object_refs field
func (b *TeamInstanceBuilder) RelatedObjectRefs(value []string) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyRelatedObjectRefs, value)
	return b
}

// SetRelatedObjectRefs is a compatibility alias for RelatedObjectRefs.
func (b *TeamInstanceBuilder) SetRelatedObjectRefs(value []string) *TeamInstanceBuilder {
	return b.RelatedObjectRefs(value)
}

// SourceType sets the source_type field
func (b *TeamInstanceBuilder) SourceType(value enumv.SourceType) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeySourceType, string(value))
	return b
}

// SetSourceType is a compatibility alias for SourceType.
func (b *TeamInstanceBuilder) SetSourceType(value enumv.SourceType) *TeamInstanceBuilder {
	return b.SourceType(value)
}

// SpecAdherence sets the spec_adherence field
func (b *TeamInstanceBuilder) SpecAdherence(value map[string]any) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeySpecAdherence, value)
	return b
}

// SetSpecAdherence is a compatibility alias for SpecAdherence.
func (b *TeamInstanceBuilder) SetSpecAdherence(value map[string]any) *TeamInstanceBuilder {
	return b.SpecAdherence(value)
}

// SpecContextBroker sets the spec_context_broker field
func (b *TeamInstanceBuilder) SpecContextBroker(value string) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeySpecContextBroker, value)
	return b
}

// SetSpecContextBroker is a compatibility alias for SpecContextBroker.
func (b *TeamInstanceBuilder) SetSpecContextBroker(value string) *TeamInstanceBuilder {
	return b.SpecContextBroker(value)
}

// SpecInterpreter sets the spec_interpreter field
func (b *TeamInstanceBuilder) SpecInterpreter(value string) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeySpecInterpreter, value)
	return b
}

// SetSpecInterpreter is a compatibility alias for SpecInterpreter.
func (b *TeamInstanceBuilder) SetSpecInterpreter(value string) *TeamInstanceBuilder {
	return b.SpecInterpreter(value)
}

// Stakeholders sets the stakeholders field
func (b *TeamInstanceBuilder) Stakeholders(value []string) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyStakeholders, value)
	return b
}

// SetStakeholders is a compatibility alias for Stakeholders.
func (b *TeamInstanceBuilder) SetStakeholders(value []string) *TeamInstanceBuilder {
	return b.Stakeholders(value)
}

// StatusHistory sets the status_history field
func (b *TeamInstanceBuilder) StatusHistory(value []string) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyStatusHistory, value)
	return b
}

// SetStatusHistory is a compatibility alias for StatusHistory.
func (b *TeamInstanceBuilder) SetStatusHistory(value []string) *TeamInstanceBuilder {
	return b.StatusHistory(value)
}

// TargetDate sets the target_date field
func (b *TeamInstanceBuilder) TargetDate(value string) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyTargetDate, value)
	return b
}

// SetTargetDate is a compatibility alias for TargetDate.
func (b *TeamInstanceBuilder) SetTargetDate(value string) *TeamInstanceBuilder {
	return b.TargetDate(value)
}

// TeamName sets the team_name field
func (b *TeamInstanceBuilder) TeamName(value string) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyTeamName, value)
	return b
}

// SetTeamName is a compatibility alias for TeamName.
func (b *TeamInstanceBuilder) SetTeamName(value string) *TeamInstanceBuilder {
	return b.TeamName(value)
}

// Title sets the title field
func (b *TeamInstanceBuilder) Title(value string) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyTitle, value)
	return b
}

// SetTitle is a compatibility alias for Title.
func (b *TeamInstanceBuilder) SetTitle(value string) *TeamInstanceBuilder {
	return b.Title(value)
}

// WorkstreamRefs sets the workstream_refs field
func (b *TeamInstanceBuilder) WorkstreamRefs(value []string) *TeamInstanceBuilder {
	b.SetField(objects.FieldKeyWorkstreamRefs, value)
	return b
}

// SetWorkstreamRefs is a compatibility alias for WorkstreamRefs.
func (b *TeamInstanceBuilder) SetWorkstreamRefs(value []string) *TeamInstanceBuilder {
	return b.WorkstreamRefs(value)
}

func init() {
	instance_builders.RegisterBuilder(NewTeamInstanceBuilder(objects.DefaultSchemaVersion))
}
