// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package bldr_instance_v1

import (
	"github.com/lanceman/zqk/pkg/objects"
	enumv "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/watchdog_registration"
	"github.com/lanceman/zqk/pkg/specbuilder/instance_builders"
)

// WatchdogRegistrationInstanceBuilder builds watchdog_registration instances
// ONE builder handles ALL watchdog_registration instances
type WatchdogRegistrationInstanceBuilder struct {
	*instance_builders.BaseInstanceBuilder
}

// NewWatchdogRegistrationInstanceBuilder creates a new watchdog_registration instance builder.
// Pass the instance schema_version string for this spec; use objects.DefaultSchemaVersion for the project default (pkg/objects constants).
// Field order is derived from the spec (not hardcoded) to avoid drift
func NewWatchdogRegistrationInstanceBuilder(schemaVersion string) *WatchdogRegistrationInstanceBuilder {
	// Derive canonical field order from spec (follows architecture pattern)
	// System fields first, then spec-defined fields in sorted order
	fieldOrder := buildFieldOrderFromSpec("watchdog_registration")

	// Create base builder
	builder := &WatchdogRegistrationInstanceBuilder{
		BaseInstanceBuilder: instance_builders.NewBaseInstanceBuilder(
			"watchdog_registration",
			schemaVersion,
			fieldOrder,
			nil, // spec builder (optional)
		),
	}

	return builder
}

// Status sets the status field
func (b *WatchdogRegistrationInstanceBuilder) Status(value enumv.Status) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyStatus, string(value))
	return b
}

// ID sets the id field
func (b *WatchdogRegistrationInstanceBuilder) ID(value string) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyID, value)
	return b
}

// ArchivedAt sets the archived_at field
func (b *WatchdogRegistrationInstanceBuilder) ArchivedAt(value any) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedAt, value)
	return b
}

// SetArchivedAt is a compatibility alias for ArchivedAt.
func (b *WatchdogRegistrationInstanceBuilder) SetArchivedAt(value any) *WatchdogRegistrationInstanceBuilder {
	return b.ArchivedAt(value)
}

// ArchivedBy sets the archived_by field
func (b *WatchdogRegistrationInstanceBuilder) ArchivedBy(value string) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedBy, value)
	return b
}

// SetArchivedBy is a compatibility alias for ArchivedBy.
func (b *WatchdogRegistrationInstanceBuilder) SetArchivedBy(value string) *WatchdogRegistrationInstanceBuilder {
	return b.ArchivedBy(value)
}

// Artifacts sets the artifacts field
func (b *WatchdogRegistrationInstanceBuilder) Artifacts(value []string) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyArtifacts, value)
	return b
}

// SetArtifacts is a compatibility alias for Artifacts.
func (b *WatchdogRegistrationInstanceBuilder) SetArtifacts(value []string) *WatchdogRegistrationInstanceBuilder {
	return b.Artifacts(value)
}

// ChangeLog sets the change_log field
func (b *WatchdogRegistrationInstanceBuilder) ChangeLog(value []string) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyChangeLog, value)
	return b
}

// SetChangeLog is a compatibility alias for ChangeLog.
func (b *WatchdogRegistrationInstanceBuilder) SetChangeLog(value []string) *WatchdogRegistrationInstanceBuilder {
	return b.ChangeLog(value)
}

// CompletenessValidation sets the completeness_validation field
func (b *WatchdogRegistrationInstanceBuilder) CompletenessValidation(value []string) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyCompletenessValidation, value)
	return b
}

// SetCompletenessValidation is a compatibility alias for CompletenessValidation.
func (b *WatchdogRegistrationInstanceBuilder) SetCompletenessValidation(value []string) *WatchdogRegistrationInstanceBuilder {
	return b.CompletenessValidation(value)
}

// ConditionQuery sets the condition_query field
func (b *WatchdogRegistrationInstanceBuilder) ConditionQuery(value string) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyConditionQuery, value)
	return b
}

// SetConditionQuery is a compatibility alias for ConditionQuery.
func (b *WatchdogRegistrationInstanceBuilder) SetConditionQuery(value string) *WatchdogRegistrationInstanceBuilder {
	return b.ConditionQuery(value)
}

// Context sets the context field
func (b *WatchdogRegistrationInstanceBuilder) Context(value any) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyContext, value)
	return b
}

// SetContext is a compatibility alias for Context.
func (b *WatchdogRegistrationInstanceBuilder) SetContext(value any) *WatchdogRegistrationInstanceBuilder {
	return b.Context(value)
}

// Deadline sets the deadline field
func (b *WatchdogRegistrationInstanceBuilder) Deadline(value string) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyDeadline, value)
	return b
}

// SetDeadline is a compatibility alias for Deadline.
func (b *WatchdogRegistrationInstanceBuilder) SetDeadline(value string) *WatchdogRegistrationInstanceBuilder {
	return b.Deadline(value)
}

// Dependencies sets the dependencies field
func (b *WatchdogRegistrationInstanceBuilder) Dependencies(value []string) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyDependencies, value)
	return b
}

// SetDependencies is a compatibility alias for Dependencies.
func (b *WatchdogRegistrationInstanceBuilder) SetDependencies(value []string) *WatchdogRegistrationInstanceBuilder {
	return b.Dependencies(value)
}

// Description sets the description field
func (b *WatchdogRegistrationInstanceBuilder) Description(value any) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyDescription, value)
	return b
}

// SetDescription is a compatibility alias for Description.
func (b *WatchdogRegistrationInstanceBuilder) SetDescription(value any) *WatchdogRegistrationInstanceBuilder {
	return b.Description(value)
}

// Frequency sets the frequency field
func (b *WatchdogRegistrationInstanceBuilder) Frequency(value string) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyFrequency, value)
	return b
}

// SetFrequency is a compatibility alias for Frequency.
func (b *WatchdogRegistrationInstanceBuilder) SetFrequency(value string) *WatchdogRegistrationInstanceBuilder {
	return b.Frequency(value)
}

// HeartbeatEnabled sets the heartbeat_enabled field
func (b *WatchdogRegistrationInstanceBuilder) HeartbeatEnabled(value bool) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyHeartbeatEnabled, value)
	return b
}

// SetHeartbeatEnabled is a compatibility alias for HeartbeatEnabled.
func (b *WatchdogRegistrationInstanceBuilder) SetHeartbeatEnabled(value bool) *WatchdogRegistrationInstanceBuilder {
	return b.HeartbeatEnabled(value)
}

// Note sets the note field
func (b *WatchdogRegistrationInstanceBuilder) Note(value any) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyNote, value)
	return b
}

// SetNote is a compatibility alias for Note.
func (b *WatchdogRegistrationInstanceBuilder) SetNote(value any) *WatchdogRegistrationInstanceBuilder {
	return b.Note(value)
}

// NotifyTargetRef sets the notify_target_ref field
func (b *WatchdogRegistrationInstanceBuilder) NotifyTargetRef(value string) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyNotifyTargetRef, value)
	return b
}

// SetNotifyTargetRef is a compatibility alias for NotifyTargetRef.
func (b *WatchdogRegistrationInstanceBuilder) SetNotifyTargetRef(value string) *WatchdogRegistrationInstanceBuilder {
	return b.NotifyTargetRef(value)
}

// OriginProject sets the origin_project field
func (b *WatchdogRegistrationInstanceBuilder) OriginProject(value string) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyOriginProject, value)
	return b
}

// SetOriginProject is a compatibility alias for OriginProject.
func (b *WatchdogRegistrationInstanceBuilder) SetOriginProject(value string) *WatchdogRegistrationInstanceBuilder {
	return b.OriginProject(value)
}

// OriginSystem sets the origin_system field
func (b *WatchdogRegistrationInstanceBuilder) OriginSystem(value string) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyOriginSystem, value)
	return b
}

// SetOriginSystem is a compatibility alias for OriginSystem.
func (b *WatchdogRegistrationInstanceBuilder) SetOriginSystem(value string) *WatchdogRegistrationInstanceBuilder {
	return b.OriginSystem(value)
}

// Plane sets the plane field
func (b *WatchdogRegistrationInstanceBuilder) Plane(value enumv.Plane) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyPlane, string(value))
	return b
}

// SetPlane is a compatibility alias for Plane.
func (b *WatchdogRegistrationInstanceBuilder) SetPlane(value enumv.Plane) *WatchdogRegistrationInstanceBuilder {
	return b.Plane(value)
}

// PriorityTier sets the priority_tier field
func (b *WatchdogRegistrationInstanceBuilder) PriorityTier(value enumv.PriorityTier) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyPriorityTier, string(value))
	return b
}

// SetPriorityTier is a compatibility alias for PriorityTier.
func (b *WatchdogRegistrationInstanceBuilder) SetPriorityTier(value enumv.PriorityTier) *WatchdogRegistrationInstanceBuilder {
	return b.PriorityTier(value)
}

// Provenance sets the provenance field
func (b *WatchdogRegistrationInstanceBuilder) Provenance(value map[string]any) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyProvenance, value)
	return b
}

// SetProvenance is a compatibility alias for Provenance.
func (b *WatchdogRegistrationInstanceBuilder) SetProvenance(value map[string]any) *WatchdogRegistrationInstanceBuilder {
	return b.Provenance(value)
}

// Questions sets the questions field
func (b *WatchdogRegistrationInstanceBuilder) Questions(value []string) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyQuestions, value)
	return b
}

// SetQuestions is a compatibility alias for Questions.
func (b *WatchdogRegistrationInstanceBuilder) SetQuestions(value []string) *WatchdogRegistrationInstanceBuilder {
	return b.Questions(value)
}

// RelatedObjectRefs sets the related_object_refs field
func (b *WatchdogRegistrationInstanceBuilder) RelatedObjectRefs(value []string) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyRelatedObjectRefs, value)
	return b
}

// SetRelatedObjectRefs is a compatibility alias for RelatedObjectRefs.
func (b *WatchdogRegistrationInstanceBuilder) SetRelatedObjectRefs(value []string) *WatchdogRegistrationInstanceBuilder {
	return b.RelatedObjectRefs(value)
}

// SchemaRef sets the schema_ref field
func (b *WatchdogRegistrationInstanceBuilder) SchemaRef(value string) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeySchemaRef, value)
	return b
}

// SetSchemaRef is a compatibility alias for SchemaRef.
func (b *WatchdogRegistrationInstanceBuilder) SetSchemaRef(value string) *WatchdogRegistrationInstanceBuilder {
	return b.SchemaRef(value)
}

// SourceType sets the source_type field
func (b *WatchdogRegistrationInstanceBuilder) SourceType(value enumv.SourceType) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeySourceType, string(value))
	return b
}

// SetSourceType is a compatibility alias for SourceType.
func (b *WatchdogRegistrationInstanceBuilder) SetSourceType(value enumv.SourceType) *WatchdogRegistrationInstanceBuilder {
	return b.SourceType(value)
}

// SpecAdherence sets the spec_adherence field
func (b *WatchdogRegistrationInstanceBuilder) SpecAdherence(value map[string]any) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeySpecAdherence, value)
	return b
}

// SetSpecAdherence is a compatibility alias for SpecAdherence.
func (b *WatchdogRegistrationInstanceBuilder) SetSpecAdherence(value map[string]any) *WatchdogRegistrationInstanceBuilder {
	return b.SpecAdherence(value)
}

// Stakeholders sets the stakeholders field
func (b *WatchdogRegistrationInstanceBuilder) Stakeholders(value []string) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyStakeholders, value)
	return b
}

// SetStakeholders is a compatibility alias for Stakeholders.
func (b *WatchdogRegistrationInstanceBuilder) SetStakeholders(value []string) *WatchdogRegistrationInstanceBuilder {
	return b.Stakeholders(value)
}

// StatusHistory sets the status_history field
func (b *WatchdogRegistrationInstanceBuilder) StatusHistory(value []string) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyStatusHistory, value)
	return b
}

// SetStatusHistory is a compatibility alias for StatusHistory.
func (b *WatchdogRegistrationInstanceBuilder) SetStatusHistory(value []string) *WatchdogRegistrationInstanceBuilder {
	return b.StatusHistory(value)
}

// TargetDate sets the target_date field
func (b *WatchdogRegistrationInstanceBuilder) TargetDate(value string) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyTargetDate, value)
	return b
}

// SetTargetDate is a compatibility alias for TargetDate.
func (b *WatchdogRegistrationInstanceBuilder) SetTargetDate(value string) *WatchdogRegistrationInstanceBuilder {
	return b.TargetDate(value)
}

// TargetKind sets the target_kind field
func (b *WatchdogRegistrationInstanceBuilder) TargetKind(value string) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyTargetKind, value)
	return b
}

// SetTargetKind is a compatibility alias for TargetKind.
func (b *WatchdogRegistrationInstanceBuilder) SetTargetKind(value string) *WatchdogRegistrationInstanceBuilder {
	return b.TargetKind(value)
}

// Title sets the title field
func (b *WatchdogRegistrationInstanceBuilder) Title(value string) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyTitle, value)
	return b
}

// SetTitle is a compatibility alias for Title.
func (b *WatchdogRegistrationInstanceBuilder) SetTitle(value string) *WatchdogRegistrationInstanceBuilder {
	return b.Title(value)
}

// Urn sets the urn field
func (b *WatchdogRegistrationInstanceBuilder) Urn(value string) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyUrn, value)
	return b
}

// SetUrn is a compatibility alias for Urn.
func (b *WatchdogRegistrationInstanceBuilder) SetUrn(value string) *WatchdogRegistrationInstanceBuilder {
	return b.Urn(value)
}

// Version sets the version field
func (b *WatchdogRegistrationInstanceBuilder) Version(value int) *WatchdogRegistrationInstanceBuilder {
	b.SetField(objects.FieldKeyVersion, value)
	return b
}

// SetVersion is a compatibility alias for Version.
func (b *WatchdogRegistrationInstanceBuilder) SetVersion(value int) *WatchdogRegistrationInstanceBuilder {
	return b.Version(value)
}

func init() {
	instance_builders.RegisterBuilder(NewWatchdogRegistrationInstanceBuilder(objects.DefaultSchemaVersion))
}
