// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package bldr_instance_v1

import (
	"github.com/zqk-os/zqk/pkg/objects"
	enumv "github.com/zqk-os/zqk/pkg/specbuilder/bldr_enum_v1/workflow"
	"github.com/zqk-os/zqk/pkg/specbuilder/instance_builders"
)

// WorkflowInstanceBuilder builds workflow instances
// ONE builder handles ALL workflow instances
type WorkflowInstanceBuilder struct {
	*instance_builders.BaseInstanceBuilder
}

// NewWorkflowInstanceBuilder creates a new workflow instance builder.
// Pass the instance schema_version string for this spec; use objects.DefaultSchemaVersion for the project default (pkg/objects constants).
// Field order is derived from the spec (not hardcoded) to avoid drift
func NewWorkflowInstanceBuilder(schemaVersion string) *WorkflowInstanceBuilder {
	// Derive canonical field order from spec (follows architecture pattern)
	// System fields first, then spec-defined fields in sorted order
	fieldOrder := instance_builders.FieldOrderFromSpec("workflow")

	// Create base builder
	builder := &WorkflowInstanceBuilder{
		BaseInstanceBuilder: instance_builders.NewBaseInstanceBuilder(
			"workflow",
			schemaVersion,
			fieldOrder,
			nil, // spec builder (optional)
		),
	}

	return builder
}

// Status sets the status field
func (b *WorkflowInstanceBuilder) Status(value enumv.Status) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyStatus, string(value))
	return b
}

// ID sets the id field
func (b *WorkflowInstanceBuilder) ID(value string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyID, value)
	return b
}

// ApplicableAccounts sets the applicable_accounts field
func (b *WorkflowInstanceBuilder) ApplicableAccounts(value []string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyApplicableAccounts, value)
	return b
}

// SetApplicableAccounts is a compatibility alias for ApplicableAccounts.
func (b *WorkflowInstanceBuilder) SetApplicableAccounts(value []string) *WorkflowInstanceBuilder {
	return b.ApplicableAccounts(value)
}

// ApplicableRoles sets the applicable_roles field
func (b *WorkflowInstanceBuilder) ApplicableRoles(value []string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyApplicableRoles, value)
	return b
}

// SetApplicableRoles is a compatibility alias for ApplicableRoles.
func (b *WorkflowInstanceBuilder) SetApplicableRoles(value []string) *WorkflowInstanceBuilder {
	return b.ApplicableRoles(value)
}

// ArchivedAt sets the archived_at field
func (b *WorkflowInstanceBuilder) ArchivedAt(value any) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedAt, value)
	return b
}

// SetArchivedAt is a compatibility alias for ArchivedAt.
func (b *WorkflowInstanceBuilder) SetArchivedAt(value any) *WorkflowInstanceBuilder {
	return b.ArchivedAt(value)
}

// ArchivedBy sets the archived_by field
func (b *WorkflowInstanceBuilder) ArchivedBy(value string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedBy, value)
	return b
}

// SetArchivedBy is a compatibility alias for ArchivedBy.
func (b *WorkflowInstanceBuilder) SetArchivedBy(value string) *WorkflowInstanceBuilder {
	return b.ArchivedBy(value)
}

// Artifacts sets the artifacts field
func (b *WorkflowInstanceBuilder) Artifacts(value []string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyArtifacts, value)
	return b
}

// SetArtifacts is a compatibility alias for Artifacts.
func (b *WorkflowInstanceBuilder) SetArtifacts(value []string) *WorkflowInstanceBuilder {
	return b.Artifacts(value)
}

// BlockingCheckConfigRef sets the blocking_check_config_ref field
func (b *WorkflowInstanceBuilder) BlockingCheckConfigRef(value string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyBlockingCheckConfigRef, value)
	return b
}

// SetBlockingCheckConfigRef is a compatibility alias for BlockingCheckConfigRef.
func (b *WorkflowInstanceBuilder) SetBlockingCheckConfigRef(value string) *WorkflowInstanceBuilder {
	return b.BlockingCheckConfigRef(value)
}

// Category sets the category field
func (b *WorkflowInstanceBuilder) Category(value enumv.Category) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyCategory, string(value))
	return b
}

// SetCategory is a compatibility alias for Category.
func (b *WorkflowInstanceBuilder) SetCategory(value enumv.Category) *WorkflowInstanceBuilder {
	return b.Category(value)
}

// ChangeLog sets the change_log field
func (b *WorkflowInstanceBuilder) ChangeLog(value []string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyChangeLog, value)
	return b
}

// SetChangeLog is a compatibility alias for ChangeLog.
func (b *WorkflowInstanceBuilder) SetChangeLog(value []string) *WorkflowInstanceBuilder {
	return b.ChangeLog(value)
}

// CompletenessValidation sets the completeness_validation field
func (b *WorkflowInstanceBuilder) CompletenessValidation(value []string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyCompletenessValidation, value)
	return b
}

// SetCompletenessValidation is a compatibility alias for CompletenessValidation.
func (b *WorkflowInstanceBuilder) SetCompletenessValidation(value []string) *WorkflowInstanceBuilder {
	return b.CompletenessValidation(value)
}

// Constraints sets the constraints field
func (b *WorkflowInstanceBuilder) Constraints(value map[string]any) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyConstraints, value)
	return b
}

// SetConstraints is a compatibility alias for Constraints.
func (b *WorkflowInstanceBuilder) SetConstraints(value map[string]any) *WorkflowInstanceBuilder {
	return b.Constraints(value)
}

// Context sets the context field
func (b *WorkflowInstanceBuilder) Context(value any) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyContext, value)
	return b
}

// SetContext is a compatibility alias for Context.
func (b *WorkflowInstanceBuilder) SetContext(value any) *WorkflowInstanceBuilder {
	return b.Context(value)
}

// Deadline sets the deadline field
func (b *WorkflowInstanceBuilder) Deadline(value string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyDeadline, value)
	return b
}

// SetDeadline is a compatibility alias for Deadline.
func (b *WorkflowInstanceBuilder) SetDeadline(value string) *WorkflowInstanceBuilder {
	return b.Deadline(value)
}

// Dependencies sets the dependencies field
func (b *WorkflowInstanceBuilder) Dependencies(value []string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyDependencies, value)
	return b
}

// SetDependencies is a compatibility alias for Dependencies.
func (b *WorkflowInstanceBuilder) SetDependencies(value []string) *WorkflowInstanceBuilder {
	return b.Dependencies(value)
}

// Description sets the description field
func (b *WorkflowInstanceBuilder) Description(value any) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyDescription, value)
	return b
}

// SetDescription is a compatibility alias for Description.
func (b *WorkflowInstanceBuilder) SetDescription(value any) *WorkflowInstanceBuilder {
	return b.Description(value)
}

// Enabled sets the enabled field
func (b *WorkflowInstanceBuilder) Enabled(value bool) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyEnabled, value)
	return b
}

// SetEnabled is a compatibility alias for Enabled.
func (b *WorkflowInstanceBuilder) SetEnabled(value bool) *WorkflowInstanceBuilder {
	return b.Enabled(value)
}

// LifecycleKinds sets the lifecycle_kinds field
func (b *WorkflowInstanceBuilder) LifecycleKinds(value []string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyLifecycleKinds, value)
	return b
}

// SetLifecycleKinds is a compatibility alias for LifecycleKinds.
func (b *WorkflowInstanceBuilder) SetLifecycleKinds(value []string) *WorkflowInstanceBuilder {
	return b.LifecycleKinds(value)
}

// McpConfig sets the mcp_config field
func (b *WorkflowInstanceBuilder) McpConfig(value map[string]any) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyMcpConfig, value)
	return b
}

// SetMcpConfig is a compatibility alias for McpConfig.
func (b *WorkflowInstanceBuilder) SetMcpConfig(value map[string]any) *WorkflowInstanceBuilder {
	return b.McpConfig(value)
}

// Metadata sets the metadata field
func (b *WorkflowInstanceBuilder) Metadata(value map[string]any) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyMetadata, value)
	return b
}

// SetMetadata is a compatibility alias for Metadata.
func (b *WorkflowInstanceBuilder) SetMetadata(value map[string]any) *WorkflowInstanceBuilder {
	return b.Metadata(value)
}

// OriginProject sets the origin_project field
func (b *WorkflowInstanceBuilder) OriginProject(value string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyOriginProject, value)
	return b
}

// SetOriginProject is a compatibility alias for OriginProject.
func (b *WorkflowInstanceBuilder) SetOriginProject(value string) *WorkflowInstanceBuilder {
	return b.OriginProject(value)
}

// OriginSystem sets the origin_system field
func (b *WorkflowInstanceBuilder) OriginSystem(value string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyOriginSystem, value)
	return b
}

// SetOriginSystem is a compatibility alias for OriginSystem.
func (b *WorkflowInstanceBuilder) SetOriginSystem(value string) *WorkflowInstanceBuilder {
	return b.OriginSystem(value)
}

// Plane sets the plane field
func (b *WorkflowInstanceBuilder) Plane(value enumv.Plane) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyPlane, string(value))
	return b
}

// SetPlane is a compatibility alias for Plane.
func (b *WorkflowInstanceBuilder) SetPlane(value enumv.Plane) *WorkflowInstanceBuilder {
	return b.Plane(value)
}

// PolicyRefs sets the policy_refs field
func (b *WorkflowInstanceBuilder) PolicyRefs(value []string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyPolicyRefs, value)
	return b
}

// SetPolicyRefs is a compatibility alias for PolicyRefs.
func (b *WorkflowInstanceBuilder) SetPolicyRefs(value []string) *WorkflowInstanceBuilder {
	return b.PolicyRefs(value)
}

// PriorityTier sets the priority_tier field
func (b *WorkflowInstanceBuilder) PriorityTier(value enumv.PriorityTier) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyPriorityTier, string(value))
	return b
}

// SetPriorityTier is a compatibility alias for PriorityTier.
func (b *WorkflowInstanceBuilder) SetPriorityTier(value enumv.PriorityTier) *WorkflowInstanceBuilder {
	return b.PriorityTier(value)
}

// Provenance sets the provenance field
func (b *WorkflowInstanceBuilder) Provenance(value map[string]any) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyProvenance, value)
	return b
}

// SetProvenance is a compatibility alias for Provenance.
func (b *WorkflowInstanceBuilder) SetProvenance(value map[string]any) *WorkflowInstanceBuilder {
	return b.Provenance(value)
}

// Questions sets the questions field
func (b *WorkflowInstanceBuilder) Questions(value []string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyQuestions, value)
	return b
}

// SetQuestions is a compatibility alias for Questions.
func (b *WorkflowInstanceBuilder) SetQuestions(value []string) *WorkflowInstanceBuilder {
	return b.Questions(value)
}

// RelatedObjectRefs sets the related_object_refs field
func (b *WorkflowInstanceBuilder) RelatedObjectRefs(value []string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyRelatedObjectRefs, value)
	return b
}

// SetRelatedObjectRefs is a compatibility alias for RelatedObjectRefs.
func (b *WorkflowInstanceBuilder) SetRelatedObjectRefs(value []string) *WorkflowInstanceBuilder {
	return b.RelatedObjectRefs(value)
}

// SchemaRef sets the schema_ref field
func (b *WorkflowInstanceBuilder) SchemaRef(value string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeySchemaRef, value)
	return b
}

// SetSchemaRef is a compatibility alias for SchemaRef.
func (b *WorkflowInstanceBuilder) SetSchemaRef(value string) *WorkflowInstanceBuilder {
	return b.SchemaRef(value)
}

// SourceType sets the source_type field
func (b *WorkflowInstanceBuilder) SourceType(value enumv.SourceType) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeySourceType, string(value))
	return b
}

// SetSourceType is a compatibility alias for SourceType.
func (b *WorkflowInstanceBuilder) SetSourceType(value enumv.SourceType) *WorkflowInstanceBuilder {
	return b.SourceType(value)
}

// SpecAdherence sets the spec_adherence field
func (b *WorkflowInstanceBuilder) SpecAdherence(value map[string]any) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeySpecAdherence, value)
	return b
}

// SetSpecAdherence is a compatibility alias for SpecAdherence.
func (b *WorkflowInstanceBuilder) SetSpecAdherence(value map[string]any) *WorkflowInstanceBuilder {
	return b.SpecAdherence(value)
}

// Stages sets the stages field
func (b *WorkflowInstanceBuilder) Stages(value []string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyStages, value)
	return b
}

// SetStages is a compatibility alias for Stages.
func (b *WorkflowInstanceBuilder) SetStages(value []string) *WorkflowInstanceBuilder {
	return b.Stages(value)
}

// Stakeholders sets the stakeholders field
func (b *WorkflowInstanceBuilder) Stakeholders(value []string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyStakeholders, value)
	return b
}

// SetStakeholders is a compatibility alias for Stakeholders.
func (b *WorkflowInstanceBuilder) SetStakeholders(value []string) *WorkflowInstanceBuilder {
	return b.Stakeholders(value)
}

// StatusHistory sets the status_history field
func (b *WorkflowInstanceBuilder) StatusHistory(value []string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyStatusHistory, value)
	return b
}

// SetStatusHistory is a compatibility alias for StatusHistory.
func (b *WorkflowInstanceBuilder) SetStatusHistory(value []string) *WorkflowInstanceBuilder {
	return b.StatusHistory(value)
}

// TargetDate sets the target_date field
func (b *WorkflowInstanceBuilder) TargetDate(value string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyTargetDate, value)
	return b
}

// SetTargetDate is a compatibility alias for TargetDate.
func (b *WorkflowInstanceBuilder) SetTargetDate(value string) *WorkflowInstanceBuilder {
	return b.TargetDate(value)
}

// TemplateRefs sets the template_refs field
func (b *WorkflowInstanceBuilder) TemplateRefs(value []string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyTemplateRefs, value)
	return b
}

// SetTemplateRefs is a compatibility alias for TemplateRefs.
func (b *WorkflowInstanceBuilder) SetTemplateRefs(value []string) *WorkflowInstanceBuilder {
	return b.TemplateRefs(value)
}

// Title sets the title field
func (b *WorkflowInstanceBuilder) Title(value string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyTitle, value)
	return b
}

// SetTitle is a compatibility alias for Title.
func (b *WorkflowInstanceBuilder) SetTitle(value string) *WorkflowInstanceBuilder {
	return b.Title(value)
}

// Urn sets the urn field
func (b *WorkflowInstanceBuilder) Urn(value string) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyUrn, value)
	return b
}

// SetUrn is a compatibility alias for Urn.
func (b *WorkflowInstanceBuilder) SetUrn(value string) *WorkflowInstanceBuilder {
	return b.Urn(value)
}

// Version sets the version field
func (b *WorkflowInstanceBuilder) Version(value int) *WorkflowInstanceBuilder {
	b.SetField(objects.FieldKeyVersion, value)
	return b
}

// SetVersion is a compatibility alias for Version.
func (b *WorkflowInstanceBuilder) SetVersion(value int) *WorkflowInstanceBuilder {
	return b.Version(value)
}
