// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package bldr_instance_v1

import (
	"github.com/lanceman/zqk/pkg/objects"
	enumv "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/workstream"
	"github.com/lanceman/zqk/pkg/specbuilder/instance_builders"
)

// WorkstreamInstanceBuilder builds workstream instances
// ONE builder handles ALL workstream instances
type WorkstreamInstanceBuilder struct {
	*instance_builders.BaseInstanceBuilder
}

// NewWorkstreamInstanceBuilder creates a new workstream instance builder.
// Pass the instance schema_version string for this spec; use objects.DefaultSchemaVersion for the project default (pkg/objects constants).
// Field order is derived from the spec (not hardcoded) to avoid drift
func NewWorkstreamInstanceBuilder(schemaVersion string) *WorkstreamInstanceBuilder {
	// Derive canonical field order from spec (follows architecture pattern)
	// System fields first, then spec-defined fields in sorted order
	fieldOrder := buildFieldOrderFromSpec("workstream")

	// Create base builder
	builder := &WorkstreamInstanceBuilder{
		BaseInstanceBuilder: instance_builders.NewBaseInstanceBuilder(
			"workstream",
			schemaVersion,
			fieldOrder,
			nil, // spec builder (optional)
		),
	}

	return builder
}

// Status sets the status field
func (b *WorkstreamInstanceBuilder) Status(value enumv.Status) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyStatus, string(value))
	return b
}

// ID sets the id field
func (b *WorkstreamInstanceBuilder) ID(value string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyID, value)
	return b
}

// AnswerDueBy sets the answer_due_by field
func (b *WorkstreamInstanceBuilder) AnswerDueBy(value string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyAnswerDueBy, value)
	return b
}

// SetAnswerDueBy is a compatibility alias for AnswerDueBy.
func (b *WorkstreamInstanceBuilder) SetAnswerDueBy(value string) *WorkstreamInstanceBuilder {
	return b.AnswerDueBy(value)
}

// Application sets the application field
func (b *WorkstreamInstanceBuilder) Application(value string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyApplication, value)
	return b
}

// SetApplication is a compatibility alias for Application.
func (b *WorkstreamInstanceBuilder) SetApplication(value string) *WorkstreamInstanceBuilder {
	return b.Application(value)
}

// ArchivedAt sets the archived_at field
func (b *WorkstreamInstanceBuilder) ArchivedAt(value any) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedAt, value)
	return b
}

// SetArchivedAt is a compatibility alias for ArchivedAt.
func (b *WorkstreamInstanceBuilder) SetArchivedAt(value any) *WorkstreamInstanceBuilder {
	return b.ArchivedAt(value)
}

// ArchivedBy sets the archived_by field
func (b *WorkstreamInstanceBuilder) ArchivedBy(value string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedBy, value)
	return b
}

// SetArchivedBy is a compatibility alias for ArchivedBy.
func (b *WorkstreamInstanceBuilder) SetArchivedBy(value string) *WorkstreamInstanceBuilder {
	return b.ArchivedBy(value)
}

// Artifacts sets the artifacts field
func (b *WorkstreamInstanceBuilder) Artifacts(value []string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyArtifacts, value)
	return b
}

// SetArtifacts is a compatibility alias for Artifacts.
func (b *WorkstreamInstanceBuilder) SetArtifacts(value []string) *WorkstreamInstanceBuilder {
	return b.Artifacts(value)
}

// Blockers sets the blockers field
func (b *WorkstreamInstanceBuilder) Blockers(value []string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyBlockers, value)
	return b
}

// SetBlockers is a compatibility alias for Blockers.
func (b *WorkstreamInstanceBuilder) SetBlockers(value []string) *WorkstreamInstanceBuilder {
	return b.Blockers(value)
}

// Category sets the category field
func (b *WorkstreamInstanceBuilder) Category(value enumv.Category) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyCategory, string(value))
	return b
}

// SetCategory is a compatibility alias for Category.
func (b *WorkstreamInstanceBuilder) SetCategory(value enumv.Category) *WorkstreamInstanceBuilder {
	return b.Category(value)
}

// ChangeLog sets the change_log field
func (b *WorkstreamInstanceBuilder) ChangeLog(value []string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyChangeLog, value)
	return b
}

// SetChangeLog is a compatibility alias for ChangeLog.
func (b *WorkstreamInstanceBuilder) SetChangeLog(value []string) *WorkstreamInstanceBuilder {
	return b.ChangeLog(value)
}

// CompletedAt sets the completed_at field
func (b *WorkstreamInstanceBuilder) CompletedAt(value string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyCompletedAt, value)
	return b
}

// SetCompletedAt is a compatibility alias for CompletedAt.
func (b *WorkstreamInstanceBuilder) SetCompletedAt(value string) *WorkstreamInstanceBuilder {
	return b.CompletedAt(value)
}

// CompletenessValidation sets the completeness_validation field
func (b *WorkstreamInstanceBuilder) CompletenessValidation(value []string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyCompletenessValidation, value)
	return b
}

// SetCompletenessValidation is a compatibility alias for CompletenessValidation.
func (b *WorkstreamInstanceBuilder) SetCompletenessValidation(value []string) *WorkstreamInstanceBuilder {
	return b.CompletenessValidation(value)
}

// Context sets the context field
func (b *WorkstreamInstanceBuilder) Context(value any) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyContext, value)
	return b
}

// SetContext is a compatibility alias for Context.
func (b *WorkstreamInstanceBuilder) SetContext(value any) *WorkstreamInstanceBuilder {
	return b.Context(value)
}

// Deadline sets the deadline field
func (b *WorkstreamInstanceBuilder) Deadline(value string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyDeadline, value)
	return b
}

// SetDeadline is a compatibility alias for Deadline.
func (b *WorkstreamInstanceBuilder) SetDeadline(value string) *WorkstreamInstanceBuilder {
	return b.Deadline(value)
}

// Dependencies sets the dependencies field
func (b *WorkstreamInstanceBuilder) Dependencies(value []string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyDependencies, value)
	return b
}

// SetDependencies is a compatibility alias for Dependencies.
func (b *WorkstreamInstanceBuilder) SetDependencies(value []string) *WorkstreamInstanceBuilder {
	return b.Dependencies(value)
}

// Description sets the description field
func (b *WorkstreamInstanceBuilder) Description(value any) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyDescription, value)
	return b
}

// SetDescription is a compatibility alias for Description.
func (b *WorkstreamInstanceBuilder) SetDescription(value any) *WorkstreamInstanceBuilder {
	return b.Description(value)
}

// EntryPoint sets the entry_point field
func (b *WorkstreamInstanceBuilder) EntryPoint(value string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyEntryPoint, value)
	return b
}

// SetEntryPoint is a compatibility alias for EntryPoint.
func (b *WorkstreamInstanceBuilder) SetEntryPoint(value string) *WorkstreamInstanceBuilder {
	return b.EntryPoint(value)
}

// Metadata sets the metadata field
func (b *WorkstreamInstanceBuilder) Metadata(value map[string]any) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyMetadata, value)
	return b
}

// SetMetadata is a compatibility alias for Metadata.
func (b *WorkstreamInstanceBuilder) SetMetadata(value map[string]any) *WorkstreamInstanceBuilder {
	return b.Metadata(value)
}

// Order sets the order field
func (b *WorkstreamInstanceBuilder) Order(value int) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyOrder, value)
	return b
}

// SetOrder is a compatibility alias for Order.
func (b *WorkstreamInstanceBuilder) SetOrder(value int) *WorkstreamInstanceBuilder {
	return b.Order(value)
}

// OriginProject sets the origin_project field
func (b *WorkstreamInstanceBuilder) OriginProject(value string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyOriginProject, value)
	return b
}

// SetOriginProject is a compatibility alias for OriginProject.
func (b *WorkstreamInstanceBuilder) SetOriginProject(value string) *WorkstreamInstanceBuilder {
	return b.OriginProject(value)
}

// OriginSystem sets the origin_system field
func (b *WorkstreamInstanceBuilder) OriginSystem(value string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyOriginSystem, value)
	return b
}

// SetOriginSystem is a compatibility alias for OriginSystem.
func (b *WorkstreamInstanceBuilder) SetOriginSystem(value string) *WorkstreamInstanceBuilder {
	return b.OriginSystem(value)
}

// OwnerDisplay sets the owner_display field
func (b *WorkstreamInstanceBuilder) OwnerDisplay(value string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyOwnerDisplay, value)
	return b
}

// SetOwnerDisplay is a compatibility alias for OwnerDisplay.
func (b *WorkstreamInstanceBuilder) SetOwnerDisplay(value string) *WorkstreamInstanceBuilder {
	return b.OwnerDisplay(value)
}

// OwnerRef sets the owner_ref field
func (b *WorkstreamInstanceBuilder) OwnerRef(value any) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyOwnerRef, value)
	return b
}

// SetOwnerRef is a compatibility alias for OwnerRef.
func (b *WorkstreamInstanceBuilder) SetOwnerRef(value any) *WorkstreamInstanceBuilder {
	return b.OwnerRef(value)
}

// Prerequisites sets the prerequisites field
func (b *WorkstreamInstanceBuilder) Prerequisites(value []string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyPrerequisites, value)
	return b
}

// SetPrerequisites is a compatibility alias for Prerequisites.
func (b *WorkstreamInstanceBuilder) SetPrerequisites(value []string) *WorkstreamInstanceBuilder {
	return b.Prerequisites(value)
}

// PriorityTier sets the priority_tier field
func (b *WorkstreamInstanceBuilder) PriorityTier(value enumv.PriorityTier) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyPriorityTier, string(value))
	return b
}

// SetPriorityTier is a compatibility alias for PriorityTier.
func (b *WorkstreamInstanceBuilder) SetPriorityTier(value enumv.PriorityTier) *WorkstreamInstanceBuilder {
	return b.PriorityTier(value)
}

// Questions sets the questions field
func (b *WorkstreamInstanceBuilder) Questions(value []string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyQuestions, value)
	return b
}

// SetQuestions is a compatibility alias for Questions.
func (b *WorkstreamInstanceBuilder) SetQuestions(value []string) *WorkstreamInstanceBuilder {
	return b.Questions(value)
}

// RelatedDocs sets the related_docs field
func (b *WorkstreamInstanceBuilder) RelatedDocs(value []string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyRelatedDocs, value)
	return b
}

// SetRelatedDocs is a compatibility alias for RelatedDocs.
func (b *WorkstreamInstanceBuilder) SetRelatedDocs(value []string) *WorkstreamInstanceBuilder {
	return b.RelatedDocs(value)
}

// RelatedObjectRefs sets the related_object_refs field
func (b *WorkstreamInstanceBuilder) RelatedObjectRefs(value []string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyRelatedObjectRefs, value)
	return b
}

// SetRelatedObjectRefs is a compatibility alias for RelatedObjectRefs.
func (b *WorkstreamInstanceBuilder) SetRelatedObjectRefs(value []string) *WorkstreamInstanceBuilder {
	return b.RelatedObjectRefs(value)
}

// SourceType sets the source_type field
func (b *WorkstreamInstanceBuilder) SourceType(value enumv.SourceType) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeySourceType, string(value))
	return b
}

// SetSourceType is a compatibility alias for SourceType.
func (b *WorkstreamInstanceBuilder) SetSourceType(value enumv.SourceType) *WorkstreamInstanceBuilder {
	return b.SourceType(value)
}

// SpecAdherence sets the spec_adherence field
func (b *WorkstreamInstanceBuilder) SpecAdherence(value map[string]any) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeySpecAdherence, value)
	return b
}

// SetSpecAdherence is a compatibility alias for SpecAdherence.
func (b *WorkstreamInstanceBuilder) SetSpecAdherence(value map[string]any) *WorkstreamInstanceBuilder {
	return b.SpecAdherence(value)
}

// StageType sets the stage_type field
func (b *WorkstreamInstanceBuilder) StageType(value string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyStageType, value)
	return b
}

// SetStageType is a compatibility alias for StageType.
func (b *WorkstreamInstanceBuilder) SetStageType(value string) *WorkstreamInstanceBuilder {
	return b.StageType(value)
}

// Stakeholders sets the stakeholders field
func (b *WorkstreamInstanceBuilder) Stakeholders(value []string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyStakeholders, value)
	return b
}

// SetStakeholders is a compatibility alias for Stakeholders.
func (b *WorkstreamInstanceBuilder) SetStakeholders(value []string) *WorkstreamInstanceBuilder {
	return b.Stakeholders(value)
}

// StartedAt sets the started_at field
func (b *WorkstreamInstanceBuilder) StartedAt(value string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyStartedAt, value)
	return b
}

// SetStartedAt is a compatibility alias for StartedAt.
func (b *WorkstreamInstanceBuilder) SetStartedAt(value string) *WorkstreamInstanceBuilder {
	return b.StartedAt(value)
}

// StatusHistory sets the status_history field
func (b *WorkstreamInstanceBuilder) StatusHistory(value []string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyStatusHistory, value)
	return b
}

// SetStatusHistory is a compatibility alias for StatusHistory.
func (b *WorkstreamInstanceBuilder) SetStatusHistory(value []string) *WorkstreamInstanceBuilder {
	return b.StatusHistory(value)
}

// TargetDate sets the target_date field
func (b *WorkstreamInstanceBuilder) TargetDate(value string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyTargetDate, value)
	return b
}

// SetTargetDate is a compatibility alias for TargetDate.
func (b *WorkstreamInstanceBuilder) SetTargetDate(value string) *WorkstreamInstanceBuilder {
	return b.TargetDate(value)
}

// Title sets the title field
func (b *WorkstreamInstanceBuilder) Title(value string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyTitle, value)
	return b
}

// SetTitle is a compatibility alias for Title.
func (b *WorkstreamInstanceBuilder) SetTitle(value string) *WorkstreamInstanceBuilder {
	return b.Title(value)
}

// WorkflowRef sets the workflow_ref field
func (b *WorkstreamInstanceBuilder) WorkflowRef(value string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyWorkflowRef, value)
	return b
}

// SetWorkflowRef is a compatibility alias for WorkflowRef.
func (b *WorkstreamInstanceBuilder) SetWorkflowRef(value string) *WorkstreamInstanceBuilder {
	return b.WorkflowRef(value)
}

// WorkstreamRefs sets the workstream_refs field
func (b *WorkstreamInstanceBuilder) WorkstreamRefs(value []string) *WorkstreamInstanceBuilder {
	b.SetField(objects.FieldKeyWorkstreamRefs, value)
	return b
}

// SetWorkstreamRefs is a compatibility alias for WorkstreamRefs.
func (b *WorkstreamInstanceBuilder) SetWorkstreamRefs(value []string) *WorkstreamInstanceBuilder {
	return b.WorkstreamRefs(value)
}

func init() {
	instance_builders.RegisterBuilder(NewWorkstreamInstanceBuilder(objects.DefaultSchemaVersion))
}
