// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec/lifecycle YAML.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package brand

import (
	base_objectenum "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/base_object"
	shared_brandsenum "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/shared_brands"
)

type PriorityTier = base_objectenum.PriorityTier

const (
	PriorityTierP0 PriorityTier = base_objectenum.PriorityTierP0
	PriorityTierP1 PriorityTier = base_objectenum.PriorityTierP1
	PriorityTierP2 PriorityTier = base_objectenum.PriorityTierP2
	PriorityTierP3 PriorityTier = base_objectenum.PriorityTierP3
)

type PropagationMode string

const (
	PropagationModeImmediate PropagationMode = "immediate"
	PropagationModeManual    PropagationMode = "manual"
	PropagationModeScheduled PropagationMode = "scheduled"
	PropagationModeVersioned PropagationMode = "versioned"
)

type SourceType = base_objectenum.SourceType

const (
	SourceTypeExternal SourceType = base_objectenum.SourceTypeExternal
	SourceTypeImported SourceType = base_objectenum.SourceTypeImported
	SourceTypeInternal SourceType = base_objectenum.SourceTypeInternal
)

type Status = shared_brandsenum.Status

const (
	StatusApproved    Status = shared_brandsenum.StatusApproved
	StatusArchived    Status = shared_brandsenum.StatusArchived
	StatusError       Status = shared_brandsenum.StatusError
	StatusImplemented Status = shared_brandsenum.StatusImplemented
	StatusInProgress  Status = shared_brandsenum.StatusInProgress
	StatusProposed    Status = shared_brandsenum.StatusProposed
)
