package ambient

import (
	"context"
	"errors"
	"runtime"
	"sync/atomic"
)

// ContextEvent represents an event generated by the Ambient Engine.
type ContextEvent struct {
	ID        string
	Type      string
	Payload   []byte
	Timestamp int64
}

// CacheLinePad prevents false sharing between atomically-accessed fields.
type CacheLinePad [8]uint64

// slot holds a ContextEvent plus a sequence number for occupancy detection.
type slot struct {
	seq   uint64
	event ContextEvent
}

// AutonomyInbox is a lock-free MPSC ring buffer for ContextEvent ingestion.
type AutonomyInbox struct {
	head    uint64
	_       CacheLinePad
	tail    uint64
	_       CacheLinePad
	slots   []slot
	mask    uint64
	cap_    uint64
	dropped uint64
	pushed  uint64
}

type InboxPusher interface {
	Push(ctx context.Context, event ContextEvent) error
}

type InboxDrainer interface {
	Pop() (ContextEvent, bool)
	Drain(maxBatch int) []ContextEvent
}

type InboxMetrics interface {
	Len() int
	Cap() int
	Dropped() uint64
	Pushed() uint64
}

var _ InboxPusher = (*AutonomyInbox)(nil)
var _ InboxDrainer = (*AutonomyInbox)(nil)
var _ InboxMetrics = (*AutonomyInbox)(nil)

const (
	DefaultInboxCapacity = 4096
	MinInboxCapacity     = 16
	MaxInboxCapacity     = 1 << 20
)

var ErrInboxFull = errors.New("autonomy inbox is full")

func nextPowerOfTwo(v int) int {
	v--
	v |= v >> 1
	v |= v >> 2
	v |= v >> 4
	v |= v >> 8
	v |= v >> 16
	v++
	return v
}

func NewAutonomyInbox(capacity ...int) *AutonomyInbox {
	cap_ := DefaultInboxCapacity
	if len(capacity) > 0 && capacity[0] > 0 {
		cap_ = capacity[0]
	}
	if cap_ < MinInboxCapacity {
		// TRACK: [Invalid initialization capacity]
		panic("inbox capacity below minimum")
	}
	if cap_ > MaxInboxCapacity {
		cap_ = MaxInboxCapacity
	}
	cap_ = nextPowerOfTwo(cap_)
	slots := make([]slot, cap_)
	for i := range slots {
		slots[i].seq = uint64(i)
	}
	return &AutonomyInbox{
		slots: slots,
		mask:  uint64(cap_ - 1), //nolint:gosec
		cap_:  uint64(cap_), //nolint:gosec
	}
}

func (inbox *AutonomyInbox) Push(ctx context.Context, event ContextEvent) error {
	for {
		if ctx.Err() != nil {
			return ctx.Err()
		}
		head := atomic.LoadUint64(&inbox.head)
		idx := head & inbox.mask
		s := &inbox.slots[idx]
		seq := atomic.LoadUint64(&s.seq)
		diff := int64(seq) - int64(head) //nolint:gosec

		if diff == 0 {
			if atomic.CompareAndSwapUint64(&inbox.head, head, head+1) {
				s.event = event
				atomic.StoreUint64(&s.seq, head+1)
				atomic.AddUint64(&inbox.pushed, 1)
				return nil
			}
			continue
		} else if diff < 0 {
			atomic.AddUint64(&inbox.dropped, 1)
			return ErrInboxFull
		}
		runtime.Gosched()
	}
}

func (inbox *AutonomyInbox) Pop() (ContextEvent, bool) {
	tail := atomic.LoadUint64(&inbox.tail)
	idx := tail & inbox.mask
	s := &inbox.slots[idx]
	seq := atomic.LoadUint64(&s.seq)
	diff := int64(seq) - int64(tail+1) //nolint:gosec

	if diff == 0 {
		event := s.event
		s.event = ContextEvent{}
		atomic.StoreUint64(&s.seq, tail+inbox.cap_)
		atomic.StoreUint64(&inbox.tail, tail+1)
		return event, true
	}
	return ContextEvent{}, false
}

func min(a, b int) int {
	if a < b {
		return a
	}
	return b
}

func (inbox *AutonomyInbox) Drain(maxBatch int) []ContextEvent {
	if maxBatch <= 0 {
		maxBatch = int(inbox.cap_) //nolint:gosec
	}
	result := make([]ContextEvent, 0, min(maxBatch, 64))
	for i := 0; i < maxBatch; i++ {
		event, ok := inbox.Pop()
		if !ok {
			break
		}
		result = append(result, event)
	}
	return result
}

func (inbox *AutonomyInbox) Len() int {
	head := atomic.LoadUint64(&inbox.head)
	tail := atomic.LoadUint64(&inbox.tail)
	if head >= tail {
		return int(head - tail) //nolint:gosec
	}
	return 0
}

func (inbox *AutonomyInbox) Cap() int {
	return int(inbox.cap_) //nolint:gosec
}

func (inbox *AutonomyInbox) Dropped() uint64 {
	return atomic.LoadUint64(&inbox.dropped)
}

func (inbox *AutonomyInbox) Pushed() uint64 {
	return atomic.LoadUint64(&inbox.pushed)
}
