package gitconstants

// Centralized Git CLI command, subcommand, action, and flag constants.
// Used across all git wrapper and execution invocations in ZQK to prevent
// hardcoded string literals and ensure consistency.

const (
	// Binary name
	BinaryGit = "git"

	// Primary Subcommands
	SubcmdAdd        = "add"
	SubcmdBranch     = "branch"
	SubcmdCatFile    = "cat-file"
	SubcmdCheckout   = "checkout"
	SubcmdCherry     = "cherry"
	SubcmdClean      = "clean"
	SubcmdClone      = "clone"
	SubcmdCommit     = "commit"
	SubcmdConfig     = "config"
	SubcmdDiff       = "diff"
	SubcmdDiffTree   = "diff-tree"
	SubcmdFetch      = "fetch"
	SubcmdForEachRef = "for-each-ref"
	SubcmdInit       = "init"
	SubcmdLog        = "log"
	SubcmdLsFiles    = "ls-files"
	SubcmdMerge      = "merge"
	SubcmdMergeBase  = "merge-base"
	SubcmdPull       = "pull"
	SubcmdPush       = "push"
	SubcmdRebase     = "rebase"
	SubcmdRemote     = "remote"
	SubcmdReset      = "reset"
	SubcmdRevList    = "rev-list"
	SubcmdRevParse   = "rev-parse"
	SubcmdShow       = "show"
	SubcmdShowRef    = "show-ref"
	SubcmdStash      = "stash"
	SubcmdStatus     = "status"
	SubcmdTag        = "tag"
	SubcmdUpdateRef  = "update-ref"
	SubcmdWorktree   = "worktree"

	// Subcommand Actions (verbs passed to subcommands like worktree or remote)
	ActionAdd    = "add"
	ActionGetURL = "get-url"
	ActionList   = "list"
	ActionLock   = "lock"
	ActionMove   = "move"
	ActionPrune  = "prune"
	ActionPush   = "push"
	ActionRemove = "remove"
	ActionUnlock = "unlock"

	// Flags and Switches
	FlagAbbrevRef             = "--abbrev-ref"
	FlagAll                   = "--all"
	FlagAllShort              = "-A"
	FlagAllowEmpty            = "--allow-empty"
	FlagBranch                = "-b"
	FlagBranchForce           = "-B"
	FlagC                     = "-c"
	FlagCapitalC              = "-C"
	FlagCached                = "--cached"
	FlagCleanForceDirs        = "-fd"
	FlagContains              = "--contains"
	FlagCount                 = "--count"
	FlagDate                  = "--date"
	FlagDelete                = "--delete"
	FlagDeleteForce           = "-D"
	FlagDeleteShort           = "-d"
	FlagDiffFilterEquals      = "--diff-filter="
	FlagDoubleDash            = "--"
	FlagErrorUnmatch          = "--error-unmatch"
	FlagExclude               = "-e"
	FlagExcludeLong           = "--exclude"
	FlagExcludeStandard       = "--exclude-standard"
	FlagForce                 = "-f"
	FlagForceLong             = "--force"
	FlagFormat                = "--format"
	FlagFormatEquals          = "--format="
	FlagGitCommonDir          = "--git-common-dir"
	FlagGitDir                = "--git-dir"
	FlagHard                  = "--hard"
	FlagHead                  = "HEAD"
	FlagIncludeUntrackedShort = "-u"
	FlagIncludeUntrackedLong  = "--include-untracked"
	FlagIsAncestor            = "--is-ancestor"
	FlagList                  = "--list"
	FlagMerged                = "--merged"
	FlagMessage               = "-m"
	FlagNameOnly              = "--name-only"
	FlagNameStatus            = "--name-status"
	FlagNoCommitID            = "--no-commit-id"
	FlagNumberShort           = "-n"
	FlagOneline               = "--oneline"
	FlagOthers                = "--others"
	FlagPorcelain             = "--porcelain"
	FlagPrettyEquals          = "--pretty="
	FlagPrune                 = "--prune"
	FlagQuiet                 = "-q"
	FlagQuietLong             = "--quiet"
	FlagRemotes               = "-r"
	FlagRemoteAndLocal        = "-a"
	FlagShort                 = "-s"
	FlagShortLong             = "--short"
	FlagShowCurrent           = "--show-current"
	FlagStat                  = "--stat"
	FlagSummary               = "--summary"
	FlagUntrackedAll          = "-uall"
	FlagVerify                = "--verify"

	// Common Reference Prefixes and Names
	RefPrefixHeads   = "refs/heads/"
	RefPrefixRemotes = "refs/remotes/"
	RefPrefixTags    = "refs/tags/"
	RefPrefixArchive = "refs/archive/"
	RemoteOrigin     = "origin"
)
