// Code generated by scripts/generate_enum_tests.py; DO NOT EDIT.

package scheduler_handler_bindings

import (
	"testing"
)

func TestEnums_Completeness(t *testing.T) {
	tests := []struct {
		name string
		val  string
	}{
		{"HandlerKeyAggregationMetricsCleanup", string(HandlerKeyAggregationMetricsCleanup)},
		{"HandlerKeyAuditEventAggregation", string(HandlerKeyAuditEventAggregation)},
		{"HandlerKeyAutofixBatchCleanup", string(HandlerKeyAutofixBatchCleanup)},
		{"HandlerKeyCacheInvalidation", string(HandlerKeyCacheInvalidation)},
		{"HandlerKeyCachePrewarm", string(HandlerKeyCachePrewarm)},
		{"HandlerKeyCallbackListener", string(HandlerKeyCallbackListener)},
		{"HandlerKeyCascadeUpdate", string(HandlerKeyCascadeUpdate)},
		{"HandlerKeyChangeJournalAggregation", string(HandlerKeyChangeJournalAggregation)},
		{"HandlerKeyCleanup", string(HandlerKeyCleanup)},
		{"HandlerKeyContextRefresh", string(HandlerKeyContextRefresh)},
		{"HandlerKeyConvergenceSessionTick", string(HandlerKeyConvergenceSessionTick)},
		{"HandlerKeyDataCellEnvelopeTick", string(HandlerKeyDataCellEnvelopeTick)},
		{"HandlerKeyGenericMetricsCleanup", string(HandlerKeyGenericMetricsCleanup)},
		{"HandlerKeyIntegrityCheck", string(HandlerKeyIntegrityCheck)},
		{"HandlerKeyLifecycleCheck", string(HandlerKeyLifecycleCheck)},
		{"HandlerKeyMaintenance", string(HandlerKeyMaintenance)},
		{"HandlerKeyMetricsCollection", string(HandlerKeyMetricsCollection)},
		{"HandlerKeyObjectValidation", string(HandlerKeyObjectValidation)},
		{"HandlerKeyOperationExecution", string(HandlerKeyOperationExecution)},
		{"HandlerKeyRetentionTolerance", string(HandlerKeyRetentionTolerance)},
		{"HandlerKeyRunWrapper", string(HandlerKeyRunWrapper)},
		{"HandlerKeySchedulerEventsAggregation", string(HandlerKeySchedulerEventsAggregation)},
		{"HandlerKeySchedulerJobRetention", string(HandlerKeySchedulerJobRetention)},
		{"HandlerKeyTestIo", string(HandlerKeyTestIo)},
		{"JobTypeAggregation", string(JobTypeAggregation)},
		{"JobTypeAggregationMetricsCleanup", string(JobTypeAggregationMetricsCleanup)},
		{"JobTypeAuditEventAggregation", string(JobTypeAuditEventAggregation)},
		{"JobTypeAutofixBatchCleanup", string(JobTypeAutofixBatchCleanup)},
		{"JobTypeCacheInvalidation", string(JobTypeCacheInvalidation)},
		{"JobTypeCachePrewarm", string(JobTypeCachePrewarm)},
		{"JobTypeCallbackListener", string(JobTypeCallbackListener)},
		{"JobTypeCascadeUpdate", string(JobTypeCascadeUpdate)},
		{"JobTypeChangeJournalAggregation", string(JobTypeChangeJournalAggregation)},
		{"JobTypeCleanup", string(JobTypeCleanup)},
		{"JobTypeContextRefresh", string(JobTypeContextRefresh)},
		{"JobTypeConvergenceSessionTick", string(JobTypeConvergenceSessionTick)},
		{"JobTypeDataCellEnvelopeTick", string(JobTypeDataCellEnvelopeTick)},
		{"JobTypeGenericMetricsCleanup", string(JobTypeGenericMetricsCleanup)},
		{"JobTypeIntegrityCheck", string(JobTypeIntegrityCheck)},
		{"JobTypeLifecycleCheck", string(JobTypeLifecycleCheck)},
		{"JobTypeMaintenance", string(JobTypeMaintenance)},
		{"JobTypeManifestSnapshot", string(JobTypeManifestSnapshot)},
		{"JobTypeMetricsCollection", string(JobTypeMetricsCollection)},
		{"JobTypeObjectValidation", string(JobTypeObjectValidation)},
		{"JobTypeOperationExecution", string(JobTypeOperationExecution)},
		{"JobTypeRetentionTolerance", string(JobTypeRetentionTolerance)},
		{"JobTypeRunWrapper", string(JobTypeRunWrapper)},
		{"JobTypeSchedulerEventsAggregation", string(JobTypeSchedulerEventsAggregation)},
		{"JobTypeSchedulerJobRetention", string(JobTypeSchedulerJobRetention)},
		{"JobTypeTestRunner", string(JobTypeTestRunner)},
		{"PriorityTierP0", string(PriorityTierP0)},
		{"PriorityTierP1", string(PriorityTierP1)},
		{"PriorityTierP2", string(PriorityTierP2)},
		{"PriorityTierP3", string(PriorityTierP3)},
		{"SourceTypeExternal", string(SourceTypeExternal)},
		{"SourceTypeImported", string(SourceTypeImported)},
		{"SourceTypeInternal", string(SourceTypeInternal)},
		{"StatusApproved", string(StatusApproved)},
		{"StatusArchived", string(StatusArchived)},
		{"StatusError", string(StatusError)},
		{"StatusImplemented", string(StatusImplemented)},
		{"StatusInProgress", string(StatusInProgress)},
		{"StatusProposed", string(StatusProposed)},
	}
	for _, tt := range tests {
		if tt.val == "" {
			t.Errorf("constant %s has empty value", tt.name)
		}
	}
}
