// Code generated by scripts/generate_enum_tests.py; DO NOT EDIT.

package change_journal

import (
	"testing"
)

func TestEnums_Completeness(t *testing.T) {
	tests := []struct {
		name string
		val  string
	}{
		{"ChangeTypeCreate", string(ChangeTypeCreate)},
		{"ChangeTypeDelete", string(ChangeTypeDelete)},
		{"ChangeTypeHealthCheck", string(ChangeTypeHealthCheck)},
		{"ChangeTypeImport", string(ChangeTypeImport)},
		{"ChangeTypeUpdate", string(ChangeTypeUpdate)},
		{"PriorityTierP0", string(PriorityTierP0)},
		{"PriorityTierP1", string(PriorityTierP1)},
		{"PriorityTierP2", string(PriorityTierP2)},
		{"PriorityTierP3", string(PriorityTierP3)},
		{"SourceTypeExternal", string(SourceTypeExternal)},
		{"SourceTypeImported", string(SourceTypeImported)},
		{"SourceTypeInternal", string(SourceTypeInternal)},
		{"StatusAggregated", string(StatusAggregated)},
		{"StatusArchived", string(StatusArchived)},
		{"StatusCompleted", string(StatusCompleted)},
		{"StatusError", string(StatusError)},
		{"StatusFailed", string(StatusFailed)},
		{"StatusPending", string(StatusPending)},
		{"StatusReverted", string(StatusReverted)},
	}
	for _, tt := range tests {
		if tt.val == "" {
			t.Errorf("constant %s has empty value", tt.name)
		}
	}
}
