package storage

const (
	ConstStream20060102t150405                                   = `2006-01-02T15:04:05`
	ConstStreamAccountAcc001                                     = `account:ACC-001`
	ConstStreamAccountTestuser                                   = `account:testuser`
	ConstStreamAgentArch03d                                      = `AGENT-ARCH-%03d`
	ConstStreamAgentPrep03d                                      = `AGENT-PREP-%03d`
	ConstStreamAggregatedEntryCount                              = `aggregated_entry_count`
	ConstStreamAggregatingFederatedProjectData                   = `aggregating federated project data`
	ConstStreamAnyXInNStrWhereXStr                               = `any(x IN n.%s WHERE x = $%s)`
	ConstStreamAtLeastOneAggregationIsRequired                   = `at least one aggregation is required`
	ConstStreamAvgAggregationRequiresAField                      = `avg aggregation requires a field`
	ConstStreamBackgroundWorker                                  = `background_worker`
	ConstStreamBatchCasDeleteStrErr                              = `batch CAS delete %s: %w`
	ConstStreamBatchStreamDeletedStrErr                          = `batch stream deleted %s: %w`
	ConstStreamBlockingIssuesDetectedResolveCriticalViolations   = `blocking issues detected - resolve critical violations before performing write operations:\n`
	ConstStreamBuildingPathCacheAliases                          = `building path cache aliases`
	ConstStreamBuildingPathCacheellipsis                         = `Building path cache...`
	ConstStreamCStrKStrPStr                                      = `c=%s|k=%s|p=%s`
	ConstStreamCacheCheckerAddr                                  = `cache_checker_addr`
	ConstStreamCacheCheckerSet                                   = `cache_checker_set`
	ConstStreamCachedFilePath                                    = `cached_file_path`
	ConstStreamCannotDeleteObjectStrIntDependentObjectSStill     = `cannot delete object %s: %d dependent object(s) still reference it (use --unlink-references to remove references from dependents, or cascade=true to delete dependents)`
	ConstStreamCannotDetermineObjectKindForReferenceStrInField   = `cannot determine object kind for reference %s in field %s: %w`
	ConstStreamCannotInferKindFromId                             = `cannot infer kind from ID`
	ConstStreamCannotParseTimestampFromTypeType                  = `cannot parse timestamp from type %T`
	ConstStreamCasHashMismatchForStrKindStrErr                   = `CAS hash mismatch for %s (kind: %s): %w`
	ConstStreamCasIndexDrainCollector                            = `cas_index_drain_collector`
	ConstStreamCasIndexDrainWait                                 = `cas_index_drain_wait`
	ConstStreamCasIndexQueueStrInt                               = `cas_index_queue_%s_%d`
	ConstStreamCasIndexReconciliationWorker                      = `CAS index reconciliation worker`
	ConstStreamCasIndexRefreshFallback                           = `CAS index refresh fallback`
	ConstStreamCasIndexRemove                                    = `cas_index_remove`
	ConstStreamCasIndexStateChangeEvent                          = `cas_index_state_change_event`
	ConstStreamCasIndexUpdate                                    = `cas_index_update`
	ConstStreamCasIndexWorkerLifecycle                           = `cas_index_worker_lifecycle`
	ConstStreamCasIndexWriteQueueWorker                          = `cas_index_write_queue_worker`
	ConstStreamCasMetricsAsyncWorker                             = `cas_metrics_async_worker`
	ConstStreamCasMetricsIntOperationsFromStrToStr               = `CAS Metrics: %d operations from %s to %s`
	ConstStreamCasOperations                                     = `cas_operations`
	ConstStreamCasOrphanCleanup                                  = `cas_orphan_cleanup`
	ConstStreamCasOrphanCleanupDrainWait                         = `cas_orphan_cleanup_drain_wait`
	ConstStreamCasOrphanCleanupQueue                             = `cas_orphan_cleanup_queue`
	ConstStreamCasOrphanCleanupRetry                             = `cas_orphan_cleanup_retry`
	ConstStreamCasOrphanCleanupShutdownWait                      = `cas_orphan_cleanup_shutdown_wait`
	ConstStreamCasOrphanCleanupWorker                            = `cas_orphan_cleanup_worker`
	ConstStreamCasReadFailedForStrKindStrErr                     = `CAS read failed for %s (kind: %s): %w`
	ConstStreamCascadeDeleteFailed                               = `cascade delete failed`
	ConstStreamCaseWhenTolowerNTitleContainsStrOrTolowerN        = ` + CASE WHEN (toLower(n.title) CONTAINS $%s OR toLower(n.description) CONTAINS $%s OR toLower(n.body) CONTAINS $%s) THEN 1.0 ELSE 0.0 END`
	ConstStreamChangeNotification                                = `change_notification`
	ConstStreamCheckExistsStrErr                                 = `check exists %s: %w`
	ConstStreamCheckerIsNil                                      = `checker_is_nil`
	ConstStreamCleanedUpIntOrphanedCasHashFilesIntSucceededInt   = `Cleaned up %d orphaned CAS hash files (%d succeeded, %d failed) in %v`
	ConstStreamContentAddressed                                  = `content_addressed_`
	ConstStreamContentAddressed2                                 = `content_addressed`
	ConstStreamContentAddressedAvgDeleteTimeMs                   = `content_addressed_avg_delete_time_ms`
	ConstStreamContentAddressedAvgPutTimeMs                      = `content_addressed_avg_put_time_ms`
	ConstStreamContentAddressedAvgReadTimeMs                     = `content_addressed_avg_read_time_ms`
	ConstStreamContentAddressedAvgUpdateTimeMs                   = `content_addressed_avg_update_time_ms`
	ConstStreamContentAddressedDelete                            = `content_addressed_delete`
	ConstStreamContentAddressedDeletes                           = `content_addressed_deletes`
	ConstStreamContentAddressedMaxDeleteTimeMs                   = `content_addressed_max_delete_time_ms`
	ConstStreamContentAddressedMaxPutTimeMs                      = `content_addressed_max_put_time_ms`
	ConstStreamContentAddressedMaxReadTimeMs                     = `content_addressed_max_read_time_ms`
	ConstStreamContentAddressedMaxUpdateTimeMs                   = `content_addressed_max_update_time_ms`
	ConstStreamContentAddressedMeasurementWindowEnd              = `content_addressed_measurement_window_end`
	ConstStreamContentAddressedMeasurementWindowStart            = `content_addressed_measurement_window_start`
	ConstStreamContentAddressedPut                               = `content_addressed_put`
	ConstStreamContentAddressedPuts                              = `content_addressed_puts`
	ConstStreamContentAddressedRead                              = `content_addressed_read`
	ConstStreamContentAddressedReads                             = `content_addressed_reads`
	ConstStreamContentAddressedUpdates                           = `content_addressed_updates`
	ConstStreamCorruptfilepathIsRequired                         = `corruptFilePath is required`
	ConstStreamCouldNotFindProjectRoot                           = `could not find project root`
	ConstStreamCouldNotInferKindFromIdStr                        = `could not infer kind from ID: %s`
	ConstStreamCountFilterWorker                                 = `count filter worker`
	ConstStreamCountQueryDidNotReturnCountField                  = `count query did not return 'count' field`
	ConstStreamCountingLinesInSegment                            = `counting lines in segment`
	ConstStreamCreateWalDir                                      = `create WAL dir`
	ConstStreamD4D2D2                                            = `\\d{4}-\\d{2}-\\d{2}`
	ConstStreamDDD                                               = `\\d+\\.\\d+\\.\\d+`
	ConstStreamDecodeRecordDataForStrStrErr                      = `decode record data for %s %s: %w`
	ConstStreamDecodeWalRecordData                               = `decode WAL record data`
	ConstStreamDeleteOperationsMustBePerformedThroughCli         = `delete operations must be performed through CLI (unauthorized direct API call)`
	ConstStreamDrainTimeoutAfterVal                              = `drain timeout after %v`
	ConstStreamDryRunWouldWriteCorrectHashFileUpdateIndexAnd     = `DRY RUN: would write correct hash file, update index, and quarantine corrupt file`
	ConstStreamEllipsisAndIntMoreBlockingIssues                  = `... and %d more blocking issues`
	ConstStreamEmittingBatchProcessingEventViaCoordinator        = `emitting batch processing event via coordinator`
	ConstStreamEmittingBatchStartEventForStrSizeInt              = `emitting batch start event for %s (size %d)`
	ConstStreamEmittingBatchStrEventForStrSizeInt                = `emitting batch %s event for %s (size %d)`
	ConstStreamEmittingStateChangeProjectRootSet                 = `emitting state change project_root_set`
	ConstStreamEmittingStateChangeStorageSet                     = `emitting state change storage_set`
	ConstStreamEmittingWorkerLifecycleEventViaCoordinator        = `emitting worker lifecycle event via coordinator`
	ConstStreamEmittingWorkerShutdownEventForStr                 = `emitting worker shutdown event for %s`
	ConstStreamEmittingWorkerStartEventForStr                    = `emitting worker start event for %s`
	ConstStreamEnsurePathAliasCache                              = `ensure path alias cache`
	ConstStreamEntriesLoaded                                     = `entries_loaded`
	ConstStreamExistingProjectRoot                               = `existing_project_root`
	ConstStreamExistsInCache                                     = `exists_in_cache`
	ConstStreamExpectedUpdatedAt                                 = `expected_updated_at`
	ConstStreamExpectedYamlFileGotQuote                          = `expected YAML file, got %q`
	ConstStreamFailedFilesTruncated                              = `failed_files_truncated`
	ConstStreamFailedToAcquireCasIndexLockForSave                = `failed to acquire CAS index lock for save`
	ConstStreamFailedToAcquireLockForCasMetricsRecorderInitValN  = `failed to acquire lock for CAS metrics recorder init: %v\n`
	ConstStreamFailedToBeginTransaction                          = `failed to begin transaction`
	ConstStreamFailedToBeginTransactionForChunkStartingAtInt     = `failed to begin transaction for chunk starting at %d`
	ConstStreamFailedToBeginTransactionForDeleteChunkStartingAt  = `failed to begin transaction for delete chunk starting at %d`
	ConstStreamFailedToBuildCasMetricInstance                    = `failed to build cas_metric instance`
	ConstStreamFailedToCascadeDeleteDependentStrErr              = `failed to cascade delete dependent %s: %w`
	ConstStreamFailedToCheckDependencies                         = `failed to check dependencies`
	ConstStreamFailedToCheckDependenciesAfterUnlink              = `failed to check dependencies after unlink`
	ConstStreamFailedToCheckFileExistence                        = `failed to check file existence`
	ConstStreamFailedToCheckIfListingindexwritequeueIsDrained    = `failed to check if ListingIndexWriteQueue is drained: %v\n`
	ConstStreamFailedToCheckIfNewIdExists                        = `failed to check if new ID exists`
	ConstStreamFailedToCheckIfObjectExists                       = `failed to check if object exists`
	ConstStreamFailedToCheckStreamBackedObjectExistence          = `failed to check stream-backed object existence`
	ConstStreamFailedToCloseDirStrAfterOrphanRemovalValN         = `failed to close dir %s after orphan removal: %v\n`
	ConstStreamFailedToCloseTempWalFile                          = `failed to close temp WAL file`
	ConstStreamFailedToCollectFilePaths                          = `failed to collect file paths`
	ConstStreamFailedToCommitBulkCreateTransaction               = `failed to commit bulk create transaction`
	ConstStreamFailedToCommitBulkDeleteTransaction               = `failed to commit bulk delete transaction`
	ConstStreamFailedToCommitBulkUpdateTransaction               = `failed to commit bulk update transaction`
	ConstStreamFailedToCreateCasInstanceForKindStrErr            = `failed to create CAS instance for kind %s: %w`
	ConstStreamFailedToCreateCasMetric                           = `failed to create CAS metric`
	ConstStreamFailedToCreateCasOrphanCleanupBatchAuditEventValN = `failed to create CAS orphan cleanup batch audit event: %v\n`
	ConstStreamFailedToCreateObjectAtIndexIntVal                 = `failed to create object at index %d: %v`
	ConstStreamFailedToCreateObjectInCas                         = `failed to create object in CAS`
	ConstStreamFailedToCreateObjectStrErr                        = `failed to create object %s: %w`
	ConstStreamFailedToCreateQuarantineDir                       = `failed to create quarantine dir`
	ConstStreamFailedToCreateTargetDirectory                     = `failed to create target directory`
	ConstStreamFailedToCreateTempWalFile                         = `failed to create temp WAL file`
	ConstStreamFailedToCreateTestObjectStrForKindStrValSkipping  = `failed to create test object %s for kind %s: %v (skipping)`
	ConstStreamFailedToDeleteObjectStrErr                        = `failed to delete object %s: %w`
	ConstStreamFailedToDeleteObjectStrObjectStillExists          = `failed to delete object %s: object still exists`
	ConstStreamFailedToDeleteObjectStrVal                        = `failed to delete object %s: %v`
	ConstStreamFailedToDisableAsyncCasMetricsCollectorValN       = `failed to disable async CAS metrics collector: %v\n`
	ConstStreamFailedToEnsureIdForObjectAtIndexIntVal            = `failed to ensure ID for object at index %d: %v`
	ConstStreamFailedToExecuteAggregationQuery                   = `failed to execute aggregation query`
	ConstStreamFailedToExecuteCountQuery                         = `failed to execute count query`
	ConstStreamFailedToExecuteQuery                              = `failed to execute query`
	ConstStreamFailedToExecuteSearchQuery                        = `failed to execute search query`
	ConstStreamFailedToFindDependents                            = `failed to find dependents`
	ConstStreamFailedToFlushAllCasIndexesVal                     = `Failed to flush all CAS indexes: %v`
	ConstStreamFailedToFlushCasIndexForStrVal                    = `Failed to flush CAS index for %s: %v`
	ConstStreamFailedToFlushWalFile                              = `failed to flush WAL file`
	ConstStreamFailedToGetAllKinds                               = `failed to get all kinds`
	ConstStreamFailedToGetAllMappings                            = `failed to get all mappings`
	ConstStreamFailedToGetCasIndexQueueForKindStrValN            = `failed to get CAS index queue for kind %s: %v\n`
	ConstStreamFailedToGetCasIndexQueueStatsCopyValN             = `failed to get CAS index queue stats copy: %v\n`
	ConstStreamFailedToGetCasIndexQueueStatsForKindStrValN       = `failed to get CAS index queue stats for kind %s: %v\n`
	ConstStreamFailedToGetCasIndexTotalPendingCountValN          = `failed to get CAS index total pending count: %v\n`
	ConstStreamFailedToGetLatestSchemaVersionForCommandMetric    = `failed to get latest schema version for command_metric`
	ConstStreamFailedToGetListingIndexBatchEventCallbackValN     = `failed to get listing index batch event callback: %v\n`
	ConstStreamFailedToGetListingIndexStateChangeEventCallback   = `failed to get listing index state change event callback: %v\n`
	ConstStreamFailedToGetListingIndexWriteQueueFactoryValN      = `failed to get listing index write queue factory: %v\n`
	ConstStreamFailedToGetOrphanCleanupEventCallbackValN         = `failed to get orphan cleanup event callback: %v\n`
	ConstStreamFailedToListIdsAfterReconciliation                = `failed to list IDs after reconciliation`
	ConstStreamFailedToListIdsFromContentAddressableStorage      = `failed to list IDs from content-addressable storage`
	ConstStreamFailedToListObjectsForAggregation                 = `failed to list objects for aggregation`
	ConstStreamFailedToLoadFieldRegistry                         = `failed to load field registry`
	ConstStreamFailedToLoadIdPatterns                            = `failed to load ID patterns`
	ConstStreamFailedToMarshalObject                             = `failed to marshal object`
	ConstStreamFailedToMarshalUpdatedObject                      = `failed to marshal updated object`
	ConstStreamFailedToMarshalWalRecord                          = `failed to marshal WAL record`
	ConstStreamFailedToMergeBatchIntoInMemoryIndexValN           = `failed to merge batch into in-memory index: %v\n`
	ConstStreamFailedToMigrateStrErr                             = `failed to migrate %s: %w`
	ConstStreamFailedToMirrorBulkcreateToSecondaryStorage        = `failed to mirror BulkCreate to secondary storage`
	ConstStreamFailedToMirrorBulkdeleteToSecondaryStorage        = `failed to mirror BulkDelete to secondary storage`
	ConstStreamFailedToMirrorBulkupdateToSecondaryStorage        = `failed to mirror BulkUpdate to secondary storage`
	ConstStreamFailedToMirrorCreateToSecondaryStorage            = `failed to mirror Create to secondary storage`
	ConstStreamFailedToMirrorDeleteToSecondaryStorage            = `failed to mirror Delete to secondary storage`
	ConstStreamFailedToMirrorMoveToSecondaryStorage              = `failed to mirror Move to secondary storage`
	ConstStreamFailedToMirrorRenameToSecondaryStorage            = `failed to mirror Rename to secondary storage`
	ConstStreamFailedToMirrorTransactionCommitToSecondaryStorage = `failed to mirror transaction Commit to secondary storage`
	ConstStreamFailedToMirrorUpdateToSecondaryStorage            = `failed to mirror Update to secondary storage`
	ConstStreamFailedToMirrorUpdateToSecondaryStorageForStr      = `failed to mirror Update to secondary storage for %s`
	ConstStreamFailedToOpenWalFile                               = `failed to open WAL file`
	ConstStreamFailedToParseIdBasedFile                          = `failed to parse ID-based file`
	ConstStreamFailedToPersistHashRegistryForNewLocationErrMove  = `failed to persist hash registry for new location: %w (move rolled back)`
	ConstStreamFailedToProcessFinalBatchForStrDuringShutdownValN = `failed to process final batch for %s during shutdown: %v\n`
	ConstStreamFailedToQuarantineCorruptFileRenameFailedVal      = `failed to quarantine corrupt file (rename failed: %v, write failed: %w)`
	ConstStreamFailedToQueryDependents                           = `failed to query dependents`
	ConstStreamFailedToReadCheckpoint                            = `failed to read checkpoint`
	ConstStreamFailedToReadDirectory                             = `failed to read directory`
	ConstStreamFailedToReadFile                                  = `failed to read file`
	ConstStreamFailedToReadObject                                = `failed to read object`
	ConstStreamFailedToReadObjectStrErr                          = `failed to read object %s: %w`
	ConstStreamFailedToReadObjectStrInPathErr                    = `failed to read object %s in path: %w`
	ConstStreamFailedToReadObjectStrVal                          = `failed to read object %s: %v`
	ConstStreamFailedToReadSourceFile                            = `failed to read source file`
	ConstStreamFailedToReadWalCheckpoint                         = `failed to read WAL checkpoint`
	ConstStreamFailedToReadWalFile                               = `failed to read WAL file`
	ConstStreamFailedToRecordContentAddressedDeleteMetricValN    = `failed to record content_addressed_delete metric: %v\n`
	ConstStreamFailedToRecordContentAddressedPutMetricValN       = `failed to record content_addressed_put metric: %v\n`
	ConstStreamFailedToRecordContentAddressedReadMetricValN      = `failed to record content_addressed_read metric: %v\n`
	ConstStreamFailedToRecordListingIndexLoadMetricValN          = `failed to record listing_index_load metric: %v\n`
	ConstStreamFailedToRecordListingIndexRemoveMappingMetricValN = `failed to record listing_index_remove_mapping metric: %v\n`
	ConstStreamFailedToRecordListingIndexSaveMetricValN          = `failed to record listing_index_save metric: %v\n`
	ConstStreamFailedToRecordListingIndexSetMappingMetricValN    = `failed to record listing_index_set_mapping metric: %v\n`
	ConstStreamFailedToRecreateFile                              = `failed to recreate file`
	ConstStreamFailedToReleaseCasIndexLockForStrValN             = `failed to release CAS index lock for %s: %v\n`
	ConstStreamFailedToRemoveCorruptFileAfterQuarantineCopy      = `failed to remove corrupt file after quarantine copy`
	ConstStreamFailedToRemoveFromIndex                           = `failed to remove from index`
	ConstStreamFailedToRemoveOldFileObjectMigratedToCas          = `failed to remove old file (object migrated to CAS)`
	ConstStreamFailedToRemoveOrphanedFileStrErr                  = `failed to remove orphaned file %s: %w`
	ConstStreamFailedToRemoveOrphanedTmpFileStrErr               = `failed to remove orphaned .tmp file %s: %w`
	ConstStreamFailedToRemoveTmpOrphanFileStrValN                = `failed to remove tmp orphan file %s: %v\n`
	ConstStreamFailedToReplaceWalFile                            = `failed to replace WAL file`
	ConstStreamFailedToSaveIndexAfterRemoval                     = `failed to save index after removal`
	ConstStreamFailedToSearchKindStrErr                          = `failed to search kind %s: %w`
	ConstStreamFailedToSetListingIndexBatchEventCallbackValN     = `failed to set listing index batch event callback: %v\n`
	ConstStreamFailedToSetListingIndexStateChangeEventCallback   = `failed to set listing index state change event callback: %v\n`
	ConstStreamFailedToSetListingIndexWriteQueueFactoryFor       = `failed to set listing index write queue factory for project root: %v\n`
	ConstStreamFailedToSetListingIndexWriteQueueFactoryValN      = `failed to set listing index write queue factory: %v\n`
	ConstStreamFailedToSetOrphanCleanupEventCallbackValN         = `failed to set orphan cleanup event callback: %v\n`
	ConstStreamFailedToSnapshotCasPointerValN                    = `failed to snapshot CAS pointer: %v\n`
	ConstStreamFailedToStatKindDirectory                         = `failed to stat kind directory`
	ConstStreamFailedToSyncDirStrAfterOrphanRemovalValN          = `failed to sync dir %s after orphan removal: %v\n`
	ConstStreamFailedToSyncWalFile                               = `failed to sync WAL file`
	ConstStreamFailedToUnmarshalObject                           = `failed to unmarshal object`
	ConstStreamFailedToUnmarshalObjectAfterCasDiscovery          = `failed to unmarshal object after CAS discovery`
	ConstStreamFailedToUnmarshalPendingObject                    = `failed to unmarshal pending object`
	ConstStreamFailedToUpdateCasIndexMapping                     = `failed to update CAS index mapping`
	ConstStreamFailedToUpdateCasIndexQueueForKindStrValN         = `failed to update CAS index queue for kind %s: %v\n`
	ConstStreamFailedToUpdateIndex                               = `failed to update index`
	ConstStreamFailedToUpdateNodeInGraph                         = `failed to update node in graph`
	ConstStreamFailedToUpdateObjectStrErr                        = `failed to update object %s: %w`
	ConstStreamFailedToUpdateObjectStrVal                        = `failed to update object %s: %v`
	ConstStreamFailedToWalkBucketedDirectory                     = `failed to walk bucketed directory`
	ConstStreamFailedToWalkDirectoryUsingStrategy                = `failed to walk directory using strategy`
	ConstStreamFailedToWriteNewFile                              = `failed to write new file`
	ConstStreamFailedToWriteObjectToNewLocation                  = `failed to write object to new location`
	ConstStreamFailedToWriteRepairedCasFile                      = `failed to write repaired CAS file`
	ConstStreamFailedToWriteStreamCurrentForStrKindStrErr        = `failed to write stream_current for %s (kind: %s): %w`
	ConstStreamFailedToWriteWalNewline                           = `failed to write WAL newline`
	ConstStreamFailedToWriteWalRecord                            = `failed to write WAL record`
	ConstStreamFileBackendOnlySupportsFilterQueries              = `file backend only supports filter queries`
	ConstStreamFileExistsNoRecoveryNeeded                        = `File exists, no recovery needed`
	ConstStreamFileMissingAndRecoveryNotPossibleHashStr          = `file missing and recovery not possible (hash: %s)`
	ConstStreamFileMissingForHashStr                             = `File missing for hash %s`
	ConstStreamFileMissingRecoveryNotPossible                    = `File missing, recovery not possible`
	ConstStreamFileStorageCountFile                              = `file_storage_count_file`
	ConstStreamFileStorageCountResultsCloser                     = `file_storage_count_results_closer`
	ConstStreamFileStorageCountWaiter                            = `file_storage_count_waiter`
	ConstStreamFileStorageListAuditByIds                         = `file_storage_list_audit_by_ids`
	ConstStreamFileStorageListAuditByIdsCloser                   = `file_storage_list_audit_by_ids_closer`
	ConstStreamFileStorageListByPaths                            = `file_storage_list_by_paths`
	ConstStreamFileStorageListByPathsCloser                      = `file_storage_list_by_paths_closer`
	ConstStreamFileStorageListCasRead                            = `file_storage_list_cas_read`
	ConstStreamFileStorageListCasResultsCloser                   = `file_storage_list_cas_results_closer`
	ConstStreamFileStorageListCasWaiter                          = `file_storage_list_cas_waiter`
	ConstStreamFileStorageListResultsCloser                      = `file_storage_list_results_closer`
	ConstStreamFileStorageParseFile                              = `file_storage_parse_file`
	ConstStreamFilenameAlreadyMatchesContentHashNoRepairNeeded   = `filename already matches content hash; no repair needed`
	ConstStreamFixtureStrInt                                     = `Fixture: %s #%d`
	ConstStreamFlushCasIndexForKindQuoteErr                      = `flush CAS index for kind %q: %w`
	ConstStreamGraphBackendOnlySupportsCypherAndVectorQueries    = `graph backend only supports Cypher and Vector queries`
	ConstStreamGraphConnectionIsRequired                         = `graph connection is required`
	ConstStreamGroupingViolationObjectValHasStrNilButIsInGroup   = `grouping violation: object %v has %s=nil but is in group %s`
	ConstStreamGroupingViolationObjectValHasStrValStrStrButIsIn  = `grouping violation: object %v has %s=%v (str=%s) but is in group %s`
	ConstStreamHashRegistryCacheKeyInvalidExpectedKind0dirQuote  = `hash registry cache key invalid (expected kind\\0dir): %q`
	ConstStreamHighVolumeCacheCount                              = `high_volume_cache_count`
	ConstStreamIdAndKindRequiredForDeletebyidandkind             = `id and kind required for DeleteByIDAndKind`
	ConstStreamIdStrNotFoundInCasDirectoryStr                    = `ID %s not found in CAS directory %s`
	ConstStreamInvalidKindStrNoDirectoryMappingFound             = `invalid kind: %s (no directory mapping found)`
	ConstStreamInvalidReferenceStrInFieldStrErr                  = `invalid reference %s in field %s: %w`
	ConstStreamKindIsRequired                                    = `kind is required`
	ConstStreamKindMismatchObjectHasKindStrButExpectedStr        = `kind mismatch: object has kind %s but expected %s`
	ConstStreamKindStrDoesNotUseContentAddressableStorage        = `kind %s does not use content-addressable storage`
	ConstStreamKindsSearched                                     = `kinds_searched`
	ConstStreamLazyMigrationFailedDuringPrimaryCreateForStr      = `lazy migration failed during primary create for %s`
	ConstStreamLifecycleJobTrigger                               = `lifecycle_job_trigger`
	ConstStreamListAuditByIdsWorker                              = `list audit by IDs worker`
	ConstStreamListCasWorker                                     = `list CAS worker`
	ConstStreamListFileWorker                                    = `list file worker`
	ConstStreamListObjectsFromPathsWorker                        = `list objects from paths worker`
	ConstStreamListingIndex                                      = `listing_index_`
	ConstStreamListingIndexAvgTimeMs                             = `listing_index_avg_time_ms`
	ConstStreamListingIndexBatchEvent                            = `listing_index_batch_event`
	ConstStreamListingIndexEntriesAdded                          = `listing_index_entries_added`
	ConstStreamListingIndexEntriesRemoved                        = `listing_index_entries_removed`
	ConstStreamListingIndexFileLockAcquisitions                  = `listing_index_file_lock_acquisitions`
	ConstStreamListingIndexFileLockFailures                      = `listing_index_file_lock_failures`
	ConstStreamListingIndexFileLockWaitTimeMs                    = `listing_index_file_lock_wait_time_ms`
	ConstStreamListingIndexLoad                                  = `listing_index_load`
	ConstStreamListingIndexLoads                                 = `listing_index_loads`
	ConstStreamListingIndexLockContention                        = `listing_index_lock_contention`
	ConstStreamListingIndexLockWaitTimeMs                        = `listing_index_lock_wait_time_ms`
	ConstStreamListingIndexMaxTimeMs                             = `listing_index_max_time_ms`
	ConstStreamListingIndexMergeOperations                       = `listing_index_merge_operations`
	ConstStreamListingIndexReloads                               = `listing_index_reloads`
	ConstStreamListingIndexReloadsDuringSet                      = `listing_index_reloads_during_set`
	ConstStreamListingIndexRemoveMapping                         = `listing_index_remove_mapping`
	ConstStreamListingIndexRemoveMappings                        = `listing_index_remove_mappings`
	ConstStreamListingIndexSave                                  = `listing_index_save`
	ConstStreamListingIndexSaves                                 = `listing_index_saves`
	ConstStreamListingIndexSetMapping                            = `listing_index_set_mapping`
	ConstStreamListingIndexSetMappings                           = `listing_index_set_mappings`
	ConstStreamListingIndexSize                                  = `listing_index_size`
	ConstStreamListingIndexWriteQueue                            = `listing_index_write_queue`
	ConstStreamLockFailedInEnableValN                            = `lock failed in Enable: %v\n`
	ConstStreamLockFailedInStopValN                              = `lock failed in Stop: %v\n`
	ConstStreamMarshalStrErr                                     = `marshal %s: %w`
	ConstStreamMarshalUpdateStrErr                               = `marshal update %s: %w`
	ConstStreamMarshalWalBatch                                   = `marshal WAL batch`
	ConstStreamMarshalWalRecord                                  = `marshal WAL record`
	ConstStreamMatchNStrEntity                                   = `MATCH (n:%s:Entity)`
	ConstStreamMatchNstrEntity                                   = `MATCH (n%s:Entity)`
	ConstStreamMaxAggregationRequiresAField                      = `max aggregation requires a field`
	ConstStreamMeshQueryPool                                     = `mesh_query_pool`
	ConstStreamMetricIdNotSetAfterCreation                       = `metric ID not set after creation`
	ConstStreamMigrateObjectWalRenameStrToStrErr                 = `migrate object WAL: rename %s -> %s: %w`
	ConstStreamMigrateStreamSegmentsMoveStrErr                   = `migrate stream segments: move %s: %w`
	ConstStreamMigrateStreamSegmentsReadStreamsDir               = `migrate stream segments: read streams dir`
	ConstStreamMigrateStreamSegmentsRewriteRegistryStrErr        = `migrate stream segments: rewrite registry %s: %w`
	ConstStreamMinAggregationRequiresAField                      = `min aggregation requires a field`
	ConstStreamMoveOperationsMustBePerformedThroughCli           = `move operations must be performed through CLI (unauthorized direct API call)`
	ConstStreamMovedObjectStrFromKindStrToStr                    = `Moved object %s from kind %s to %s`
	ConstStreamN1CheckIfFileExistsLsLaStr                        = `\n    1. Check if file exists: ls -la %s`
	ConstStreamN1VerifyObjectExistsZqkObjectGetStr               = `\n    1. Verify object exists: zqk object get %s`
	ConstStreamN2SearchForFileFindStrNameStrstr                  = `\n    2. Search for file: find %s -name '%s%s'`
	ConstStreamN2VerifyObjectExistsZqkObjectGetStr               = `\n    2. Verify object exists: zqk object get %s`
	ConstStreamN3CheckIfKindDirectoryExistsLsLaStr               = `\n    3. Check if kind directory exists: ls -la %s`
	ConstStreamN3SearchForFileFindStrNameStrstr                  = `\n    3. Search for file: find %s -name '%s%s'`
	ConstStreamNDiagnosticSteps                                  = `\n  Diagnostic steps:`
	ConstStreamNDirectoryDoesNotExistStr                         = `\n  Directory does not exist: %s`
	ConstStreamNDirectoryExistsStr                               = `\n  Directory exists: %s`
	ConstStreamNExpectedFileStr                                  = `\n  Expected file: %s`
	ConstStreamNFilePathResolutionIssueCheckNamespaceOrBucketing = `\n    - File path resolution issue (check namespace or bucketing)`
	ConstStreamNIfObjectExistsButFileDoesnTThisMayIndicate       = `\n  If object exists but file doesn't, this may indicate:`
	ConstStreamNObjectIsStoredInGraphBackendInsteadOfFileBackend = `\n    - Object is stored in graph backend instead of file backend`
	ConstStreamNObjectWasCreatedOutsideFileStorage               = `\n    - Object was created outside file storage`
	ConstStreamNStrContainsStr                                   = `n.%s CONTAINS $%s`
	ConstStreamNStrEndsWithStr                                   = `n.%s ENDS WITH $%s`
	ConstStreamNStrStartsWithStr                                 = `n.%s STARTS WITH $%s`
	ConstStreamNewIdIsTheSameAsCurrentIdNoRenameNeeded           = `new ID is the same as current ID (no rename needed)`
	ConstStreamNewKindCannotBeEmpty                              = `new kind cannot be empty`
	ConstStreamNewProjectRoot                                    = `new_project_root`
	ConstStreamNonFunctional                                     = `non-functional`
	ConstStreamNormalizeExpectedCachecountinputGotType           = `NORMALIZE expected *cacheCountInput, got %T`
	ConstStreamNotNStrInStr                                      = `NOT n.%s IN $%s`
	ConstStreamObjectAtIndexIntMissingKindField                  = `object at index %d missing kind field`
	ConstStreamObjectIsAlreadyOfKindStrNoMoveNeeded              = `object is already of kind %s (no move needed)`
	ConstStreamObjectIsNilOrEmpty                                = `object is nil or empty`
	ConstStreamObjectMissingKindField                            = `object missing kind field`
	ConstStreamObjectMissingKindField2                           = `object missing 'kind' field`
	ConstStreamObjectMissingRequiredFieldId                      = `object missing required field: id`
	ConstStreamObjectMissingRequiredFieldKind                    = `object missing required field: kind`
	ConstStreamObjectMustHaveAnIdField                           = `object must have an 'id' field`
	ConstStreamObjectMustHaveKindAndId                           = `object must have kind and id`
	ConstStreamObjectNotInCasIndex                               = `Object not in CAS index`
	ConstStreamObjectStillExistsAfterDeletion                    = `object still exists after deletion`
	ConstStreamObjectStrKindStrNotFoundInStreamErr               = `object %s (kind: %s) not found in stream: %w`
	ConstStreamObjectStrKindStrNotFoundValErr                    = `object %s (kind: %s) not found: %v: %w`
	ConstStreamObjectStrMissingKindField                         = `object %s missing kind field`
	ConstStreamObjectValidationFailedBeforeMigrationSkippingTo   = `object validation failed before migration (skipping to avoid creating invalid object in CAS)`
	ConstStreamObjectWalRequiresNonEmptyProjectRoot              = `object WAL requires non-empty project root`
	ConstStreamObjectWithIdStrAlreadyExists                      = `object with ID %s already exists`
	ConstStreamObjectWriteBehindReplay                           = `object_write_behind_replay`
	ConstStreamObjectWriteBehindWorker                           = `object_write_behind_worker`
	ConstStreamObjectWriteBufferWaitUntilEmptyInterruptor        = `object write buffer wait until empty interruptor`
	ConstStreamObjectidIsRequired                                = `objectID is required`
	ConstStreamOperationType                                     = `operation_type`
	ConstStreamOrderByGroupkey                                   = ` ORDER BY groupKey`
	ConstStreamOrderByNStrStr                                    = ` ORDER BY n.%s %s`
	ConstStreamOrderByScoreDesc                                  = ` ORDER BY score DESC`
	ConstStreamOrderByScoreDescLimitInt                          = ` ORDER BY score DESC LIMIT %d`
	ConstStreamOrphanCleanup                                     = `orphan_cleanup`
	ConstStreamOrphanCleanupBatch                                = `orphan_cleanup_batch`
	ConstStreamOrphanCleanupBatchInt                             = `orphan_cleanup_batch_%d`
	ConstStreamOrphanCleanupComplete                             = `orphan_cleanup_complete`
	ConstStreamOrphanCleanupCoordinatorEvent                     = `orphan_cleanup_coordinator_event`
	ConstStreamOrphanCleanupError                                = `orphan_cleanup_error`
	ConstStreamOrphanCleanupQueueIsFullCannotEnqueueCleanupFor   = `orphan cleanup queue is full, cannot enqueue cleanup for %s`
	ConstStreamOrphanCleanupWorkerInt                            = `orphan_cleanup_worker_%d`
	ConstStreamPartialFailure                                    = `partial_failure`
	ConstStreamPartialOrIncompleteDataDetected                   = `partial or incomplete data detected`
	ConstStreamPathCacheRefresh                                  = `path_cache_refresh`
	ConstStreamPathCacheRefreshBuild                             = `path_cache_refresh_build`
	ConstStreamPathCacheRefreshHeartbeat                         = `path_cache_refresh_heartbeat`
	ConstStreamPathCacheRefreshHeartbeatCompletion               = `path cache refresh heartbeat+completion`
	ConstStreamPendingUpdates                                    = `pending_updates`
	ConstStreamPermissionDeniedErrDeleteOperationsRequire        = `permission denied: %w (delete operations require explicit authorization)`
	ConstStreamPermissionDeniedForKindStrErr                     = `permission denied for kind %s: %w`
	ConstStreamPermissionDeniedForSourceKindStrErr               = `permission denied for source kind %s: %w`
	ConstStreamPermissionDeniedForTargetKindStrErr               = `permission denied for target kind %s: %w`
	ConstStreamPreparePathStrErr                                 = `prepare path %s: %w`
	ConstStreamPreviousSizeMb                                    = `previous_size_mb`
	ConstStreamProcessDirectoryNotFound                          = `process directory not found`
	ConstStreamProcessInternal                                   = `process_internal`
	ConstStreamProcessingAsyncCasMetricsCollection               = `processing async CAS metrics collection`
	ConstStreamProcessingCasIndexWriteQueueForStr                = `processing CAS index write queue for %s`
	ConstStreamProcessingOrphanedHashFileCleanupOperations       = `processing orphaned hash file cleanup operations`
	ConstStreamProjectRootIsRequired                             = `project root is required`
	ConstStreamProjectRootNotSet                                 = `project root not set`
	ConstStreamProjectRootRequiredForWalCompaction               = `project root required for WAL compaction`
	ConstStreamProjectRootSet                                    = `project_root_set`
	ConstStreamReadAfterCasDiscoveryFailedForStrKindStrErr       = `read after CAS discovery failed for %s (kind: %s): %w`
	ConstStreamReadFailedForStrKindStrErr                        = `read failed for %s (kind: %s): %w`
	ConstStreamRecordsApplied                                    = `records_applied`
	ConstStreamRecreatedFileFromIdBasedSourceHashStr             = `Recreated file from ID-based source (hash: %s)`
	ConstStreamRecreatedFileWithUpdatedHashOldStrNewStr          = `Recreated file with updated hash (old: %s, new: %s)`
	ConstStreamReferenceValidationFailed                         = `reference validation failed`
	ConstStreamReferenceValidationFailedTierIntBlocksSaveErr     = `reference validation failed (Tier %d, blocks save): %w`
	ConstStreamReferenceValueIsNotAValidObjectIdOrNamespaced     = `reference value is not a valid object ID or namespaced reference`
	ConstStreamReferencedObjectStrKindStrInFieldStrDoesNotExist  = `referenced object %s (kind: %s) in field %s does not exist at expected path: %s`
	ConstStreamReferencedObjectStrKindStrInFieldStrExistsAtStr   = `referenced object %s (kind: %s) in field %s exists at %s but cannot be accessed: %w`
	ConstStreamReferencedObjectStrKindStrInFieldStrPathStr       = `referenced object %s (kind: %s) in field %s: path %s exists but is a directory, not a file`
	ConstStreamReferencedObjectStrKindStrLabelStrInFieldStrDoes  = `referenced object %s (kind: %s, label: %s) in field %s does not exist in graph backend: %w\n  Try: zqk object get %s (to verify object exists and check storage backend)`
	ConstStreamRemoveMapping                                     = `remove_mapping`
	ConstStreamRemovedEntries                                    = `removed_entries`
	ConstStreamRemovedFromIndex                                  = `removed_from_index`
	ConstStreamRemovedFromIndexFileMissingHashStr                = `Removed from index (file missing, hash: %s)`
	ConstStreamRenameNotImplementedForGraphStorageUseFileBased   = `rename not implemented for graph storage (use file-based storage for rename)`
	ConstStreamRenameOperationsMustBePerformedThroughCli         = `rename operations must be performed through CLI (unauthorized direct API call)`
	ConstStreamReplayRecordSeqIntErr                             = `replay record seq %d: %w`
	ConstStreamReplayedSoFar                                     = `replayed_so_far`
	ConstStreamRetryingIntFailedCleanupOperations                = `retrying %d failed cleanup operations`
	ConstStreamReturnCountNAsCount                               = ` RETURN COUNT(n) AS count`
	ConstStreamReturnGroupKeyStr                                 = ` RETURN group_key, %s`
	ConstStreamReturnNGroupkey                                   = ` RETURN n, groupKey`
	ConstStreamReturnNStrAsScore                                 = ` RETURN n, %s AS score`
	ConstStreamReturnedCount                                     = `returned_count`
	ConstStreamRunZqkSystemCheckToSeeAllIssuesN                  = `  Run 'zqk system check' to see all issues\n`
	ConstStreamSaveQueueIsFull                                   = `save queue is full`
	ConstStreamScanningSegmentForCount                           = `scanning segment for count`
	ConstStreamScanningSegmentForList                            = `scanning segment for list`
	ConstStreamShutdownInProgressCannotEnqueueCleanupOperation   = `shutdown in progress, cannot enqueue cleanup operation`
	ConstStreamShutdownInProgressCannotEnqueueIndexUpdate        = `shutdown in progress, cannot enqueue index update`
	ConstStreamShutdownTimeout                                   = `shutdown_timeout`
	ConstStreamSkippingSetfilestorageOnGlobalAuditBuffer         = `Skipping SetFileStorage on global audit buffer - different project root already set`
	ConstStreamSortOrderViolationValValAtPositionsIntInt         = `sort order violation: %v > %v at positions %d, %d`
	ConstStreamSortOrderViolationValValAtPositionsIntInt2        = `sort order violation: %v < %v at positions %d, %d`
	ConstStreamSourceFileIntegrityCheckFailed                    = `source file integrity check failed`
	ConstStreamSpecValidationFailed                              = `spec validation failed`
	ConstStreamStakeholderInt                                    = `stakeholder_%d`
	ConstStreamStewardEnqueueFailed                              = `steward enqueue failed`
	ConstStreamStewardEnqueueFailedAfterRegistryCompactError     = `steward enqueue failed after registry compact error`
	ConstStreamStewardEnqueueFailedRuntimeDeltaPhase             = `steward enqueue failed (runtime_delta phase)`
	ConstStreamStrTierIntStr                                     = `%s (Tier %d): %s`
	ConstStreamStrTrueAndNStrIsNotNullOrStrFalseAndNStrIsNull    = `($%s = true AND n.%s IS NOT NULL) OR ($%s = false AND n.%s IS NULL)`
	ConstStreamStrTrueAndNStrIsNullOrNotExistsNStrOrStrFalseAnd  = `($%s = true AND (n.%s IS NULL OR NOT exists(n.%s))) OR ($%s = false AND n.%s IS NOT NULL)`
	ConstStreamStreamCountReadDir                                = `stream count: read dir`
	ConstStreamStreamCountSegment                                = `stream_count_segment`
	ConstStreamStreamCountWaitTimeoutExceededVal                 = `stream count: wait timeout exceeded (%v)`
	ConstStreamStreamCountWaiter                                 = `stream_count_waiter`
	ConstStreamStreamCountWorker                                 = `stream_count_worker`
	ConstStreamStreamDeletedClose                                = `stream deleted: close`
	ConstStreamStreamDeletedCompactCreateTemp                    = `stream deleted compact: create temp`
	ConstStreamStreamDeletedCompactRename                        = `stream deleted compact: rename`
	ConstStreamStreamDeletedMkdir                                = `stream deleted: mkdir`
	ConstStreamStreamDeletedOpen                                 = `stream deleted: open`
	ConstStreamStreamDeletedWrite                                = `stream deleted: write`
	ConstStreamStreamInstanceAppend                              = `stream instance append`
	ConstStreamStreamListWaitTimeoutExceededVal                  = `stream list: wait timeout exceeded (%v)`
	ConstStreamStreamListWaiter                                  = `stream_list_waiter`
	ConstStreamStreamListWorker                                  = `stream_list_worker`
	ConstStreamStreamMarshal                                     = `stream: marshal`
	ConstStreamStreamProjectrootKindAndIdRequired                = `stream: projectRoot, kind, and id required`
	ConstStreamStreamReadDecode                                  = `stream read: decode`
	ConstStreamStreamReadFailedForStrKindStrErr                  = `stream read failed for %s (kind: %s): %w`
	ConstStreamStreamReadOpen                                    = `stream read: open`
	ConstStreamStreamReadSeek                                    = `stream read: seek`
	ConstStreamStreamRegistryCompactCreateTemp                   = `stream registry compact: create temp`
	ConstStreamStreamRegistryCompactRename                       = `stream registry compact: rename`
	ConstStreamStreamRegistryMkdir                               = `stream registry: mkdir`
	ConstStreamStreamRegistryOpen                                = `stream registry: open`
	ConstStreamStreamRegistryWrite                               = `stream registry: write`
	ConstStreamSumAggregationRequiresAField                      = `sum aggregation requires a field`
	ConstStreamSwallowedErrorValN                                = `swallowed error: %v\n`
	ConstStreamSystemConfigChange                                = `system_config_change`
	ConstStreamTD2D2D2Z                                          = `T\\d{2}:\\d{2}:\\d{2}Z`
	ConstStreamTargetFileAlreadyExistsStr                        = `target file already exists: %s`
	ConstStreamTestAccountForWorkstream                          = `Test Account for Workstream`
	ConstStreamTestDocumentEntry                                 = `Test document entry`
	ConstStreamTestMissionStatement                              = `Test mission statement`
	ConstStreamTestOperation                                     = `test_operation`
	ConstStreamTestOperationInt                                  = `Test operation %d`
	ConstStreamTestQuestion                                      = `Test question?`
	ConstStreamTestValueIntAbc                                   = `test_value_%d_ABC`
	ConstStreamTestValueWithSpaces                               = `test_value_with_spaces`
	ConstStreamTestVisionNarrative                               = `Test vision narrative`
	ConstStreamTestvalue123Abc                                   = `TestValue123_ABC`
	ConstStreamTimeoutWaitingForAllListingIndexFlushesDeadline   = `timeout waiting for all listing index flushes (deadline exceeded)`
	ConstStreamTimeoutWaitingForQueueToFlushForKindStrPendingInt = `timeout waiting for queue to flush for kind %s (pending: %d)`
	ConstStreamTimeoutWaitingForWalProcessingAppliedSeqInt       = `timeout waiting for WAL processing (applied_seq=%d, progressed=%v)`
	ConstStreamTimeoutWaitingForWriteBehindDrainBufferLenIntErr  = `timeout waiting for write-behind drain (buffer_len=%d): %w`
	ConstStreamTimeoutWaitingForWriteBufferToDrain               = `timeout waiting for write buffer to drain`
	ConstStreamToReduceWalSizeRunTheSchedulerSoTheWriteBehind    = `To reduce WAL size, run the scheduler so the write-behind worker can apply more entries and advance the checkpoint, then run compact-wal again.`
	ConstStreamTolowerNBodyContainsStr                           = `toLower(n.body) CONTAINS $%s`
	ConstStreamTolowerNDescriptionContainsStr                    = `toLower(n.description) CONTAINS $%s`
	ConstStreamTolowerNTitleContainsStr                          = `toLower(n.title) CONTAINS $%s`
	ConstStreamTolowerTostringNStrContainsStr                    = `toLower(toString(n.%s)) CONTAINS $%s`
	ConstStreamTotalBytesFreed                                   = `total_bytes_freed`
	ConstStreamTotalCollected                                    = `total_collected`
	ConstStreamTotalFailedFiles                                  = `total_failed_files`
	ConstStreamTotalFilesRemoved                                 = `total_files_removed`
	ConstStreamTotalReplayed                                     = `total_replayed`
	ConstStreamTransactionAlreadyCommitted                       = `transaction already committed`
	ConstStreamTransactionAlreadyCommittedOrRolledBack           = `transaction already committed or rolled back`
	ConstStreamTransactionWasRolledBack                          = `transaction was rolled back`
	ConstStreamTraversalFailed                                   = `traversal failed`
	ConstStreamTriggeringLifecycleJobForStrStrToStr              = `triggering lifecycle job for %s: %s -> %s`
	ConstStreamUnableToParseTimestampStr                         = `unable to parse timestamp: %s`
	ConstStreamUnexpectedCountValueTypeType                      = `unexpected count value type: %T`
	ConstStreamUnknownKindStr                                    = `unknown kind: %s`
	ConstStreamUnknownObjectKindStr                              = `unknown object kind: %s`
	ConstStreamUnknownOpTypeQuote                                = `unknown op type %q`
	ConstStreamUnlinkReferencesBeforeDeleteFailed                = `unlink references before delete failed`
	ConstStreamUnsupportedAggregationFunctionStr                 = `unsupported aggregation function: %s`
	ConstStreamUpdateStrChangesIdUsePerOpPath                    = `update %s changes id: use per-op path`
	ConstStreamValidateStrErr                                    = `validate %s: %w`
	ConstStreamValidationErrorsBlockSaveStr                      = `validation errors block save: %s`
	ConstStreamValidationErrorsStr                               = `validation errors: %s`
	ConstStreamValidationFailed                                  = `validation failed`
	ConstStreamValidationFailedForNewKind                        = `validation failed for new kind`
	ConstStreamValidationFailure                                 = `validation_failure`
	ConstStreamValidationRule                                    = `validation_rule`
	ConstStreamValidatorNotAvailable                             = `validator not available`
	ConstStreamVectorQueryRequiresAVectorParameterOfTypeFloat32  = `vector query requires a 'vector' parameter of type []float32`
	ConstStreamWaitingForAllCasIndexQueueDrainsToComplete        = `waiting for all CAS index queue drains to complete`
	ConstStreamWaitingForCasIndexQueueWorkerStr                  = `waiting for CAS index queue worker: %s`
	ConstStreamWaitingForCasOrphanCleanupWorkerToDrain           = `waiting for CAS orphan cleanup worker to drain`
	ConstStreamWaitingForCasOrphanCleanupWorkerToStop            = `waiting for CAS orphan cleanup worker to stop`
	ConstStreamWaitingForCountWorkers                            = `waiting for count workers`
	ConstStreamWaitingForCountWorkersAndClosingResultsChannel    = `waiting for count workers and closing results channel`
	ConstStreamWaitingForListAuditByIdsWorkers                   = `waiting for list audit by IDs workers`
	ConstStreamWaitingForListByPathsWorkers                      = `waiting for list by paths workers`
	ConstStreamWaitingForListCasWorkers                          = `waiting for list CAS workers`
	ConstStreamWaitingForListCasWorkersAndClosingResultsChannel  = `waiting for list CAS workers and closing results channel`
	ConstStreamWaitingForListWorkersAndClosingResultsChannel     = `waiting for list workers and closing results channel`
	ConstStreamWaitingForListingIndexFlushForKindStrErr          = `waiting for listing index flush for kind %s: %w`
	ConstStreamWaitingForListingIndexQueueErr                    = `waiting for listing index queue: %w`
	ConstStreamWaitingForStreamCountSegments                     = `waiting for stream count segments`
	ConstStreamWaitingForStreamCountWorkers                      = `waiting for stream count workers`
	ConstStreamWaitingForStreamListWorkers                       = `waiting for stream list workers`
	ConstStreamWalBatchMarshalledSizeIntExceedsMaxLineSizeInt    = `WAL batch marshalled size %d exceeds max line size %d (%d records); reduce batch size or object payload size`
	ConstStreamWalBatchRecordObjectIdLengthIntExceedsMaxIntKind  = `WAL batch record object id length %d exceeds max %d (kind=%s id=%q)`
	ConstStreamWalRecordMarshalledSizeIntExceedsMaxLineSizeInt   = `WAL record marshalled size %d exceeds max line size %d (kind=%s id=%s); object payload may be too large`
	ConstStreamWalRecordObjectIdLengthIntExceedsMaxIntKindStr    = `WAL record object id length %d exceeds max %d (kind=%s)`
	ConstStreamWalReplayForStr                                   = `WAL replay for %s`
	ConstStreamWarningCouldNotCreateReferencedAccountStrVal      = `Warning: Could not create referenced account %s: %v`
	ConstStreamWithNNStrAsGroupkey                               = ` WITH n, n.%s AS groupKey`
	ConstStreamWithNStrAsGroupKeyStr                             = ` WITH n.%s AS group_key, %s`
	ConstStreamWorkerRunning                                     = `worker_running`
	ConstStreamWorkerStarted                                     = `worker_started`
	ConstStreamWorkerStopped                                     = `worker_stopped`
	ConstStreamWriteBehindWorkerForStr                           = `write-behind worker for %s`
	ConstStreamWriteWalBatch                                     = `write WAL batch`
	ConstStreamWriteWalNewline                                   = `write WAL newline`
)
