// BLI-STARTER-COMMUNITY-049 / PRI-STARTER-COMMUNITY-049 coverage elevation
package config

import (
	"path/filepath"
	"testing"

	"github.com/zqk-os/zqk/pkg/paths"
	"github.com/zqk-os/zqk/pkg/utils/fileutil"
)

func TestExtraAccessorsAndLoaders(t *testing.T) {
	_ = LoadForRoot(t.TempDir())
	_ = NewProfileLoader("")
	_ = NewSchedulerLogsLoader(t.TempDir())
	_ = SystemStorageMode().Safe()
	_ = SystemStorageModeHybridLegacy().Safe()
	_ = SystemStreamStorageEnabled().Safe()
	_ = SystemProjectionFailClosed().Safe()
	_ = SystemMaxOSThreads().Safe()
	_ = SystemMaxObjectYAMLIO().Safe()
	_ = SystemHostCPUBackpressure().Safe()
	_ = SystemHostloadDisable().Safe()
	_ = SystemDemoMode().Safe()
	_ = SystemSpecializationTier().Safe()
	_ = SystemSkipDeleteAudit().Safe()
	_ = SchedulerAdmissionTimeout().Safe()
	_ = SchedulerDispatchResourceWaitMax().Safe()
	_ = SchedulerMaxWallDuration().Safe()
	_ = SchedulerGoroutineCap().Safe()
	_ = SchedulerDefaultPackageConcurrency().Safe()
	_ = SchedulerTriggeredPoolSize().Safe()
	_ = SchedulerImmediateLoadBatchSize().Safe()
	_ = SchedulerImmediateLoadBatchPause().Safe()
	_ = SchedulerDaemonMode().Safe()
	_ = SchedulerDaemonBin().Safe()
	_ = SchedulerLogsConfigPath().Safe()
	_ = SchedulerMaintenanceConfigPath().Safe()
	_ = SchedulerCVSLedgerMaxFailures().Safe()
	_ = SchedulerAggregationMetricCreationTimeout().Safe()
	_ = LLMProvider().Safe()
	_ = LLMChatModel().Safe()
	_ = LLMContextWindowSize().Safe()
	_ = LLMTemperature().Safe()
	_ = LLMTopP().Safe()
	_ = LLMEmbedModel().Safe()
	_ = LLMBaseURL().Safe()
	_ = LLMOpenAIBaseURL().Safe()
	_ = LLMFalBaseURL().Safe()
	_ = LLMMubertBaseURL().Safe()
	_ = LLMQwenBaseURL().Safe()
	_ = LLMTrace().Safe()
	_ = StorageGraphEnabled().Safe()
	_ = StorageMockGraph().Safe()
	_ = StorageLegacyMockGraph().Safe()
	_ = StorageAdminGraphEnabled().Safe()
	_ = StorageAdminMockGraph().Safe()
	_ = StorageHighVolumeCacheBuildWorkers().Safe()
	_ = StorageHighVolumeCacheKindParallelism().Safe()
	_ = StorageBulkBenchSize().Safe()
	_ = StorageTableMaxRows().Safe()
	_ = StorageRollbackRetainCount().Safe()
	_ = StorageRollbackRetainDuration().Safe()
	_ = StorageRollbackCaptureDisabled().Safe()
	_ = StorageListCountMaxConcurrent().Safe()
	_ = StorageListReadWorkers().Safe()
	_ = StorageStreamDeltaFieldsConfig().Safe()
	_ = MaintenanceAutofixBatchChunkSize().Safe()
	_ = MaintenanceAutofixGlossaryMaxCreate().Safe()
	_ = MaintenanceMetricsChunkRetentionDays().Safe()
	_ = MaintenanceRetentionToleranceConfig().Safe()
	_ = MaintenanceCacheDiagnosticEnabled().Safe()
	_ = MaintenanceCacheDiagnosticObjects().Safe()
	_ = MaintenanceCacheDiagnosticPrefixes().Safe()
	_ = SwarmMaxSteps().Safe()
	_ = SwarmWatchdogTimeout().Safe()
	_ = ValidationDisableCriteriaAutoValidate().Safe()
	_ = ValidationSkipSpecSchemaValidation().Safe()
	_ = ValidationSkipStateCommit().Safe()
	_ = ValidationDebugValidationObjectIDs().Safe()
	_ = TestingMockSuccess().Safe()
	_ = TestingMockFailure().Safe()
	_ = TestingBypassAuth().Safe()
	_ = TestingSkipValidation().Safe()
	_ = TestingMetricsRecording().Safe()
	_ = TestingVerbose().Safe()
	_ = TestingMode().Safe()
	_ = TestingCRUDBaselineCount().Safe()
	_ = TestingCRUDHeapProfile().Safe()
	_ = TestingCRUDProfile().Safe()
	_ = TestingRunPerfTests().Safe()
	_ = TestingStressRealRoot().Safe()
	_ = TestingPopulateScenarioTest().Safe()
	_ = TestingBypassGitevidence().Safe()
	_ = TestingEnableBootstrapCRUDTests().Safe()
	_ = TestingEnableSpecCellIntegrationTests().Safe()
	_ = TestingEnableSpecCellREQ019Validate().Safe()
	_ = TestingEnableCASMigrationScenarioTest().Safe()
	_ = TestingEnableCLIScenarioTests().Safe()
	_ = TestingEnableHashRegistryCoordinatorTests().Safe()
	_ = TestingEnableIOQueueShutdownTests().Safe()
	_ = TestingEnablePublicCandidateTest().Safe()
	_ = TestingEnableMigrateLegacyToStreamIntegrationTest().Safe()
	_ = TestingEnableStudioPackTools().Safe()
	_ = TestingStudioDogfood().Safe()
	_ = TestingEnableAmbientWatcher().Safe()
	_ = TestingTDDDiffTarget().Safe()
	_ = PathsMCPConfigPath().Safe()
	_ = PathsTestDataDir().Safe()
	_ = PathsTaskArtifacts().Safe()
	_ = PathsLLMTraceDir().Safe()
	_ = PathsDiagnosticsDir().Safe()
	_ = PathsStableBinaryPath().Safe()
	_ = PathsFFMPEGWorkerEndpoint().Safe()
	_ = CLIUpdateHelpGolden().Safe()
	_ = KernelStateProjectRoot().Safe()
	_ = MCPRunDeadlockReproduction().Safe()
	_ = LoggingSchedulerLogsConfig().Safe()
	_ = DiagnosticsPprof().Safe()
	_ = DiagnosticsPprofPort().Safe()
	_ = DiagnosticsThreadStackSkipMinGoroutines().Safe()
	_ = IDEPastePrefixSteps().Safe()
	_ = IDEPasteApp().Safe()
}

func TestExtraProfilesLogsAndProject(t *testing.T) {
	dir := t.TempDir()
	parent := []byte("schema_version: \"1\"\nkind: profile\ntype: cli_context\nmetadata:\n  name: parent\nspec:\n  a: 1\n  nested:\n    x: 1\n")
	child := []byte("schema_version: \"1\"\nkind: profile\ntype: cli_context\nmetadata:\n  name: child\n  extends: parent\nspec:\n  b: 2\n  nested:\n    y: 2\n")
	bad := []byte("kind: not-profile\n")
	if err := fileutil.WriteFile(filepath.Join(dir, "parent.yaml"), parent, paths.FilePerm644); err != nil {
		t.Fatal(err)
	}
	if err := fileutil.WriteFile(filepath.Join(dir, "child.yaml"), child, paths.FilePerm644); err != nil {
		t.Fatal(err)
	}
	if err := fileutil.WriteFile(filepath.Join(dir, "bad.yaml"), bad, paths.FilePerm644); err != nil {
		t.Fatal(err)
	}
	pl := NewProfileLoader(dir)
	got, err := pl.LoadProfileWithInheritance("child")
	if err != nil || got == nil {
		t.Fatal(err)
	}
	pl.ClearCache()
	if _, err := pl.LoadProfileWithInheritance("missing"); err == nil {
		t.Fatal("missing profile")
	}
	if _, err := pl.LoadProfileWithInheritance("bad"); err == nil {
		t.Fatal("bad kind")
	}
	logs := NewSchedulerLogsLoader(dir)
	cfg, err := logs.Load()
	if err != nil || cfg == nil {
		t.Fatal(err)
	}
	_ = GetMaxJobLogLines(dir)
	_ = GetLogLevel(dir)
	_ = GetLogLevel("")
	rt := NewRetentionToleranceLoader(dir)
	_ = rt.GetConfigPath()
	_, _ = ParseToleranceFromMap(nil, "k")
	_, _ = ParseToleranceFromMap(map[string]any{"archive_after": "1h", "cleanup_after": "2h"}, "k")
}
