package config

import (
	"errors"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/zqk-os/zqk/pkg/paths"
	fileutil "github.com/zqk-os/zqk/pkg/utils/fileutil"
)

// ErrWipeNotApproved is returned when a wipe operation is attempted without
// explicit human approval in the wipe guard file.
var ErrWipeNotApproved = errors.New("wipe not approved: set approval block in .zqk/wipe_guard.yaml")

// DefaultConfigContent is the template written by RestoreConfig to
// "config/zqk.yaml". It provides a consistent baseline for all restored
// ZQK projects.
const DefaultConfigContent = `# ZQK Project Configuration — generated by pkg/config.RestoreConfig
# This file may be overridden after restore; it represents the canonical baseline.
project:
  name: my-project
  version: 0.0.1
  description: "A restored ZQK project"
  owner: ""

workflow:
  vds_enabled: true
  require_chunk_evidence: true

wipe_guard:
  enabled: true
  mode: fail-closed
`

// DefaultWipeGuardContent is the template written by RestoreConfig to
// ".zqk/wipe_guard.yaml". It enforces a default fail-closed posture on all
// destructive operations.
const DefaultWipeGuardContent = `# Wipe Guard — fail-closed by default
# To allow destructive operations you MUST:
#   1. Enable unguarded mode by setting is_unguarded to true below
#   2. Add an approval block with your name, date, and reason
project:
  name: my-project
  is_unguarded: false

approval_block:
  approved_by: ""
  approved_at: ""
  reason: ""
`

// RestoreConfig creates or overwrites the canonical ZQK configuration layout
// under `root/.zqk/`. It is idempotent: running it multiple times yields an
// identical directory tree with no errors on subsequent invocations.
func RestoreConfig(root string) error {
	if root == "" {
		return fmt.Errorf("RestoreConfig: root must not be empty")
	}

	info, err := fileutil.Stat(root)
	if err != nil {
		if fileutil.IsNotExist(err) {
			return fmt.Errorf("RestoreConfig: project root %q does not exist", root)
		}
		return fmt.Errorf("RestoreConfig: cannot stat project root %q: %w", root, err)
	}
	if !info.IsDir() {
		return fmt.Errorf("RestoreConfig: project root %q is not a directory", root)
	}

	configPath := filepath.Join(root, paths.ConfigDir, paths.ZqkConfigFileName)
	guardPath := filepath.Join(root, paths.ProjectDataDir, "wipe_guard.yaml")

	if err := fileutil.EnsureDir(filepath.Dir(configPath)); err != nil {
		return fmt.Errorf("RestoreConfig: create config dir: %w", err)
	}
	if err := fileutil.EnsureDir(filepath.Dir(guardPath)); err != nil {
		return fmt.Errorf("RestoreConfig: create data dir: %w", err)
	}

	// Write config — overwrites in place with secure permissions
	if err := fileutil.WriteSecureFile(configPath, []byte(DefaultConfigContent)); err != nil {
		return fmt.Errorf("RestoreConfig: write config: %w", err)
	}

	// Write wipe guard — defaults to fail-closed (is_unguarded: false) with secure permissions
	if err := fileutil.WriteSecureFile(guardPath, []byte(DefaultWipeGuardContent)); err != nil {
		return fmt.Errorf("RestoreConfig: write wipe_guard: %w", err)
	}

	return nil
}

// CanWipeProject checks the wipe guard for `root` and returns true only if the
// project is explicitly unguarded AND has a valid approval block. Otherwise it
// returns an error explaining why the wipe is blocked.
func CanWipeProject(root, projectName string) error {
	if root == "" || projectName == "" {
		return fmt.Errorf("CanWipeProject: root and projectName must not be empty")
	}

	guardPath := filepath.Join(root, paths.ProjectDataDir, "wipe_guard.yaml")

	data, err := fileutil.ReadFile(guardPath) //nolint:gosec // path is rooted in validated project root
	if err != nil {
		return fmt.Errorf("CanWipeProject: read wipe guard: %w (run RestoreConfig first?)", err)
	}

	content := string(data)

	// Check is_unguarded flag
	if strings.Contains(content, "is_unguarded: true") || strings.Contains(content, "is_unguarded:true") {
		// Guard is open — now require approval block
		if hasApprovalBlock(content) {
			return nil // Approved and unguarded — allowed
		}
		return ErrWipeNotApproved
	}

	// Default: fail-closed — deny
	return ErrWipeNotApproved
}

// WipeProject performs a destructive wipe of project files *except* config/
// and .zqk/ (the guard itself must survive to protect against future
// accidental wipes). It first calls CanWipeProject which enforces the approval gate.
func WipeProject(root, projectName string) error {
	// Gate: fail-closed by default
	if err := CanWipeProject(root, projectName); err != nil {
		return err
	}

	// Read the entire directory layout
	entries, err := fileutil.ReadDir(root)
	if err != nil {
		return fmt.Errorf("WipeProject: read project root: %w", err)
	}

	for _, entry := range entries {
		if entry.Name() == paths.ProjectDataDir || entry.Name() == paths.ConfigDir {
			continue // Preserve kernel data and committed product config
		}
		targetPath := filepath.Join(root, entry.Name())
		if err := fileutil.RemoveAll(targetPath); err != nil {
			return fmt.Errorf("WipeProject: remove %s: %w", targetPath, err)
		}
	}

	return nil
}

// hasApprovalBlock checks if the wipe guard content contains all three required
// fields in the approval_block section.
func hasApprovalBlock(content string) bool {
	return strings.Contains(content, "approved_by:") &&
		strings.Contains(content, "approved_at:") &&
		strings.Contains(content, "reason:")
}
