// Code generated by pkg/specbuilder/config_builders/codegen.go from docs/architecture/_internal/configs/id_prefixes_config.yaml.
// DO NOT EDIT. Regenerate with: zqk system generate-config-builders --overwrite

package bldr_config_v1

import (
	"github.com/lanceman/zqk/pkg/specbuilder/config_builders"
)

// IdPrefixesConfigBuilder builds the id_prefixes_config config at version v1_0_0
// File: bldr_config_v1/id_prefixes_config_builder.go - version is encoded in package/directory name
type IdPrefixesConfigBuilder struct {
	*config_builders.BaseConfigBuilder
}

// NewIdPrefixesConfigBuilder creates a new builder for id_prefixes_config config version v1_0_0
func NewIdPrefixesConfigBuilder() *IdPrefixesConfigBuilder {
	builder := &IdPrefixesConfigBuilder{
		BaseConfigBuilder: config_builders.NewBaseConfigBuilder("id_prefixes_config", "v1_0_0"),
	}

	// Configure the config
	builder.
		SetConfig(map[string]any{
			"$schema": "../../../.zqk/cli/specs/schemas/id_prefixes_config.schema.json",
			"default_strategy": map[string]any{
				"example": "backlog_item -> BAC-",
				"method":  "first_part_upper_3",
			},
			"description": "Configuration for object kind to ID prefix mappings.\nThis allows the system to validate and generate object IDs without hardcoding\nprefix rules in the source code.\n\nEach kind can have multiple valid prefixes (for backward compatibility or\nmigration scenarios). The first prefix listed is considered the primary/current prefix.\n",
			"inference_rules": map[string]any{
				"patterns": []any{
					map[string]any{
						"example":         "backlog_item -> ITEM-",
						"pattern":         "^(.+)_item$",
						"prefix_template": "{base_upper_3}-",
					},
					map[string]any{
						"example":         "command_metric -> CMD-",
						"pattern":         "^.+_metric$",
						"prefix_template": "{base_upper_3}-",
					},
					map[string]any{
						"example":         "priority_plan -> PLAN-",
						"pattern":         "^([^_]+)_.+$",
						"prefix_template": "{first_part_upper_3}-",
					},
					map[string]any{
						"example":         "component -> COM-",
						"pattern":         "^(.+)$",
						"prefix_template": "{first_3_upper}-",
					},
				},
			},
			"kind_to_prefixes": map[string]any{
				"account": []any{
					"ACC-",
				},
				"agent_architecture": []any{
					"AGENT-ARCH-",
				},
				"agent_feed": []any{
					"AGF-",
				},
				"agent_instruction": []any{
					"AGI-",
				},
				"agent_onboarding_preparation": []any{
					"AGENT-PREP-",
					"AGE-",
				},
				"agent_skill": []any{
					"ASK-",
				},
				"agent_task": []any{
					"ATK-",
				},
				"application_record": []any{
					"APP-",
				},
				"assessment_rating": []any{
					"ASR-",
				},
				"audit_aggregation_metric": []any{
					"AAM-",
					"CJA-",
				},
				"audit_event": []any{
					"AUD-",
				},
				"auth_strategy": []any{
					"AUTH-",
				},
				"auto_fix_rule": []any{
					"AFR-",
				},
				"backlog_item": []any{
					"ITEM-",
				},
				"base_metric": []any{
					"BAS-",
				},
				"base_sampler": []any{
					"BSA-",
				},
				"brand": []any{
					"BRA-",
				},
				"brand_asset": []any{
					"BAA-",
				},
				"bucketing_strategy": []any{
					"BST-",
					"BS-",
				},
				"capacity_advertisement": []any{
					"CADV-",
				},
				"certificate": []any{
					"CERT-",
				},
				"change_journal_entry": []any{
					"CHA-",
				},
				"code_quality_metric": []any{
					"CQM-",
				},
				"code_reference": []any{
					"COD-",
				},
				"command_metric": []any{
					"CMD-",
				},
				"command_spec": []any{
					"CSPEC-",
				},
				"commercial_sequence": []any{
					"CSE-",
				},
				"component": []any{
					"COMP-",
				},
				"compression_policy": []any{
					"COMPOLICY-",
				},
				"compute_advertisement": []any{
					"CAD-",
				},
				"context_refresh_schedule": []any{
					"CON-",
				},
				"convergence_session": []any{
					"CONV-",
				},
				"corporate_initiative": []any{
					"CI-",
				},
				"criteria": []any{
					"CRIT-",
				},
				"decision": []any{
					"DEC-",
					"ADR-",
				},
				"department": []any{
					"DEP-",
				},
				"digital_asset": []any{
					"AST-",
				},
				"display": []any{
					"DSP-",
				},
				"division": []any{
					"DIV-",
				},
				"doc_entry": []any{
					"DOC-",
				},
				"domain_registry": []any{
					"DOMAIN-REG-",
				},
				"economic_policy": []any{
					"ECP-",
					"ECO-",
				},
				"evolution_management": []any{
					"EVO-",
					"EVOL-",
				},
				"extensible_object": []any{
					"EXT-",
				},
				"field_registry": []any{
					"FIE-",
				},
				"file_lock_metric": []any{
					"FLM-",
				},
				"fission_event": []any{
					"FIS-",
				},
				"glossary_term": []any{
					"GLS-",
				},
				"glossary_term_relation": []any{
					"GTR-",
				},
				"goal": []any{
					"GOAL-",
					"G-",
				},
				"impact_analysis": []any{
					"IMP-",
				},
				"import_tracking": []any{
					"IMPTRK-",
				},
				"important_date": []any{
					"DATE-",
				},
				"inference_heuristic": []any{
					"IFH-",
				},
				"infrastructure_adapter": []any{
					"IFA-",
				},
				"integrity_manifest": []any{
					"INT-",
				},
				"job_listing": []any{
					"JLI-",
				},
				"job_search_profile": []any{
					"JSP-",
				},
				"keystore_entry": []any{
					"KEY-",
				},
				"kind_mapping_metric": []any{
					"KMM-",
				},
				"kind_synonym": []any{
					"SYN-",
				},
				"library": []any{
					"LIB-",
				},
				"lifecycle": []any{
					"LIFECYCLE-",
					"LIF-",
				},
				"list_metric_sampler": []any{
					"LIS-",
				},
				"mcp_session": []any{
					"MCP-",
				},
				"metadata_package": []any{
					"MET-",
				},
				"metrics_exchange_contract": []any{
					"MXC-",
				},
				"metrics_feedback": []any{
					"MFB-",
				},
				"milestone": []any{
					"MIL-",
				},
				"mission": []any{
					"MIS-",
				},
				"namespace": []any{
					"NAM-",
					"NAMESPACE-",
				},
				"namespace_registry": []any{
					"NSR-",
					"NAMESPACE-REGISTRY-",
				},
				"narrative": []any{
					"NAR-",
				},
				"object_spec": []any{
					"OBJ-",
				},
				"ordered_list_metric_sampler": []any{
					"ORD-",
				},
				"organization": []any{
					"ORG-",
				},
				"organizational_change": []any{
					"OCH-",
				},
				"partnership": []any{
					"PAR-",
				},
				"persona": []any{
					"PER-",
				},
				"pipeline": []any{
					"PIP-",
				},
				"pipeline_definition": []any{
					"PLD-",
				},
				"pipeline_execution": []any{
					"PLX-",
				},
				"policy": []any{
					"POLICY-CODE-",
					"POLICY-SEC-",
					"POLICY-DATA-",
					"POLICY-OPS-",
					"POLICY-ARCH-",
					"POLICY-DEBUG-",
					"POLICY-DOC-",
					"POLICY-EST-",
					"POLICY-FEATURE-",
					"POLICY-MCP-",
					"POLICY-ONBOARD-",
					"POLICY-PLAN-",
					"POLICY-TRACK-",
					"POLICY-WORKFLOW-",
					"POLICY-AGENT-",
					"POLICY-OBS-",
				},
				"priority_plan": []any{
					"PLAN-",
					"PRIO-",
				},
				"probe_spec": []any{
					"PRB-",
				},
				"process_hygiene_rule": []any{
					"PHR-",
				},
				"prompt_template": []any{
					"PROMPT-",
				},
				"provider_profile": []any{
					"PPRV-",
				},
				"qa_success": []any{
					"QAS",
				},
				"question": []any{
					"QUE-",
				},
				"release": []any{
					"REL-",
				},
				"remote_kernel": []any{
					"RMK-",
					"REM-",
				},
				"requirement": []any{
					"REQ-",
					"REQU-",
				},
				"resolver": []any{
					"RES-",
				},
				"risk_blocker": []any{
					"RIS-",
				},
				"roadmap": []any{
					"ROAD-",
				},
				"role": []any{
					"ROL-",
				},
				"rollback_report": []any{
					"RBR-",
				},
				"rule": []any{
					"RUL-",
				},
				"sampler_profile": []any{
					"SAM-",
				},
				"scalar_metric_sampler": []any{
					"SCA-",
				},
				"scenario": []any{
					"SCE-",
				},
				"scheduler_handler_binding": []any{
					"SHB-",
				},
				"scheduler_health_metric": []any{
					"SHM-",
				},
				"scheduler_job": []any{
					"SCH-",
				},
				"shockwave_router": []any{
					"SWR-",
				},
				"stakeholder_profile": []any{
					"STK-",
				},
				"status_history_metric_sampler": []any{
					"STA-",
				},
				"strategic_context": []any{
					"SC-",
				},
				"strategic_plan": []any{
					"STRAT-PLAN-",
				},
				"tde_envelope": []any{
					"TDEE-",
				},
				"team": []any{
					"TEA-",
				},
				"team_configuration": []any{
					"TCFG-",
				},
				"technical_debt": []any{
					"TDE-",
				},
				"technical_spec": []any{
					"TSP-",
				},
				"template": []any{
					"TEM-",
				},
				"test_audit_aggregation_metric": []any{
					"TES-",
					"TAM-",
				},
				"test_case": []any{
					"TST",
					"TEST",
				},
				"test_command_rule": []any{
					"TCR-",
				},
				"validation_rule": []any{
					"VAL-",
					"RULE-",
				},
				"verification_matrix": []any{
					"VMX-",
				},
				"vision": []any{
					"VIS-",
				},
				"visual_plan": []any{
					"VPL-",
				},
				"vitality_report": []any{
					"VIT-",
				},
				"vocabulary_scheme": []any{
					"VOC-",
				},
				"workflow": []any{
					"WFL-",
				},
				"workstream": []any{
					"WS-",
				},
				"workstream_transition": []any{
					"WST-",
				},
			},
			"kind_to_synonyms": map[string]any{
				"account": []any{
					"acc",
				},
				"audit_event": []any{
					"ae",
					"audit",
					"event",
				},
				"backlog_item": []any{
					"bli",
					"bl-item",
					"backlog",
					"bl",
				},
				"change_journal_entry": []any{
					"cje",
					"journal",
					"change_journal",
				},
				"component": []any{
					"comp",
				},
				"convergence_session": []any{
					"cvs",
					"conv-session",
				},
				"corporate_initiative": []any{
					"ci",
					"initiative",
					"corp_init",
				},
				"criteria": []any{
					"crit",
				},
				"decision": []any{
					"dec",
				},
				"display": []any{
					"dsp",
				},
				"goal": []any{
					"go",
				},
				"lifecycle": []any{
					"lc",
					"life",
				},
				"milestone": []any{
					"mil",
					"ms",
				},
				"mission": []any{
					"mis",
				},
				"object_spec": []any{
					"spec",
					"ospec",
				},
				"priority_plan": []any{
					"pplan",
					"p-plan",
					"plan",
					"pp",
				},
				"release": []any{
					"rel",
				},
				"requirement": []any{
					"req",
					"requ",
				},
				"roadmap": []any{
					"road",
					"rm",
				},
				"role": []any{
					"rol",
				},
				"shockwave_router": []any{
					"router",
					"shockwave",
				},
				"template": []any{
					"tpl",
					"tmpl",
				},
				"test_case": []any{
					"test",
					"tc",
					"testcase",
				},
				"validation_rule": []any{
					"vrule",
					"val_rule",
				},
				"verification_matrix": []any{
					"vmx",
					"vmatrix",
					"ver_matrix",
				},
				"vision": []any{
					"vis",
				},
				"workstream": []any{
					"ws",
					"work",
				},
			},
			"version": ConfigYAMLVersionV1,
		})

	return builder
}

func init() {
	config_builders.RegisterBuilder(NewIdPrefixesConfigBuilder())
}
