// Code generated by scripts/generate_enum_tests.py; DO NOT EDIT.

package displays

import (
	"testing"
)

func TestEnums_Completeness(t *testing.T) {
	tests := []struct {
		name string
		val  string
	}{
		{"PriorityTierP0", string(PriorityTierP0)},
		{"PriorityTierP1", string(PriorityTierP1)},
		{"PriorityTierP2", string(PriorityTierP2)},
		{"PriorityTierP3", string(PriorityTierP3)},
		{"SourceTypeExternal", string(SourceTypeExternal)},
		{"SourceTypeImported", string(SourceTypeImported)},
		{"SourceTypeInternal", string(SourceTypeInternal)},
		{"StatusArchived", string(StatusArchived)},
		{"StatusConfigured", string(StatusConfigured)},
		{"StatusCreated", string(StatusCreated)},
		{"StatusError", string(StatusError)},
		{"StatusRendered", string(StatusRendered)},
		{"StatusValidated", string(StatusValidated)},
	}
	for _, tt := range tests {
		if tt.val == "" {
			t.Errorf("constant %s has empty value", tt.name)
		}
	}
}
