// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package bldr_instance_v1

import (
	enumv "github.com/zqk-os/zqk/packs/work/bldr_enum_v1/goal"
	"github.com/zqk-os/zqk/pkg/objects"
	"github.com/zqk-os/zqk/pkg/specbuilder/instance_builders"
)

// GoalInstanceBuilder builds goal instances
// ONE builder handles ALL goal instances
type GoalInstanceBuilder struct {
	*instance_builders.BaseInstanceBuilder
}

// NewGoalInstanceBuilder creates a new goal instance builder.
// Pass the instance schema_version string for this spec; use objects.DefaultSchemaVersion for the project default (pkg/objects constants).
// Field order is derived from the spec (not hardcoded) to avoid drift
func NewGoalInstanceBuilder(schemaVersion string) *GoalInstanceBuilder {
	// Derive canonical field order from spec (follows architecture pattern)
	// System fields first, then spec-defined fields in sorted order
	fieldOrder := instance_builders.FieldOrderFromSpec("goal")

	// Create base builder
	builder := &GoalInstanceBuilder{
		BaseInstanceBuilder: instance_builders.NewBaseInstanceBuilder(
			"goal",
			schemaVersion,
			fieldOrder,
			nil, // spec builder (optional)
		),
	}

	return builder
}

// Status sets the status field
func (b *GoalInstanceBuilder) Status(value enumv.Status) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyStatus, string(value))
	return b
}

// ID sets the id field
func (b *GoalInstanceBuilder) ID(value string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyID, value)
	return b
}

// AchievedAt sets the achieved_at field
func (b *GoalInstanceBuilder) AchievedAt(value string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyAchievedAt, value)
	return b
}

// SetAchievedAt is a compatibility alias for AchievedAt.
func (b *GoalInstanceBuilder) SetAchievedAt(value string) *GoalInstanceBuilder {
	return b.AchievedAt(value)
}

// ArchivedAt sets the archived_at field
func (b *GoalInstanceBuilder) ArchivedAt(value any) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedAt, value)
	return b
}

// SetArchivedAt is a compatibility alias for ArchivedAt.
func (b *GoalInstanceBuilder) SetArchivedAt(value any) *GoalInstanceBuilder {
	return b.ArchivedAt(value)
}

// ArchivedBy sets the archived_by field
func (b *GoalInstanceBuilder) ArchivedBy(value string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedBy, value)
	return b
}

// SetArchivedBy is a compatibility alias for ArchivedBy.
func (b *GoalInstanceBuilder) SetArchivedBy(value string) *GoalInstanceBuilder {
	return b.ArchivedBy(value)
}

// Artifacts sets the artifacts field
func (b *GoalInstanceBuilder) Artifacts(value []string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyArtifacts, value)
	return b
}

// SetArtifacts is a compatibility alias for Artifacts.
func (b *GoalInstanceBuilder) SetArtifacts(value []string) *GoalInstanceBuilder {
	return b.Artifacts(value)
}

// Authority sets the authority field
func (b *GoalInstanceBuilder) Authority(value string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyAuthority, value)
	return b
}

// SetAuthority is a compatibility alias for Authority.
func (b *GoalInstanceBuilder) SetAuthority(value string) *GoalInstanceBuilder {
	return b.Authority(value)
}

// ChangeLog sets the change_log field
func (b *GoalInstanceBuilder) ChangeLog(value []string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyChangeLog, value)
	return b
}

// SetChangeLog is a compatibility alias for ChangeLog.
func (b *GoalInstanceBuilder) SetChangeLog(value []string) *GoalInstanceBuilder {
	return b.ChangeLog(value)
}

// CommitHashes sets the commit_hashes field
func (b *GoalInstanceBuilder) CommitHashes(value []string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyCommitHashes, value)
	return b
}

// SetCommitHashes is a compatibility alias for CommitHashes.
func (b *GoalInstanceBuilder) SetCommitHashes(value []string) *GoalInstanceBuilder {
	return b.CommitHashes(value)
}

// CompletedAt sets the completed_at field
func (b *GoalInstanceBuilder) CompletedAt(value string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyCompletedAt, value)
	return b
}

// SetCompletedAt is a compatibility alias for CompletedAt.
func (b *GoalInstanceBuilder) SetCompletedAt(value string) *GoalInstanceBuilder {
	return b.CompletedAt(value)
}

// CompletenessValidation sets the completeness_validation field
func (b *GoalInstanceBuilder) CompletenessValidation(value []string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyCompletenessValidation, value)
	return b
}

// SetCompletenessValidation is a compatibility alias for CompletenessValidation.
func (b *GoalInstanceBuilder) SetCompletenessValidation(value []string) *GoalInstanceBuilder {
	return b.CompletenessValidation(value)
}

// Context sets the context field
func (b *GoalInstanceBuilder) Context(value any) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyContext, value)
	return b
}

// SetContext is a compatibility alias for Context.
func (b *GoalInstanceBuilder) SetContext(value any) *GoalInstanceBuilder {
	return b.Context(value)
}

// CurrentValue sets the current_value field
func (b *GoalInstanceBuilder) CurrentValue(value string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyCurrentValue, value)
	return b
}

// SetCurrentValue is a compatibility alias for CurrentValue.
func (b *GoalInstanceBuilder) SetCurrentValue(value string) *GoalInstanceBuilder {
	return b.CurrentValue(value)
}

// Deadline sets the deadline field
func (b *GoalInstanceBuilder) Deadline(value string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyDeadline, value)
	return b
}

// SetDeadline is a compatibility alias for Deadline.
func (b *GoalInstanceBuilder) SetDeadline(value string) *GoalInstanceBuilder {
	return b.Deadline(value)
}

// Dependencies sets the dependencies field
func (b *GoalInstanceBuilder) Dependencies(value []string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyDependencies, value)
	return b
}

// SetDependencies is a compatibility alias for Dependencies.
func (b *GoalInstanceBuilder) SetDependencies(value []string) *GoalInstanceBuilder {
	return b.Dependencies(value)
}

// Description sets the description field
func (b *GoalInstanceBuilder) Description(value any) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyDescription, value)
	return b
}

// SetDescription is a compatibility alias for Description.
func (b *GoalInstanceBuilder) SetDescription(value any) *GoalInstanceBuilder {
	return b.Description(value)
}

// EpicRefs sets the epic_refs field
func (b *GoalInstanceBuilder) EpicRefs(value []string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyEpicRefs, value)
	return b
}

// SetEpicRefs is a compatibility alias for EpicRefs.
func (b *GoalInstanceBuilder) SetEpicRefs(value []string) *GoalInstanceBuilder {
	return b.EpicRefs(value)
}

// Metric sets the metric field
func (b *GoalInstanceBuilder) Metric(value string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyMetric, value)
	return b
}

// SetMetric is a compatibility alias for Metric.
func (b *GoalInstanceBuilder) SetMetric(value string) *GoalInstanceBuilder {
	return b.Metric(value)
}

// MetricTemplateId sets the metric_template_id field
func (b *GoalInstanceBuilder) MetricTemplateId(value string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyMetricTemplateID, value)
	return b
}

// SetMetricTemplateId is a compatibility alias for MetricTemplateId.
func (b *GoalInstanceBuilder) SetMetricTemplateId(value string) *GoalInstanceBuilder {
	return b.MetricTemplateId(value)
}

// OriginProject sets the origin_project field
func (b *GoalInstanceBuilder) OriginProject(value string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyOriginProject, value)
	return b
}

// SetOriginProject is a compatibility alias for OriginProject.
func (b *GoalInstanceBuilder) SetOriginProject(value string) *GoalInstanceBuilder {
	return b.OriginProject(value)
}

// OriginSystem sets the origin_system field
func (b *GoalInstanceBuilder) OriginSystem(value string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyOriginSystem, value)
	return b
}

// SetOriginSystem is a compatibility alias for OriginSystem.
func (b *GoalInstanceBuilder) SetOriginSystem(value string) *GoalInstanceBuilder {
	return b.OriginSystem(value)
}

// Plane sets the plane field
func (b *GoalInstanceBuilder) Plane(value enumv.Plane) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyPlane, string(value))
	return b
}

// SetPlane is a compatibility alias for Plane.
func (b *GoalInstanceBuilder) SetPlane(value enumv.Plane) *GoalInstanceBuilder {
	return b.Plane(value)
}

// PriorityTier sets the priority_tier field
func (b *GoalInstanceBuilder) PriorityTier(value enumv.PriorityTier) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyPriorityTier, string(value))
	return b
}

// SetPriorityTier is a compatibility alias for PriorityTier.
func (b *GoalInstanceBuilder) SetPriorityTier(value enumv.PriorityTier) *GoalInstanceBuilder {
	return b.PriorityTier(value)
}

// Provenance sets the provenance field
func (b *GoalInstanceBuilder) Provenance(value map[string]any) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyProvenance, value)
	return b
}

// SetProvenance is a compatibility alias for Provenance.
func (b *GoalInstanceBuilder) SetProvenance(value map[string]any) *GoalInstanceBuilder {
	return b.Provenance(value)
}

// Questions sets the questions field
func (b *GoalInstanceBuilder) Questions(value []string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyQuestions, value)
	return b
}

// SetQuestions is a compatibility alias for Questions.
func (b *GoalInstanceBuilder) SetQuestions(value []string) *GoalInstanceBuilder {
	return b.Questions(value)
}

// RelatedObjectRefs sets the related_object_refs field
func (b *GoalInstanceBuilder) RelatedObjectRefs(value []string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyRelatedObjectRefs, value)
	return b
}

// SetRelatedObjectRefs is a compatibility alias for RelatedObjectRefs.
func (b *GoalInstanceBuilder) SetRelatedObjectRefs(value []string) *GoalInstanceBuilder {
	return b.RelatedObjectRefs(value)
}

// SchemaRef sets the schema_ref field
func (b *GoalInstanceBuilder) SchemaRef(value string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeySchemaRef, value)
	return b
}

// SetSchemaRef is a compatibility alias for SchemaRef.
func (b *GoalInstanceBuilder) SetSchemaRef(value string) *GoalInstanceBuilder {
	return b.SchemaRef(value)
}

// SourceType sets the source_type field
func (b *GoalInstanceBuilder) SourceType(value enumv.SourceType) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeySourceType, string(value))
	return b
}

// SetSourceType is a compatibility alias for SourceType.
func (b *GoalInstanceBuilder) SetSourceType(value enumv.SourceType) *GoalInstanceBuilder {
	return b.SourceType(value)
}

// SpecAdherence sets the spec_adherence field
func (b *GoalInstanceBuilder) SpecAdherence(value map[string]any) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeySpecAdherence, value)
	return b
}

// SetSpecAdherence is a compatibility alias for SpecAdherence.
func (b *GoalInstanceBuilder) SetSpecAdherence(value map[string]any) *GoalInstanceBuilder {
	return b.SpecAdherence(value)
}

// Stakeholders sets the stakeholders field
func (b *GoalInstanceBuilder) Stakeholders(value []string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyStakeholders, value)
	return b
}

// SetStakeholders is a compatibility alias for Stakeholders.
func (b *GoalInstanceBuilder) SetStakeholders(value []string) *GoalInstanceBuilder {
	return b.Stakeholders(value)
}

// StartedAt sets the started_at field
func (b *GoalInstanceBuilder) StartedAt(value string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyStartedAt, value)
	return b
}

// SetStartedAt is a compatibility alias for StartedAt.
func (b *GoalInstanceBuilder) SetStartedAt(value string) *GoalInstanceBuilder {
	return b.StartedAt(value)
}

// StatusHistory sets the status_history field
func (b *GoalInstanceBuilder) StatusHistory(value []string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyStatusHistory, value)
	return b
}

// SetStatusHistory is a compatibility alias for StatusHistory.
func (b *GoalInstanceBuilder) SetStatusHistory(value []string) *GoalInstanceBuilder {
	return b.StatusHistory(value)
}

// Target sets the target field
func (b *GoalInstanceBuilder) Target(value string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyTarget, value)
	return b
}

// SetTarget is a compatibility alias for Target.
func (b *GoalInstanceBuilder) SetTarget(value string) *GoalInstanceBuilder {
	return b.Target(value)
}

// TargetDate sets the target_date field
func (b *GoalInstanceBuilder) TargetDate(value string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyTargetDate, value)
	return b
}

// SetTargetDate is a compatibility alias for TargetDate.
func (b *GoalInstanceBuilder) SetTargetDate(value string) *GoalInstanceBuilder {
	return b.TargetDate(value)
}

// Title sets the title field
func (b *GoalInstanceBuilder) Title(value string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyTitle, value)
	return b
}

// SetTitle is a compatibility alias for Title.
func (b *GoalInstanceBuilder) SetTitle(value string) *GoalInstanceBuilder {
	return b.Title(value)
}

// Urn sets the urn field
func (b *GoalInstanceBuilder) Urn(value string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyUrn, value)
	return b
}

// SetUrn is a compatibility alias for Urn.
func (b *GoalInstanceBuilder) SetUrn(value string) *GoalInstanceBuilder {
	return b.Urn(value)
}

// Version sets the version field
func (b *GoalInstanceBuilder) Version(value int) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyVersion, value)
	return b
}

// SetVersion is a compatibility alias for Version.
func (b *GoalInstanceBuilder) SetVersion(value int) *GoalInstanceBuilder {
	return b.Version(value)
}

// WorkstreamRefs sets the workstream_refs field
func (b *GoalInstanceBuilder) WorkstreamRefs(value []string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyWorkstreamRefs, value)
	return b
}

// SetWorkstreamRefs is a compatibility alias for WorkstreamRefs.
func (b *GoalInstanceBuilder) SetWorkstreamRefs(value []string) *GoalInstanceBuilder {
	return b.WorkstreamRefs(value)
}

// RequirementRefs sets the requirement_refs field
func (b *GoalInstanceBuilder) RequirementRefs(value []string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyRequirementRefs, value)
	return b
}

// SetRequirementRefs is a compatibility alias for RequirementRefs.
func (b *GoalInstanceBuilder) SetRequirementRefs(value []string) *GoalInstanceBuilder {
	return b.RequirementRefs(value)
}

// SuccessCriteria sets the success_criteria field
func (b *GoalInstanceBuilder) SuccessCriteria(value []string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeySuccessCriteria, value)
	return b
}

// SetSuccessCriteria is a compatibility alias for SuccessCriteria.
func (b *GoalInstanceBuilder) SetSuccessCriteria(value []string) *GoalInstanceBuilder {
	return b.SuccessCriteria(value)
}

// VisionRef sets the vision_ref field
func (b *GoalInstanceBuilder) VisionRef(value string) *GoalInstanceBuilder {
	b.SetField(objects.FieldKeyVisionRef, value)
	return b
}

// SetVisionRef is a compatibility alias for VisionRef.
func (b *GoalInstanceBuilder) SetVisionRef(value string) *GoalInstanceBuilder {
	return b.VisionRef(value)
}

