// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package bldr_instance_v1

import (
	"github.com/zqk-os/zqk/pkg/objects"
	enumv "github.com/zqk-os/zqk/packs/work/bldr_enum_v1/technical_debt"
	"github.com/zqk-os/zqk/pkg/specbuilder/instance_builders"
)

// TechnicalDebtInstanceBuilder builds technical_debt instances
// ONE builder handles ALL technical_debt instances
type TechnicalDebtInstanceBuilder struct {
	*instance_builders.BaseInstanceBuilder
}

// NewTechnicalDebtInstanceBuilder creates a new technical_debt instance builder.
// Pass the instance schema_version string for this spec; use objects.DefaultSchemaVersion for the project default (pkg/objects constants).
// Field order is derived from the spec (not hardcoded) to avoid drift
func NewTechnicalDebtInstanceBuilder(schemaVersion string) *TechnicalDebtInstanceBuilder {
	// Derive canonical field order from spec (follows architecture pattern)
	// System fields first, then spec-defined fields in sorted order
	fieldOrder := instance_builders.FieldOrderFromSpec("technical_debt")

	// Create base builder
	builder := &TechnicalDebtInstanceBuilder{
		BaseInstanceBuilder: instance_builders.NewBaseInstanceBuilder(
			"technical_debt",
			schemaVersion,
			fieldOrder,
			nil, // spec builder (optional)
		),
	}

	return builder
}

// Status sets the status field
func (b *TechnicalDebtInstanceBuilder) Status(value enumv.Status) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyStatus, string(value))
	return b
}

// ID sets the id field
func (b *TechnicalDebtInstanceBuilder) ID(value string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyID, value)
	return b
}

// ActualEffort sets the actual_effort field
func (b *TechnicalDebtInstanceBuilder) ActualEffort(value string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyActualEffort, value)
	return b
}

// SetActualEffort is a compatibility alias for ActualEffort.
func (b *TechnicalDebtInstanceBuilder) SetActualEffort(value string) *TechnicalDebtInstanceBuilder {
	return b.ActualEffort(value)
}

// ArchivedAt sets the archived_at field
func (b *TechnicalDebtInstanceBuilder) ArchivedAt(value any) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedAt, value)
	return b
}

// SetArchivedAt is a compatibility alias for ArchivedAt.
func (b *TechnicalDebtInstanceBuilder) SetArchivedAt(value any) *TechnicalDebtInstanceBuilder {
	return b.ArchivedAt(value)
}

// ArchivedBy sets the archived_by field
func (b *TechnicalDebtInstanceBuilder) ArchivedBy(value string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedBy, value)
	return b
}

// SetArchivedBy is a compatibility alias for ArchivedBy.
func (b *TechnicalDebtInstanceBuilder) SetArchivedBy(value string) *TechnicalDebtInstanceBuilder {
	return b.ArchivedBy(value)
}

// Artifacts sets the artifacts field
func (b *TechnicalDebtInstanceBuilder) Artifacts(value []string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyArtifacts, value)
	return b
}

// SetArtifacts is a compatibility alias for Artifacts.
func (b *TechnicalDebtInstanceBuilder) SetArtifacts(value []string) *TechnicalDebtInstanceBuilder {
	return b.Artifacts(value)
}

// BacklogRef sets the backlog_ref field
func (b *TechnicalDebtInstanceBuilder) BacklogRef(value string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyBacklogRef, value)
	return b
}

// SetBacklogRef is a compatibility alias for BacklogRef.
func (b *TechnicalDebtInstanceBuilder) SetBacklogRef(value string) *TechnicalDebtInstanceBuilder {
	return b.BacklogRef(value)
}

// ChangeLog sets the change_log field
func (b *TechnicalDebtInstanceBuilder) ChangeLog(value []string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyChangeLog, value)
	return b
}

// SetChangeLog is a compatibility alias for ChangeLog.
func (b *TechnicalDebtInstanceBuilder) SetChangeLog(value []string) *TechnicalDebtInstanceBuilder {
	return b.ChangeLog(value)
}

// CompletedAt sets the completed_at field
func (b *TechnicalDebtInstanceBuilder) CompletedAt(value string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyCompletedAt, value)
	return b
}

// SetCompletedAt is a compatibility alias for CompletedAt.
func (b *TechnicalDebtInstanceBuilder) SetCompletedAt(value string) *TechnicalDebtInstanceBuilder {
	return b.CompletedAt(value)
}

// CompletenessValidation sets the completeness_validation field
func (b *TechnicalDebtInstanceBuilder) CompletenessValidation(value []string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyCompletenessValidation, value)
	return b
}

// SetCompletenessValidation is a compatibility alias for CompletenessValidation.
func (b *TechnicalDebtInstanceBuilder) SetCompletenessValidation(value []string) *TechnicalDebtInstanceBuilder {
	return b.CompletenessValidation(value)
}

// ComplexityScore sets the complexity_score field
func (b *TechnicalDebtInstanceBuilder) ComplexityScore(value int) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyComplexityScore, value)
	return b
}

// SetComplexityScore is a compatibility alias for ComplexityScore.
func (b *TechnicalDebtInstanceBuilder) SetComplexityScore(value int) *TechnicalDebtInstanceBuilder {
	return b.ComplexityScore(value)
}

// Context sets the context field
func (b *TechnicalDebtInstanceBuilder) Context(value any) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyContext, value)
	return b
}

// SetContext is a compatibility alias for Context.
func (b *TechnicalDebtInstanceBuilder) SetContext(value any) *TechnicalDebtInstanceBuilder {
	return b.Context(value)
}

// Deadline sets the deadline field
func (b *TechnicalDebtInstanceBuilder) Deadline(value string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyDeadline, value)
	return b
}

// SetDeadline is a compatibility alias for Deadline.
func (b *TechnicalDebtInstanceBuilder) SetDeadline(value string) *TechnicalDebtInstanceBuilder {
	return b.Deadline(value)
}

// DebtType sets the debt_type field
func (b *TechnicalDebtInstanceBuilder) DebtType(value enumv.DebtType) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyDebtType, string(value))
	return b
}

// SetDebtType is a compatibility alias for DebtType.
func (b *TechnicalDebtInstanceBuilder) SetDebtType(value enumv.DebtType) *TechnicalDebtInstanceBuilder {
	return b.DebtType(value)
}

// Dependencies sets the dependencies field
func (b *TechnicalDebtInstanceBuilder) Dependencies(value []string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyDependencies, value)
	return b
}

// SetDependencies is a compatibility alias for Dependencies.
func (b *TechnicalDebtInstanceBuilder) SetDependencies(value []string) *TechnicalDebtInstanceBuilder {
	return b.Dependencies(value)
}

// Description sets the description field
func (b *TechnicalDebtInstanceBuilder) Description(value string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyDescription, value)
	return b
}

// SetDescription is a compatibility alias for Description.
func (b *TechnicalDebtInstanceBuilder) SetDescription(value string) *TechnicalDebtInstanceBuilder {
	return b.Description(value)
}

// EstimatedEffort sets the estimated_effort field
func (b *TechnicalDebtInstanceBuilder) EstimatedEffort(value string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyEstimatedEffort, value)
	return b
}

// SetEstimatedEffort is a compatibility alias for EstimatedEffort.
func (b *TechnicalDebtInstanceBuilder) SetEstimatedEffort(value string) *TechnicalDebtInstanceBuilder {
	return b.EstimatedEffort(value)
}

// FilePath sets the file_path field
func (b *TechnicalDebtInstanceBuilder) FilePath(value string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyFilePath, value)
	return b
}

// SetFilePath is a compatibility alias for FilePath.
func (b *TechnicalDebtInstanceBuilder) SetFilePath(value string) *TechnicalDebtInstanceBuilder {
	return b.FilePath(value)
}

// FunctionName sets the function_name field
func (b *TechnicalDebtInstanceBuilder) FunctionName(value string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyFunctionName, value)
	return b
}

// SetFunctionName is a compatibility alias for FunctionName.
func (b *TechnicalDebtInstanceBuilder) SetFunctionName(value string) *TechnicalDebtInstanceBuilder {
	return b.FunctionName(value)
}

// ImpactAssessment sets the impact_assessment field
func (b *TechnicalDebtInstanceBuilder) ImpactAssessment(value enumv.ImpactAssessment) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyImpactAssessment, string(value))
	return b
}

// SetImpactAssessment is a compatibility alias for ImpactAssessment.
func (b *TechnicalDebtInstanceBuilder) SetImpactAssessment(value enumv.ImpactAssessment) *TechnicalDebtInstanceBuilder {
	return b.ImpactAssessment(value)
}

// LinterRule sets the linter_rule field
func (b *TechnicalDebtInstanceBuilder) LinterRule(value string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyLinterRule, value)
	return b
}

// SetLinterRule is a compatibility alias for LinterRule.
func (b *TechnicalDebtInstanceBuilder) SetLinterRule(value string) *TechnicalDebtInstanceBuilder {
	return b.LinterRule(value)
}

// MitigationPlan sets the mitigation_plan field
func (b *TechnicalDebtInstanceBuilder) MitigationPlan(value string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyMitigationPlan, value)
	return b
}

// SetMitigationPlan is a compatibility alias for MitigationPlan.
func (b *TechnicalDebtInstanceBuilder) SetMitigationPlan(value string) *TechnicalDebtInstanceBuilder {
	return b.MitigationPlan(value)
}

// OriginProject sets the origin_project field
func (b *TechnicalDebtInstanceBuilder) OriginProject(value string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyOriginProject, value)
	return b
}

// SetOriginProject is a compatibility alias for OriginProject.
func (b *TechnicalDebtInstanceBuilder) SetOriginProject(value string) *TechnicalDebtInstanceBuilder {
	return b.OriginProject(value)
}

// OriginSystem sets the origin_system field
func (b *TechnicalDebtInstanceBuilder) OriginSystem(value string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyOriginSystem, value)
	return b
}

// SetOriginSystem is a compatibility alias for OriginSystem.
func (b *TechnicalDebtInstanceBuilder) SetOriginSystem(value string) *TechnicalDebtInstanceBuilder {
	return b.OriginSystem(value)
}

// Plane sets the plane field
func (b *TechnicalDebtInstanceBuilder) Plane(value enumv.Plane) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyPlane, string(value))
	return b
}

// SetPlane is a compatibility alias for Plane.
func (b *TechnicalDebtInstanceBuilder) SetPlane(value enumv.Plane) *TechnicalDebtInstanceBuilder {
	return b.Plane(value)
}

// PolicyRef sets the policy_ref field
func (b *TechnicalDebtInstanceBuilder) PolicyRef(value string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyPolicyRef, value)
	return b
}

// SetPolicyRef is a compatibility alias for PolicyRef.
func (b *TechnicalDebtInstanceBuilder) SetPolicyRef(value string) *TechnicalDebtInstanceBuilder {
	return b.PolicyRef(value)
}

// PriorityTier sets the priority_tier field
func (b *TechnicalDebtInstanceBuilder) PriorityTier(value enumv.PriorityTier) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyPriorityTier, string(value))
	return b
}

// SetPriorityTier is a compatibility alias for PriorityTier.
func (b *TechnicalDebtInstanceBuilder) SetPriorityTier(value enumv.PriorityTier) *TechnicalDebtInstanceBuilder {
	return b.PriorityTier(value)
}

// Provenance sets the provenance field
func (b *TechnicalDebtInstanceBuilder) Provenance(value map[string]any) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyProvenance, value)
	return b
}

// SetProvenance is a compatibility alias for Provenance.
func (b *TechnicalDebtInstanceBuilder) SetProvenance(value map[string]any) *TechnicalDebtInstanceBuilder {
	return b.Provenance(value)
}

// Questions sets the questions field
func (b *TechnicalDebtInstanceBuilder) Questions(value []string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyQuestions, value)
	return b
}

// SetQuestions is a compatibility alias for Questions.
func (b *TechnicalDebtInstanceBuilder) SetQuestions(value []string) *TechnicalDebtInstanceBuilder {
	return b.Questions(value)
}

// RelatedObjectRefs sets the related_object_refs field
func (b *TechnicalDebtInstanceBuilder) RelatedObjectRefs(value []string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyRelatedObjectRefs, value)
	return b
}

// SetRelatedObjectRefs is a compatibility alias for RelatedObjectRefs.
func (b *TechnicalDebtInstanceBuilder) SetRelatedObjectRefs(value []string) *TechnicalDebtInstanceBuilder {
	return b.RelatedObjectRefs(value)
}

// ResolutionNotes sets the resolution_notes field
func (b *TechnicalDebtInstanceBuilder) ResolutionNotes(value string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyResolutionNotes, value)
	return b
}

// SetResolutionNotes is a compatibility alias for ResolutionNotes.
func (b *TechnicalDebtInstanceBuilder) SetResolutionNotes(value string) *TechnicalDebtInstanceBuilder {
	return b.ResolutionNotes(value)
}

// SchemaRef sets the schema_ref field
func (b *TechnicalDebtInstanceBuilder) SchemaRef(value string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeySchemaRef, value)
	return b
}

// SetSchemaRef is a compatibility alias for SchemaRef.
func (b *TechnicalDebtInstanceBuilder) SetSchemaRef(value string) *TechnicalDebtInstanceBuilder {
	return b.SchemaRef(value)
}

// SourceType sets the source_type field
func (b *TechnicalDebtInstanceBuilder) SourceType(value enumv.SourceType) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeySourceType, string(value))
	return b
}

// SetSourceType is a compatibility alias for SourceType.
func (b *TechnicalDebtInstanceBuilder) SetSourceType(value enumv.SourceType) *TechnicalDebtInstanceBuilder {
	return b.SourceType(value)
}

// SpecAdherence sets the spec_adherence field
func (b *TechnicalDebtInstanceBuilder) SpecAdherence(value map[string]any) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeySpecAdherence, value)
	return b
}

// SetSpecAdherence is a compatibility alias for SpecAdherence.
func (b *TechnicalDebtInstanceBuilder) SetSpecAdherence(value map[string]any) *TechnicalDebtInstanceBuilder {
	return b.SpecAdherence(value)
}

// Stakeholders sets the stakeholders field
func (b *TechnicalDebtInstanceBuilder) Stakeholders(value []string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyStakeholders, value)
	return b
}

// SetStakeholders is a compatibility alias for Stakeholders.
func (b *TechnicalDebtInstanceBuilder) SetStakeholders(value []string) *TechnicalDebtInstanceBuilder {
	return b.Stakeholders(value)
}

// StartedAt sets the started_at field
func (b *TechnicalDebtInstanceBuilder) StartedAt(value string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyStartedAt, value)
	return b
}

// SetStartedAt is a compatibility alias for StartedAt.
func (b *TechnicalDebtInstanceBuilder) SetStartedAt(value string) *TechnicalDebtInstanceBuilder {
	return b.StartedAt(value)
}

// StatusHistory sets the status_history field
func (b *TechnicalDebtInstanceBuilder) StatusHistory(value []string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyStatusHistory, value)
	return b
}

// SetStatusHistory is a compatibility alias for StatusHistory.
func (b *TechnicalDebtInstanceBuilder) SetStatusHistory(value []string) *TechnicalDebtInstanceBuilder {
	return b.StatusHistory(value)
}

// Tags sets the tags field
func (b *TechnicalDebtInstanceBuilder) Tags(value []string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyTags, value)
	return b
}

// SetTags is a compatibility alias for Tags.
func (b *TechnicalDebtInstanceBuilder) SetTags(value []string) *TechnicalDebtInstanceBuilder {
	return b.Tags(value)
}

// TargetDate sets the target_date field
func (b *TechnicalDebtInstanceBuilder) TargetDate(value string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyTargetDate, value)
	return b
}

// SetTargetDate is a compatibility alias for TargetDate.
func (b *TechnicalDebtInstanceBuilder) SetTargetDate(value string) *TechnicalDebtInstanceBuilder {
	return b.TargetDate(value)
}

// TargetResolutionDate sets the target_resolution_date field
func (b *TechnicalDebtInstanceBuilder) TargetResolutionDate(value string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyTargetResolutionDate, value)
	return b
}

// SetTargetResolutionDate is a compatibility alias for TargetResolutionDate.
func (b *TechnicalDebtInstanceBuilder) SetTargetResolutionDate(value string) *TechnicalDebtInstanceBuilder {
	return b.TargetResolutionDate(value)
}

// Title sets the title field
func (b *TechnicalDebtInstanceBuilder) Title(value string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyTitle, value)
	return b
}

// SetTitle is a compatibility alias for Title.
func (b *TechnicalDebtInstanceBuilder) SetTitle(value string) *TechnicalDebtInstanceBuilder {
	return b.Title(value)
}

// Urn sets the urn field
func (b *TechnicalDebtInstanceBuilder) Urn(value string) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyUrn, value)
	return b
}

// SetUrn is a compatibility alias for Urn.
func (b *TechnicalDebtInstanceBuilder) SetUrn(value string) *TechnicalDebtInstanceBuilder {
	return b.Urn(value)
}

// Version sets the version field
func (b *TechnicalDebtInstanceBuilder) Version(value int) *TechnicalDebtInstanceBuilder {
	b.SetField(objects.FieldKeyVersion, value)
	return b
}

// SetVersion is a compatibility alias for Version.
func (b *TechnicalDebtInstanceBuilder) SetVersion(value int) *TechnicalDebtInstanceBuilder {
	return b.Version(value)
}
