// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package bldr_instance_v1

import (
	enumv "github.com/zqk-os/zqk/packs/work/bldr_enum_v1/work_unit"
	"github.com/zqk-os/zqk/pkg/objects"
	"github.com/zqk-os/zqk/pkg/specbuilder/instance_builders"
)

// WorkUnitInstanceBuilder builds work_unit instances
// ONE builder handles ALL work_unit instances
type WorkUnitInstanceBuilder struct {
	*instance_builders.BaseInstanceBuilder
}

// NewWorkUnitInstanceBuilder creates a new work_unit instance builder.
// Pass the instance schema_version string for this spec; use objects.DefaultSchemaVersion for the project default (pkg/objects constants).
// Field order is derived from the spec (not hardcoded) to avoid drift
func NewWorkUnitInstanceBuilder(schemaVersion string) *WorkUnitInstanceBuilder {
	// Derive canonical field order from spec (follows architecture pattern)
	// System fields first, then spec-defined fields in sorted order
	fieldOrder := instance_builders.FieldOrderFromSpec("work_unit")

	// Create base builder
	builder := &WorkUnitInstanceBuilder{
		BaseInstanceBuilder: instance_builders.NewBaseInstanceBuilder(
			"work_unit",
			schemaVersion,
			fieldOrder,
			nil, // spec builder (optional)
		),
	}

	return builder
}

// Status sets the status field
func (b *WorkUnitInstanceBuilder) Status(value enumv.Status) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyStatus, string(value))
	return b
}

// ID sets the id field
func (b *WorkUnitInstanceBuilder) ID(value string) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyID, value)
	return b
}

// ActualEffort sets the actual_effort field
func (b *WorkUnitInstanceBuilder) ActualEffort(value string) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyActualEffort, value)
	return b
}

// SetActualEffort is a compatibility alias for ActualEffort.
func (b *WorkUnitInstanceBuilder) SetActualEffort(value string) *WorkUnitInstanceBuilder {
	return b.ActualEffort(value)
}

// ArchivedAt sets the archived_at field
func (b *WorkUnitInstanceBuilder) ArchivedAt(value any) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedAt, value)
	return b
}

// SetArchivedAt is a compatibility alias for ArchivedAt.
func (b *WorkUnitInstanceBuilder) SetArchivedAt(value any) *WorkUnitInstanceBuilder {
	return b.ArchivedAt(value)
}

// ArchivedBy sets the archived_by field
func (b *WorkUnitInstanceBuilder) ArchivedBy(value string) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyArchivedBy, value)
	return b
}

// SetArchivedBy is a compatibility alias for ArchivedBy.
func (b *WorkUnitInstanceBuilder) SetArchivedBy(value string) *WorkUnitInstanceBuilder {
	return b.ArchivedBy(value)
}

// Artifacts sets the artifacts field
func (b *WorkUnitInstanceBuilder) Artifacts(value []string) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyArtifacts, value)
	return b
}

// SetArtifacts is a compatibility alias for Artifacts.
func (b *WorkUnitInstanceBuilder) SetArtifacts(value []string) *WorkUnitInstanceBuilder {
	return b.Artifacts(value)
}

// ChangeLog sets the change_log field
func (b *WorkUnitInstanceBuilder) ChangeLog(value []string) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyChangeLog, value)
	return b
}

// SetChangeLog is a compatibility alias for ChangeLog.
func (b *WorkUnitInstanceBuilder) SetChangeLog(value []string) *WorkUnitInstanceBuilder {
	return b.ChangeLog(value)
}

// CompletedAt sets the completed_at field
func (b *WorkUnitInstanceBuilder) CompletedAt(value string) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyCompletedAt, value)
	return b
}

// SetCompletedAt is a compatibility alias for CompletedAt.
func (b *WorkUnitInstanceBuilder) SetCompletedAt(value string) *WorkUnitInstanceBuilder {
	return b.CompletedAt(value)
}

// CompletenessValidation sets the completeness_validation field
func (b *WorkUnitInstanceBuilder) CompletenessValidation(value []string) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyCompletenessValidation, value)
	return b
}

// SetCompletenessValidation is a compatibility alias for CompletenessValidation.
func (b *WorkUnitInstanceBuilder) SetCompletenessValidation(value []string) *WorkUnitInstanceBuilder {
	return b.CompletenessValidation(value)
}

// Context sets the context field
func (b *WorkUnitInstanceBuilder) Context(value any) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyContext, value)
	return b
}

// SetContext is a compatibility alias for Context.
func (b *WorkUnitInstanceBuilder) SetContext(value any) *WorkUnitInstanceBuilder {
	return b.Context(value)
}

// Deadline sets the deadline field
func (b *WorkUnitInstanceBuilder) Deadline(value string) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyDeadline, value)
	return b
}

// SetDeadline is a compatibility alias for Deadline.
func (b *WorkUnitInstanceBuilder) SetDeadline(value string) *WorkUnitInstanceBuilder {
	return b.Deadline(value)
}

// Dependencies sets the dependencies field
func (b *WorkUnitInstanceBuilder) Dependencies(value []string) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyDependencies, value)
	return b
}

// SetDependencies is a compatibility alias for Dependencies.
func (b *WorkUnitInstanceBuilder) SetDependencies(value []string) *WorkUnitInstanceBuilder {
	return b.Dependencies(value)
}

// Description sets the description field
func (b *WorkUnitInstanceBuilder) Description(value any) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyDescription, value)
	return b
}

// SetDescription is a compatibility alias for Description.
func (b *WorkUnitInstanceBuilder) SetDescription(value any) *WorkUnitInstanceBuilder {
	return b.Description(value)
}

// EstimatedEffort sets the estimated_effort field
func (b *WorkUnitInstanceBuilder) EstimatedEffort(value string) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyEstimatedEffort, value)
	return b
}

// SetEstimatedEffort is a compatibility alias for EstimatedEffort.
func (b *WorkUnitInstanceBuilder) SetEstimatedEffort(value string) *WorkUnitInstanceBuilder {
	return b.EstimatedEffort(value)
}

// OriginProject sets the origin_project field
func (b *WorkUnitInstanceBuilder) OriginProject(value string) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyOriginProject, value)
	return b
}

// SetOriginProject is a compatibility alias for OriginProject.
func (b *WorkUnitInstanceBuilder) SetOriginProject(value string) *WorkUnitInstanceBuilder {
	return b.OriginProject(value)
}

// OriginSystem sets the origin_system field
func (b *WorkUnitInstanceBuilder) OriginSystem(value string) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyOriginSystem, value)
	return b
}

// SetOriginSystem is a compatibility alias for OriginSystem.
func (b *WorkUnitInstanceBuilder) SetOriginSystem(value string) *WorkUnitInstanceBuilder {
	return b.OriginSystem(value)
}

// Plane sets the plane field
func (b *WorkUnitInstanceBuilder) Plane(value enumv.Plane) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyPlane, string(value))
	return b
}

// SetPlane is a compatibility alias for Plane.
func (b *WorkUnitInstanceBuilder) SetPlane(value enumv.Plane) *WorkUnitInstanceBuilder {
	return b.Plane(value)
}

// PriorityTier sets the priority_tier field
func (b *WorkUnitInstanceBuilder) PriorityTier(value enumv.PriorityTier) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyPriorityTier, string(value))
	return b
}

// SetPriorityTier is a compatibility alias for PriorityTier.
func (b *WorkUnitInstanceBuilder) SetPriorityTier(value enumv.PriorityTier) *WorkUnitInstanceBuilder {
	return b.PriorityTier(value)
}

// Provenance sets the provenance field
func (b *WorkUnitInstanceBuilder) Provenance(value map[string]any) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyProvenance, value)
	return b
}

// SetProvenance is a compatibility alias for Provenance.
func (b *WorkUnitInstanceBuilder) SetProvenance(value map[string]any) *WorkUnitInstanceBuilder {
	return b.Provenance(value)
}

// Questions sets the questions field
func (b *WorkUnitInstanceBuilder) Questions(value []string) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyQuestions, value)
	return b
}

// SetQuestions is a compatibility alias for Questions.
func (b *WorkUnitInstanceBuilder) SetQuestions(value []string) *WorkUnitInstanceBuilder {
	return b.Questions(value)
}

// RelatedObjectRefs sets the related_object_refs field
func (b *WorkUnitInstanceBuilder) RelatedObjectRefs(value []string) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyRelatedObjectRefs, value)
	return b
}

// SetRelatedObjectRefs is a compatibility alias for RelatedObjectRefs.
func (b *WorkUnitInstanceBuilder) SetRelatedObjectRefs(value []string) *WorkUnitInstanceBuilder {
	return b.RelatedObjectRefs(value)
}

// SchemaRef sets the schema_ref field
func (b *WorkUnitInstanceBuilder) SchemaRef(value string) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeySchemaRef, value)
	return b
}

// SetSchemaRef is a compatibility alias for SchemaRef.
func (b *WorkUnitInstanceBuilder) SetSchemaRef(value string) *WorkUnitInstanceBuilder {
	return b.SchemaRef(value)
}

// SourceType sets the source_type field
func (b *WorkUnitInstanceBuilder) SourceType(value enumv.SourceType) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeySourceType, string(value))
	return b
}

// SetSourceType is a compatibility alias for SourceType.
func (b *WorkUnitInstanceBuilder) SetSourceType(value enumv.SourceType) *WorkUnitInstanceBuilder {
	return b.SourceType(value)
}

// SpecAdherence sets the spec_adherence field
func (b *WorkUnitInstanceBuilder) SpecAdherence(value map[string]any) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeySpecAdherence, value)
	return b
}

// SetSpecAdherence is a compatibility alias for SpecAdherence.
func (b *WorkUnitInstanceBuilder) SetSpecAdherence(value map[string]any) *WorkUnitInstanceBuilder {
	return b.SpecAdherence(value)
}

// Stakeholders sets the stakeholders field
func (b *WorkUnitInstanceBuilder) Stakeholders(value []string) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyStakeholders, value)
	return b
}

// SetStakeholders is a compatibility alias for Stakeholders.
func (b *WorkUnitInstanceBuilder) SetStakeholders(value []string) *WorkUnitInstanceBuilder {
	return b.Stakeholders(value)
}

// StartedAt sets the started_at field
func (b *WorkUnitInstanceBuilder) StartedAt(value string) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyStartedAt, value)
	return b
}

// SetStartedAt is a compatibility alias for StartedAt.
func (b *WorkUnitInstanceBuilder) SetStartedAt(value string) *WorkUnitInstanceBuilder {
	return b.StartedAt(value)
}

// StatusHistory sets the status_history field
func (b *WorkUnitInstanceBuilder) StatusHistory(value []string) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyStatusHistory, value)
	return b
}

// SetStatusHistory is a compatibility alias for StatusHistory.
func (b *WorkUnitInstanceBuilder) SetStatusHistory(value []string) *WorkUnitInstanceBuilder {
	return b.StatusHistory(value)
}

// TargetDate sets the target_date field
func (b *WorkUnitInstanceBuilder) TargetDate(value string) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyTargetDate, value)
	return b
}

// SetTargetDate is a compatibility alias for TargetDate.
func (b *WorkUnitInstanceBuilder) SetTargetDate(value string) *WorkUnitInstanceBuilder {
	return b.TargetDate(value)
}

// Title sets the title field
func (b *WorkUnitInstanceBuilder) Title(value string) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyTitle, value)
	return b
}

// SetTitle is a compatibility alias for Title.
func (b *WorkUnitInstanceBuilder) SetTitle(value string) *WorkUnitInstanceBuilder {
	return b.Title(value)
}

// Urn sets the urn field
func (b *WorkUnitInstanceBuilder) Urn(value string) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyUrn, value)
	return b
}

// SetUrn is a compatibility alias for Urn.
func (b *WorkUnitInstanceBuilder) SetUrn(value string) *WorkUnitInstanceBuilder {
	return b.Urn(value)
}

// Version sets the version field
func (b *WorkUnitInstanceBuilder) Version(value int) *WorkUnitInstanceBuilder {
	b.SetField(objects.FieldKeyVersion, value)
	return b
}

// SetVersion is a compatibility alias for Version.
func (b *WorkUnitInstanceBuilder) SetVersion(value int) *WorkUnitInstanceBuilder {
	return b.Version(value)
}
