// Code generated by pkg/specbuilder/instance_builders/codegen.go from lifecycle YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package shared_epics

type Status string

const (
	StatusArchived   Status = "archived"
	StatusCompleted  Status = "completed"
	StatusConceptual Status = "conceptual"
	StatusDraft      Status = "draft"
	StatusError      Status = "error"
	StatusInProgress Status = "in_progress"
	StatusOriginated Status = "originated"
	StatusPaused     Status = "paused"
	StatusPlanned    Status = "planned"
)
