// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec/lifecycle YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package workstream

import (
	base_objectenum "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/base_object"
	shared_workstreamsenum "github.com/lanceman/zqk/pkg/specbuilder/bldr_enum_v1/shared_workstreams"
)

type Category string

const (
	CategoryApplication Category = "application"
	CategoryComponent   Category = "component"
	CategoryFeature     Category = "feature"
	CategoryOps         Category = "ops"
	CategorySystem      Category = "system"
	CategoryTooling     Category = "tooling"
)

type PriorityTier = base_objectenum.PriorityTier

const (
	PriorityTierP0 PriorityTier = base_objectenum.PriorityTierP0
	PriorityTierP1 PriorityTier = base_objectenum.PriorityTierP1
	PriorityTierP2 PriorityTier = base_objectenum.PriorityTierP2
	PriorityTierP3 PriorityTier = base_objectenum.PriorityTierP3
)

type SourceType = base_objectenum.SourceType

const (
	SourceTypeExternal SourceType = base_objectenum.SourceTypeExternal
	SourceTypeImported SourceType = base_objectenum.SourceTypeImported
	SourceTypeInternal SourceType = base_objectenum.SourceTypeInternal
)

type Status = shared_workstreamsenum.Status

const (
	StatusActive   Status = shared_workstreamsenum.StatusActive
	StatusArchived Status = shared_workstreamsenum.StatusArchived
	StatusComplete Status = shared_workstreamsenum.StatusComplete
	StatusError    Status = shared_workstreamsenum.StatusError
	StatusPaused   Status = shared_workstreamsenum.StatusPaused
	StatusPlanned  Status = shared_workstreamsenum.StatusPlanned
)
