// Code generated by pkg/specbuilder/instance_builders/codegen.go from object spec/lifecycle YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package persona

import (
	base_objectenum "github.com/zqk-os/zqk/pkg/specbuilder/bldr_enum_v1/base_object"
	shared_personasenum "github.com/zqk-os/zqk/pkg/specbuilder/bldr_enum_v1/shared_personas"
)

type Plane = base_objectenum.Plane

const (
	PlaneApoptotic Plane = base_objectenum.PlaneApoptotic
	PlaneDraft     Plane = base_objectenum.PlaneDraft
	PlanePromoted  Plane = base_objectenum.PlanePromoted
	PlaneStaged    Plane = base_objectenum.PlaneStaged
)

type PriorityTier = base_objectenum.PriorityTier

const (
	PriorityTierP0 PriorityTier = base_objectenum.PriorityTierP0
	PriorityTierP1 PriorityTier = base_objectenum.PriorityTierP1
	PriorityTierP2 PriorityTier = base_objectenum.PriorityTierP2
	PriorityTierP3 PriorityTier = base_objectenum.PriorityTierP3
)

type SourceType = base_objectenum.SourceType

const (
	SourceTypeExternal SourceType = base_objectenum.SourceTypeExternal
	SourceTypeImported SourceType = base_objectenum.SourceTypeImported
	SourceTypeInternal SourceType = base_objectenum.SourceTypeInternal
)

type Status = shared_personasenum.Status

const (
	StatusApproved    Status = shared_personasenum.StatusApproved
	StatusArchived    Status = shared_personasenum.StatusArchived
	StatusConceptual  Status = shared_personasenum.StatusConceptual
	StatusError       Status = shared_personasenum.StatusError
	StatusImplemented Status = shared_personasenum.StatusImplemented
	StatusInProgress  Status = shared_personasenum.StatusInProgress
	StatusOriginated  Status = shared_personasenum.StatusOriginated
	StatusProposed    Status = shared_personasenum.StatusProposed
)
