// Code generated by zqk-admin system generate-builders. DO NOT EDIT.

package bldr_profile_v1

import (
	"github.com/lanceman/zqk/pkg/config"
	"github.com/lanceman/zqk/pkg/objects"
	"github.com/lanceman/zqk/pkg/specbuilder/profile_builders"
)

// BaseRouterBuilder builds the base_router profile at version v1_0_0
// File: bldr_profile_v1/base_router_builder.go - version is encoded in package/directory name
type BaseRouterBuilder struct {
	*profile_builders.BaseProfileBuilder
}

// NewBaseRouterBuilder creates a new builder for base_router profile version v1_0_0
func NewBaseRouterBuilder() *BaseRouterBuilder {
	builder := &BaseRouterBuilder{
		BaseProfileBuilder: profile_builders.NewBaseProfileBuilder("base_router", "v1_0_0"),
	}

	// Configure the profile
	builder.
		SetSchemaVersion(SchemaVersionV1).
		SetKind("profile").
		SetType(config.ProfileTypeTransceiverRouter).
		SetMetadata(config.ProfileMetadata{
			Name:        "base_router",
			Description: "Base router profile for the transceiver. Defines common knobs for async\\nrouting such as worker pool sizing, queue capacity, and timeouts.\\nOther router profiles should extend this base profile.\\n",
		}).
		SetSpec(map[string]any{
			"backoff_strategy":      "exponential",
			"default_timeout_ms":    5000,
			objects.FieldKeyEnabled: true,
			"enqueue_timeout_ms":    100,
			"max_backoff_ms":        30000,
			"max_workers":           10,
			"metrics_interval_ms":   0,
			"queue_size":            100,
		})

	return builder
}

func init() {
	profile_builders.RegisterBuilder(NewBaseRouterBuilder())
}
