package system

import (
	"fmt"
	"path/filepath"
	"time"

	"github.com/lanceman/zqk/pkg/agentonboard"
	"github.com/lanceman/zqk/pkg/datacell"
	"github.com/lanceman/zqk/pkg/errfmt"
	"github.com/lanceman/zqk/pkg/logging"
	"github.com/lanceman/zqk/pkg/paths"
	fileutil "github.com/lanceman/zqk/pkg/utils/fileutil"
)

// writeRootIsolationFiles ensures that all root isolation and kernel config files
// are scaffolded during system init (both greenfield and legacy), preventing
// a second root from sharing studio sockets, feeds, or configurations.
func writeRootIsolationFiles(projectRoot string, force bool, logger logging.Logger) error {
	absRoot, err := filepath.Abs(projectRoot)
	if err != nil || absRoot == "" {
		absRoot = projectRoot
	}

	// 1. config/zqk.yaml
	cfgDir := filepath.Join(projectRoot, paths.ConfigDir)
	if err := fileutil.EnsureDir(cfgDir); err != nil {
		return errfmt.Newf("ensure config dir").Wrap(err)
	}

	zqkConfigPath := filepath.Join(cfgDir, paths.ZqkConfigFileName)
	if _, err := fileutil.Stat(zqkConfigPath); fileutil.IsNotExist(err) || force {
		content := `# Knowledge Kernel Root Configuration
# Generated by system init
system:
  storage_mode: "file"

paths:
  project_root: "."

kernel_state:
  project_root: "."
`
		if err := fileutil.WriteStandardFile(zqkConfigPath, []byte(content)); err != nil {
			logging.Fluent(logger).Warn("Failed to write config/zqk.yaml").WithError(err).Log()
		}
	}

	// 2. config/zqk-local.yaml
	zqkLocalPath := filepath.Join(cfgDir, paths.ZqkLocalConfigFileName)
	if _, err := fileutil.Stat(zqkLocalPath); fileutil.IsNotExist(err) || force {
		content := fmt.Sprintf(`# Local Developer / Environment Overrides
# Generated by system init
kernel_state:
  project_root: "%s"

paths:
  project_root: "%s"
`, absRoot, absRoot)
		if err := fileutil.WriteStandardFile(zqkLocalPath, []byte(content)); err != nil {
			logging.Fluent(logger).Warn("Failed to write config/zqk-local.yaml").WithError(err).Log()
		} else {
			paths.AssumeUnchangedWorktreeConfig(projectRoot)
		}
	}

	// 3. .zqk/config/agent_chat_channel.json
	chatChannelPath := datacell.AgentChatChannelConfigPath(projectRoot)
	if _, err := fileutil.Stat(chatChannelPath); fileutil.IsNotExist(err) || force {
		c := datacell.AgentChatChannelConfig{
			SchemaVersion: datacell.AgentChatChannelSchemaVersion,
			Enabled:       true,
			DeliveryMode:  datacell.DeliveryModeLog,
			Note:          "Community local feed channel",
		}
		if err := datacell.WriteAgentChatChannelConfig(projectRoot, c); err != nil {
			logging.Fluent(logger).Warn("Failed to write agent_chat_channel.json").WithError(err).Log()
		}
	}

	// 4. .zqk/config/agent_workspace_sync.json
	syncReportPath := filepath.Join(projectRoot, filepath.FromSlash(agentonboard.SyncReportRelPath))
	if _, err := fileutil.Stat(syncReportPath); fileutil.IsNotExist(err) || force {
		rep := agentonboard.SyncReport{
			Schema:         agentonboard.SyncReportSchema,
			UpdatedAt:      time.Now().UTC().Format(time.RFC3339),
			Vector:         "community_bootstrap",
			SeatingCreated: 0,
			SmokeOK:        true,
			Notes:          []string{"Scaffolded during system init"},
		}
		if _, err := agentonboard.WriteSyncReport(projectRoot, rep, false); err != nil {
			logging.Fluent(logger).Warn("Failed to write agent_workspace_sync.json").WithError(err).Log()
		}
	}

	// 5. .zqk/config/agent_git_identity.env.example
	gitIdentityExamplePath := filepath.Join(projectRoot, paths.ProjectDataDir, paths.ConfigDir, "agent_git_identity.env.example")
	if _, err := fileutil.Stat(gitIdentityExamplePath); fileutil.IsNotExist(err) || force {
		content := `# Copy to agent_git_identity.env (gitignored) and set values for THIS machine.
# Agents must load this before any ` + "`git commit`" + ` so history is not attributed to the human owner.
#
# For GitHub attribution that is not your personal account, create a machine user
# (e.g. zqk-studio-agent) and use that account's noreply email + push with its credentials.
# Author/committer env alone does not change who authenticates ` + "`git push`" + `.

ZQK_AGENT_GIT_NAME=zqk-community-agent
ZQK_AGENT_GIT_EMAIL=zqk-community-agent@users.noreply.github.com
`
		if err := fileutil.EnsureDir(filepath.Dir(gitIdentityExamplePath)); err == nil {
			if err := fileutil.WriteStandardFile(gitIdentityExamplePath, []byte(content)); err != nil {
				logging.Fluent(logger).Warn("Failed to write agent_git_identity.env.example").WithError(err).Log()
			}
		}
	}

	// 6. .zqk/state/remote_hold.json
	remoteHoldPath := filepath.Join(projectRoot, paths.ProjectDataDir, paths.StateDir, "remote_hold.json")
	if _, err := fileutil.Stat(remoteHoldPath); fileutil.IsNotExist(err) || force {
		content := fmt.Sprintf(`{
  "schema": "zqk_remote_hold_v1",
  "hold": true,
  "reason": "Default deny publish of public-candidate / Open-Core trees until human clears hold and writes public_push_ack.json",
  "updated_at": "%s"
}
`, time.Now().UTC().Format(time.RFC3339))
		if err := fileutil.EnsureDir(filepath.Dir(remoteHoldPath)); err == nil {
			if err := fileutil.WriteStandardFile(remoteHoldPath, []byte(content)); err != nil {
				logging.Fluent(logger).Warn("Failed to write remote_hold.json").WithError(err).Log()
			}
		}
	}

	return nil
}
