// Lock operation names for RunInLockWithLogger / RunInRLockWithLogger,
// and WithLockTimeout / WithRLockTimeout (same string contract).
// CONSTANTS_AND_DRY_INVENTORY_PLAN Phase A.
package system

const (
	LockNameAuditEventBufferAdd                 = "audit_event_buffer_add"
	LockNameAuditEventBufferAddHashFix          = "audit_event_buffer_add_hash_fix"
	LockNameAuditEventBufferFlushCopy           = "audit_event_buffer_flush_copy"
	LockNameAuditEventBufferGet                 = "audit_event_buffer_get"
	LockNameAuditEventBufferGetCount            = "audit_event_buffer_get_count"
	LockNameAuditEventBufferGetSummary          = "audit_event_buffer_get_summary"
	LockNameAuditEventBufferReset               = "audit_event_buffer_reset"
	LockNameCacheBuildClear                     = "cache_build_clear"
	LockNameCacheBuildGetCountAfter             = "cache_build_get_count_after"
	LockNameCacheBuildGetCountBefore            = "cache_build_get_count_before"
	LockNameCacheBuildStoreEntries              = "cache_build_store_entries"
	LockNameCacheItemStrategyGet                = "cache_item_strategy_get"
	LockNameCacheItemStrategyRegister           = "cache_item_strategy_register"
	LockNameFixExecutorEnqueue                  = "fix_executor_enqueue"
	LockNameFixExecutorGetCompletionCallback    = "fix_executor_get_completion_callback"
	LockNameFixExecutorGetErrorCallback         = "fix_executor_get_error_callback"
	LockNameFixExecutorGetProgressCallback      = "fix_executor_get_progress_callback"
	LockNameFixExecutorRequestApproval          = "fix_executor_request_approval"
	LockNameFixExecutorSetApprovalCallback      = "fix_executor_set_approval_callback"
	LockNameFixExecutorSetCompletionCallback    = "fix_executor_set_completion_callback"
	LockNameFixExecutorSetErrorCallback         = "fix_executor_set_error_callback"
	LockNameFixExecutorSetProgressCallback      = "fix_executor_set_progress_callback"
	LockNameFixExecutorSetRequiresApproval      = "fix_executor_set_requires_approval"
	LockNameFixExecutorSetTimeouts              = "fix_executor_set_timeouts"
	LockNameFixExecutorStart                    = "fix_executor_start"
	LockNameFixExecutorStop                     = "fix_executor_stop"
	LockNameHashRegistryCacheDelete             = "hash_registry_cache_delete"
	LockNameHashRegistryCacheGet                = "hash_registry_cache_get"
	LockNameHashRegistryCacheReloadAll          = "hash_registry_cache_reload_all"
	LockNameHashRegistryCacheReloadCheck        = "hash_registry_cache_reload_check"
	LockNameHashRegistryCacheSet                = "hash_registry_cache_set"
	LockNameHashRegistryCollectModified         = "hash_registry_collect_modified"
	LockNameObjectIDCacheBuildGetCountBuilt     = "object_id_cache_build_get_count_built"
	LockNameObjectIDCacheBuildGetCountLoaded    = "object_id_cache_build_get_count_loaded"
	LockNameObjectIDCacheBuildVerify            = "object_id_cache_build_verify"
	LockNameObjectIDCacheBulkInvalidate         = "object_id_cache_bulk_invalidate"
	LockNameObjectIDCacheClearInMemory          = "object_id_cache_clear_in_memory"
	LockNameObjectIDCacheCountKind              = "object_id_cache_count_kind"
	LockNameObjectIDCacheDiagnostic             = "object_id_cache_diagnostic"
	LockNameObjectIDCacheEnsureReady            = "object_id_cache_ensure_ready"
	LockNameObjectIDCacheGet                    = "object_id_cache_get"
	LockNameObjectIDCacheGetEntryCount          = "object_id_cache_get_entry_count"
	LockNameObjectIDCacheGetMetadata            = "object_id_cache_get_metadata"
	LockNameObjectIDCacheGetRunner              = "object_id_cache_get_runner"
	LockNameObjectIDCacheInvalidate             = "object_id_cache_invalidate"
	LockNameObjectIDCacheInvalidateKind         = "object_id_cache_invalidate_kind"
	LockNameObjectIDCacheKindNamesForReverseRef = "object_id_cache_kind_names_for_reverse_ref"
	LockNameObjectIDCacheLoad                   = "object_id_cache_load"
	LockNameObjectIDCacheSavePrepare            = "object_id_cache_save_prepare"
	LockNameObjectIDCacheSet                    = "object_id_cache_set"
	LockNameObjectIDCacheTryLoadCount           = "object_id_cache_try_load_count"
	LockNameObjectIDCacheValidateClean          = "object_id_cache_validate_clean"
	LockNameObjectIDCacheVerifyFunction         = "object_id_cache_verify_function"
	LockNameObjectIDCacheVerifyReady            = "object_id_cache_verify_ready"
)
