// Package kindnames holds canonical object kind string literals and
// LoadKindNamesFromSpecsDir for the ontology set under object_specs.
//
// pkg/objects re-exports string literals as objects.Kind* for backward compatibility.
// pkg/kindsynonyms and other packages use kindnames (or objects.Kind*) — never duplicate
// the same literal in multiple packages.
package kindnames

// Canonical kind strings (object `kind` field / list filters / specs).
const (
	BaseObject             = "base_object"
	Auditable              = "auditable"
	WorkInterval           = "work_interval"
	WorkUnit               = "work_unit"
	Occupancy              = "occupancy"
	RemainingOpen          = "remaining_open"
	BaseMetric             = "base_metric"
	SchedulerJob           = "scheduler_job"
	CommandMetric          = "command_metric"
	FileLockMetric         = "file_lock_metric"
	AuditAggregationMetric = "audit_aggregation_metric"
	ChangeJournalEntry     = "change_journal_entry"
	AuditEvent             = "audit_event"
	AuditEventAggregation  = "audit_event_aggregation"
	DomainRegistry         = "domain_registry"
	ExtensibleObject       = "extensible_object"
	EvolutionManagement    = "evolution_management"
	Brand                  = "brand"
	Policy                 = "policy"
	RemoteKernel           = "remote_kernel"
	Account                = "account"
	Role                   = "role"
	Team                   = "team"
	Partnership            = "partnership"
	// Process / traceability
	Goal               = "goal"
	Epic               = "epic"
	PriorityPlan       = "priority_plan"
	Question           = "question"
	Milestone          = "milestone"
	Criteria           = "criteria"
	Decision           = "decision"
	Requirement        = "requirement"
	Roadmap            = "roadmap"
	TestCase           = "test_case"
	BacklogItem        = "backlog_item"
	DocEntry           = "doc_entry"
	ConvergenceSession = "convergence_session"
	Pipeline           = "pipeline"
	ProviderProfile    = "provider_profile"
	TechnicalSpec      = "technical_spec"
	CodeFile           = "code_file"
	CommandSpec        = "command_spec"
	AgentTask          = "agent_task"
	Lifecycle          = "lifecycle"
	Component          = "component"
	Workstream         = "workstream"
	ImprovementReport  = "improvement_report"
	MetricsFeedback    = "metrics_feedback"
	Vision             = "vision"
	Mission            = "mission"
	StrategicPlan      = "strategic_plan"
	ZqkSession         = "zqk_session"

	// Internal / infrastructure kinds (often visibility=internal in specs)
	ObjectSpec        = "object_spec"
	Template          = "template"
	IntegrityManifest = "integrity_manifest"
	KindSynonym       = "kind_synonym"

	// Supporting / tooling kinds (spec-backed)
	AutoFixRule           = "auto_fix_rule"
	CodeReference         = "code_reference"
	Namespace             = "namespace"
	Scenario              = "scenario"
	SchedulerHealthMetric = "scheduler_health_metric"

	// Import / organizational (spec-backed)
	ImportTracking       = "import_tracking"
	Organization         = "organization"
	Division             = "division"
	Department           = "department"
	OrganizationalChange = "organizational_change"
	ImpactAnalysis       = "impact_analysis"

	// Additional spec-backed kinds (object_specs; CLI/tests reference these literals)
	TestAuditAggregationMetric = "test_audit_aggregation_metric"
	KindMappingMetric          = "kind_mapping_metric"
	CodeQualityMetric          = "code_quality_metric"
	NamespaceRegistry          = "namespace_registry"
	MetadataPackage            = "metadata_package"
	Certificate                = "certificate"
	KeystoreEntry              = "keystore_entry"
	GlossaryTerm               = "glossary_term"
	GlossaryTermRelation       = "glossary_term_relation"
	Library                    = "library"
	Display                    = "display"
	Persona                    = "persona"
	Release                    = "release"
	Resolver                   = "resolver"
	RollbackReport             = "rollback_report"
	Rule                       = "rule"
	SchedulerHandlerBinding    = "scheduler_handler_binding"
	ListMetricSampler          = "list_metric_sampler"
	OrderedListMetricSampler   = "ordered_list_metric_sampler"
	ScalarMetricSampler        = "scalar_metric_sampler"
	StatusHistoryMetricSampler = "status_history_metric_sampler"
	McpBuiltInTool             = "mcp_built_in_tool"
	McpSession                 = "mcp_session"
	McpSpec                    = "mcp_spec"
	AgentArchitecture          = "agent_architecture"
	AgentFeed                  = "agent_feed"
	AgentInstruction           = "agent_instruction"
	AgentOnboardingPreparation = "agent_onboarding_preparation"
	AuthStrategy               = "auth_strategy"
	BaseSampler                = "base_sampler"
	BucketingStrategy          = "bucketing_strategy"
	ContextRefreshSchedule     = "context_refresh_schedule"
	SamplerProfile             = "sampler_profile"
	TdeEnvelope                = "tde_envelope"
	TechnicalDebt              = "technical_debt"
	TestCommandRule            = "test_command_rule"
	WorkstreamTransition       = "workstream_transition"
	VerificationMatrix         = "verification_matrix"

	// Spec-backed kinds (object_specs; Kind* in pkg/objects for builders/CLI)
	CorporateInitiative   = "corporate_initiative"
	ImportantDate         = "important_date"
	PromptTemplate        = "prompt_template"
	StakeholderProfile    = "stakeholder_profile"
	StrategicContext      = "strategic_context"
	Workflow              = "workflow"
	VocabularyScheme      = "vocabulary_scheme"
	AgentSkill            = "agent_skill"
	CapacityAdvertisement = "capacity_advertisement"
	ComputeAdvertisement  = "compute_advertisement"
	EconomicPolicy        = "economic_policy"

	RiskBlocker = "risk_blocker"

	InferenceHeuristic = "inference_heuristic"
	VitalityReport     = "vitality_report"
	MaturationReport   = "maturation_report"
	FissionEvent       = "fission_event"
	ReputationScore    = "reputation_score"
	ValidationRule     = "validation_rule"
	PipelineDefinition = "pipeline_definition"
	PipelineExecution  = "pipeline_execution"
)
