// Code generated by pkg/specbuilder/instance_builders/codegen.go from lifecycle YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package shared_agent_instructions

type Status string

const (
	StatusApproved   Status = "approved"
	StatusArchived   Status = "archived"
	StatusCompleted  Status = "completed"
	StatusConceptual Status = "conceptual"
	StatusError      Status = "error"
	StatusInProgress Status = "in_progress"
	StatusOriginated Status = "originated"
	StatusProposed   Status = "proposed"
	StatusRejected   Status = "rejected"
)
