// Code generated by pkg/specbuilder/instance_builders/codegen.go from lifecycle YAML. DO NOT EDIT.
// DO NOT EDIT. Regenerate with: zqk system generate-instance-builders --overwrite

package shared_goals

type Status string

const (
	StatusActive   Status = "active"
	StatusArchived Status = "archived"
	StatusBlocked  Status = "blocked"
	StatusComplete Status = "complete"
	StatusError    Status = "error"
	StatusProposed Status = "proposed"
)
